// resource/apps/web/src/admin/pages/oauth-settings-page.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import type { GooseAdminApi, OAuthProviderSettings } from "@gooseforum/client";
import { Badge } from "@gooseforum/ui/components/badge";
import { Button } from "@gooseforum/ui/components/button";
import {
  Field,
  FieldDescription,
  FieldLabel,
} from "@gooseforum/ui/components/field";
import { Input } from "@gooseforum/ui/components/input";
import { Spinner } from "@gooseforum/ui/components/spinner";
import { Switch } from "@gooseforum/ui/components/switch";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@gooseforum/ui/components/tabs";
import { KeyRound, Plus, Save, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import type { IdentityTextKey } from "../identity-settings-i18n";
type Text = (k: IdentityTextKey) => string;
type Form = OAuthProviderSettings & { scopeDraft: string };
function toForm(p: OAuthProviderSettings): Form {
  return {
    ...p,
    clientSecret: "",
    clearClientSecret: false,
    scopes: p.scopes?.length ? [...p.scopes] : ["openid", "profile", "email"],
    scopeDraft: "",
  };
}
export function OAuthSettingsPage({
  api,
  text,
}: {
  api: GooseAdminApi;
  text: Text;
}) {
  const [items, setItems] = useState<Form[]>([]);
  const [active, setActive] = useState("0");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const tr = useRef(text);
  useEffect(() => {
    tr.current = text;
  }, [text]);
  const load = useCallback(async () => {
    setLoading(true);
    try {
      setItems((await api.settings.oauth()).providers.map(toForm));
    } catch (r) {
      toast.error(r instanceof Error ? r.message : tr.current("loadFailed"));
    } finally {
      setLoading(false);
    }
  }, [api]);
  useEffect(() => {
    void load();
  }, [load]);
  const index = Math.min(Number(active) || 0, Math.max(items.length - 1, 0));
  const current = items[index];
  function update(fn: (p: Form) => void) {
    setItems((list) =>
      list.map((p, i) => {
        if (i !== index) return p;
        const next = { ...p, scopes: [...(p.scopes || [])] };
        fn(next);
        return next;
      }),
    );
  }
  function add() {
    setItems((list) => [
      ...list,
      {
        key: "",
        displayName: "",
        kind: "oidc",
        enabled: false,
        clientId: "",
        clientSecret: "",
        clientSecretConfigured: false,
        clearClientSecret: false,
        callbackUrl: "",
        discoveryUrl: "",
        scopes: ["openid", "profile", "email"],
        scopeDraft: "",
      },
    ]);
    setActive(String(items.length));
  }
  async function save() {
    setSaving(true);
    try {
      const result = await api.settings.saveOAuth({
        providers: items.map((p) => ({
          key: p.key.trim().toLowerCase(),
          displayName: p.displayName.trim(),
          kind: p.kind,
          enabled: p.enabled,
          clientId: p.clientId.trim(),
          clientSecret: p.clientSecret?.trim() || "",
          clientSecretConfigured: p.clientSecretConfigured,
          clearClientSecret: Boolean(p.clearClientSecret),
          callbackUrl: p.callbackUrl,
          discoveryUrl: p.discoveryUrl?.trim() || "",
          scopes: p.scopes || [],
        })),
      });
      setItems(result.providers.map(toForm));
      setActive(String(Math.min(index, result.providers.length - 1)));
      toast.success(text("saved"));
    } catch (r) {
      toast.error(r instanceof Error ? r.message : text("saveFailed"));
    } finally {
      setSaving(false);
    }
  }
  return (
    <main className="flex flex-1 flex-col gap-4 px-3 py-3 lg:px-4">
      <header className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold">{text("oauth")}</h2>
          <p className="text-xs text-muted-foreground">{text("oauthHint")}</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={add}>
            <Plus data-icon="inline-start" />
            {text("addProvider")}
          </Button>
          <Button
            size="sm"
            disabled={saving || loading}
            onClick={() => void save()}
          >
            {saving ? (
              <Spinner data-icon="inline-start" />
            ) : (
              <Save data-icon="inline-start" />
            )}
            {text("save")}
          </Button>
        </div>
      </header>
      {loading ? (
        <div className="grid min-h-64 place-items-center">
          <Spinner />
        </div>
      ) : current ? (
        <Tabs value={String(index)} onValueChange={setActive}>
          <TabsList>
            {items.map((p, i) => (
              <TabsTrigger key={`${p.kind}-${p.key}-${i}`} value={String(i)}>
                <KeyRound />
                {p.displayName || p.key || text("provider")}
                <span
                  className={`size-1.5 rounded-full ${p.enabled ? "bg-success" : "bg-muted-foreground/35"}`}
                />
              </TabsTrigger>
            ))}
          </TabsList>
          <TabsContent value={String(index)} className="flex flex-col gap-6">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="font-semibold">
                  {current.displayName || current.key || text("provider")}
                </h3>
                <p className="text-xs text-muted-foreground">
                  {current.kind === "oidc" ? text("custom") : text("builtin")} ·{" "}
                  {current.clientSecretConfigured
                    ? text("secretConfigured")
                    : text("secretMissing")}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <Field orientation="horizontal" className="w-auto">
                  <FieldLabel>{text("enabled")}</FieldLabel>
                  <Switch
                    checked={current.enabled}
                    onCheckedChange={(enabled) =>
                      update((p) => {
                        p.enabled = enabled;
                      })
                    }
                  />
                </Field>
                {current.kind === "oidc" ? (
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    onClick={() => {
                      setItems(items.filter((_, i) => i !== index));
                      setActive(String(Math.max(0, index - 1)));
                    }}
                  >
                    <Trash2 />
                  </Button>
                ) : null}
              </div>
            </div>
            {current.kind === "oidc" ? (
              <div className="grid gap-4 md:grid-cols-2">
                <F
                  label={text("displayName")}
                  value={current.displayName}
                  onChange={(displayName) =>
                    update((p) => {
                      p.displayName = displayName;
                    })
                  }
                />
                <F
                  label={text("key")}
                  value={current.key}
                  onChange={(key) =>
                    update((p) => {
                      p.key = key;
                    })
                  }
                />
              </div>
            ) : null}
            <div className="grid gap-4 md:grid-cols-2">
              <F
                label={text("clientId")}
                value={current.clientId}
                onChange={(clientId) =>
                  update((p) => {
                    p.clientId = clientId;
                  })
                }
              />
              <Field>
                <FieldLabel>{text("clientSecret")}</FieldLabel>
                <div className="flex gap-2">
                  <Input
                    type="password"
                    autoComplete="new-password"
                    value={current.clientSecret || ""}
                    disabled={current.clearClientSecret}
                    placeholder={
                      current.clientSecretConfigured ? text("keepSecret") : ""
                    }
                    onChange={(e) =>
                      update((p) => {
                        p.clientSecret = e.target.value;
                      })
                    }
                  />
                  {current.clientSecretConfigured ? (
                    <Button
                      variant="outline"
                      onClick={() =>
                        update((p) => {
                          p.clearClientSecret = !p.clearClientSecret;
                        })
                      }
                    >
                      {current.clearClientSecret
                        ? text("undoClear")
                        : text("clearSecret")}
                    </Button>
                  ) : null}
                </div>
                {current.clearClientSecret ? (
                  <FieldDescription className="text-destructive">
                    {text("clearWarning")}
                  </FieldDescription>
                ) : null}
              </Field>
            </div>
            {current.kind === "oidc" ? (
              <>
                <F
                  label={text("discovery")}
                  value={current.discoveryUrl || ""}
                  onChange={(discoveryUrl) =>
                    update((p) => {
                      p.discoveryUrl = discoveryUrl;
                    })
                  }
                />
                <Field>
                  <FieldLabel>{text("scopes")}</FieldLabel>
                  <div className="flex gap-2">
                    <Input
                      value={current.scopeDraft}
                      onChange={(e) =>
                        update((p) => {
                          p.scopeDraft = e.target.value;
                        })
                      }
                      onKeyDown={(e) => {
                        if (e.key === "Enter") {
                          e.preventDefault();
                          const v = current.scopeDraft.trim();
                          if (v && !current.scopes?.includes(v))
                            update((p) => {
                              p.scopes = [...(p.scopes || []), v];
                              p.scopeDraft = "";
                            });
                        }
                      }}
                    />
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={() => {
                        const v = current.scopeDraft.trim();
                        if (v)
                          update((p) => {
                            p.scopes = [...new Set([...(p.scopes || []), v])];
                            p.scopeDraft = "";
                          });
                      }}
                    >
                      <Plus />
                    </Button>
                  </div>
                  <div className="flex flex-wrap gap-1.5">
                    {current.scopes?.map((s) => (
                      <Badge
                        key={s}
                        variant="secondary"
                        className="gap-1 font-mono"
                      >
                        {s}
                        {s !== "openid" ? (
                          <Button
                            variant="ghost"
                            size="icon-xs"
                            onClick={() =>
                              update((p) => {
                                p.scopes = p.scopes?.filter((x) => x !== s);
                              })
                            }
                          >
                            <X />
                          </Button>
                        ) : null}
                      </Badge>
                    ))}
                  </div>
                </Field>
              </>
            ) : null}
            <Field>
              <FieldLabel>{text("callback")}</FieldLabel>
              <Input
                readOnly
                value={current.callbackUrl}
                className="font-mono text-xs"
              />
            </Field>
          </TabsContent>
        </Tabs>
      ) : null}
    </main>
  );
}
function F({
  label,
  value,
  onChange,
}: {
  label: string;
  value: string;
  onChange(v: string): void;
}) {
  return (
    <Field>
      <FieldLabel>{label}</FieldLabel>
      <Input value={value} onChange={(e) => onChange(e.target.value)} />
    </Field>
  );
}

// resource/src/admin/pages/OAuthSettingsPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { KeyRound, Loader2, Plus, Save, Trash2, X } from '@lucide/vue'
import { siDiscord, siGithub, siGoogle, type SimpleIcon } from 'simple-icons'
import { BasicPage } from '@/admin/components/global-layout'
import { Badge } from '@/admin/components/ui/badge'
import { Button } from '@/admin/components/ui/button'
import { Input } from '@/admin/components/ui/input'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/admin/components/ui/tabs'
import { Switch } from '@/admin/components/ui/switch'
import { adminText } from '@/admin/runtime/i18n-text'
import { getOAuthSettings, saveOAuthSettings } from '@/admin/runtime/api'
import { adminToast } from '@/admin/runtime/toast'
import type { OAuthProviderSettings, OAuthSettings } from '@/admin/types'

interface OAuthProviderForm extends OAuthProviderSettings {
  scopeDraft: string
}

const providers = ref<OAuthProviderForm[]>([])
const loading = ref(false)
const saving = ref(false)
const error = ref('')
const activeProviderIndex = ref(0)
const activeProvider = computed(() => providers.value[activeProviderIndex.value])

const providerIcons: Record<string, SimpleIcon> = {
  github: siGithub,
  google: siGoogle,
  discord: siDiscord,
}

function toForm(provider: OAuthProviderSettings): OAuthProviderForm {
  return {
    ...provider,
    clientSecret: '',
    clearClientSecret: false,
    scopes: provider.scopes?.length ? [...provider.scopes] : ['openid', 'profile', 'email'],
    scopeDraft: '',
  }
}

function applySettings(settings: OAuthSettings) {
  providers.value = settings.providers.map(toForm)
  activeProviderIndex.value = Math.min(activeProviderIndex.value, Math.max(providers.value.length - 1, 0))
}

async function load() {
  loading.value = true
  error.value = ''
  try {
    applySettings(await getOAuthSettings())
  } catch (err) {
    error.value = err instanceof Error ? err.message : adminText('k00g4')
  } finally {
    loading.value = false
  }
}

function addProvider() {
  providers.value.push({
    key: '',
    displayName: '',
    kind: 'oidc',
    enabled: false,
    clientId: '',
    clientSecret: '',
    clientSecretConfigured: false,
    clearClientSecret: false,
    callbackUrl: '',
    discoveryUrl: '',
    scopes: ['openid', 'profile', 'email'],
    scopeDraft: '',
  })
  activeProviderIndex.value = providers.value.length - 1
}

function removeProvider(index: number) {
  if (providers.value[index]?.kind !== 'oidc') return
  providers.value.splice(index, 1)
  activeProviderIndex.value = Math.min(index, Math.max(providers.value.length - 1, 0))
}

function addScope(provider: OAuthProviderForm) {
  const scope = provider.scopeDraft.trim()
  if (!scope || provider.scopes?.includes(scope)) return
  provider.scopes = [...(provider.scopes || []), scope]
  provider.scopeDraft = ''
}

function removeScope(provider: OAuthProviderForm, scope: string) {
  if (scope === 'openid') return
  provider.scopes = (provider.scopes || []).filter(item => item !== scope)
}

async function save() {
  saving.value = true
  try {
    const settings: OAuthSettings = {
      providers: providers.value.map(provider => ({
        key: provider.key.trim().toLowerCase(),
        displayName: provider.displayName.trim(),
        kind: provider.kind,
        enabled: provider.enabled,
        clientId: provider.clientId.trim(),
        clientSecret: provider.clientSecret?.trim() || '',
        clientSecretConfigured: provider.clientSecretConfigured,
        clearClientSecret: Boolean(provider.clearClientSecret),
        callbackUrl: provider.callbackUrl,
        discoveryUrl: provider.discoveryUrl?.trim() || '',
        scopes: provider.scopes || [],
      })),
    }
    applySettings(await saveOAuthSettings(settings))
    adminToast.success(adminText('k00g0'))
  } catch (err) {
    adminToast.error(err, adminText('k000f'))
  } finally {
    saving.value = false
  }
}

onMounted(load)
</script>

<template>
  <BasicPage :title="adminText('k00fl')" :description="adminText('k00fm')">
    <template #primary-action>
      <div class="flex items-center gap-2">
        <Button type="button" variant="outline" @click="addProvider">
          <Plus class="size-4" />
          {{ adminText('k00fn') }}
        </Button>
        <Button type="button" :disabled="saving" @click="save">
          <Loader2 v-if="saving" class="size-4 animate-spin" />
          <Save v-else class="size-4" />
          {{ adminText('k004f') }}
        </Button>
      </div>
    </template>

    <div v-if="loading" class="flex h-[400px] items-center justify-center">
      <Loader2 class="size-8 animate-spin text-primary" />
    </div>
    <div v-else-if="error" class="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">
      {{ error }}
    </div>
    <form v-else-if="activeProvider" class="min-w-0" @submit.prevent="save">
      <Tabs v-model="activeProviderIndex" class="gap-6">
        <div class="min-w-0 overflow-x-auto pb-1">
          <TabsList :aria-label="adminText('k00fl')">
            <TabsTrigger
              v-for="(provider, index) in providers"
              :key="`${provider.kind}-${provider.key || index}`"
              :value="index"
            >
              <svg
                v-if="providerIcons[provider.key]"
                class="size-4"
                viewBox="0 0 24 24"
                fill="currentColor"
                aria-hidden="true"
                :style="{ color: `#${providerIcons[provider.key].hex}` }"
              >
                <path :d="providerIcons[provider.key].path" />
              </svg>
              <KeyRound v-else class="size-4" />
              <span>{{ provider.displayName || provider.key || adminText('k00fp') }}</span>
              <span class="size-1.5 rounded-full" :class="provider.enabled ? 'bg-emerald-500' : 'bg-muted-foreground/35'" />
            </TabsTrigger>
          </TabsList>
        </div>

        <TabsContent :key="activeProviderIndex" :value="activeProviderIndex" class="flex flex-col gap-6">
          <header class="flex flex-wrap items-center justify-between gap-3">
            <div>
              <h2 class="text-base font-semibold">{{ activeProvider.displayName || activeProvider.key || adminText('k00fp') }}</h2>
              <p class="mt-0.5 text-xs text-muted-foreground">
                {{ activeProvider.kind === 'oidc' ? adminText('k00fp') : adminText('k00fo') }} ·
                {{ activeProvider.clientSecretConfigured ? adminText('k00ft') : adminText('k00fu') }}
              </p>
            </div>
            <div class="flex items-center gap-3">
              <label class="flex items-center gap-2 text-sm font-medium">
                {{ adminText('k00fq') }}
                <Switch v-model="activeProvider.enabled" />
              </label>
              <Button v-if="activeProvider.kind === 'oidc'" type="button" size="icon" variant="ghost" :title="adminText('k00fz')" @click="removeProvider(activeProviderIndex)">
                <Trash2 class="size-4 text-destructive" />
              </Button>
            </div>
          </header>

          <div v-if="activeProvider.kind === 'oidc'" class="grid gap-6 md:grid-cols-2">
            <label class="grid gap-2 text-sm font-medium">
              {{ adminText('k00g1') }}
              <Input v-model="activeProvider.displayName" placeholder="Company SSO" />
            </label>
            <label class="grid gap-2 text-sm font-medium">
              {{ adminText('k00g2') }}
              <Input v-model="activeProvider.key" placeholder="company-sso" :title="adminText('k00g3')" />
            </label>
          </div>

          <div class="grid gap-6 md:grid-cols-2">
            <label class="grid gap-2 text-sm font-medium">
              {{ adminText('k00fr') }}
              <Input v-model="activeProvider.clientId" autocomplete="off" />
            </label>
            <label class="grid gap-2 text-sm font-medium">
              {{ adminText('k00fs') }}
              <div class="flex gap-2">
                <Input
                  v-model="activeProvider.clientSecret"
                  class="min-w-0"
                  type="password"
                  autocomplete="new-password"
                  :disabled="activeProvider.clearClientSecret"
                  :placeholder="activeProvider.clientSecretConfigured ? adminText('k00fv') : ''"
                />
                <Button
                  v-if="activeProvider.clientSecretConfigured"
                  type="button"
                  variant="outline"
                  class="shrink-0"
                  @click="activeProvider.clearClientSecret = !activeProvider.clearClientSecret"
                >
                  {{ activeProvider.clearClientSecret ? adminText('k00g7') : adminText('k00g6') }}
                </Button>
              </div>
              <span v-if="activeProvider.clearClientSecret" class="text-xs font-normal text-destructive">{{ adminText('k00g5') }}</span>
            </label>
          </div>

          <div v-if="activeProvider.kind === 'oidc'" class="grid gap-6 md:grid-cols-2">
            <label class="grid gap-2 text-sm font-medium">
              {{ adminText('k00fx') }}
              <Input v-model="activeProvider.discoveryUrl" placeholder="https://id.example.com/.well-known/openid-configuration" />
            </label>
            <label class="grid gap-2 text-sm font-medium">
              {{ adminText('k00fy') }}
              <div class="flex min-w-0 gap-2">
                <Input
                  v-model="activeProvider.scopeDraft"
                  class="min-w-0"
                  placeholder="email"
                  @keydown.enter.prevent="addScope(activeProvider)"
                />
                <Button type="button" size="icon" variant="outline" :title="adminText('k0094')" @click="addScope(activeProvider)">
                  <Plus class="size-4" />
                </Button>
              </div>
            </label>
            <div class="flex min-h-7 flex-wrap gap-1.5 md:col-start-2">
              <Badge v-for="scope in activeProvider.scopes" :key="scope" variant="secondary" class="gap-1 px-2 py-1 font-mono text-xs font-normal">
                {{ scope }}
                <button
                  v-if="scope !== 'openid'"
                  type="button"
                  class="rounded-sm text-muted-foreground hover:text-foreground"
                  :title="adminText('k005i')"
                  @click="removeScope(activeProvider, scope)"
                >
                  <X class="size-3" />
                </button>
              </Badge>
            </div>
          </div>

          <label class="grid gap-2 text-sm font-medium">
            {{ adminText('k00fw') }}
            <Input :model-value="activeProvider.callbackUrl" readonly class="font-mono text-xs" />
          </label>
        </TabsContent>
      </Tabs>
    </form>
  </BasicPage>
</template>
