// resource/apps/web/src/admin/pages/oidc-provider-settings-page.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import type {
  GooseAdminApi,
  OIDCClient,
  OIDCClientAuthMethod,
  OIDCClientInput,
  OIDCProviderStatus,
} from "@gooseforum/client";
import { Badge } from "@gooseforum/ui/components/badge";
import { Button } from "@gooseforum/ui/components/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@gooseforum/ui/components/dialog";
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSet,
} from "@gooseforum/ui/components/field";
import { Input } from "@gooseforum/ui/components/input";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@gooseforum/ui/components/select";
import { Spinner } from "@gooseforum/ui/components/spinner";
import { Switch } from "@gooseforum/ui/components/switch";
import { Textarea } from "@gooseforum/ui/components/textarea";
import { Check, Copy, Pencil, Plus, RefreshCw, RotateCw } from "lucide-react";
import { toast } from "sonner";
import type { IdentityTextKey } from "../identity-settings-i18n";
type Text = (k: IdentityTextKey) => string;
const scopes = ["openid", "profile", "email", "offline_access"];
type Form = {
  clientId: string;
  name: string;
  redirectUris: string;
  scopes: string[];
  tokenEndpointAuthMethod: OIDCClientAuthMethod;
  requirePkce: boolean;
  public: boolean;
  enabled: boolean;
};
const blank = (): Form => ({
  clientId: "",
  name: "",
  redirectUris: "",
  scopes: ["openid", "profile", "email"],
  tokenEndpointAuthMethod: "client_secret_basic",
  requirePkce: true,
  public: false,
  enabled: true,
});
export function OIDCProviderSettingsPage({
  api,
  text,
}: {
  api: GooseAdminApi;
  text: Text;
}) {
  const [status, setStatus] = useState<OIDCProviderStatus | null>(null);
  const [clients, setClients] = useState<OIDCClient[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [editor, setEditor] = useState<Form | null>(null);
  const [rotate, setRotate] = useState<OIDCClient | null>(null);
  const [rotateSigning, setRotateSigning] = useState(false);
  const [secret, setSecret] = useState<{
    clientId: string;
    value: string;
  } | null>(null);
  const [copied, setCopied] = useState(false);
  const tr = useRef(text);
  useEffect(() => {
    tr.current = text;
  }, [text]);
  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [a, b] = await Promise.allSettled([
        api.settings.oidcStatus(),
        api.settings.oidcClients(),
      ]);
      if (a.status === "fulfilled") setStatus(a.value);
      if (b.status === "fulfilled") setClients(b.value);
      const failure =
        a.status === "rejected"
          ? a.reason
          : b.status === "rejected"
            ? b.reason
            : null;
      if (failure)
        toast.error(
          failure instanceof Error ? failure.message : tr.current("loadFailed"),
        );
    } finally {
      setLoading(false);
    }
  }, [api]);
  useEffect(() => {
    void load();
  }, [load]);
  async function toggleProvider(enabled: boolean) {
    setSaving(true);
    try {
      setStatus(await api.settings.saveOIDCStatus(enabled));
      toast.success(text("saved"));
    } catch (r) {
      toast.error(r instanceof Error ? r.message : text("saveFailed"));
    } finally {
      setSaving(false);
    }
  }
  async function submit() {
    if (!editor) return;
    const input = toInput(editor);
    if (!input.name) {
      toast.warning(text("nameRequired"));
      return;
    }
    if (!input.redirectUris.length) {
      toast.warning(text("redirectRequired"));
      return;
    }
    if (input.redirectUris.some((uri) => !/^https?:\/\//i.test(uri))) {
      toast.warning(text("redirectInvalid"));
      return;
    }
    setSaving(true);
    try {
      if (editor.clientId) {
        const result = await api.settings.updateOIDCClient({
          ...input,
          clientId: editor.clientId,
        });
        setClients(
          clients.map((c) => (c.clientId === result.clientId ? result : c)),
        );
      } else {
        const result = await api.settings.createOIDCClient(input);
        setClients([...clients, result.client]);
        setSecret({
          clientId: result.client.clientId,
          value: result.clientSecret || "",
        });
      }
      setEditor(null);
      toast.success(text("saved"));
    } catch (r) {
      toast.error(r instanceof Error ? r.message : text("saveFailed"));
    } finally {
      setSaving(false);
    }
  }
  async function rotateClient() {
    if (!rotate) return;
    setSaving(true);
    try {
      const r = await api.settings.rotateOIDCClientSecret(rotate.clientId);
      setClients(
        clients.map((c) => (c.clientId === r.client.clientId ? r.client : c)),
      );
      setSecret({ clientId: r.client.clientId, value: r.clientSecret || "" });
      setRotate(null);
    } catch (r) {
      toast.error(r instanceof Error ? r.message : text("saveFailed"));
    } finally {
      setSaving(false);
    }
  }
  return (
    <main className="flex flex-1 flex-col gap-4 px-3 py-3 lg:px-4">
      <header className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold">{text("oidc")}</h2>
          <p className="text-xs text-muted-foreground">{text("oidcHint")}</p>
        </div>
        <Button size="sm" onClick={() => setEditor(blank())}>
          <Plus data-icon="inline-start" />
          {text("create")}
        </Button>
      </header>
      <section className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <div className="flex items-center gap-2 font-semibold">
            {text("status")}
            <Badge variant={status?.available ? "default" : "outline"}>
              {status?.available
                ? text("running")
                : status?.enabled
                  ? text("configError")
                  : text("notEnabled")}
            </Badge>
          </div>
          <p className="mt-1 font-mono text-xs text-muted-foreground">
            {status?.issuer || status?.error || text("issuerHint")}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Button
            variant="outline"
            size="sm"
            disabled={!status?.available || saving}
            onClick={() => setRotateSigning(true)}
          >
            <RotateCw data-icon="inline-start" />
            {text("rotateSigning")}
          </Button>
          <Switch
            checked={status?.enabled || false}
            disabled={!status || saving}
            onCheckedChange={(v) => void toggleProvider(v)}
          />
        </div>
      </section>
      <section className="overflow-hidden rounded-lg border">
        <div className="flex items-center justify-between border-b p-3">
          <div>
            <h3 className="font-semibold">{text("apps")}</h3>
            <p className="text-xs text-muted-foreground">{clients.length}</p>
          </div>
          <Button
            variant="ghost"
            size="icon-sm"
            disabled={loading}
            onClick={() => void load()}
          >
            <RefreshCw className={loading ? "animate-spin" : undefined} />
          </Button>
        </div>
        {loading && !clients.length ? (
          <div className="grid h-28 place-items-center">
            <Spinner />
          </div>
        ) : clients.length ? (
          <div className="divide-y">
            {clients.map((client) => (
              <article
                key={client.clientId}
                className="grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"
              >
                <div>
                  <div className="flex items-center gap-2">
                    <h4 className="font-semibold">{client.name}</h4>
                    <Badge variant="secondary">
                      {client.public ? text("public") : text("confidential")}
                    </Badge>
                    <Badge variant={client.enabled ? "default" : "outline"}>
                      {client.enabled ? text("enabled") : text("notEnabled")}
                    </Badge>
                  </div>
                  <p className="mt-1 font-mono text-xs text-muted-foreground">
                    {client.clientId}
                  </p>
                  <div className="mt-2 flex gap-1">
                    {client.scopes.map((s) => (
                      <Badge key={s} variant="outline" className="font-mono">
                        {s}
                      </Badge>
                    ))}
                  </div>
                </div>
                <div className="flex items-center gap-1">
                  <Switch
                    checked={client.enabled}
                    disabled={saving}
                    onCheckedChange={async (enabled) => {
                      setSaving(true);
                      try {
                        const r = await api.settings.updateOIDCClient({
                          ...client,
                          enabled,
                        });
                        setClients(
                          clients.map((c) =>
                            c.clientId === r.clientId ? r : c,
                          ),
                        );
                      } catch (r) {
                        toast.error(
                          r instanceof Error ? r.message : text("saveFailed"),
                        );
                      } finally {
                        setSaving(false);
                      }
                    }}
                  />
                  {!client.public ? (
                    <Button
                      variant="ghost"
                      size="icon-sm"
                      onClick={() => setRotate(client)}
                    >
                      <RotateCw />
                    </Button>
                  ) : null}
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    onClick={() => setEditor(fromClient(client))}
                  >
                    <Pencil />
                  </Button>
                </div>
              </article>
            ))}
          </div>
        ) : (
          <div className="p-8 text-center text-muted-foreground">
            {text("empty")}
          </div>
        )}
      </section>
      <ClientEditor
        form={editor}
        saving={saving}
        text={text}
        onChange={setEditor}
        onClose={() => setEditor(null)}
        onSave={() => void submit()}
      />
      <Confirm
        open={rotateSigning}
        title={text("rotateSigningTitle")}
        description={text("rotateSigningHint")}
        text={text}
        saving={saving}
        onClose={() => setRotateSigning(false)}
        onConfirm={async () => {
          setSaving(true);
          try {
            setStatus(await api.settings.rotateOIDCSigningKey());
            setRotateSigning(false);
            toast.success(text("saved"));
          } catch (r) {
            toast.error(r instanceof Error ? r.message : text("saveFailed"));
          } finally {
            setSaving(false);
          }
        }}
      />
      <Confirm
        open={Boolean(rotate)}
        title={text("rotateSecret")}
        description={text("rotateSecretHint")}
        text={text}
        saving={saving}
        onClose={() => setRotate(null)}
        onConfirm={rotateClient}
      />
      <Secret
        value={secret}
        copied={copied}
        text={text}
        onClose={() => {
          setSecret(null);
          setCopied(false);
        }}
        onCopy={async () => {
          if (secret?.value) {
            await navigator.clipboard.writeText(secret.value);
            setCopied(true);
          }
        }}
      />
    </main>
  );
}
function ClientEditor({
  form,
  saving,
  text,
  onChange,
  onClose,
  onSave,
}: {
  form: Form | null;
  saving: boolean;
  text: Text;
  onChange(v: Form): void;
  onClose(): void;
  onSave(): void;
}) {
  if (!form) return <Dialog open={false} />;
  function set<K extends keyof Form>(k: K, v: Form[K]) {
    onChange({ ...form!, [k]: v });
  }
  return (
    <Dialog open onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="max-h-[calc(100vh-2rem)] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>
            {form.clientId ? text("edit") : text("create")}
          </DialogTitle>
          <DialogDescription>{text("oidcHint")}</DialogDescription>
        </DialogHeader>
        <FieldGroup>
          <Field>
            <FieldLabel>{text("appName")}</FieldLabel>
            <Input
              autoFocus
              value={form.name}
              onChange={(e) => set("name", e.target.value)}
            />
          </Field>
          <Field>
            <FieldLabel>{text("redirects")}</FieldLabel>
            <Textarea
              className="min-h-24 font-mono text-xs"
              value={form.redirectUris}
              onChange={(e) => set("redirectUris", e.target.value)}
            />
          </Field>
          <FieldSet>
            <FieldLegend>{text("clientType")}</FieldLegend>
            <div className="grid gap-2 sm:grid-cols-2">
              <Button
                type="button"
                variant={form.public ? "outline" : "default"}
                disabled={Boolean(form.clientId)}
                onClick={() =>
                  onChange({
                    ...form,
                    public: false,
                    tokenEndpointAuthMethod:
                      form.tokenEndpointAuthMethod === "none"
                        ? "client_secret_basic"
                        : form.tokenEndpointAuthMethod,
                  })
                }
              >
                {text("confidential")}
              </Button>
              <Button
                type="button"
                variant={form.public ? "default" : "outline"}
                disabled={Boolean(form.clientId)}
                onClick={() =>
                  onChange({
                    ...form,
                    public: true,
                    tokenEndpointAuthMethod: "none",
                    requirePkce: true,
                  })
                }
              >
                {text("public")}
              </Button>
            </div>
          </FieldSet>
          <div className="grid gap-3 sm:grid-cols-2">
            <Field>
              <FieldLabel>{text("tokenAuth")}</FieldLabel>
              <Select
                value={form.tokenEndpointAuthMethod}
                disabled={form.public}
                onValueChange={(v) =>
                  set("tokenEndpointAuthMethod", v as OIDCClientAuthMethod)
                }
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="client_secret_basic">
                      client_secret_basic
                    </SelectItem>
                    <SelectItem value="client_secret_post">
                      client_secret_post
                    </SelectItem>
                    {form.public ? (
                      <SelectItem value="none">none</SelectItem>
                    ) : null}
                  </SelectGroup>
                </SelectContent>
              </Select>
            </Field>
            <Field orientation="horizontal">
              <div className="flex-1">
                <FieldLabel>{text("pkce")}</FieldLabel>
                <FieldDescription>{text("pkceHint")}</FieldDescription>
              </div>
              <Switch
                checked={form.public || form.requirePkce}
                disabled={form.public}
                onCheckedChange={(v) => set("requirePkce", v)}
              />
            </Field>
          </div>
          <FieldSet>
            <FieldLegend>{text("scopes")}</FieldLegend>
            <div className="grid gap-2 sm:grid-cols-2">
              {scopes.map((scope) => (
                <Field key={scope} orientation="horizontal">
                  <FieldLabel className="font-mono">{scope}</FieldLabel>
                  <Switch
                    checked={form.scopes.includes(scope)}
                    disabled={scope === "openid"}
                    onCheckedChange={(v) =>
                      set(
                        "scopes",
                        v
                          ? [...new Set([...form.scopes, scope])]
                          : form.scopes.filter((x) => x !== scope),
                      )
                    }
                  />
                </Field>
              ))}
            </div>
          </FieldSet>
          <Field orientation="horizontal">
            <FieldLabel>{text("clientEnabled")}</FieldLabel>
            <Switch
              checked={form.enabled}
              onCheckedChange={(v) => set("enabled", v)}
            />
          </Field>
        </FieldGroup>
        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            {text("cancel")}
          </Button>
          <Button disabled={saving} onClick={onSave}>
            {saving ? <Spinner data-icon="inline-start" /> : null}
            {text("save")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
function Confirm({
  open,
  title,
  description,
  text,
  saving,
  onClose,
  onConfirm,
}: {
  open: boolean;
  title: string;
  description: string;
  text: Text;
  saving: boolean;
  onClose(): void;
  onConfirm(): void | Promise<void>;
}) {
  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
          <DialogDescription>{description}</DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            {text("cancel")}
          </Button>
          <Button disabled={saving} onClick={() => void onConfirm()}>
            {text("confirm")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
function Secret({
  value,
  copied,
  text,
  onClose,
  onCopy,
}: {
  value: { clientId: string; value: string } | null;
  copied: boolean;
  text: Text;
  onClose(): void;
  onCopy(): void;
}) {
  return (
    <Dialog open={Boolean(value)} onOpenChange={(o) => !o && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{text("secretTitle")}</DialogTitle>
          <DialogDescription>{text("secretHint")}</DialogDescription>
        </DialogHeader>
        <code className="rounded-md border bg-muted p-3 text-xs">
          {value?.clientId}
        </code>
        <div className="flex gap-2">
          <Input readOnly value={value?.value || ""} className="font-mono" />
          <Button variant="outline" size="icon" onClick={onCopy}>
            {copied ? <Check /> : <Copy />}
          </Button>
        </div>
        <DialogFooter>
          <Button onClick={onClose}>{text("stored")}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
function fromClient(c: OIDCClient): Form {
  return { ...c, redirectUris: c.redirectUris.join("\n") };
}
function toInput(f: Form): OIDCClientInput {
  const scopes = [...new Set(["openid", ...f.scopes])];
  return {
    name: f.name.trim(),
    redirectUris: [
      ...new Set(
        f.redirectUris
          .split(/\r?\n/)
          .map((x) => x.trim())
          .filter(Boolean),
      ),
    ],
    scopes,
    grantTypes: scopes.includes("offline_access")
      ? ["authorization_code", "refresh_token"]
      : ["authorization_code"],
    tokenEndpointAuthMethod: f.public ? "none" : f.tokenEndpointAuthMethod,
    requirePkce: f.public || f.requirePkce,
    public: f.public,
    enabled: f.enabled,
  };
}

// resource/src/admin/pages/OIDCProviderSettingsPage.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { Check, CircleAlert, Copy, KeyRound, Loader2, Pencil, Plus, RefreshCw, RotateCw } from '@lucide/vue'
import { BasicPage } from '@/admin/components/global-layout'
import AdminConfirmDialog from '@/admin/components/AdminConfirmDialog.vue'
import { Badge } from '@/admin/components/ui/badge'
import { Button } from '@/admin/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/admin/components/ui/dialog'
import { Input } from '@/admin/components/ui/input'
import { Label } from '@/admin/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/admin/components/ui/select'
import { Switch } from '@/admin/components/ui/switch'
import { Textarea } from '@/admin/components/ui/textarea'
import { createOIDCClient, getOIDCClients, getOIDCProviderStatus, rotateOIDCClientSecret, rotateOIDCSigningKey, saveOIDCProviderSettings, updateOIDCClient } from '@/admin/runtime/api'
import { adminToast } from '@/admin/runtime/toast'
import type { OIDCClient, OIDCClientAuthMethod, OIDCClientInput, OIDCProviderStatus } from '@/admin/types'

const supportedScopes = ['openid', 'profile', 'email', 'offline_access'] as const
const clients = ref<OIDCClient[]>([])
const loading = ref(false)
const saving = ref(false)
const togglingId = ref('')
const error = ref('')
const editorOpen = ref(false)
const rotateTarget = ref<OIDCClient | null>(null)
const rotating = ref(false)
const secretOpen = ref(false)
const revealedSecret = ref('')
const secretClientId = ref('')
const copied = ref(false)
const providerStatus = ref<OIDCProviderStatus | null>(null)
const providerSaving = ref(false)
const signingKeyDialogOpen = ref(false)
const signingKeyRotating = ref(false)

interface ClientForm {
  clientId: string
  name: string
  redirectUris: string
  scopes: string[]
  tokenEndpointAuthMethod: OIDCClientAuthMethod
  requirePkce: boolean
  public: boolean
  enabled: boolean
}

const form = reactive<ClientForm>(emptyForm())
const editing = computed(() => Boolean(form.clientId))

function emptyForm(): ClientForm {
  return {
    clientId: '',
    name: '',
    redirectUris: '',
    scopes: ['openid', 'profile', 'email'],
    tokenEndpointAuthMethod: 'client_secret_basic',
    requirePkce: true,
    public: false,
    enabled: true,
  }
}

function resetForm(client?: OIDCClient) {
  Object.assign(form, client ? {
    clientId: client.clientId,
    name: client.name,
    redirectUris: client.redirectUris.join('\n'),
    scopes: [...client.scopes],
    tokenEndpointAuthMethod: client.tokenEndpointAuthMethod,
    requirePkce: client.requirePkce,
    public: client.public,
    enabled: client.enabled,
  } : emptyForm())
}

async function loadClients() {
  loading.value = true
  error.value = ''
  try {
    clients.value = await getOIDCClients()
  } catch (err) {
    error.value = err instanceof Error ? err.message : '加载 OIDC 客户端失败'
  } finally {
    loading.value = false
  }
}

async function loadProviderStatus() {
  try {
    providerStatus.value = await getOIDCProviderStatus()
  } catch (err) {
    error.value = err instanceof Error ? err.message : '加载 OIDC Provider 状态失败'
  }
}

async function toggleProvider(enabled: boolean) {
  if (providerSaving.value) return
  providerSaving.value = true
  try {
    providerStatus.value = await saveOIDCProviderSettings(enabled)
    if (providerStatus.value.available) adminToast.success('OIDC Provider 已启用')
    else if (!providerStatus.value.enabled) adminToast.success('OIDC Provider 已停用')
    else adminToast.warning(providerStatus.value.error || 'OIDC Provider 配置尚未就绪')
  } catch (err) {
    adminToast.error(err, '保存 OIDC Provider 设置失败')
  } finally {
    providerSaving.value = false
  }
}

async function confirmSigningKeyRotation() {
  if (signingKeyRotating.value) return
  signingKeyRotating.value = true
  try {
    providerStatus.value = await rotateOIDCSigningKey()
    signingKeyDialogOpen.value = false
    adminToast.success('OIDC 签名密钥已轮换')
  } catch (err) {
    adminToast.error(err, '轮换 OIDC 签名密钥失败')
  } finally {
    signingKeyRotating.value = false
  }
}

function openCreate() {
  resetForm()
  editorOpen.value = true
}

function openEdit(client: OIDCClient) {
  resetForm(client)
  editorOpen.value = true
}

function setPublic(value: boolean) {
  form.public = value
  if (value) {
    form.tokenEndpointAuthMethod = 'none'
    form.requirePkce = true
  } else if (form.tokenEndpointAuthMethod === 'none') {
    form.tokenEndpointAuthMethod = 'client_secret_basic'
  }
}

function toggleScope(scope: string, enabled: boolean) {
  if (scope === 'openid') return
  form.scopes = enabled
    ? Array.from(new Set([...form.scopes, scope]))
    : form.scopes.filter(item => item !== scope)
}

function toInput(): OIDCClientInput {
  const scopes = Array.from(new Set(['openid', ...form.scopes]))
  return {
    name: form.name.trim(),
    redirectUris: Array.from(new Set(form.redirectUris.split(/\r?\n/).map(value => value.trim()).filter(Boolean))),
    scopes,
    grantTypes: scopes.includes('offline_access') ? ['authorization_code', 'refresh_token'] : ['authorization_code'],
    tokenEndpointAuthMethod: form.public ? 'none' : form.tokenEndpointAuthMethod,
    requirePkce: form.public || form.requirePkce,
    public: form.public,
    enabled: form.enabled,
  }
}

function validateInput(input: OIDCClientInput) {
  if (!input.name) return '请输入应用名称'
  if (!input.redirectUris.length) return '请至少填写一个回调地址'
  if (input.redirectUris.some(uri => !/^https?:\/\//i.test(uri))) return '回调地址必须是完整的 HTTP(S) URL'
  return ''
}

async function submit() {
  if (saving.value) return
  const input = toInput()
  const message = validateInput(input)
  if (message) {
    adminToast.warning(message)
    return
  }
  saving.value = true
  try {
    if (editing.value) {
      const updated = await updateOIDCClient({ ...input, clientId: form.clientId })
      clients.value = clients.value.map(client => client.clientId === updated.clientId ? updated : client)
      editorOpen.value = false
      adminToast.success('OIDC 客户端已保存')
    } else {
      const credentials = await createOIDCClient(input)
      clients.value = [...clients.value, credentials.client]
      editorOpen.value = false
      showSecret(credentials.client.clientId, credentials.clientSecret || '')
    }
  } catch (err) {
    adminToast.error(err, editing.value ? '保存 OIDC 客户端失败' : '创建 OIDC 客户端失败')
  } finally {
    saving.value = false
  }
}

async function toggleEnabled(client: OIDCClient, enabled: boolean) {
  if (togglingId.value) return
  togglingId.value = client.clientId
  try {
    const updated = await updateOIDCClient({ ...client, enabled })
    clients.value = clients.value.map(item => item.clientId === updated.clientId ? updated : item)
  } catch (err) {
    adminToast.error(err, '更新客户端状态失败')
  } finally {
    togglingId.value = ''
  }
}

async function confirmRotate() {
  if (!rotateTarget.value || rotating.value) return
  rotating.value = true
  const clientId = rotateTarget.value.clientId
  try {
    const credentials = await rotateOIDCClientSecret(clientId)
    clients.value = clients.value.map(client => client.clientId === credentials.client.clientId ? credentials.client : client)
    rotateTarget.value = null
    showSecret(credentials.client.clientId, credentials.clientSecret || '')
  } catch (err) {
    adminToast.error(err, '重置客户端密钥失败')
  } finally {
    rotating.value = false
  }
}

function showSecret(clientId: string, secret: string) {
  secretClientId.value = clientId
  revealedSecret.value = secret
  copied.value = false
  secretOpen.value = true
}

function clearSecret() {
  revealedSecret.value = ''
  secretClientId.value = ''
  copied.value = false
}

function setSecretOpen(open: boolean) {
  secretOpen.value = open
  if (!open) clearSecret()
}

async function copySecret() {
  if (!revealedSecret.value) return
  await navigator.clipboard.writeText(revealedSecret.value)
  copied.value = true
}

onMounted(() => void Promise.all([loadProviderStatus(), loadClients()]))
onBeforeUnmount(clearSecret)
</script>

<template>
  <BasicPage title="OIDC Provider" description="管理使用 GooseForum 统一登录的应用。">
    <template #primary-action>
      <Button type="button" @click="openCreate">
        <Plus class="size-4" />
        新建客户端
      </Button>
    </template>

    <section class="mb-4 flex flex-col gap-3 border-y bg-muted/20 px-4 py-4 sm:flex-row sm:items-center sm:justify-between">
      <div class="min-w-0">
        <div class="flex items-center gap-2">
          <span class="text-sm font-semibold">服务状态</span>
          <Badge v-if="providerStatus" :variant="providerStatus.available ? 'default' : 'outline'">
            {{ providerStatus.available ? '运行中' : providerStatus.enabled ? '配置错误' : '未启用' }}
          </Badge>
        </div>
        <p v-if="providerStatus?.issuer" class="mt-1 truncate font-mono text-xs text-muted-foreground">{{ providerStatus.issuer }}</p>
        <p v-else-if="providerStatus?.error" class="mt-1 flex items-start gap-1.5 text-xs text-destructive">
          <CircleAlert class="mt-0.5 size-3.5 shrink-0" />
          <span>{{ providerStatus.error }}</span>
        </p>
        <p v-else class="mt-1 text-xs text-muted-foreground">启用前请先在站点设置中配置规范站点地址。</p>
      </div>
      <div class="flex shrink-0 flex-wrap items-center gap-3">
        <Button type="button" size="sm" variant="outline" :disabled="!providerStatus?.available || signingKeyRotating" @click="signingKeyDialogOpen = true">
          <RotateCw class="size-4" />
          轮换签名密钥
        </Button>
        <label class="flex items-center gap-2 text-sm">
          启用 Provider
          <Switch :model-value="providerStatus?.enabled ?? false" :disabled="!providerStatus || providerSaving" @update:model-value="toggleProvider(Boolean($event))" />
        </label>
      </div>
    </section>

    <div v-if="error" class="mb-4 flex items-center justify-between gap-4 rounded-md border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">
      <span>{{ error }}</span>
      <Button type="button" size="sm" variant="outline" @click="loadClients">重试</Button>
    </div>

    <section class="overflow-hidden rounded-lg border bg-background">
      <header class="flex items-center justify-between gap-3 border-b bg-muted/20 px-4 py-3">
        <div>
          <h2 class="text-sm font-semibold">已注册应用</h2>
          <p class="mt-0.5 text-xs text-muted-foreground">{{ clients.length }} 个客户端</p>
        </div>
        <Button type="button" size="icon-sm" variant="ghost" :disabled="loading" title="刷新" @click="loadClients">
          <RefreshCw class="size-4" :class="loading ? 'animate-spin' : ''" />
        </Button>
      </header>

      <div v-if="loading && !clients.length" class="grid min-h-64 place-items-center">
        <Loader2 class="size-7 animate-spin text-muted-foreground" />
      </div>
      <div v-else-if="!clients.length" class="grid min-h-64 place-items-center px-6 text-center">
        <div>
          <KeyRound class="mx-auto size-8 text-muted-foreground" />
          <p class="mt-3 text-sm font-medium">还没有 OIDC 客户端</p>
          <p class="mt-1 text-xs text-muted-foreground">创建客户端后，外部应用即可使用 GooseForum 登录。</p>
        </div>
      </div>
      <div v-else class="divide-y">
        <article v-for="client in clients" :key="client.clientId" class="grid gap-4 px-4 py-4 md:grid-cols-[minmax(0,1fr)_auto] md:items-center">
          <div class="min-w-0">
            <div class="flex flex-wrap items-center gap-2">
              <h3 class="truncate text-sm font-semibold">{{ client.name }}</h3>
              <Badge variant="secondary">{{ client.public ? 'Public' : 'Confidential' }}</Badge>
              <Badge :variant="client.enabled ? 'default' : 'outline'">{{ client.enabled ? '已启用' : '已停用' }}</Badge>
            </div>
            <p class="mt-1 truncate font-mono text-xs text-muted-foreground">{{ client.clientId }}</p>
            <div class="mt-2 flex flex-wrap gap-1.5">
              <Badge v-for="scope in client.scopes" :key="scope" variant="outline" class="font-mono text-[11px] font-normal">{{ scope }}</Badge>
              <span class="text-xs text-muted-foreground">{{ client.redirectUris.length }} 个回调地址</span>
            </div>
          </div>
          <div class="flex items-center gap-1 md:justify-end">
            <label class="mr-2 flex items-center gap-2 text-xs text-muted-foreground">
              启用
              <Switch :model-value="client.enabled" :disabled="Boolean(togglingId)" @update:model-value="toggleEnabled(client, Boolean($event))" />
            </label>
            <Button v-if="!client.public" type="button" size="icon-sm" variant="ghost" title="重置客户端密钥" @click="rotateTarget = client">
              <RotateCw class="size-4" />
            </Button>
            <Button type="button" size="icon-sm" variant="ghost" title="编辑" @click="openEdit(client)">
              <Pencil class="size-4" />
            </Button>
          </div>
        </article>
      </div>
    </section>

    <Dialog v-model:open="editorOpen">
      <DialogContent class="max-h-[calc(100vh-2rem)] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>{{ editing ? '编辑 OIDC 客户端' : '新建 OIDC 客户端' }}</DialogTitle>
          <DialogDescription>客户端类型创建后不可更改；每行填写一个回调地址。</DialogDescription>
        </DialogHeader>

        <form id="oidc-client-form" class="grid gap-5" @submit.prevent="submit">
          <div class="grid gap-2">
            <Label for="oidc-client-name">应用名称</Label>
            <Input id="oidc-client-name" v-model="form.name" maxlength="255" placeholder="Internal Wiki" autofocus />
          </div>

          <div class="grid gap-2">
            <Label for="oidc-client-redirects">回调地址</Label>
            <Textarea id="oidc-client-redirects" v-model="form.redirectUris" class="min-h-24 font-mono text-xs" placeholder="https://wiki.example.com/oauth/callback" />
          </div>

          <fieldset class="grid gap-3">
            <legend class="text-sm font-medium">客户端类型</legend>
            <div class="grid gap-2 sm:grid-cols-2">
              <button type="button" class="rounded-md border p-3 text-left text-sm transition-colors" :class="!form.public ? 'border-primary bg-primary/5' : 'hover:bg-muted/50'" :disabled="editing" @click="setPublic(false)">
                <span class="font-medium">Confidential</span>
                <span class="mt-1 block text-xs text-muted-foreground">服务端应用，使用客户端密钥认证。</span>
              </button>
              <button type="button" class="rounded-md border p-3 text-left text-sm transition-colors" :class="form.public ? 'border-primary bg-primary/5' : 'hover:bg-muted/50'" :disabled="editing" @click="setPublic(true)">
                <span class="font-medium">Public</span>
                <span class="mt-1 block text-xs text-muted-foreground">浏览器或原生应用，强制 PKCE。</span>
              </button>
            </div>
          </fieldset>

          <div class="grid gap-4 sm:grid-cols-2">
            <div class="grid gap-2">
              <Label>Token 端点认证</Label>
              <Select v-model="form.tokenEndpointAuthMethod" :disabled="form.public">
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="client_secret_basic">client_secret_basic</SelectItem>
                  <SelectItem value="client_secret_post">client_secret_post</SelectItem>
                  <SelectItem v-if="form.public" value="none">none</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div class="flex items-center justify-between gap-4 rounded-md border px-3 py-2.5">
              <div>
                <p class="text-sm font-medium">要求 PKCE</p>
                <p class="text-xs text-muted-foreground">Public 客户端始终开启。</p>
              </div>
              <Switch :model-value="form.public || form.requirePkce" :disabled="form.public" @update:model-value="form.requirePkce = Boolean($event)" />
            </div>
          </div>

          <fieldset class="grid gap-2">
            <legend class="text-sm font-medium">允许的 Scope</legend>
            <div class="grid gap-2 sm:grid-cols-2">
              <label v-for="scope in supportedScopes" :key="scope" class="flex items-center justify-between rounded-md border px-3 py-2 text-sm">
                <span class="font-mono text-xs">{{ scope }}</span>
                <Switch :model-value="form.scopes.includes(scope)" :disabled="scope === 'openid'" @update:model-value="toggleScope(scope, Boolean($event))" />
              </label>
            </div>
          </fieldset>

          <label class="flex items-center justify-between gap-4 rounded-md border px-3 py-2.5">
            <span>
              <span class="block text-sm font-medium">启用客户端</span>
              <span class="block text-xs text-muted-foreground">停用后将拒绝新的授权和 Token 请求。</span>
            </span>
            <Switch v-model="form.enabled" />
          </label>
        </form>

        <DialogFooter>
          <Button type="button" variant="outline" @click="editorOpen = false">取消</Button>
          <Button type="submit" form="oidc-client-form" :disabled="saving">
            <Loader2 v-if="saving" class="size-4 animate-spin" />
            {{ saving ? '保存中' : '保存' }}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>

    <AdminConfirmDialog
      :open="signingKeyDialogOpen"
      :loading="signingKeyRotating"
      title="轮换 OIDC 签名密钥"
      description="新 ID Token 将立即使用新密钥签名；旧公钥会保留到所有已签发 ID Token 过期。"
      confirm-text="轮换密钥"
      @update:open="signingKeyDialogOpen = $event"
      @confirm="confirmSigningKeyRotation"
    />

    <AdminConfirmDialog
      :open="Boolean(rotateTarget)"
      :loading="rotating"
      title="重置客户端密钥"
      description="现有密钥会立即失效，依赖此客户端的应用需要同步更新。"
      confirm-text="重置密钥"
      @update:open="!$event && (rotateTarget = null)"
      @confirm="confirmRotate"
    />

    <Dialog :open="secretOpen" @update:open="setSecretOpen">
      <DialogContent class="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>客户端密钥</DialogTitle>
          <DialogDescription>该密钥只显示这一次。关闭后无法再次查看，只能重新生成。</DialogDescription>
        </DialogHeader>
        <div class="grid gap-3">
          <div>
            <p class="mb-1 text-xs font-medium text-muted-foreground">Client ID</p>
            <code class="block overflow-x-auto rounded-md border bg-muted/40 p-3 text-xs">{{ secretClientId }}</code>
          </div>
          <div>
            <p class="mb-1 text-xs font-medium text-muted-foreground">Client Secret</p>
            <div class="flex min-w-0 gap-2">
              <Input :model-value="revealedSecret" readonly class="min-w-0 font-mono text-xs" />
              <Button type="button" size="icon" variant="outline" :title="copied ? '已复制' : '复制密钥'" @click="copySecret">
                <Check v-if="copied" class="size-4" />
                <Copy v-else class="size-4" />
              </Button>
            </div>
          </div>
        </div>
        <DialogFooter>
          <Button type="button" @click="setSecretOpen(false)">我已妥善保存</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </BasicPage>
</template>
