// resource/src/site/pages/LoginPage.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { KeyRound, LoaderCircle, LockKeyhole, Mail, UserRound } from '@lucide/vue'
import { useI18n } from 'vue-i18n'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { forgotPassword, getCaptcha, login, register } from '@/runtime/api'
import { queueFlashMessage } from '@/runtime/flash-message'
import { setLocale, supportedLocales, type Locale } from '@/runtime/i18n'
import type { LayoutPayload, LoginPageProps } from '@gooseforum/client'

const page = defineProps<{
  layout: LayoutPayload
  props: LoginPageProps
}>()

type Mode = 'login' | 'register' | 'forgot'

const { t, locale } = useI18n()
const mode = ref<Mode>(page.props.initialMode || 'login')
const captchaImg = ref('')
const captchaId = ref('')
const captchaLoading = ref(false)
const notice = ref('')
const error = ref('')

const loading = reactive({
  login: false,
  register: false,
  forgot: false,
})

const loginForm = reactive({
  username: '',
  password: '',
  captcha: '',
})

const registerForm = reactive({
  username: '',
  email: '',
  password: '',
  confirmPassword: '',
  captcha: '',
  agree: false,
})

const forgotForm = reactive({
  email: '',
  captcha: '',
})

const title = computed(() => {
  if (mode.value === 'register') return t('auth.registerTitle')
  if (mode.value === 'forgot') return t('auth.forgotTitle')
  return t('auth.loginTitle')
})

const subtitle = computed(() => {
  if (mode.value === 'register') return t('auth.registerSubtitle')
  if (mode.value === 'forgot') return t('auth.forgotSubtitle')
  return t('auth.loginSubtitle')
})

const showSocial = computed(() => mode.value !== 'forgot' && page.props.oauthProviders.length > 0)
const homeUrl = computed(() => page.props.redirectUrl || '/')
const inputClass = 'h-10 rounded-[var(--gf-radius-field)] border-line bg-base-100 shadow-none focus-visible:border-primary focus-visible:ring-4 focus-visible:ring-primary/20'

onMounted(() => {
  refreshCaptcha()
})

function switchMode(next: Mode) {
  mode.value = next
  error.value = ''
  notice.value = ''
}

async function refreshCaptcha() {
  captchaLoading.value = true
  try {
    const captcha = await getCaptcha()
    captchaId.value = captcha.captchaId
    captchaImg.value = captcha.captchaImg
  } catch (err) {
    error.value = errorMessage(err, t('auth.validation.captchaLoadFailed'))
  } finally {
    captchaLoading.value = false
  }
}

async function handleLogin() {
  loginForm.username = loginForm.username.trim()
  loginForm.captcha = loginForm.captcha.trim()
  if (!loginForm.username || !loginForm.password || !loginForm.captcha) {
    error.value = t('auth.validation.loginRequired')
    return
  }
  loading.login = true
  error.value = ''
  try {
    await login(loginForm.username, loginForm.password, captchaId.value, loginForm.captcha)
    window.location.href = homeUrl.value
  } catch (err) {
    error.value = errorMessage(err, t('auth.validation.loginFailed'))
    loginForm.captcha = ''
    refreshCaptcha()
  } finally {
    loading.login = false
  }
}

async function handleRegister() {
  registerForm.username = registerForm.username.trim()
  registerForm.email = registerForm.email.trim()
  registerForm.captcha = registerForm.captcha.trim()
  if (!registerForm.username || !registerForm.email || !registerForm.password || !registerForm.captcha) {
    error.value = t('auth.validation.registerRequired')
    return
  }
  if (registerForm.password !== registerForm.confirmPassword) {
    error.value = t('auth.validation.passwordMismatch')
    return
  }
  if (!registerForm.agree) {
    error.value = t('auth.validation.termsRequired')
    return
  }
  loading.register = true
  error.value = ''
  try {
    const message = await register(registerForm.username, registerForm.email, registerForm.password, captchaId.value, registerForm.captcha, String(locale.value))
    queueFlashMessage(message || t('auth.validation.registerSuccess'), 'success')
    window.location.href = homeUrl.value
  } catch (err) {
    error.value = errorMessage(err, t('auth.validation.registerFailed'))
    registerForm.captcha = ''
    refreshCaptcha()
  } finally {
    loading.register = false
  }
}

async function handleForgot() {
  forgotForm.email = forgotForm.email.trim()
  forgotForm.captcha = forgotForm.captcha.trim()
  if (!forgotForm.email || !forgotForm.captcha) {
    error.value = t('auth.validation.forgotRequired')
    return
  }
  loading.forgot = true
  error.value = ''
  try {
    notice.value = await forgotPassword(forgotForm.email, captchaId.value, forgotForm.captcha)
    forgotForm.captcha = ''
    refreshCaptcha()
  } catch (err) {
    error.value = errorMessage(err, t('auth.validation.resetEmailFailed'))
    forgotForm.captcha = ''
    refreshCaptcha()
  } finally {
    loading.forgot = false
  }
}

function switchLocale(next: Locale) {
  setLocale(next)
}

function errorMessage(err: unknown, fallback: string) {
  return err instanceof Error && err.message ? err.message : fallback
}
</script>

<template>
  <main class="relative min-h-screen bg-base-100 text-base-content sm:bg-base-200 sm:px-6 sm:py-8 lg:px-8">
    <Tabs
      :model-value="locale"
      class="absolute right-3 top-3 z-10 sm:right-4 sm:top-4"
      @update:model-value="switchLocale($event as Locale)"
    >
      <TabsList class="inline-flex h-auto items-center gap-1 rounded-full border border-line bg-base-100 p-1 shadow-[0_8px_22px_-16px_rgb(15_23_42/calc(var(--gf-depth)*0.5))]">
        <TabsTrigger
          v-for="item in supportedLocales"
          :key="item"
          :value="item"
          class="h-8 min-w-8 rounded-full px-2 text-xs font-semibold text-base-content/55 shadow-none data-[state=active]:bg-neutral data-[state=active]:text-neutral-content data-[state=active]:shadow-sm hover:text-base-content data-[state=active]:hover:bg-neutral data-[state=active]:hover:text-neutral-content"
        >
          {{ t(`locale.short.${item}`) }}
        </TabsTrigger>
      </TabsList>
    </Tabs>

    <section class="mx-auto flex min-h-screen w-full max-w-[880px] items-stretch justify-center sm:min-h-[calc(100vh-4rem)] sm:items-center">
      <div class="gf-card grid w-full overflow-hidden border-0 shadow-none sm:border sm:shadow-[0_2px_12px_rgb(0_0_0/calc(var(--gf-depth)*0.04))] md:grid-cols-2">
        <div class="flex min-h-screen flex-col justify-center px-4 py-12 sm:min-h-[470px] sm:px-8 sm:py-6">
          <a href="/" class="mb-6 inline-flex items-baseline text-[27px] font-semibold leading-none tracking-[-0.04em] text-primary">
            <span v-if="page.layout.site.brandType === 'image' && page.layout.site.brandImage" class="inline-flex">
              <img :src="page.layout.site.brandImage" :alt="page.layout.site.name" class="h-8 w-auto object-contain" />
            </span>
            <span v-else-if="page.layout.site.brandType === 'text'">
              {{ page.layout.site.brandText || page.layout.site.name }}
            </span>
            <span v-else>
              Goose<span class="text-base-content">Forum</span>
            </span>
          </a>

          <div class="mb-4">
            <h1 class="text-[27px] font-bold leading-tight tracking-tight text-base-content">{{ title }}</h1>
            <p class="mt-1.5 text-sm leading-6 text-base-content/55">{{ subtitle }}</p>
          </div>

          <Tabs v-if="mode !== 'forgot'" :model-value="mode" class="mb-4" @update:model-value="value => switchMode(value as Mode)">
            <TabsList class="grid w-full grid-cols-2">
              <TabsTrigger value="login">{{ t('shell.login') }}</TabsTrigger>
              <TabsTrigger value="register">{{ t('shell.register') }}</TabsTrigger>
            </TabsList>
          </Tabs>

          <p v-if="error" class="gf-status-message gf-status-message-error mb-4">{{ error }}</p>
          <p v-if="notice" class="gf-status-message gf-status-message-success mb-4">{{ notice }}</p>

          <form v-if="mode === 'login'" class="space-y-3" @submit.prevent="handleLogin">
            <label class="block">
              <span class="sr-only">{{ t('auth.usernameOrEmail') }}</span>
              <span class="relative block">
                <UserRound class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-base-content/55" />
                <Input v-model="loginForm.username" :class="[inputClass, 'pl-10']" :placeholder="t('auth.usernameOrEmail')" autocomplete="username" />
              </span>
            </label>
            <label class="block">
              <span class="sr-only">{{ t('auth.password') }}</span>
              <span class="relative block">
                <LockKeyhole class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-base-content/55" />
                <Input v-model="loginForm.password" type="password" :class="[inputClass, 'pl-10']" :placeholder="t('auth.password')" autocomplete="current-password" />
              </span>
            </label>
            <div class="flex gap-3">
              <Input v-model="loginForm.captcha" :class="[inputClass, 'min-w-0 flex-1']" :placeholder="t('auth.captcha')" />
              <Button type="button" variant="surface" class="relative h-10 w-28 overflow-hidden rounded-md p-0 shadow-none gf-panel" @click="refreshCaptcha">
                <LoaderCircle v-if="captchaLoading || !captchaImg" class="mx-auto h-5 w-5 animate-spin text-base-content/55" />
                <img v-else :src="captchaImg" :alt="t('auth.captchaAlt')" class="h-full w-full object-cover" />
              </Button>
            </div>
            <div class="flex justify-end">
              <Button type="button" variant="brand-ghost" size="sm" class="h-auto px-0 py-0" @click="switchMode('forgot')">{{ t('auth.forgotPassword') }}</Button>
            </div>
            <Button type="submit" variant="brand" size="xl" class="w-full" :disabled="loading.login">
              <LoaderCircle v-if="loading.login" class="h-4 w-4 animate-spin" />
              {{ t('shell.login') }}
            </Button>
          </form>

          <form v-else-if="mode === 'register'" class="space-y-3" @submit.prevent="handleRegister">
            <label class="block">
              <span class="sr-only">{{ t('auth.username') }}</span>
              <span class="relative block">
                <UserRound class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-base-content/55" />
                <Input v-model="registerForm.username" :class="[inputClass, 'pl-10']" :placeholder="t('auth.username')" autocomplete="username" />
              </span>
            </label>
            <label class="block">
              <span class="sr-only">{{ t('auth.email') }}</span>
              <span class="relative block">
                <Mail class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-base-content/55" />
                <Input v-model="registerForm.email" type="email" :class="[inputClass, 'pl-10']" :placeholder="t('auth.email')" autocomplete="email" />
              </span>
            </label>
            <label class="block">
              <span class="sr-only">{{ t('auth.password') }}</span>
              <span class="relative block">
                <LockKeyhole class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-base-content/55" />
                <Input v-model="registerForm.password" type="password" :class="[inputClass, 'pl-10']" :placeholder="t('auth.password')" autocomplete="new-password" />
              </span>
            </label>
            <label class="block">
              <span class="sr-only">{{ t('auth.confirmPassword') }}</span>
              <span class="relative block">
                <LockKeyhole class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-base-content/55" />
                <Input v-model="registerForm.confirmPassword" type="password" :class="[inputClass, 'pl-10']" :placeholder="t('auth.confirmPassword')" autocomplete="new-password" />
              </span>
            </label>
            <div class="flex gap-3">
              <span class="relative min-w-0 flex-1">
                <Input v-model="registerForm.captcha" :class="inputClass" :placeholder="t('auth.captcha')" />
              </span>
              <Button type="button" variant="surface" class="relative h-10 w-28 overflow-hidden rounded-md p-0 shadow-none gf-panel" @click="refreshCaptcha">
                <LoaderCircle v-if="captchaLoading || !captchaImg" class="mx-auto h-5 w-5 animate-spin text-base-content/55" />
                <img v-else :src="captchaImg" :alt="t('auth.captchaAlt')" class="h-full w-full object-cover" />
              </Button>
            </div>
            <label class="flex items-start gap-2 text-sm leading-5 text-base-content/55">
              <Checkbox v-model="registerForm.agree" class="mt-1 border-line shadow-none focus-visible:ring-primary" />
              <span>{{ t('auth.agreeTerms') }}</span>
            </label>
            <Button type="submit" variant="neutral" size="xl" class="w-full" :disabled="loading.register">
              <LoaderCircle v-if="loading.register" class="h-4 w-4 animate-spin" />
              {{ t('auth.createAccount') }}
            </Button>
          </form>

          <form v-else class="space-y-3.5" @submit.prevent="handleForgot">
            <label class="block">
              <span class="relative block">
                <Mail class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-base-content/55" />
                <Input v-model="forgotForm.email" type="email" :class="[inputClass, 'pl-10']" :placeholder="t('auth.registeredEmail')" autocomplete="email" />
              </span>
            </label>
            <div class="flex gap-3">
              <Input v-model="forgotForm.captcha" :class="[inputClass, 'min-w-0 flex-1']" :placeholder="t('auth.captcha')" />
              <Button type="button" variant="surface" class="relative h-10 w-28 overflow-hidden rounded-md p-0 shadow-none gf-panel" @click="refreshCaptcha">
                <LoaderCircle v-if="captchaLoading || !captchaImg" class="mx-auto h-5 w-5 animate-spin text-base-content/55" />
                <img v-else :src="captchaImg" :alt="t('auth.captchaAlt')" class="h-full w-full object-cover" />
              </Button>
            </div>
            <Button type="submit" variant="brand" size="xl" class="w-full" :disabled="loading.forgot">
              <LoaderCircle v-if="loading.forgot" class="h-4 w-4 animate-spin" />
              {{ t('auth.sendResetEmail') }}
            </Button>
            <Button type="button" variant="brand-ghost" size="sm" class="h-auto w-full py-0" @click="switchMode('login')">{{ t('auth.backToLogin') }}</Button>
          </form>

          <div v-if="showSocial" class="mt-5 border-t border-line pt-4 md:hidden">
            <h2 class="mb-2 text-xs font-bold uppercase text-base-content/45">{{ t('auth.continueWith') }}</h2>
            <div class="grid grid-cols-1 gap-2 sm:grid-cols-2">
              <Button v-for="provider in page.props.oauthProviders" :key="provider.key" as-child variant="surface" class="w-full px-3">
                <a :href="provider.loginUrl">
                  <svg v-if="provider.key === 'github'" class="h-4 w-4" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                    <path d="M12 0C5.37 0 0 5.37 0 12c0 5.3 3.44 9.8 8.21 11.39.6.11.79-.26.79-.58v-2.03c-3.34.73-4.04-1.42-4.04-1.42-.55-1.39-1.34-1.76-1.34-1.76-1.09-.75.08-.73.08-.73 1.21.08 1.85 1.24 1.85 1.24 1.07 1.83 2.81 1.3 3.49 1 .11-.78.42-1.3.76-1.6-2.67-.31-5.47-1.34-5.47-5.93 0-1.31.47-2.38 1.24-3.22-.12-.3-.54-1.52.12-3.18 0 0 1.01-.32 3.3 1.23A11.5 11.5 0 0 1 12 6c1.02 0 2.05.14 3.01.4 2.29-1.55 3.3-1.23 3.3-1.23.65 1.66.24 2.88.12 3.18.77.84 1.24 1.91 1.24 3.22 0 4.61-2.81 5.62-5.48 5.92.43.37.81 1.1.81 2.22v3.29c0 .32.19.69.8.58A12.01 12.01 0 0 0 24 12c0-6.63-5.37-12-12-12Z" />
                  </svg>
                  <KeyRound v-else class="h-4 w-4" />
                  {{ provider.displayName }}
                </a>
              </Button>
            </div>
          </div>
        </div>

        <aside class="hidden border-t border-line bg-base-200/70 px-4 py-6 sm:px-8 md:block md:border-l md:border-t-0">
          <div class="flex h-full flex-col justify-center">
            <div v-if="showSocial">
              <h2 class="text-sm font-bold text-base-content">{{ t('auth.continueWith') }}</h2>
              <div class="mt-8 space-y-3.5">
                <Button v-for="provider in page.props.oauthProviders" :key="provider.key" as-child variant="surface" size="lg" class="w-full px-4">
                  <a :href="provider.loginUrl">
                    <svg v-if="provider.key === 'github'" class="h-5 w-5" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                      <path d="M12 0C5.37 0 0 5.37 0 12c0 5.3 3.44 9.8 8.21 11.39.6.11.79-.26.79-.58v-2.03c-3.34.73-4.04-1.42-4.04-1.42-.55-1.39-1.34-1.76-1.34-1.76-1.09-.75.08-.73.08-.73 1.21.08 1.85 1.24 1.85 1.24 1.07 1.83 2.81 1.3 3.49 1 .11-.78.42-1.3.76-1.6-2.67-.31-5.47-1.34-5.47-5.93 0-1.31.47-2.38 1.24-3.22-.12-.3-.54-1.52.12-3.18 0 0 1.01-.32 3.3 1.23A11.5 11.5 0 0 1 12 6c1.02 0 2.05.14 3.01.4 2.29-1.55 3.3-1.23 3.3-1.23.65 1.66.24 2.88.12 3.18.77.84 1.24 1.91 1.24 3.22 0 4.61-2.81 5.62-5.48 5.92.43.37.81 1.1.81 2.22v3.29c0 .32.19.69.8.58A12.01 12.01 0 0 0 24 12c0-6.63-5.37-12-12-12Z" />
                    </svg>
                    <KeyRound v-else class="h-5 w-5" />
                    {{ provider.displayName }}
                  </a>
                </Button>
              </div>
            </div>
          </div>
        </aside>
      </div>
    </section>
  </main>
</template>

// resource/packages/theme-default/src/site/auth/login-page.tsx
"use client"

import {
  useCallback,
  useEffect,
  useState,
  type ComponentProps,
  type FormEvent,
} from 'react'
import {
  CircleAlertIcon,
  CircleCheckIcon,
  KeyRoundIcon,
} from 'lucide-react'
import {
  loginWithPassword,
  type LayoutPayload,
  type LoginPageProps,
} from '@gooseforum/client'
import { useTranslation } from 'react-i18next'
import { Alert, AlertDescription } from '@gooseforum/ui/components/alert'
import { Button } from '@gooseforum/ui/components/button'
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@gooseforum/ui/components/card'
import { Checkbox } from '@gooseforum/ui/components/checkbox'
import { Field, FieldGroup, FieldLabel } from '@gooseforum/ui/components/field'
import { Input } from '@gooseforum/ui/components/input'
import { Spinner } from '@gooseforum/ui/components/spinner'
import { Tabs, TabsList, TabsTrigger } from '@gooseforum/ui/components/tabs'
import { useGooseRuntime } from '@gooseforum/runtime'
import { AuthBrand } from './auth-brand'
import { AuthLocaleSwitcher } from './auth-locale-switcher'

type Mode = 'login' | 'register' | 'forgot'

interface LoginPageViewProps {
  layout: LayoutPayload
  page: LoginPageProps
}

export function LoginPageView({ layout, page }: LoginPageViewProps) {
  const runtime = useGooseRuntime()
  const { t } = useTranslation('auth')
  const [mode, setMode] = useState<Mode>(page.initialMode || 'login')
  const [captcha, setCaptcha] = useState({ id: '', image: '' })
  const [captchaLoading, setCaptchaLoading] = useState(false)
  const [pending, setPending] = useState<Mode | null>(null)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [loginForm, setLoginForm] = useState({ username: '', password: '', captcha: '' })
  const [registerForm, setRegisterForm] = useState({
    username: '', email: '', password: '', confirmPassword: '', captcha: '', agree: false,
  })
  const [forgotForm, setForgotForm] = useState({ email: '', captcha: '' })

  const refreshCaptcha = useCallback(async () => {
    setCaptchaLoading(true)
    try {
      const nextCaptcha = await runtime.api.auth.captcha()
      setCaptcha({ id: nextCaptcha.captchaId, image: nextCaptcha.captchaImg })
    } catch (nextError) {
      setError(errorMessage(nextError, t('validation.captchaLoadFailed')))
    } finally {
      setCaptchaLoading(false)
    }
  }, [runtime.api.auth, t])

  useEffect(() => {
    void refreshCaptcha()
  }, [refreshCaptcha])

  function switchMode(nextMode: Mode) {
    setMode(nextMode)
    setError('')
    setNotice('')
  }

  async function handleLogin(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const username = loginForm.username.trim()
    const captchaCode = loginForm.captcha.trim()
    if (!username || !loginForm.password || !captchaCode) {
      setError(t('validation.loginRequired'))
      return
    }

    setPending('login')
    setError('')
    try {
      await loginWithPassword(runtime.api.auth, {
        username,
        password: loginForm.password,
        captchaId: captcha.id,
        captchaCode,
      })
      await runtime.navigate(page.redirectUrl || '/', { replace: true })
    } catch (nextError) {
      setError(errorMessage(nextError, t('validation.loginFailed')))
      setLoginForm((current) => ({ ...current, captcha: '' }))
      void refreshCaptcha()
    } finally {
      setPending(null)
    }
  }

  async function handleRegister(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const username = registerForm.username.trim()
    const email = registerForm.email.trim()
    const captchaCode = registerForm.captcha.trim()
    if (!username || !email || !registerForm.password || !captchaCode) {
      setError(t('validation.registerRequired'))
      return
    }
    if (registerForm.password !== registerForm.confirmPassword) {
      setError(t('validation.passwordMismatch'))
      return
    }
    if (!registerForm.agree) {
      setError(t('validation.termsRequired'))
      return
    }

    setPending('register')
    setError('')
    try {
      const result = await runtime.api.auth.register({
        username,
        email,
        password: registerForm.password,
        captchaId: captcha.id,
        captchaCode,
        locale: runtime.locale,
      })
      runtime.queueFlash(result.message || t('validation.registerSuccess'), 'success')
      await runtime.navigate(page.redirectUrl || '/', { replace: true })
    } catch (nextError) {
      setError(errorMessage(nextError, t('validation.registerFailed')))
      setRegisterForm((current) => ({ ...current, captcha: '' }))
      void refreshCaptcha()
    } finally {
      setPending(null)
    }
  }

  async function handleForgot(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const email = forgotForm.email.trim()
    const captchaCode = forgotForm.captcha.trim()
    if (!email || !captchaCode) {
      setError(t('validation.forgotRequired'))
      return
    }

    setPending('forgot')
    setError('')
    try {
      const result = await runtime.api.auth.forgotPassword(email, captcha.id, captchaCode)
      setNotice(result.message || t('server.passwordResetMailQueued'))
      setForgotForm((current) => ({ ...current, captcha: '' }))
      void refreshCaptcha()
    } catch (nextError) {
      setError(errorMessage(nextError, t('validation.resetEmailFailed')))
      setForgotForm((current) => ({ ...current, captcha: '' }))
      void refreshCaptcha()
    } finally {
      setPending(null)
    }
  }

  const title = mode === 'register'
    ? t('registerTitle')
    : mode === 'forgot'
      ? t('forgotTitle')
      : t('loginTitle')
  const subtitle = mode === 'register'
    ? t('registerSubtitle')
    : mode === 'forgot'
      ? t('forgotSubtitle')
      : t('loginSubtitle')
  const showOAuth = mode !== 'forgot' && page.oauthProviders.length > 0

  return (
    <main className="relative flex min-h-svh items-center justify-center bg-muted px-4 py-16 sm:px-6">
      <AuthLocaleSwitcher />

      <Card className="w-full max-w-md">
        <CardHeader>
          <AuthBrand layout={layout} />
          <CardTitle className="text-2xl">
            <h1>{title}</h1>
          </CardTitle>
          <p className="text-sm leading-6 text-muted-foreground">{subtitle}</p>
        </CardHeader>

        <CardContent className="flex flex-col gap-4">
          {mode !== 'forgot'
            ? (
                <Tabs value={mode} onValueChange={(value) => switchMode(value as Mode)}>
                  <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="login">{t('login')}</TabsTrigger>
                    <TabsTrigger value="register">{t('register')}</TabsTrigger>
                  </TabsList>
                </Tabs>
              )
            : null}

          {error
            ? (
                <Alert variant="destructive">
                  <CircleAlertIcon />
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )
            : notice
              ? (
                  <Alert>
                    <CircleCheckIcon />
                    <AlertDescription>{notice}</AlertDescription>
                  </Alert>
                )
              : null}

          {mode === 'login'
            ? (
                <form onSubmit={handleLogin} noValidate>
                  <FieldGroup className="gap-3">
                    <TextField
                      id="login-username"
                      label={t('usernameOrEmail')}
                      autoComplete="username"
                      value={loginForm.username}
                      onChange={(event) => setLoginForm((current) => ({ ...current, username: event.target.value }))}
                    />
                    <TextField
                      id="login-password"
                      label={t('password')}
                      type="password"
                      autoComplete="current-password"
                      value={loginForm.password}
                      onChange={(event) => setLoginForm((current) => ({ ...current, password: event.target.value }))}
                    />
                    <CaptchaField
                      value={loginForm.captcha}
                      onChange={(value) => setLoginForm((current) => ({ ...current, captcha: value }))}
                      image={captcha.image}
                      loading={captchaLoading}
                      label={t('captcha')}
                      imageAlt={t('captchaAlt')}
                      refreshLabel={t('refreshCaptcha')}
                      onRefresh={() => void refreshCaptcha()}
                    />
                    <Button type="button" variant="link" className="self-end px-0" onClick={() => switchMode('forgot')}>
                      {t('forgotPassword')}
                    </Button>
                    <SubmitButton pending={pending === 'login'}>{t('login')}</SubmitButton>
                  </FieldGroup>
                </form>
              )
            : mode === 'register'
              ? (
                  <form onSubmit={handleRegister} noValidate>
                    <FieldGroup className="gap-3">
                      <TextField
                        id="register-username"
                        label={t('username')}
                        autoComplete="username"
                        value={registerForm.username}
                        onChange={(event) => setRegisterForm((current) => ({ ...current, username: event.target.value }))}
                      />
                      <TextField
                        id="register-email"
                        label={t('email')}
                        type="email"
                        autoComplete="email"
                        value={registerForm.email}
                        onChange={(event) => setRegisterForm((current) => ({ ...current, email: event.target.value }))}
                      />
                      <TextField
                        id="register-password"
                        label={t('password')}
                        type="password"
                        autoComplete="new-password"
                        value={registerForm.password}
                        onChange={(event) => setRegisterForm((current) => ({ ...current, password: event.target.value }))}
                      />
                      <TextField
                        id="register-confirm-password"
                        label={t('confirmPassword')}
                        type="password"
                        autoComplete="new-password"
                        value={registerForm.confirmPassword}
                        onChange={(event) => setRegisterForm((current) => ({ ...current, confirmPassword: event.target.value }))}
                      />
                      <CaptchaField
                        value={registerForm.captcha}
                        onChange={(value) => setRegisterForm((current) => ({ ...current, captcha: value }))}
                        image={captcha.image}
                        loading={captchaLoading}
                        label={t('captcha')}
                        imageAlt={t('captchaAlt')}
                        refreshLabel={t('refreshCaptcha')}
                        onRefresh={() => void refreshCaptcha()}
                      />
                      <Field orientation="horizontal">
                        <Checkbox
                          id="register-terms"
                          checked={registerForm.agree}
                          onCheckedChange={(checked) => setRegisterForm((current) => ({ ...current, agree: checked === true }))}
                        />
                        <FieldLabel htmlFor="register-terms">{t('agreeTerms')}</FieldLabel>
                      </Field>
                      <SubmitButton pending={pending === 'register'}>{t('createAccount')}</SubmitButton>
                    </FieldGroup>
                  </form>
                )
              : (
                  <form onSubmit={handleForgot} noValidate>
                    <FieldGroup className="gap-3">
                      <TextField
                        id="forgot-email"
                        label={t('registeredEmail')}
                        type="email"
                        autoComplete="email"
                        value={forgotForm.email}
                        onChange={(event) => setForgotForm((current) => ({ ...current, email: event.target.value }))}
                      />
                      <CaptchaField
                        value={forgotForm.captcha}
                        onChange={(value) => setForgotForm((current) => ({ ...current, captcha: value }))}
                        image={captcha.image}
                        loading={captchaLoading}
                        label={t('captcha')}
                        imageAlt={t('captchaAlt')}
                        refreshLabel={t('refreshCaptcha')}
                        onRefresh={() => void refreshCaptcha()}
                      />
                      <SubmitButton pending={pending === 'forgot'}>{t('sendResetEmail')}</SubmitButton>
                      <Button type="button" variant="link" onClick={() => switchMode('login')}>
                        {t('backToLogin')}
                      </Button>
                    </FieldGroup>
                  </form>
                )}
        </CardContent>

        {showOAuth
          ? (
              <CardFooter className="flex-col items-stretch gap-3">
                <p className="text-center text-xs font-medium text-muted-foreground">{t('continueWith')}</p>
                <div className="grid gap-2 sm:grid-cols-2">
                  {page.oauthProviders.map((provider) => (
                    <Button key={provider.key} asChild variant="outline">
                      <a href={provider.loginUrl}>
                        {provider.key === 'github'
                          ? <GithubMark />
                          : <KeyRoundIcon data-icon="inline-start" />}
                        {provider.displayName}
                      </a>
                    </Button>
                  ))}
                </div>
              </CardFooter>
            )
          : null}
      </Card>
    </main>
  )
}

function TextField({ id, label, ...props }: Omit<ComponentProps<typeof Input>, 'id' | 'className'> & {
  id: string
  label: string
}) {
  return (
    <Field>
      <FieldLabel htmlFor={id}>{label}</FieldLabel>
      <Input {...props} id={id} className="h-10" />
    </Field>
  )
}

function CaptchaField({
  value,
  onChange,
  image,
  loading,
  label,
  imageAlt,
  refreshLabel,
  onRefresh,
}: {
  value: string
  onChange(value: string): void
  image: string
  loading: boolean
  label: string
  imageAlt: string
  refreshLabel: string
  onRefresh(): void
}) {
  return (
    <Field>
      <FieldLabel htmlFor="auth-captcha">{label}</FieldLabel>
      <div className="flex gap-3">
        <Input
          id="auth-captcha"
          className="h-10"
          value={value}
          onChange={(event) => onChange(event.target.value)}
          autoComplete="off"
        />
        <Button
          type="button"
          variant="outline"
          className="h-10 w-28 overflow-hidden p-0"
          onClick={onRefresh}
          aria-label={refreshLabel}
          title={refreshLabel}
        >
          {loading || !image
            ? <Spinner />
            : <img src={image} alt={imageAlt} className="h-full w-full object-cover" />}
        </Button>
      </div>
    </Field>
  )
}

function SubmitButton({ pending, children }: { pending: boolean, children: string }) {
  return (
    <Button type="submit" size="lg" className="w-full" disabled={pending}>
      {pending ? <Spinner data-icon="inline-start" /> : null}
      {children}
    </Button>
  )
}

function GithubMark() {
  return (
    <svg data-icon="inline-start" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path d="M12 0C5.37 0 0 5.37 0 12c0 5.3 3.44 9.8 8.21 11.39.6.11.79-.26.79-.58v-2.03c-3.34.73-4.04-1.42-4.04-1.42-.55-1.39-1.34-1.76-1.34-1.76-1.09-.75.08-.73.08-.73 1.21.08 1.85 1.24 1.85 1.24 1.07 1.83 2.81 1.3 3.49 1 .11-.78.42-1.3.76-1.6-2.67-.31-5.47-1.34-5.47-5.93 0-1.31.47-2.38 1.24-3.22-.12-.3-.54-1.52.12-3.18 0 0 1.01-.32 3.3 1.23A11.5 11.5 0 0 1 12 6c1.02 0 2.05.14 3.01.4 2.29-1.55 3.3-1.23 3.3-1.23.65 1.66.24 2.88.12 3.18.77.84 1.24 1.91 1.24 3.22 0 4.61-2.81 5.62-5.48 5.92.43.37.81 1.1.81 2.22v3.29c0 .32.19.69.8.58A12.01 12.01 0 0 0 24 12c0-6.63-5.37-12-12-12Z" />
    </svg>
  )
}

function errorMessage(error: unknown, fallback: string) {
  return error instanceof Error && error.message ? error.message : fallback
}
