// resource/src/site/pages/ResetPasswordPage.vue
<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { Check, LoaderCircle, LockKeyhole } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { resetPassword } from '@/runtime/api'
import type { LayoutPayload, ResetPasswordPageProps } from '@gooseforum/client'

const page = defineProps<{
  layout: LayoutPayload
  props: ResetPasswordPageProps
}>()
const { t } = useI18n()

const form = reactive({
  password: '',
  confirmPassword: '',
})
const loading = ref(false)
const error = ref('')
const success = ref('')

const canSubmit = computed(() => Boolean(page.props.token && form.password && form.confirmPassword && !loading.value))

async function submit() {
  error.value = ''
  success.value = ''
  if (!page.props.token) {
    error.value = t('auth.resetMissingToken')
    return
  }
  if (form.password.length < 6) {
    error.value = t('auth.passwordMinLength')
    return
  }
  if (form.password !== form.confirmPassword) {
    error.value = t('auth.validation.passwordMismatch')
    return
  }
  loading.value = true
  try {
    success.value = await resetPassword(page.props.token, form.password)
    form.password = ''
    form.confirmPassword = ''
  } catch (err) {
    error.value = err instanceof Error && err.message ? err.message : t('api.passwordResetFailed')
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <main class="min-h-screen bg-base-100 text-base-content sm:bg-base-200 sm:px-6 sm:py-8 lg:px-8">
    <section class="mx-auto flex min-h-screen w-full max-w-[880px] items-stretch justify-center sm:min-h-[calc(100vh-4rem)] sm:items-center">
      <div class="gf-card grid w-full overflow-hidden border-0 shadow-none sm:border sm:shadow-[0_2px_12px_rgb(0_0_0/calc(var(--gf-depth)*0.04))] md:grid-cols-2">
        <div class="flex min-h-screen flex-col justify-center px-4 py-12 sm:min-h-[470px] sm:px-8 sm:py-6">
          <a href="/" class="mb-6 inline-flex items-baseline text-[27px] font-semibold leading-none tracking-[-0.04em] text-primary">
            <span v-if="page.layout.site.brandType === 'image' && page.layout.site.brandImage">
              <img :src="page.layout.site.brandImage" :alt="page.layout.site.name" class="h-8 w-auto object-contain" />
            </span>
            <span v-else-if="page.layout.site.brandType === 'text'">
              {{ page.layout.site.brandText || page.layout.site.name }}
            </span>
            <span v-else>Goose<span class="text-base-content">Forum</span></span>
          </a>

          <div class="mb-4">
            <h1 class="text-[27px] font-bold leading-tight tracking-tight text-base-content">{{ t('auth.resetPasswordTitle') }}</h1>
            <p class="mt-1.5 text-sm leading-6 text-base-content/55">{{ t('auth.resetPasswordSubtitle') }}</p>
          </div>

          <p v-if="error" class="gf-status-message gf-status-message-error mb-4">{{ error }}</p>
          <p v-if="success" class="gf-status-message gf-status-message-success mb-4">{{ success }}</p>

          <form class="space-y-3.5" @submit.prevent="submit">
            <label class="block">
              <span class="sr-only">{{ t('auth.newPassword') }}</span>
              <span class="relative block">
                <LockKeyhole class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-base-content/55" />
                <Input v-model="form.password" type="password" class="h-10 rounded-[var(--gf-radius-field)] border-line bg-base-100 pl-10 shadow-none focus-visible:border-primary focus-visible:ring-4 focus-visible:ring-primary/20" :placeholder="t('auth.newPassword')" autocomplete="new-password" />
              </span>
            </label>
            <label class="block">
              <span class="sr-only">{{ t('auth.confirmPassword') }}</span>
              <span class="relative block">
                <LockKeyhole class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-base-content/55" />
                <Input v-model="form.confirmPassword" type="password" class="h-10 rounded-[var(--gf-radius-field)] border-line bg-base-100 pl-10 shadow-none focus-visible:border-primary focus-visible:ring-4 focus-visible:ring-primary/20" :placeholder="t('auth.confirmPassword')" autocomplete="new-password" />
              </span>
            </label>
            <Button type="submit" variant="brand" size="xl" class="w-full" :disabled="!canSubmit">
              <LoaderCircle v-if="loading" class="h-4 w-4 animate-spin" />
              {{ t('auth.saveNewPassword') }}
            </Button>
            <Button as-child variant="brand-ghost" size="lg" class="w-full px-4">
              <a href="/login">{{ t('auth.backToLogin') }}</a>
            </Button>
          </form>
        </div>

        <aside class="border-t border-line bg-base-200/70 px-4 py-6 sm:px-8 md:border-l md:border-t-0">
          <div class="flex h-full flex-col justify-center">
            <h2 class="text-lg font-bold text-base-content">{{ t('auth.passwordAdviceTitle') }}</h2>
            <p class="mt-3 text-sm leading-6 text-base-content/55">{{ t('auth.passwordAdviceDescription') }}</p>
            <ul class="mt-6 space-y-3 text-sm text-base-content/75">
              <li class="flex items-center gap-2"><Check class="h-4 w-4 text-success" /> {{ t('auth.passwordAdvice.length') }}</li>
              <li class="flex items-center gap-2"><Check class="h-4 w-4 text-success" /> {{ t('auth.passwordAdvice.unique') }}</li>
              <li class="flex items-center gap-2"><Check class="h-4 w-4 text-success" /> {{ t('auth.passwordAdvice.loginAfterReset') }}</li>
            </ul>
          </div>
        </aside>
      </div>
    </section>
  </main>
</template>

// resource/packages/theme-default/src/site/auth/reset-password-page.tsx
"use client"

import { useState, type FormEvent } from 'react'
import { CheckIcon, CircleAlertIcon, CircleCheckIcon } from 'lucide-react'
import type { LayoutPayload, ResetPasswordPageProps } from '@gooseforum/client'
import { useTranslation } from 'react-i18next'
import { Alert, AlertDescription } from '@gooseforum/ui/components/alert'
import { Button } from '@gooseforum/ui/components/button'
import { Card, CardContent, CardHeader, CardTitle } from '@gooseforum/ui/components/card'
import { Field, FieldGroup, FieldLabel } from '@gooseforum/ui/components/field'
import { Input } from '@gooseforum/ui/components/input'
import { Spinner } from '@gooseforum/ui/components/spinner'
import { GooseLink, useGooseRuntime } from '@gooseforum/runtime'
import { AuthBrand } from './auth-brand'

export function ResetPasswordPageView({
  layout,
  page,
}: {
  layout: LayoutPayload
  page: ResetPasswordPageProps
}) {
  const { t } = useTranslation('auth')
  const runtime = useGooseRuntime()
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [pending, setPending] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setError('')
    setSuccess('')
    if (!page.token) {
      setError(t('resetMissingToken'))
      return
    }
    if (password.length < 6) {
      setError(t('passwordMinLength'))
      return
    }
    if (password !== confirmPassword) {
      setError(t('validation.passwordMismatch'))
      return
    }

    setPending(true)
    try {
      const result = await runtime.api.auth.resetPassword(page.token, password)
      setSuccess(result.message || t('server.passwordResetSuccess'))
      setPassword('')
      setConfirmPassword('')
    } catch (nextError) {
      setError(nextError instanceof Error && nextError.message
        ? nextError.message
        : t('server.passwordResetFailed'))
    } finally {
      setPending(false)
    }
  }

  return (
    <main className="flex min-h-svh items-center justify-center bg-muted px-4 py-12 sm:px-6">
      <Card className="w-full max-w-3xl md:grid md:grid-cols-2">
        <section className="flex flex-col justify-center">
          <CardHeader>
            <AuthBrand layout={layout} />
            <CardTitle className="text-2xl"><h1>{t('resetPasswordTitle')}</h1></CardTitle>
            <p className="text-sm leading-6 text-muted-foreground">{t('resetPasswordSubtitle')}</p>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            {!page.token
              ? (
                  <Alert variant="destructive">
                    <CircleAlertIcon />
                    <AlertDescription>{t('resetMissingToken')}</AlertDescription>
                  </Alert>
                )
              : error
                ? (
                    <Alert variant="destructive">
                      <CircleAlertIcon />
                      <AlertDescription>{error}</AlertDescription>
                    </Alert>
                  )
                : success
                  ? (
                      <Alert>
                        <CircleCheckIcon />
                        <AlertDescription>{success}</AlertDescription>
                      </Alert>
                    )
                  : null}

            <form onSubmit={submit} noValidate>
              <FieldGroup className="gap-3">
                <Field>
                  <FieldLabel htmlFor="reset-password">{t('newPassword')}</FieldLabel>
                  <Input
                    id="reset-password"
                    type="password"
                    className="h-10"
                    autoComplete="new-password"
                    value={password}
                    onChange={(event) => setPassword(event.target.value)}
                  />
                </Field>
                <Field>
                  <FieldLabel htmlFor="reset-confirm-password">{t('confirmPassword')}</FieldLabel>
                  <Input
                    id="reset-confirm-password"
                    type="password"
                    className="h-10"
                    autoComplete="new-password"
                    value={confirmPassword}
                    onChange={(event) => setConfirmPassword(event.target.value)}
                  />
                </Field>
                <Button
                  type="submit"
                  size="lg"
                  className="w-full"
                  disabled={!page.token || !password || !confirmPassword || pending}
                >
                  {pending ? <Spinner data-icon="inline-start" /> : null}
                  {t('saveNewPassword')}
                </Button>
                <Button asChild variant="link" size="lg">
                  <GooseLink href="/login">{t('backToLogin')}</GooseLink>
                </Button>
              </FieldGroup>
            </form>
          </CardContent>
        </section>

        <aside className="flex flex-col justify-center border-t bg-muted/50 px-6 py-8 md:border-l md:border-t-0">
          <h2 className="text-lg font-semibold">{t('passwordAdviceTitle')}</h2>
          <p className="mt-3 text-sm leading-6 text-muted-foreground">{t('passwordAdviceDescription')}</p>
          <ul className="mt-6 flex flex-col gap-3 text-sm">
            <Advice>{t('passwordAdvice.length')}</Advice>
            <Advice>{t('passwordAdvice.unique')}</Advice>
            <Advice>{t('passwordAdvice.loginAfterReset')}</Advice>
          </ul>
        </aside>
      </Card>
    </main>
  )
}

function Advice({ children }: { children: string }) {
  return (
    <li className="flex items-center gap-2">
      <CheckIcon className="text-primary" aria-hidden="true" />
      {children}
    </li>
  )
}
