// resource/packages/react/src/site/pages/categories-page.tsx
import {
  ChevronRightIcon,
  LayoutGridIcon,
  MessageCircleIcon,
} from "lucide-react";
import {
  formatCompactNumber,
  type CategoriesPageProps,
} from "@gooseforum/client";
import { useTranslation } from "react-i18next";
import { Badge } from "../../components/ui/badge";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "../../components/ui/empty";
import { GooseLink } from "../../runtime";
import { PageHeader } from "../layout/page-header";

export function CategoriesPageView({ page }: { page: CategoriesPageProps }) {
  const { t } = useTranslation("categories");
  return (
    <div className="pb-12">
      <PageHeader
        compact
        title={t("title")}
        description={t("subtitle")}
        badge={
          <Badge variant="secondary">{t("total", { count: page.total })}</Badge>
        }
      />
      {page.categories.length ? (
        <section className="grid lg:grid-cols-2 lg:gap-3 lg:pt-3">
          {page.categories.map((category) => (
            <GooseLink
              key={category.id}
              href={category.url}
              className="group flex min-w-0 items-stretch border-b bg-background p-3.5 transition-colors hover:border-primary/30 hover:bg-muted lg:rounded-xl lg:border"
            >
              <span
                className="mr-3 w-1 shrink-0 rounded-full"
                style={{ backgroundColor: category.color || "var(--primary)" }}
                aria-hidden="true"
              />
              <div className="min-w-0 flex-1 py-0.5">
                <div className="flex min-w-0 items-center gap-2">
                  {category.icon ? <CategoryIcon icon={category.icon} /> : null}
                  <h2 className="truncate text-[15px] font-bold transition-colors group-hover:text-primary">
                    {category.name}
                  </h2>
                </div>
                <p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">
                  {category.description || t("noDescription")}
                </p>
              </div>
              <div className="ml-3 flex shrink-0 items-center gap-2 self-center">
                <Badge variant="secondary" className="gap-1 text-[10px]">
                  <MessageCircleIcon data-icon="inline-start" />
                  {t("topicCount", {
                    count: formatCompactNumber(category.topicCount),
                  })}
                </Badge>
                <ChevronRightIcon
                  width={16}
                  height={16}
                  className="text-muted-foreground transition-transform group-hover:translate-x-0.5 group-hover:text-primary"
                  aria-hidden="true"
                />
              </div>
            </GooseLink>
          ))}
        </section>
      ) : (
        <Empty className="min-h-56 border bg-background">
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <LayoutGridIcon />
            </EmptyMedia>
            <EmptyTitle>{t("emptyTitle")}</EmptyTitle>
            <EmptyDescription>{t("emptyDescription")}</EmptyDescription>
          </EmptyHeader>
        </Empty>
      )}
    </div>
  );
}

function CategoryIcon({ icon }: { icon: string }) {
  const isImage = /^(https?:\/\/|\/)/.test(icon);
  return (
    <span
      className="inline-flex shrink-0 items-center justify-center text-base leading-none"
      aria-hidden="true"
    >
      {isImage ? (
        <img src={icon} alt="" className="size-5 rounded object-cover" />
      ) : (
        icon
      )}
    </span>
  );
}

// resource/src/site/pages/CategoriesPage.vue
<script setup lang="ts">
import { ChevronRight, LayoutGrid, MessageCircle } from '@lucide/vue'
import { useI18n } from 'vue-i18n'
import { Badge } from '@/components/ui/badge'
import EmptyState from '@/site/components/EmptyState.vue'
import PageHeader from '@/site/components/PageHeader.vue'
import { formatNumber } from '@/runtime/format'
import type { CategoriesPageProps, LayoutPayload } from '@gooseforum/client'

defineProps<{
  layout: LayoutPayload
  props: CategoriesPageProps
}>()

const { t } = useI18n()

function isImageIcon(icon: string) {
  return /^(https?:\/\/|\/)/.test(icon)
}
</script>

<template>
  <div class="pb-12">
    <PageHeader :title="t('categoriesPage.title')" :description="t('categoriesPage.subtitle')" compact>
      <template #badge>
        <Badge variant="muted">{{ t('categoriesPage.total', { count: props.total }) }}</Badge>
      </template>
    </PageHeader>

    <section v-if="props.categories.length" class="grid gap-0 sm:grid-cols-2 sm:gap-3">
      <a
        v-for="category in props.categories"
        :key="category.id"
        :href="category.url"
        class="group directory-card gf-card flex min-w-0 items-stretch p-3.5 transition hover:border-primary/25 hover:bg-base-200"
      >
        <span
          class="mr-3 w-1 shrink-0 rounded-full"
          :style="{ backgroundColor: category.color || 'var(--gf-color-primary)' }"
          aria-hidden="true"
        />

        <div class="min-w-0 flex-1 py-0.5">
          <div class="flex min-w-0 items-center gap-2">
            <span v-if="category.icon" class="inline-flex shrink-0 items-center justify-center text-base leading-none" aria-hidden="true">
              <img v-if="isImageIcon(category.icon)" :src="category.icon" alt="" class="h-5 w-5 rounded object-cover">
              <span v-else>{{ category.icon }}</span>
            </span>
            <h2 class="truncate text-[15px] font-bold text-base-content transition group-hover:text-primary">{{ category.name }}</h2>
          </div>
          <p class="mt-1 line-clamp-2 text-xs leading-5 text-base-content/55">
            {{ category.description || t('categoriesPage.noDescription') }}
          </p>
        </div>

        <div class="ml-3 flex shrink-0 items-center gap-2 self-center">
          <Badge variant="muted" class="gap-1 text-[10px]">
            <MessageCircle class="h-3 w-3" aria-hidden="true" />
            {{ t('categoriesPage.topicCount', { count: formatNumber(category.topicCount) }) }}
          </Badge>
          <ChevronRight class="h-4 w-4 text-icon-muted transition group-hover:translate-x-0.5 group-hover:text-primary" aria-hidden="true" />
        </div>
      </a>
    </section>

    <EmptyState
      v-else
      class="gf-panel"
      :icon="LayoutGrid"
      :title="t('categoriesPage.emptyTitle')"
      :description="t('categoriesPage.emptyDescription')"
    />
  </div>
</template>

<style scoped>
@media (max-width: 639.98px) {
  .directory-card {
    border-bottom-color: var(--gf-color-line);
  }
}
</style>
