// resource/packages/react/src/site/pages/links-page.tsx
import {
  ExternalLinkIcon,
  LinkIcon,
  SendIcon,
  ShieldCheckIcon,
} from "lucide-react";
import type { LinksPageProps } from "@gooseforum/client";
import { useTranslation } from "react-i18next";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "../../components/ui/empty";
import { GooseLink } from "../../runtime";
import { InfoPanel } from "../layout/info-panel";
import { PageHeader } from "../layout/page-header";

export function LinksPageView({ page }: { page: LinksPageProps }) {
  const { t } = useTranslation("links");
  return (
    <div className="pb-12">
      <PageHeader
        compact
        title={t("title")}
        description={t("subtitle")}
        badge={<Badge variant="secondary">{page.totalCount}</Badge>}
      />
      <div className="grid gap-5 px-2 pt-4 lg:px-0 xl:grid-cols-[minmax(0,1fr)_260px]">
        <div className="flex min-w-0 flex-col gap-6">
          {page.groups.map((group) => (
            <section key={group.name} className="flex flex-col gap-2.5">
              <div className="flex items-center justify-between gap-3 px-1 lg:px-0">
                <h2 className="flex min-w-0 items-center gap-2 text-base font-bold">
                  <span
                    className="flex size-7 shrink-0 items-center justify-center rounded-lg bg-accent text-sm"
                    style={{ color: group.color || undefined }}
                  >
                    {group.emoji || "↗"}
                  </span>
                  <span className="truncate">{group.name}</span>
                </h2>
                <Badge variant="secondary">{group.links.length}</Badge>
              </div>
              <div className="grid grid-cols-2 gap-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">
                {group.links.map((link) => (
                  <a
                    key={`${group.name}-${link.url}`}
                    href={link.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="group min-w-0 rounded-xl border bg-background p-2 transition-colors hover:border-primary/30 hover:bg-primary/5"
                  >
                    <div className="flex items-center gap-2">
                      <div className="flex size-8 shrink-0 items-center justify-center overflow-hidden rounded-lg border bg-muted">
                        {link.logoUrl ? (
                          <img
                            src={link.logoUrl}
                            alt={link.name}
                            className="size-full object-cover"
                            loading="lazy"
                          />
                        ) : (
                          <LinkIcon
                            width={16}
                            height={16}
                            className="text-muted-foreground"
                            aria-hidden="true"
                          />
                        )}
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="flex min-w-0 items-center gap-1.5">
                          <h3 className="truncate text-[13px] font-semibold group-hover:text-primary">
                            {link.name}
                          </h3>
                          <ExternalLinkIcon
                            width={12}
                            height={12}
                            className="shrink-0 text-muted-foreground group-hover:text-primary"
                            aria-hidden="true"
                          />
                        </div>
                        <p className="mt-0.5 truncate text-[11px] leading-4 text-muted-foreground">
                          {link.desc || link.url}
                        </p>
                      </div>
                    </div>
                  </a>
                ))}
              </div>
            </section>
          ))}
          {!page.groups.length ? (
            <Empty className="min-h-56 border bg-background">
              <EmptyHeader>
                <EmptyMedia variant="icon">
                  <LinkIcon />
                </EmptyMedia>
                <EmptyTitle>{t("emptyTitle")}</EmptyTitle>
                <EmptyDescription>{t("emptyDescription")}</EmptyDescription>
              </EmptyHeader>
            </Empty>
          ) : null}
        </div>

        <aside className="flex flex-col gap-3">
          <InfoPanel
            title={t("applyTitle")}
            action={
              <Button asChild>
                <GooseLink href="/publish">
                  <SendIcon data-icon="inline-start" />
                  {t("applyAction")}
                </GooseLink>
              </Button>
            }
          >
            {t("applyDescription")}
          </InfoPanel>
          <InfoPanel title={t("principlesTitle")}>
            <ul className="flex flex-col gap-2 text-foreground/75">
              {(["healthy", "relevant", "stable"] as const).map((key) => (
                <li key={key} className="flex gap-2">
                  <ShieldCheckIcon
                    width={16}
                    height={16}
                    className="mt-0.5 shrink-0 text-success"
                    aria-hidden="true"
                  />
                  <span>{t(`principles.${key}`)}</span>
                </li>
              ))}
            </ul>
          </InfoPanel>
        </aside>
      </div>
    </div>
  );
}

// resource/src/site/pages/LinksPage.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { ExternalLink, Link, Send, ShieldCheck } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import EmptyState from '@/site/components/EmptyState.vue'
import PageHeader from '@/site/components/PageHeader.vue'
import type { LayoutPayload, LinksPageProps } from '@gooseforum/client'

defineProps<{
  layout: LayoutPayload
  props: LinksPageProps
}>()
const { t } = useI18n()
</script>

<template>
    <div class="pb-12">
      <PageHeader :title="t('linksPage.title')" :description="t('linksPage.subtitle')" compact>
        <template #badge>
          <Badge variant="muted">{{ props.totalCount }}</Badge>
        </template>
      </PageHeader>

      <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_260px]">
        <div class="space-y-6">
          <section v-for="group in props.groups" :key="group.name" class="space-y-2.5">
            <div class="flex items-center justify-between gap-3">
              <h2 class="flex min-w-0 items-center gap-2 text-base font-bold text-base-content">
                <span
                  class="flex h-7 w-7 shrink-0 items-center justify-center rounded-[var(--gf-radius-field)] bg-base-200 text-sm"
                  :style="{ color: group.color || 'var(--gf-color-base-content)' }"
                >
                  {{ group.emoji || '↗' }}
                </span>
                <span class="truncate">{{ group.name }}</span>
              </h2>
              <Badge variant="muted" class="text-[11px]">{{ group.links.length }}</Badge>
            </div>

            <div class="grid grid-cols-2 gap-2 md:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5">
              <a
                v-for="link in group.links"
                :key="`${group.name}-${link.url}`"
                :href="link.url"
                target="_blank"
                rel="noopener noreferrer"
                class="group rounded-[var(--gf-radius-box)] border border-line/70 bg-base-200/45 p-2 transition hover:border-primary/25 hover:bg-info/10 sm:bg-base-100"
              >
                <div class="flex items-center gap-2">
                  <div class="flex h-8 w-8 shrink-0 items-center justify-center overflow-hidden rounded-[var(--gf-radius-field)] border border-line bg-base-100 sm:bg-base-200">
                    <img
                      v-if="link.logoUrl"
                      :src="link.logoUrl"
                      :alt="link.name"
                      class="h-full w-full object-cover"
                      loading="lazy"
                    />
                    <Link v-else class="h-4 w-4 text-base-content/55" />
                  </div>
                  <div class="min-w-0 flex-1">
                    <div class="flex min-w-0 items-center gap-1.5">
                      <h3 class="truncate text-[13px] font-semibold text-base-content group-hover:text-primary">{{ link.name }}</h3>
                      <ExternalLink class="h-3 w-3 shrink-0 text-base-content/35 group-hover:text-primary" />
                    </div>
                    <p class="mt-0.5 truncate text-[11px] leading-4 text-base-content/55">{{ link.desc || link.url }}</p>
                  </div>
                </div>
              </a>
            </div>
          </section>

          <EmptyState v-if="!props.groups.length" class="gf-panel" :icon="Link" :title="t('linksPage.emptyTitle')" :description="t('linksPage.emptyDescription')" />
        </div>

        <aside class="space-y-3">
          <div class="rounded-[var(--gf-radius-box)] border border-line/70 bg-base-200/45 p-4 sm:bg-base-100">
            <h2 class="text-sm font-semibold text-base-content">{{ t('linksPage.applyTitle') }}</h2>
            <p class="mt-2 text-sm leading-6 text-base-content/55">{{ t('linksPage.applyDescription') }}</p>
            <Button as-child variant="brand" class="mt-4">
              <a href="/publish">
                <Send class="h-4 w-4" />
                {{ t('linksPage.applyAction') }}
              </a>
            </Button>
          </div>

          <div class="rounded-[var(--gf-radius-box)] border border-line/70 bg-base-200/45 p-4 sm:bg-base-100">
            <h2 class="text-sm font-semibold text-base-content">{{ t('linksPage.principlesTitle') }}</h2>
            <div class="mt-3 space-y-2 text-sm text-base-content/75">
              <div class="flex gap-2">
                <ShieldCheck class="mt-0.5 h-4 w-4 shrink-0 text-success" />
                <span>{{ t('linksPage.principles.healthy') }}</span>
              </div>
              <div class="flex gap-2">
                <ShieldCheck class="mt-0.5 h-4 w-4 shrink-0 text-success" />
                <span>{{ t('linksPage.principles.relevant') }}</span>
              </div>
              <div class="flex gap-2">
                <ShieldCheck class="mt-0.5 h-4 w-4 shrink-0 text-success" />
                <span>{{ t('linksPage.principles.stable') }}</span>
              </div>
            </div>
          </div>
        </aside>
      </div>
    </div>
</template>
