// resource/packages/react/src/site/pages/moderation-page.tsx
import { useCallback, useEffect, useState, type ComponentType } from "react";
import type {
  ModerationLogItem,
  ModerationPageProps,
  ModerationReportItem,
  TopicPayload,
} from "@gooseforum/client";
import {
  Ban,
  CircleAlert,
  Flag,
  History,
  RotateCcw,
  Scale,
  XCircle,
} from "lucide-react";
import { useTranslation } from "react-i18next";
import { Alert, AlertDescription } from "../../components/ui/alert";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "../../components/ui/avatar";
import { Button } from "../../components/ui/button";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "../../components/ui/empty";
import { Spinner } from "../../components/ui/spinner";
import { Tabs, TabsList, TabsTrigger } from "../../components/ui/tabs";
import { GooseLink, useGooseRuntime } from "../../runtime";
import { PageHeader } from "../layout/page-header";
import { UserCardPopover } from "../users/user-card-popover";

type ConsoleTab = "reports" | "ban" | "logs" | "guidance";
type ReportStatus = "open" | "closed";
const consoleTabs: Array<{ key: ConsoleTab; icon: ComponentType }> = [
  { key: "reports", icon: Flag },
  { key: "ban", icon: Ban },
  { key: "logs", icon: History },
  { key: "guidance", icon: Scale },
];

export function ModerationPageView({ page }: { page: ModerationPageProps }) {
  const { t } = useTranslation("moderation");
  const runtime = useGooseRuntime();
  const [tab, setTab] = useState<ConsoleTab>("reports");
  const [topics, setTopics] = useState(page.topics);
  const [topicBusy, setTopicBusy] = useState<Set<number>>(() => new Set());
  const [topicError, setTopicError] = useState("");
  const [reportStatus, setReportStatus] = useState<ReportStatus>("open");
  const [reports, setReports] = useState<ModerationReportItem[]>([]);
  const [reportCursor, setReportCursor] = useState(0);
  const [reportMore, setReportMore] = useState(true);
  const [reportLoading, setReportLoading] = useState(false);
  const [reportLoaded, setReportLoaded] = useState(false);
  const [reportError, setReportError] = useState("");
  const [reportBusy, setReportBusy] = useState<Set<number>>(() => new Set());
  const [logs, setLogs] = useState<ModerationLogItem[]>([]);
  const [logCursor, setLogCursor] = useState(0);
  const [logMore, setLogMore] = useState(true);
  const [logLoading, setLogLoading] = useState(false);
  const [logLoaded, setLogLoaded] = useState(false);
  const [logError, setLogError] = useState("");

  useEffect(() => {
    setTopics(page.topics);
    setTopicError("");
  }, [page]);
  const loadReports = useCallback(
    async (reset = false, status = reportStatus) => {
      if (reportLoading) return;
      setReportLoading(true);
      setReportError("");
      try {
        const result = await runtime.api.moderation.reports(
          reset ? 0 : reportCursor,
          20,
          status,
        );
        setReports((current) =>
          reset ? result.items : merge(current, result.items),
        );
        setReportCursor(result.nextCursor);
        setReportMore(result.hasNext);
        setReportLoaded(true);
      } catch (reason) {
        setReportError(
          reason instanceof Error ? reason.message : t("reports.loadFailed"),
        );
      } finally {
        setReportLoading(false);
      }
    },
    [reportCursor, reportLoading, reportStatus, runtime.api.moderation, t],
  );
  const loadLogs = useCallback(
    async (reset = false) => {
      if (logLoading) return;
      setLogLoading(true);
      setLogError("");
      try {
        const result = await runtime.api.moderation.logs(
          reset ? 0 : logCursor,
          20,
        );
        setLogs((current) =>
          reset ? result.items : merge(current, result.items),
        );
        setLogCursor(result.nextCursor);
        setLogMore(result.hasNext);
        setLogLoaded(true);
      } catch (reason) {
        setLogError(
          reason instanceof Error ? reason.message : t("logs.loadFailed"),
        );
      } finally {
        setLogLoading(false);
      }
    },
    [logCursor, logLoading, runtime.api.moderation, t],
  );
  useEffect(() => {
    if (tab === "reports" && !reportLoaded) void loadReports(true);
    if (tab === "logs" && !logLoaded) void loadLogs(true);
  }, [loadLogs, loadReports, logLoaded, reportLoaded, tab]);

  function changeReportStatus(status: ReportStatus) {
    if (status === reportStatus) return;
    setReportStatus(status);
    setReports([]);
    setReportCursor(0);
    setReportMore(true);
    setReportLoaded(false);
    void loadReports(true, status);
  }
  async function handleReport(
    item: ModerationReportItem,
    action: "ban" | "reject",
  ) {
    if (reportBusy.has(item.id)) return;
    setReportBusy((current) => withId(current, item.id));
    setReportError("");
    try {
      if (action === "ban")
        await (item.targetType === "topic"
          ? runtime.api.moderation.setTopicStatus(item.targetId, "ban")
          : runtime.api.moderation.setPostStatus(item.targetId, "ban"));
      await runtime.api.moderation.setReportStatus(item.id, action);
      setReports((items) => items.filter((entry) => entry.id !== item.id));
      if (item.targetType === "topic")
        setTopics((items) =>
          items.filter((entry) => entry.id !== item.targetId),
        );
      setLogLoaded(false);
    } catch (reason) {
      setReportError(
        reason instanceof Error ? reason.message : t("reports.actionFailed"),
      );
    } finally {
      setReportBusy((current) => withoutId(current, item.id));
    }
  }
  async function restoreTopic(topic: TopicPayload) {
    if (topicBusy.has(topic.id)) return;
    setTopicBusy((current) => withId(current, topic.id));
    setTopicError("");
    try {
      await runtime.api.moderation.setTopicStatus(topic.id, "unban");
      setTopics((items) => items.filter((entry) => entry.id !== topic.id));
      setLogLoaded(false);
    } catch (reason) {
      setTopicError(
        reason instanceof Error ? reason.message : t("blocked.loadFailed"),
      );
    } finally {
      setTopicBusy((current) => withoutId(current, topic.id));
    }
  }

  return (
    <main className="min-w-0 pb-8">
      <PageHeader compact title={t("title")} description={t("description")} />
      <Tabs
        value={tab}
        onValueChange={(value) => setTab(value as ConsoleTab)}
        className="mb-4 gap-0"
      >
        <TabsList className="h-auto w-fit flex-wrap justify-start gap-2 rounded-none border-b bg-transparent p-0">
          {consoleTabs.map(({ key, icon: Icon }) => (
            <TabsTrigger
              key={key}
              value={key}
              className="h-10 flex-none gap-2 rounded-none border-0 border-b-2 border-transparent bg-transparent px-1 shadow-none hover:bg-transparent data-active:border-primary data-active:bg-transparent data-active:text-primary"
            >
              <Icon />
              {t(`tabs.${key}`)}
            </TabsTrigger>
          ))}
        </TabsList>
      </Tabs>
      {tab === "reports" ? (
        <ReportsPanel
          status={reportStatus}
          items={reports}
          loading={reportLoading}
          loaded={reportLoaded}
          hasMore={reportMore}
          error={reportError}
          busy={reportBusy}
          t={t}
          locale={runtime.locale}
          onStatus={changeReportStatus}
          onLoad={() => void loadReports()}
          onAction={(item, action) => void handleReport(item, action)}
        />
      ) : null}
      {tab === "ban" ? (
        <BlockedPanel
          page={page}
          topics={topics}
          busy={topicBusy}
          error={topicError}
          t={t}
          onRestore={(topic) => void restoreTopic(topic)}
        />
      ) : null}
      {tab === "logs" ? (
        <LogsPanel
          items={logs}
          loading={logLoading}
          loaded={logLoaded}
          hasMore={logMore}
          error={logError}
          t={t}
          locale={runtime.locale}
          onLoad={() => void loadLogs()}
        />
      ) : null}
      {tab === "guidance" ? <Guidance t={t} /> : null}
    </main>
  );
}

type Translate = ReturnType<typeof useTranslation>["t"];
function ReportsPanel({
  status,
  items,
  loading,
  loaded,
  hasMore,
  error,
  busy,
  t,
  locale,
  onStatus,
  onLoad,
  onAction,
}: {
  status: ReportStatus;
  items: ModerationReportItem[];
  loading: boolean;
  loaded: boolean;
  hasMore: boolean;
  error: string;
  busy: Set<number>;
  t: Translate;
  locale: string;
  onStatus(value: ReportStatus): void;
  onLoad(): void;
  onAction(item: ModerationReportItem, action: "ban" | "reject"): void;
}) {
  return (
    <section className="flex flex-col gap-3">
      {error ? (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      ) : null}
      <div className="overflow-hidden rounded-xl border bg-background">
        <Tabs
          value={status}
          onValueChange={(value) => onStatus(value as ReportStatus)}
          className="gap-0"
        >
          <TabsList className="h-auto w-full justify-start gap-1 rounded-none border-b bg-muted/50 p-2">
            <TabsTrigger value="open">
              {t("reports.statusTabs.open")}
            </TabsTrigger>
            <TabsTrigger value="closed">
              {t("reports.statusTabs.closed")}
            </TabsTrigger>
          </TabsList>
        </Tabs>
        {items.length ? (
          <div className="divide-y">
            {items.map((item) => (
              <article
                key={item.id}
                className="grid grid-cols-[28px_minmax(0,1fr)] gap-3 px-3 py-2.5 hover:bg-muted/40 lg:grid-cols-[28px_minmax(0,1fr)_150px_180px_auto] lg:items-center"
              >
                <span className="flex size-7 items-center justify-center rounded bg-muted text-amber-600">
                  <Flag />
                </span>
                <div className="min-w-0">
                  <div className="flex min-w-0 flex-wrap items-center gap-1.5">
                    <span className="text-xs text-muted-foreground">
                      {t(`reports.targetTypes.${item.targetType}`)}
                    </span>
                    <GooseLink
                      href={item.targetUrl}
                      className="min-w-0 truncate font-medium text-primary"
                    >
                      {item.title}
                    </GooseLink>
                    {item.categories.map((category) => (
                      <span
                        key={category.id}
                        className="inline-flex items-center gap-1 text-xs text-muted-foreground"
                      >
                        <span
                          className="size-2 rounded-sm"
                          style={{ backgroundColor: category.color }}
                        />
                        {category.name}
                      </span>
                    ))}
                  </div>
                  <p className="line-clamp-1 text-sm text-muted-foreground">
                    {item.excerpt || item.note || t("reports.noExcerpt")}
                  </p>
                  <time className="text-xs text-muted-foreground lg:hidden">
                    {formatDate(item.createdAt, locale)}
                  </time>
                </div>
                <div className="hidden min-w-0 text-sm lg:block">
                  <p>
                    <span className="text-muted-foreground">
                      {t("reports.reason")}{" "}
                    </span>
                    {t(`reports.reasons.${item.reason}`, {
                      defaultValue: item.reason,
                    })}
                  </p>
                  {status === "closed" ? (
                    <p>
                      <span className="text-muted-foreground">
                        {t("reports.status")}{" "}
                      </span>
                      {resolution(item, t)}
                    </p>
                  ) : null}
                </div>
                <div className="hidden min-w-0 lg:block">
                  <Person user={item.reporter} label={t("reports.reporter")} />
                  {status === "closed" && item.handler.id ? (
                    <Person user={item.handler} label={t("reports.handler")} />
                  ) : null}
                </div>
                <div className="col-start-2 flex flex-wrap items-center gap-2 lg:col-start-auto lg:justify-end">
                  {status === "open" ? (
                    <>
                      <Button
                        size="sm"
                        variant="destructive"
                        disabled={busy.has(item.id)}
                        onClick={() => onAction(item, "ban")}
                      >
                        <Ban data-icon="inline-start" />
                        {t("reports.block")}
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        disabled={busy.has(item.id)}
                        onClick={() => onAction(item, "reject")}
                      >
                        <XCircle data-icon="inline-start" />
                        {t("reports.ignore")}
                      </Button>
                    </>
                  ) : (
                    <time className="text-xs text-muted-foreground">
                      {formatDate(item.handledAt || item.createdAt, locale)}
                    </time>
                  )}
                </div>
              </article>
            ))}
          </div>
        ) : (
          <PanelEmpty
            loading={loading}
            icon={Flag}
            title={t(loading ? "reports.loading" : "reports.emptyTitle")}
            description={loading ? "" : t("reports.emptyDescription")}
          />
        )}
        {loaded && (items.length || hasMore) ? (
          <footer className="border-t px-4 py-3 text-center">
            {hasMore ? (
              <Button
                variant="ghost"
                size="sm"
                disabled={loading}
                onClick={onLoad}
              >
                {loading ? <Spinner data-icon="inline-start" /> : null}
                {loading ? t("reports.loading") : t("reports.loadMore")}
              </Button>
            ) : (
              <span className="text-xs text-muted-foreground">
                {t("reports.noMore")}
              </span>
            )}
          </footer>
        ) : null}
      </div>
    </section>
  );
}
function BlockedPanel({
  page,
  topics,
  busy,
  error,
  t,
  onRestore,
}: {
  page: ModerationPageProps;
  topics: TopicPayload[];
  busy: Set<number>;
  error: string;
  t: Translate;
  onRestore(topic: TopicPayload): void;
}) {
  return (
    <section className="flex flex-col gap-3">
      <div className="flex flex-wrap gap-2">
        {page.categoryTabs.map((tab) => (
          <Button
            key={tab.key}
            asChild
            size="sm"
            variant={tab.active ? "secondary" : "ghost"}
          >
            <GooseLink href={tab.url}>{tab.label}</GooseLink>
          </Button>
        ))}
      </div>
      {error ? (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      ) : null}
      <div className="overflow-hidden rounded-xl border bg-background">
        {topics.length ? (
          <div className="divide-y">
            {topics.map((topic) => (
              <article
                key={topic.id}
                className="flex items-center justify-between gap-4 px-4 py-3 hover:bg-muted/40"
              >
                <div className="min-w-0">
                  <GooseLink
                    href={topic.url}
                    className="block truncate font-semibold hover:text-primary"
                  >
                    {topic.title}
                  </GooseLink>
                  <p className="truncate text-sm text-muted-foreground">
                    {topic.description}
                  </p>
                </div>
                <Button
                  size="sm"
                  disabled={busy.has(topic.id)}
                  onClick={() => onRestore(topic)}
                >
                  {busy.has(topic.id) ? (
                    <Spinner data-icon="inline-start" />
                  ) : (
                    <RotateCcw data-icon="inline-start" />
                  )}
                  {t("blocked.restore")}
                </Button>
              </article>
            ))}
          </div>
        ) : (
          <PanelEmpty
            icon={Ban}
            title={t("blocked.emptyTitle")}
            description={t("blocked.emptyDescription")}
          />
        )}
        {page.pagination.hasNext ? (
          <footer className="border-t px-4 py-3 text-center">
            <Button asChild variant="outline" size="sm">
              <GooseLink href={page.pagination.nextUrl}>
                {t("blocked.next")}
              </GooseLink>
            </Button>
          </footer>
        ) : null}
      </div>
    </section>
  );
}
function LogsPanel({
  items,
  loading,
  loaded,
  hasMore,
  error,
  t,
  locale,
  onLoad,
}: {
  items: ModerationLogItem[];
  loading: boolean;
  loaded: boolean;
  hasMore: boolean;
  error: string;
  t: Translate;
  locale: string;
  onLoad(): void;
}) {
  return (
    <section className="flex flex-col gap-3">
      {error ? (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      ) : null}
      <div className="overflow-hidden rounded-xl border bg-background">
        {items.length ? (
          <div className="divide-y">
            {items.map((item) => (
              <article
                key={item.id}
                className="grid grid-cols-[34px_minmax(0,1fr)] gap-3 px-3 py-2.5 hover:bg-muted/40 md:grid-cols-[34px_minmax(0,1fr)_150px]"
              >
                <span className="flex size-8 items-center justify-center rounded-md bg-muted text-muted-foreground">
                  <History />
                </span>
                <div className="min-w-0">
                  <p className="truncate text-sm">
                    <strong>{item.actor.username}</strong>{" "}
                    <span className="text-muted-foreground">
                      {t(`logs.actions.${item.action}`, {
                        defaultValue: t("logs.actions.operation"),
                      })}
                    </span>{" "}
                    {item.subject.url ? (
                      <GooseLink
                        href={item.subject.url}
                        className="font-semibold text-primary"
                      >
                        {item.subject.title}
                      </GooseLink>
                    ) : (
                      <strong>{item.subject.title}</strong>
                    )}
                  </p>
                  {item.subject.excerpt ? (
                    <p className="truncate text-xs text-muted-foreground">
                      {item.subject.excerpt}
                    </p>
                  ) : null}
                </div>
                <time className="hidden text-right text-xs text-muted-foreground md:block">
                  {formatDate(item.createdAt, locale)}
                </time>
              </article>
            ))}
          </div>
        ) : (
          <PanelEmpty
            loading={loading}
            icon={History}
            title={t(loading ? "logs.loading" : "logs.emptyTitle")}
            description={loading ? "" : t("logs.emptyDescription")}
          />
        )}
        {loaded && (items.length || hasMore) ? (
          <footer className="border-t px-4 py-3 text-center">
            {hasMore ? (
              <Button
                variant="ghost"
                size="sm"
                disabled={loading}
                onClick={onLoad}
              >
                {loading ? <Spinner data-icon="inline-start" /> : null}
                {loading ? t("logs.loading") : t("logs.loadMore")}
              </Button>
            ) : (
              <span className="text-xs text-muted-foreground">
                {t("logs.noMore")}
              </span>
            )}
          </footer>
        ) : null}
      </div>
    </section>
  );
}
function Guidance({ t }: { t: Translate }) {
  return (
    <section className="px-4 sm:px-0">
      <div className="flex items-start gap-3 py-2.5">
        <CircleAlert className="mt-1 text-amber-600" />
        <p className="text-sm leading-6 text-muted-foreground">{t("notice")}</p>
      </div>
      <div className="flex flex-col gap-1">
        {(["rule", "context", "restraint"] as const).map((key) => (
          <article key={key} className="py-2">
            <h3 className="text-sm font-semibold">
              {t(`guidance.${key}.title`)}
            </h3>
            <p className="mt-1 text-sm leading-6 text-muted-foreground">
              {t(`guidance.${key}.description`)}
            </p>
          </article>
        ))}
      </div>
    </section>
  );
}
function Person({
  user,
  label,
}: {
  user: ModerationReportItem["reporter"];
  label: string;
}) {
  return (
    <UserCardPopover user={user}>
      <GooseLink
        href={`/u/${user.id}`}
        className="flex min-w-0 items-center gap-1.5 text-xs hover:text-primary"
      >
        <Avatar className="size-5">
          <AvatarImage src={user.avatarUrl} alt="" />
          <AvatarFallback>
            {user.username.slice(0, 1).toUpperCase()}
          </AvatarFallback>
        </Avatar>
        <span className="text-muted-foreground">{label}</span>
        <span className="truncate font-medium">{user.username}</span>
      </GooseLink>
    </UserCardPopover>
  );
}
function PanelEmpty({
  loading = false,
  icon: Icon,
  title,
  description,
}: {
  loading?: boolean;
  icon: ComponentType;
  title: string;
  description: string;
}) {
  return (
    <Empty className="min-h-48 border-0">
      <EmptyHeader>
        <EmptyMedia variant="icon">
          {loading ? <Spinner /> : <Icon />}
        </EmptyMedia>
        <EmptyTitle>{title}</EmptyTitle>
        {description ? (
          <EmptyDescription>{description}</EmptyDescription>
        ) : null}
      </EmptyHeader>
    </Empty>
  );
}
function resolution(item: ModerationReportItem, t: Translate) {
  const value =
    item.resolution || (item.status === "rejected" ? "ignored" : "resolved");
  return t(`reports.resolutions.${value}`, { defaultValue: value });
}
function formatDate(value: string, locale: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? value
    : new Intl.DateTimeFormat(locale, {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(date);
}
function merge<T extends { id: number }>(current: T[], incoming: T[]) {
  const ids = new Set(current.map((item) => item.id));
  return [...current, ...incoming.filter((item) => !ids.has(item.id))];
}
function withId(current: Set<number>, id: number) {
  const next = new Set(current);
  next.add(id);
  return next;
}
function withoutId(current: Set<number>, id: number) {
  const next = new Set(current);
  next.delete(id);
  return next;
}

// resource/src/site/pages/ModerationPage.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { Ban, CircleAlert, Flag, History, RotateCcw, Scale, XCircle } from '@lucide/vue'
import { useI18n } from 'vue-i18n'
import { Button } from '@/components/ui/button'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { fetchModerationLogs, fetchModerationReports, updateModerationTopicStatus, updateModerationPostStatus, updateModerationReportStatus } from '@/runtime/api'
import { formatDateTime } from '@/runtime/format'
import { fetchPage } from '@/runtime/router'
import EmptyState from '@/site/components/EmptyState.vue'
import PageHeader from '@/site/components/PageHeader.vue'
import TopicList from '@/site/components/TopicList.vue'
import UserAvatar from '@/site/components/UserAvatar.vue'
import UserCardPopover from '@/site/components/UserCardPopover.vue'
import type { LayoutPayload, ModerationLogItem, ModerationPageProps, ModerationReportItem, PagePayload, TopicPayload } from '@gooseforum/client'

const page = defineProps<{
  layout: LayoutPayload
  props: ModerationPageProps
}>()

const { t, te } = useI18n()
const currentProps = ref<ModerationPageProps>(page.props)
const topics = ref<TopicPayload[]>([...page.props.topics])
const busyIds = ref<number[]>([])
const actionError = ref('')
const loadingList = ref(false)
const activeConsoleTab = ref<'reports' | 'ban' | 'logs' | 'guidance'>('reports')
const reportItems = ref<ModerationReportItem[]>([])
const reportStatus = ref<'open' | 'closed'>('open')
const reportNextCursor = ref(0)
const reportHasNext = ref(true)
const reportLoading = ref(false)
const reportLoaded = ref(false)
const reportError = ref('')
const reportBusyIds = ref<number[]>([])
const logItems = ref<ModerationLogItem[]>([])
const logNextCursor = ref(0)
const logHasNext = ref(true)
const logLoading = ref(false)
const logLoaded = ref(false)
const logError = ref('')

const managementTabs = [
  { key: 'reports', icon: Flag },
  { key: 'ban', icon: Ban },
  { key: 'logs', icon: History },
  { key: 'guidance', icon: Scale },
]

watch(
  () => page.props,
  (next) => {
    currentProps.value = next
    topics.value = [...next.topics]
    actionError.value = ''
    busyIds.value = []
    loadingList.value = false
  },
  { immediate: true },
)

watch(activeConsoleTab, (tab) => {
  if (tab === 'reports' && !reportLoaded.value) {
    void loadModerationReports(true)
  }
  if (tab === 'logs' && !logLoaded.value) {
    void loadModerationLogs(true)
  }
}, { immediate: true })

function isBusy(id: number) {
  return busyIds.value.includes(id)
}

async function loadModerationURL(url: string, options: { push?: boolean } = {}) {
  if (loadingList.value) return
  loadingList.value = true
  actionError.value = ''
  busyIds.value = []
  try {
    const nextURL = new URL(url, window.location.origin)
    const payload = (await fetchPage(nextURL)) as PagePayload<ModerationPageProps>
    currentProps.value = payload.props
    topics.value = [...payload.props.topics]
    if (options.push !== false) {
      window.history.pushState(window.history.state, '', `${nextURL.pathname}${nextURL.search}${nextURL.hash}`)
    }
  } catch (error) {
    actionError.value = error instanceof Error ? error.message : t('common.loadFailed')
  } finally {
    loadingList.value = false
  }
}

async function moderateTopic(topic: TopicPayload) {
  if (isBusy(topic.id)) return
  busyIds.value = [...busyIds.value, topic.id]
  actionError.value = ''
  try {
    await updateModerationTopicStatus(topic.id, 'unban')
    topics.value = topics.value.filter(item => item.id !== topic.id)
    logLoaded.value = false
    logItems.value = []
    logNextCursor.value = 0
    logHasNext.value = true
  } catch (error) {
    actionError.value = error instanceof Error ? error.message : t('api.moderationActionFailed')
  } finally {
    busyIds.value = busyIds.value.filter(id => id !== topic.id)
  }
}

async function loadModerationLogs(reset = false) {
  if (logLoading.value) return
  logLoading.value = true
  logError.value = ''
  try {
    const payload = await fetchModerationLogs(reset ? 0 : logNextCursor.value, 20)
    logItems.value = reset ? payload.items : mergeModerationLogs(logItems.value, payload.items)
    logNextCursor.value = payload.nextCursor
    logHasNext.value = payload.hasNext
    logLoaded.value = true
  } catch (error) {
    logError.value = error instanceof Error ? error.message : t('api.moderationLogsFailed')
  } finally {
    logLoading.value = false
  }
}

async function loadModerationReports(reset = false) {
  if (reportLoading.value) return
  reportLoading.value = true
  reportError.value = ''
  try {
    const payload = await fetchModerationReports(reset ? 0 : reportNextCursor.value, 20, reportStatus.value)
    reportItems.value = reset ? payload.items : mergeModerationReports(reportItems.value, payload.items)
    reportNextCursor.value = payload.nextCursor
    reportHasNext.value = payload.hasNext
    reportLoaded.value = true
  } catch (error) {
    reportError.value = error instanceof Error ? error.message : t('api.moderationReportsFailed')
  } finally {
    reportLoading.value = false
  }
}

function switchReportStatus(status: 'open' | 'closed') {
  if (reportStatus.value === status) return
  reportStatus.value = status
  reportItems.value = []
  reportNextCursor.value = 0
  reportHasNext.value = true
  reportLoaded.value = false
  void loadModerationReports(true)
}

function mergeModerationReports(current: ModerationReportItem[], incoming: ModerationReportItem[]) {
  const seen = new Set(current.map(item => item.id))
  return [...current, ...incoming.filter(item => !seen.has(item.id))]
}

function reportBusy(id: number) {
  return reportBusyIds.value.includes(id)
}

async function handleReport(item: ModerationReportItem, action: 'resolve' | 'reject') {
  if (reportBusy(item.id)) return
  reportBusyIds.value = [...reportBusyIds.value, item.id]
  reportError.value = ''
  try {
    await updateModerationReportStatus(item.id, action)
    reportItems.value = reportItems.value.filter(report => report.id !== item.id)
    logLoaded.value = false
    logItems.value = []
    logNextCursor.value = 0
    logHasNext.value = true
  } catch (error) {
    reportError.value = error instanceof Error ? error.message : t('api.moderationActionFailed')
  } finally {
    reportBusyIds.value = reportBusyIds.value.filter(id => id !== item.id)
  }
}

async function hideReportTarget(item: ModerationReportItem) {
  if (reportBusy(item.id)) return
  reportBusyIds.value = [...reportBusyIds.value, item.id]
  reportError.value = ''
  try {
    if (item.targetType === 'topic') {
      await updateModerationTopicStatus(item.targetId, 'ban')
    } else {
      await updateModerationPostStatus(item.targetId, 'ban')
    }
    await updateModerationReportStatus(item.id, 'ban')
    reportItems.value = reportItems.value.filter(report => report.id !== item.id)
    if (item.targetType === 'topic') {
      topics.value = topics.value.filter(topic => topic.id !== item.targetId)
    }
    logLoaded.value = false
    logItems.value = []
    logNextCursor.value = 0
    logHasNext.value = true
  } catch (error) {
    reportError.value = error instanceof Error ? error.message : t('api.moderationActionFailed')
  } finally {
    reportBusyIds.value = reportBusyIds.value.filter(id => id !== item.id)
  }
}

function mergeModerationLogs(current: ModerationLogItem[], incoming: ModerationLogItem[]) {
  const seen = new Set(current.map(item => item.id))
  return [...current, ...incoming.filter(item => !seen.has(item.id))]
}

function logActionLabel(item: ModerationLogItem) {
  const key = `moderation.logs.actions.${item.action}`
  return te(key) ? t(key) : t('moderation.logs.actions.operation')
}

function reportResolutionLabel(item: ModerationReportItem) {
  if (item.resolution) return t(`moderation.reports.resolutions.${item.resolution}`)
  if (item.status === 'rejected') return t('moderation.reports.resolutions.ignored')
  return t('moderation.reports.resolutions.resolved')
}
</script>

<template>
  <main class="min-w-0 pb-8">
    <PageHeader :title="t('moderation.title')" :description="t('moderation.description')" compact class="border-b-0 !mb-2 sm:!mb-2 !pb-2 sm:!pb-2" />

    <Tabs
      :model-value="activeConsoleTab"
      class="mb-4"
      @update:model-value="activeConsoleTab = $event as 'reports' | 'ban' | 'logs' | 'guidance'"
    >
      <TabsList class="h-auto w-fit flex-wrap justify-start gap-2 rounded-none border-b border-line bg-transparent p-0">
        <TabsTrigger
          v-for="tab in managementTabs"
          :key="tab.key"
          :value="tab.key"
          class="h-10 flex-none gap-2 rounded-none border-0 border-b-2 border-transparent bg-transparent px-1 text-sm font-semibold text-base-content/55 shadow-none transition-colors hover:bg-transparent hover:text-base-content data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:text-primary data-[state=active]:shadow-none"
        >
          <component :is="tab.icon" class="h-4 w-4" />
          {{ t(`moderation.managementTabs.${tab.key}`) }}
        </TabsTrigger>
      </TabsList>
    </Tabs>

    <section v-if="activeConsoleTab === 'reports'" class="space-y-3">
      <p v-if="reportError" class="rounded border border-error/25 bg-error/10 px-3 py-2 text-sm text-error">
        {{ reportError }}
      </p>

      <div class="gf-card overflow-hidden">
        <Tabs
          :model-value="reportStatus"
          class="gap-0"
          @update:model-value="switchReportStatus($event as 'open' | 'closed')"
        >
          <TabsList class="h-auto w-full justify-start gap-1 rounded-none border-b border-line bg-base-200/60 p-2">
            <TabsTrigger
              value="open"
              class="h-8 flex-none gap-1.5 rounded-[var(--gf-radius-field)] border border-transparent px-3 text-sm font-semibold text-base-content/55 shadow-none transition hover:bg-base-100/70 hover:text-base-content data-[state=active]:bg-base-100 data-[state=active]:text-base-content data-[state=active]:shadow-sm data-[state=active]:ring-1 data-[state=active]:ring-line"
            >
            {{ t('moderation.reports.statusTabs.open') }}
            </TabsTrigger>
            <TabsTrigger
              value="closed"
              class="h-8 flex-none gap-1.5 rounded-[var(--gf-radius-field)] border border-transparent px-3 text-sm font-semibold text-base-content/55 shadow-none transition hover:bg-base-100/70 hover:text-base-content data-[state=active]:bg-base-100 data-[state=active]:text-base-content data-[state=active]:shadow-sm data-[state=active]:ring-1 data-[state=active]:ring-line"
            >
            {{ t('moderation.reports.statusTabs.closed') }}
            </TabsTrigger>
          </TabsList>
        </Tabs>

        <div class="hidden grid-cols-[28px_minmax(260px,1fr)_140px_170px_180px_176px] gap-4 border-b border-line bg-base-200/60 px-3 py-1.5 text-[11px] font-bold uppercase text-base-content/75 lg:grid">
          <div />
          <div>{{ t('moderation.reports.table.report') }}</div>
          <div>{{ t('moderation.reports.table.reason') }}</div>
          <div>{{ t('moderation.reports.table.people') }}</div>
          <div class="text-right">{{ t('moderation.reports.table.time') }}</div>
          <div class="text-right">{{ t('moderation.reports.table.action') }}</div>
        </div>

        <div v-if="reportItems.length" class="divide-y divide-line">
          <article
            v-for="item in reportItems"
            :key="item.id"
            class="grid grid-cols-[28px_minmax(0,1fr)] gap-3 px-3 py-1.5 transition hover:bg-base-200/70 lg:grid-cols-[28px_minmax(260px,1fr)_140px_170px_180px_176px] lg:items-center lg:gap-4"
          >
            <div class="flex h-7 w-7 shrink-0 items-center justify-center rounded bg-base-200 text-warning">
              <Flag class="h-4 w-4" />
            </div>
            <div class="min-w-0">
              <div class="flex min-w-0 items-center gap-1.5 text-[15px] leading-5 text-base-content/80">
                <span class="shrink-0 text-base-content/45">{{ t(`moderation.reports.targetTypes.${item.targetType}`) }}</span>
                <a :href="item.targetUrl" class="min-w-0 max-w-full truncate font-medium text-primary/90 hover:text-primary">{{ item.title }}</a>
                <span v-for="category in item.categories" :key="category.id" class="hidden shrink-0 items-center gap-1 text-xs text-base-content/45 lg:inline-flex">
                  <span class="h-2 w-2 rounded-[3px]" :style="{ backgroundColor: category.color }" />
                  {{ category.name }}
                </span>
              </div>
              <p class="line-clamp-1 text-[13px] leading-5 text-base-content/55">{{ item.excerpt || item.note || t('moderation.reports.noExcerpt') }}</p>
              <div class="mt-1 flex flex-wrap items-center gap-x-2.5 gap-y-1 text-xs text-base-content/50 lg:hidden">
                <span>{{ t('moderation.reports.reasonLabel') }} {{ t(`moderation.reports.reasons.${item.reason}`) }}</span>
                <span v-if="reportStatus === 'closed'">{{ t('moderation.reports.statusLabel') }} {{ reportResolutionLabel(item) }}</span>
                <span v-for="category in item.categories" :key="category.id" class="inline-flex items-center gap-1">
                  <span class="h-2 w-2 rounded-[3px]" :style="{ backgroundColor: category.color }" />
                  {{ category.name }}
                </span>
                <UserCardPopover :user="item.reporter">
                  <a
                    :href="`/u/${item.reporter.id}`"
                    class="inline-flex min-w-0 items-center gap-1.5 hover:text-primary lg:hidden"
                  >
                    <UserAvatar :src="item.reporter.avatarUrl" alt="" class="h-4 w-4 rounded-full object-cover ring-1 ring-line" />
                    <span class="shrink-0">{{ t('moderation.reports.reporterLabel') }}</span>
                    <span class="max-w-28 truncate font-medium text-base-content/65">{{ item.reporter.username }}</span>
                  </a>
                </UserCardPopover>
                <UserCardPopover
                  v-if="reportStatus === 'closed' && item.handler.id"
                  :user="item.handler"
                >
                  <a :href="`/u/${item.handler.id}`" class="inline-flex min-w-0 items-center gap-1.5 hover:text-primary lg:hidden">
                    <UserAvatar :src="item.handler.avatarUrl" alt="" class="h-4 w-4 rounded-full object-cover ring-1 ring-line" />
                    <span class="shrink-0">{{ t('moderation.reports.handlerLabel') }}</span>
                    <span class="max-w-28 truncate font-medium text-base-content/65">{{ item.handler.username }}</span>
                  </a>
                </UserCardPopover>
              </div>
              <time class="mt-1 block text-xs text-base-content/55 lg:hidden">{{ formatDateTime(reportStatus === 'closed' && item.handledAt ? item.handledAt : item.createdAt) }}</time>
            </div>
            <div class="hidden min-w-0 space-y-1 text-[13px] text-base-content/55 lg:block">
              <div class="flex min-w-0 items-center gap-1.5">
                <span class="shrink-0 text-base-content/40">{{ t('moderation.reports.reasonLabel') }}</span>
                <span class="min-w-0 truncate font-medium text-base-content/70">{{ t(`moderation.reports.reasons.${item.reason}`) }}</span>
              </div>
              <div v-if="reportStatus === 'closed'" class="flex min-w-0 items-center gap-1.5">
                <span class="shrink-0 text-base-content/40">{{ t('moderation.reports.statusLabel') }}</span>
                <span class="min-w-0 truncate font-medium text-base-content/70">{{ reportResolutionLabel(item) }}</span>
              </div>
            </div>
            <div class="hidden min-w-0 space-y-1 text-[13px] text-base-content/55 lg:block">
              <UserCardPopover :user="item.reporter">
                <a :href="`/u/${item.reporter.id}`" class="flex min-w-0 items-center gap-1.5 hover:text-primary">
                  <UserAvatar :src="item.reporter.avatarUrl" alt="" class="h-5 w-5 rounded-full object-cover ring-1 ring-line" />
                  <span class="shrink-0">{{ t('moderation.reports.reporterLabel') }}</span>
                  <span class="min-w-0 truncate font-medium text-base-content/65">{{ item.reporter.username }}</span>
                </a>
              </UserCardPopover>
              <UserCardPopover
                v-if="reportStatus === 'closed' && item.handler.id"
                :user="item.handler"
              >
                <a :href="`/u/${item.handler.id}`" class="flex min-w-0 items-center gap-1.5 hover:text-primary">
                  <UserAvatar :src="item.handler.avatarUrl" alt="" class="h-5 w-5 rounded-full object-cover ring-1 ring-line" />
                  <span class="shrink-0">{{ t('moderation.reports.handlerLabel') }}</span>
                  <span class="min-w-0 truncate font-medium text-base-content/65">{{ item.handler.username }}</span>
                </a>
              </UserCardPopover>
            </div>
            <div class="col-start-2 mt-1 flex flex-wrap items-center justify-start gap-2 lg:col-start-auto lg:mt-0 lg:block lg:text-right">
              <div class="space-y-0.5 text-xs tabular-nums text-base-content/55">
                <div>{{ t('moderation.reports.submittedAtLabel') }} {{ formatDateTime(item.createdAt) }}</div>
                <div v-if="reportStatus === 'closed' && item.handledAt">{{ t('moderation.reports.handledAtLabel') }} {{ formatDateTime(item.handledAt) }}</div>
              </div>
            </div>
            <div v-if="reportStatus === 'open'" class="col-start-2 mt-1 flex items-center justify-start gap-2 lg:col-start-auto lg:mt-0 lg:justify-end">
              <Button
                type="button"
                variant="danger"
                size="sm"
                class="shrink-0 whitespace-nowrap text-xs"
                :disabled="reportBusy(item.id)"
                @click="hideReportTarget(item)"
              >
                <Ban class="h-4 w-4" />
                {{ t('moderation.reports.ban') }}
              </Button>
              <Button
                type="button"
                variant="muted"
                size="sm"
                class="shrink-0 whitespace-nowrap text-xs"
                :disabled="reportBusy(item.id)"
                @click="handleReport(item, 'reject')"
              >
                <XCircle class="h-4 w-4" />
                {{ t('moderation.reports.reject') }}
              </Button>
            </div>
            <div v-else class="hidden lg:block" />
          </article>
        </div>

        <EmptyState
          v-else-if="reportLoading"
          :icon="Flag"
          :title="t('moderation.reports.loading')"
          loading
        />
        <EmptyState
          v-else
          :icon="Flag"
          :title="t('moderation.reports.emptyTitle')"
          :description="t('moderation.reports.emptyDescription')"
        />

        <footer v-if="reportLoaded && (reportItems.length || reportHasNext)" class="border-t border-line px-4 py-3 text-center text-xs font-semibold text-base-content/55">
          <Button
            v-if="reportHasNext"
            type="button"
            variant="brand-ghost"
            size="sm"
            :disabled="reportLoading"
            @click="loadModerationReports(false)"
          >
            {{ reportLoading ? t('moderation.reports.loading') : t('moderation.reports.loadMore') }}
          </Button>
          <span v-else-if="reportItems.length" class="text-xs text-base-content/45">{{ t('moderation.reports.noMore') }}</span>
        </footer>
      </div>
    </section>

    <section v-else-if="activeConsoleTab === 'ban'" class="space-y-3">
      <div class="flex flex-wrap gap-2">
        <Button
          v-for="tab in currentProps.categoryTabs"
          :key="tab.key"
          as-child
          :variant="tab.active ? 'surface' : 'brand-ghost'"
          size="sm"
          class="text-xs"
        >
          <a :href="tab.url" @click.prevent="loadModerationURL(tab.url)">{{ tab.label }}</a>
        </Button>
      </div>

      <p v-if="actionError" class="rounded border border-error/25 bg-error/10 px-3 py-2 text-sm text-error">
        {{ actionError }}
      </p>

      <div class="overflow-hidden rounded border border-line bg-base-100">
        <TopicList :topics="topics" :show-hot="false">
          <template #activity-header>
            {{ t('moderation.table.action') }}
          </template>
          <template #activity="{ topic }">
            <Button
              type="button"
              variant="brand"
              size="sm"
              class="shrink-0 text-xs"
              :disabled="isBusy(topic.id)"
              @click="moderateTopic(topic)"
            >
              <RotateCcw class="h-4 w-4" />
              {{ isBusy(topic.id) ? t('common.loadingShort') : t('moderation.unbanAction') }}
            </Button>
          </template>
          <template #mobile-action="{ topic }">
            <span class="ml-auto">
              <Button
                type="button"
                variant="brand"
                size="sm"
                class="shrink-0 text-xs"
                :disabled="isBusy(topic.id)"
                @click="moderateTopic(topic)"
              >
                <RotateCcw class="h-4 w-4" />
                {{ isBusy(topic.id) ? t('common.loadingShort') : t('moderation.unbanAction') }}
              </Button>
            </span>
          </template>
          <template #empty>
            <EmptyState v-if="!topics.length" :icon="Ban" :title="t('moderation.blockedEmptyTitle')" :description="t('moderation.emptyDescription')" />
          </template>
        </TopicList>

        <footer v-if="currentProps.pagination.hasNext" class="border-t border-line bg-base-200/50 px-4 py-3 text-center">
          <Button as-child variant="surface" size="sm">
            <a
              :href="currentProps.pagination.nextUrl"
              rel="next"
              @click.prevent="loadModerationURL(currentProps.pagination.nextUrl)"
            >
              {{ t('common.nextPage') }}
            </a>
          </Button>
        </footer>
      </div>
    </section>

    <section v-else-if="activeConsoleTab === 'logs'" class="space-y-3">
      <p v-if="logError" class="rounded border border-error/25 bg-error/10 px-3 py-2 text-sm text-error">
        {{ logError }}
      </p>

      <div class="gf-card overflow-hidden">
        <div class="hidden grid-cols-[34px_minmax(0,1fr)_116px] gap-3 border-b border-line bg-base-200/60 px-3 py-2 text-[11px] font-bold uppercase text-base-content/75 md:grid">
          <div />
          <div>{{ t('moderation.logs.table.operation') }}</div>
          <div class="text-right">{{ t('moderation.logs.table.time') }}</div>
        </div>

        <div v-if="logItems.length" class="divide-y divide-line">
          <article
            v-for="item in logItems"
            :key="item.id"
            class="grid grid-cols-[34px_minmax(0,1fr)] gap-3 px-3 py-2.5 transition hover:bg-base-200/70 md:grid-cols-[34px_minmax(0,1fr)_116px] md:items-start"
          >
            <div class="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-base-200 text-base-content/55">
              <History class="h-4 w-4" />
            </div>
            <div class="min-w-0">
              <div class="flex min-w-0 items-center gap-1.5 text-sm leading-5">
                <span class="max-w-[42%] shrink-0 truncate font-semibold text-base-content">{{ item.actor.username }}</span>
                <span class="shrink-0 text-base-content/55">{{ logActionLabel(item) }}</span>
                <a
                  v-if="item.subject.url"
                  :href="item.subject.url"
                  class="min-w-0 max-w-full truncate font-semibold text-primary hover:text-primary"
                >
                  {{ item.subject.title }}
                </a>
                <span v-else class="min-w-0 max-w-full truncate font-semibold text-base-content/75">{{ item.subject.title }}</span>
              </div>
              <p v-if="item.subject.excerpt" class="mt-0.5 line-clamp-1 text-xs text-base-content/55">
                {{ item.subject.excerpt }}
              </p>
              <time class="mt-1 block text-xs text-base-content/55 md:hidden">{{ formatDateTime(item.createdAt) }}</time>
            </div>
            <time class="hidden text-right text-xs font-medium tabular-nums text-base-content/55 md:block">{{ formatDateTime(item.createdAt) }}</time>
          </article>
        </div>

        <EmptyState
          v-else-if="logLoading"
          :icon="History"
          :title="t('moderation.logs.loading')"
          loading
        />
        <EmptyState
          v-else
          :icon="History"
          :title="t('moderation.logs.emptyTitle')"
          :description="t('moderation.logs.emptyDescription')"
        />

        <footer v-if="logLoaded && (logItems.length || logHasNext)" class="border-t border-line px-4 py-3 text-center text-xs font-semibold text-base-content/55">
          <Button
            v-if="logHasNext"
            type="button"
            variant="brand-ghost"
            size="sm"
            :disabled="logLoading"
            @click="loadModerationLogs(false)"
          >
            {{ logLoading ? t('moderation.logs.loading') : t('moderation.logs.loadMore') }}
          </Button>
          <span v-else-if="logItems.length" class="text-xs text-base-content/45">{{ t('moderation.logs.noMore') }}</span>
        </footer>
      </div>
    </section>

    <section v-else class="space-y-3 px-4 sm:px-0">
      <div>
        <div class="flex items-start gap-3 py-2.5">
          <CircleAlert class="mt-1 h-4 w-4 shrink-0 text-warning" />
          <p class="text-sm leading-6 text-base-content/70">{{ t('moderation.notice') }}</p>
        </div>
        <div class="space-y-3 pt-1">
          <div class="py-2">
            <h3 class="text-sm font-semibold text-base-content">{{ t('moderation.guidanceItems.rule.title') }}</h3>
            <p class="mt-1 text-sm leading-6 text-base-content/60">{{ t('moderation.guidanceItems.rule.description') }}</p>
          </div>
          <div class="py-2">
            <h3 class="text-sm font-semibold text-base-content">{{ t('moderation.guidanceItems.context.title') }}</h3>
            <p class="mt-1 text-sm leading-6 text-base-content/60">{{ t('moderation.guidanceItems.context.description') }}</p>
          </div>
          <div class="py-2">
            <h3 class="text-sm font-semibold text-base-content">{{ t('moderation.guidanceItems.restraint.title') }}</h3>
            <p class="mt-1 text-sm leading-6 text-base-content/60">{{ t('moderation.guidanceItems.restraint.description') }}</p>
          </div>
        </div>
      </div>
    </section>
  </main>
</template>
