// resource/packages/theme-default/src/site/pages/sponsors-page.tsx
import { ExternalLinkIcon, HeartHandshakeIcon, MailIcon, ShieldCheckIcon } from 'lucide-react'
import type { SponsorSectionPayload, SponsorsPageProps } from '@gooseforum/client'
import { useTranslation } from 'react-i18next'
import { Badge } from '@gooseforum/ui/components/badge'
import { Button } from '@gooseforum/ui/components/button'
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from '@gooseforum/ui/components/empty'
import { cn } from '@gooseforum/ui/lib/utils'
import { InfoPanel } from '../layout/info-panel'
import { PageHeader } from '../layout/page-header'

export function SponsorsPageView({ page }: { page: SponsorsPageProps }) {
  const { t } = useTranslation('sponsors')
  return (
    <div className="pb-12">
      <PageHeader compact divided={false} title={page.content.title} description={page.content.description} badge={<Badge variant="secondary">{page.totalCount}</Badge>} />
      <div className="grid gap-0 lg:gap-5 xl:grid-cols-[minmax(0,1fr)_260px]">
        <div className="flex min-w-0 flex-col gap-0 lg:gap-6">
          {page.sections.map((section) => (
            <section key={section.key} className="flex flex-col gap-0 lg:gap-2.5">
              <div className="flex items-center justify-between gap-3 px-4 py-3 lg:px-0 lg:py-0">
                <h2>
                  <Badge
                    variant="secondary"
                    className={cn(
                      section.tone === 'diamond' && 'bg-primary/10 text-primary',
                      section.tone === 'gold' && 'bg-warning/10 text-warning',
                    )}
                  >
                    {section.label}
                  </Badge>
                </h2>
                <Badge variant="secondary">{section.sponsors.length}</Badge>
              </div>
              <div className={sectionGrid(section)}>
                {section.sponsors.map((sponsor) => {
                  const content = (
                    <>
                      <img src={sponsor.avatarUrl} alt={sponsor.name} className={cn('shrink-0 rounded-lg border object-cover', avatarSize(section))} loading="lazy" />
                      <div className="min-w-0 flex-1">
                        <div className="flex min-w-0 items-center gap-1.5">
                          <h3 className="truncate text-[13px] font-semibold group-hover:text-primary lg:text-sm">{sponsor.name}</h3>
                          {sponsor.link ? <ExternalLinkIcon width={14} height={14} className="shrink-0 text-muted-foreground group-hover:text-primary" aria-hidden="true" /> : null}
                        </div>
                        <p className="mt-0.5 line-clamp-2 text-[11px] leading-4 text-muted-foreground lg:mt-1 lg:text-xs lg:leading-5">
                          {sponsor.message || t('defaultMessage')}
                        </p>
                      </div>
                    </>
                  )
                  const className = cn('group flex items-start gap-2.5 border-b bg-background lg:rounded-xl lg:border transition-colors hover:border-primary/30 hover:bg-primary/5', cardPadding(section))
                  return sponsor.link
                    ? <a key={`${section.key}-${sponsor.name}`} href={sponsor.link} target="_blank" rel="noopener noreferrer" className={className}>{content}</a>
                    : <div key={`${section.key}-${sponsor.name}`} className={className}>{content}</div>
                })}
              </div>
            </section>
          ))}
          {!page.sections.length
            ? (
                <Empty className="site-panel min-h-56 border bg-background">
                  <EmptyHeader>
                    <EmptyMedia variant="icon"><HeartHandshakeIcon /></EmptyMedia>
                    <EmptyTitle>{t('emptyTitle')}</EmptyTitle>
                    <EmptyDescription>{t('emptyDescription')}</EmptyDescription>
                  </EmptyHeader>
                </Empty>
              )
            : null}
        </div>

        <aside className="flex flex-col gap-0 lg:gap-3">
          <InfoPanel
            title={page.contact.title}
            action={<Button asChild><a href={page.contact.buttonLink}><MailIcon data-icon="inline-start" />{page.contact.buttonText}</a></Button>}
          >
            {page.contact.description}
          </InfoPanel>
          {page.rules.length
            ? (
                <InfoPanel title={t('rulesTitle')}>
                  <ul className="flex flex-col gap-2 text-foreground/75">
                    {page.rules.map((rule) => (
                      <li key={rule.content} className="flex gap-2">
                        <ShieldCheckIcon width={16} height={16} className="mt-0.5 shrink-0 text-success" aria-hidden="true" />
                        <span>{rule.content}</span>
                      </li>
                    ))}
                  </ul>
                </InfoPanel>
              )
            : null}
        </aside>
      </div>
    </div>
  )
}

function sectionGrid(section: SponsorSectionPayload) {
  return cn(
    'grid grid-cols-1 gap-0 lg:gap-3',
    section.tone === 'diamond' && 'lg:grid-cols-2',
    section.tone === 'gold' && 'lg:grid-cols-2 xl:grid-cols-3',
    section.tone !== 'diamond' && section.tone !== 'gold' && 'lg:grid-cols-4 2xl:grid-cols-5',
  )
}

function cardPadding(section: SponsorSectionPayload) {
  if (section.tone === 'diamond') return 'p-3.5'
  if (section.tone === 'gold') return 'p-3'
  return 'p-2.5'
}

function avatarSize(section: SponsorSectionPayload) {
  if (section.tone === 'diamond') return 'size-11'
  if (section.tone === 'gold') return 'size-10'
  return 'size-8'
}

// resource/src/site/pages/SponsorsPage.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ExternalLink, HeartHandshake, Mail, ShieldCheck } from '@lucide/vue'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import EmptyState from '@/site/components/EmptyState.vue'
import PageHeader from '@/site/components/PageHeader.vue'
import type { LayoutPayload, SponsorPayload, SponsorSectionPayload, SponsorsPageProps } from '@gooseforum/client'
import { useI18n } from 'vue-i18n'

const page = defineProps<{
  layout: LayoutPayload
  props: SponsorsPageProps
}>()

const { t } = useI18n()
const hasSponsors = computed(() => page.props.sections.length > 0)

function sectionGrid(section: SponsorSectionPayload) {
  if (section.tone === 'diamond') return 'grid-cols-1 md:grid-cols-2'
  if (section.tone === 'gold') return 'grid-cols-1 sm:grid-cols-2 xl:grid-cols-3'
  return 'grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5'
}

function sectionBadgeClass(section: SponsorSectionPayload) {
  if (section.tone === 'diamond') return 'bg-info/10 text-primary'
  if (section.tone === 'gold') return 'bg-warning/10 text-warning'
  if (section.tone === 'silver') return 'bg-base-300 text-base-content/75'
  return 'bg-error/10 text-error'
}

function sponsorCardClass(section: SponsorSectionPayload) {
  if (section.tone === 'diamond') return 'p-3.5 bg-base-100'
  if (section.tone === 'gold') return 'p-3 bg-base-100'
  return 'p-2.5 bg-base-200/45 sm:bg-base-100'
}

function sponsorBodyClass(section: SponsorSectionPayload) {
  return 'flex items-start gap-2.5'
}

function sponsorAvatarClass(section: SponsorSectionPayload) {
  if (section.tone === 'diamond') return 'h-11 w-11'
  if (section.tone === 'gold') return 'h-10 w-10'
  return 'h-8 w-8'
}

function showMessage(sponsor: SponsorPayload) {
  return sponsor.message || t('sponsors.defaultMessage')
}
</script>

<template>
    <div class="pb-12">
      <PageHeader :title="props.content.title" :description="props.content.description">
        <template #badge>
          <Badge variant="muted">{{ props.totalCount }}</Badge>
        </template>
      </PageHeader>

      <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_260px]">
        <div class="space-y-6">
          <section v-for="section in props.sections" :key="section.key" class="space-y-2.5">
            <div class="flex items-center justify-between gap-3">
              <h2 class="flex min-w-0 items-center gap-2 text-base font-bold text-base-content">
                <span class="rounded px-1.5 py-0.5 text-[11px] font-semibold" :class="sectionBadgeClass(section)">{{ section.label }}</span>
              </h2>
              <Badge variant="muted" class="text-[11px]">{{ section.sponsors.length }}</Badge>
            </div>

            <div class="grid gap-3" :class="sectionGrid(section)">
              <a
                v-for="sponsor in section.sponsors"
                :key="`${section.key}-${sponsor.name}`"
                :href="sponsor.link || '#'"
                :target="sponsor.link ? '_blank' : undefined"
                :rel="sponsor.link ? 'noopener noreferrer' : undefined"
                class="group relative rounded-[var(--gf-radius-box)] border border-line/70 transition hover:border-primary/25 hover:bg-info/10"
                :class="sponsorCardClass(section)"
              >
                <div :class="sponsorBodyClass(section)">
                  <img
                    :src="sponsor.avatarUrl"
                    :alt="sponsor.name"
                    class="shrink-0 rounded-[var(--gf-radius-field)] border border-line object-cover"
                    :class="sponsorAvatarClass(section)"
                    loading="lazy"
                  />
                  <div class="min-w-0 flex-1">
                    <div class="flex min-w-0 items-center gap-1.5">
                      <h3 class="truncate text-[13px] font-semibold text-base-content group-hover:text-primary sm:text-sm">{{ sponsor.name }}</h3>
                      <ExternalLink v-if="sponsor.link" class="h-3 w-3 shrink-0 text-base-content/35 group-hover:text-primary sm:h-3.5 sm:w-3.5" />
                    </div>
                    <p class="mt-0.5 line-clamp-2 text-[11px] leading-4 text-base-content/55 sm:mt-1 sm:text-xs sm:leading-5">{{ showMessage(sponsor) }}</p>
                  </div>
                </div>
              </a>
            </div>
          </section>

          <EmptyState v-if="!hasSponsors" class="gf-panel" :icon="HeartHandshake" :title="t('sponsors.emptyTitle')" :description="t('sponsors.emptyDescription')" />
        </div>

        <aside class="space-y-3">
          <div class="rounded-[var(--gf-radius-box)] border border-line/70 bg-base-200/45 p-4 sm:bg-base-100">
            <h2 class="text-sm font-semibold text-base-content">{{ props.contact.title }}</h2>
            <p class="mt-2 text-sm leading-6 text-base-content/55">{{ props.contact.description }}</p>
            <Button as-child variant="brand" class="mt-4">
              <a :href="props.contact.buttonLink">
                <Mail class="h-4 w-4" />
                {{ props.contact.buttonText }}
              </a>
            </Button>
          </div>

          <div v-if="props.rules.length" class="rounded-[var(--gf-radius-box)] border border-line/70 bg-base-200/45 p-4 sm:bg-base-100">
            <h2 class="text-sm font-semibold text-base-content">{{ t('sponsors.rulesTitle') }}</h2>
            <div class="mt-3 space-y-2 text-sm text-base-content/75">
              <div v-for="rule in props.rules" :key="rule.content" class="flex gap-2">
                <ShieldCheck class="mt-0.5 h-4 w-4 shrink-0 text-success" />
                <span>{{ rule.content }}</span>
              </div>
            </div>
          </div>
        </aside>
      </div>
    </div>
</template>
