// resource/packages/react/src/site/layout/app-shell.tsx
"use client";

import {
  useEffect,
  useRef,
  useState,
  type ComponentType,
  type ReactNode,
  type SVGProps,
} from "react";
import {
  BellIcon,
  FileTextIcon,
  FlameIcon,
  HeartIcon,
  InboxIcon,
  LanguagesIcon,
  LayoutGridIcon,
  LinkIcon,
  LogOutIcon,
  MenuIcon,
  MessageCircleIcon,
  MoonIcon,
  PaletteIcon,
  PenSquareIcon,
  SearchIcon,
  SettingsIcon,
  ShieldIcon,
  SunIcon,
  TrendingUpIcon,
  UserRoundIcon,
  UsersRoundIcon,
  XIcon,
} from "lucide-react";
import type { LayoutPayload, NavItemPayload } from "@gooseforum/client";
import { useTranslation } from "react-i18next";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "../../components/ui/avatar";
import { Button } from "../../components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "../../components/ui/dropdown-menu";
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "../../components/ui/sheet";
import { authLocales } from "../../i18n/auth";
import { cn } from "../../lib/utils";
import { GooseLink, useGooseRuntime } from "../../runtime";
import { unreadStatusEvent } from "../../runtime/unread-status";
import {
  emptyShellHeader,
  ShellHeaderContext,
  type ShellHeaderState,
} from "./shell-header";

interface ShellNavItem {
  key: string;
  label: string;
  url: string;
  active: boolean;
  icon?: ComponentType<SVGProps<SVGSVGElement>>;
  color?: string;
  attention?: boolean;
}

export function AppShell({
  layout,
  children,
}: {
  layout: LayoutPayload;
  children: ReactNode;
}) {
  const { t, i18n } = useTranslation("shell");
  const runtime = useGooseRuntime();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [unread, setUnread] = useState(layout.unread);
  const [languageMenuOpen, setLanguageMenuOpen] = useState(false);
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const [shellHeader, setShellHeader] = useState<ShellHeaderState>(
    emptyShellHeader,
  );
  const menuCloseTimers = useRef<
    Record<"language" | "user", number | undefined>
  >({
    language: undefined,
    user: undefined,
  });
  const activeKey = layout.sidebar.activeKey || "topics";
  const primary = [
    nav("topics", t("nav.topics"), "/", MessageCircleIcon),
    nav("hot", t("nav.hot"), "/?sort=hot", FlameIcon),
    nav("popular", t("nav.popular"), "/?sort=popular", TrendingUpIcon),
    nav("categories", t("nav.categories"), "/categories", LayoutGridIcon),
    nav("members", t("nav.members"), "/members", UsersRoundIcon),
    ...(layout.viewer.isAuthenticated
      ? [
          nav(
            "messages",
            t("nav.messages"),
            "/messages",
            InboxIcon,
            unread.messages,
          ),
          nav(
            "notifications",
            t("nav.notifications"),
            "/notifications",
            BellIcon,
            unread.notifications,
          ),
          nav("drafts", t("nav.drafts"), "/drafts", FileTextIcon),
        ]
      : []),
    ...(layout.viewer.isModerator
      ? [
          nav(
            "moderation",
            t("nav.moderation"),
            "/moderation",
            BellIcon,
            unread.moderationReports,
          ),
        ]
      : []),
    ...serverItems(layout.sidebar.main),
  ];
  const resources = [
    nav("links", t("nav.links"), "/links", LinkIcon),
    nav("sponsors", t("nav.sponsors"), "/sponsors", HeartIcon),
    ...serverItems(layout.sidebar.resources),
  ];
  const categories = (layout.sidebar.categories || []).map((category) => ({
    key: `category_${category.id}`,
    label: category.label,
    url: category.url,
    active: activeKey === `category_${category.id}`,
    color: category.color,
  }));
  const groups = (layout.sidebar.groups || [])
    .map((group) => ({
      key: group.key,
      title: displayLabel(group, group.title),
      items: serverItems(group.items),
    }))
    .filter((group) => group.title && group.items.length);
  const headerItems = layout.header?.length
    ? serverItems(layout.header)
    : resources.slice(0, 2);

  function nav(
    key: string,
    label: string,
    url: string,
    icon?: ShellNavItem["icon"],
    attention = false,
  ): ShellNavItem {
    return { key, label, url, icon, attention, active: activeKey === key };
  }

  function displayLabel(item: { i18nLabel?: string }, fallback: string) {
    const key = item.i18nLabel?.startsWith("shell.")
      ? item.i18nLabel.slice("shell.".length)
      : "";
    return key && i18n.exists(key, { ns: "shell" }) ? t(key) : fallback;
  }

  function serverItems(items?: NavItemPayload[]): ShellNavItem[] {
    return (items || []).map((item) =>
      nav(item.key, displayLabel(item, item.label), item.url, LinkIcon),
    );
  }

  async function logout() {
    await runtime.api.auth.logout();
    runtime.redirect(runtime.currentUrl);
  }

  function setHeaderMenu(menu: "language" | "user", open: boolean) {
    window.clearTimeout(menuCloseTimers.current[menu]);
    menuCloseTimers.current[menu] = undefined;
    if (open) {
      const other = menu === "language" ? "user" : "language";
      window.clearTimeout(menuCloseTimers.current[other]);
      menuCloseTimers.current[other] = undefined;
      if (other === "language") setLanguageMenuOpen(false);
      else setUserMenuOpen(false);
    }
    if (menu === "language") setLanguageMenuOpen(open);
    else setUserMenuOpen(open);
  }

  function closeHeaderMenuSoon(menu: "language" | "user") {
    window.clearTimeout(menuCloseTimers.current[menu]);
    menuCloseTimers.current[menu] = window.setTimeout(
      () => setHeaderMenu(menu, false),
      120,
    );
  }

  useEffect(() => {
    setUnread(layout.unread);
  }, [layout.unread]);

  useEffect(() => {
    const updateUnread = (event: Event) => {
      const detail = (event as CustomEvent<Partial<LayoutPayload["unread"]>>)
        .detail;
      setUnread((current) => ({ ...current, ...detail }));
    };
    window.addEventListener(unreadStatusEvent, updateUnread);
    return () => window.removeEventListener(unreadStatusEvent, updateUnread);
  }, []);

  useEffect(() => {
    if (!layout.viewer.isAuthenticated) return;
    const refreshUnread = () => {
      void runtime.api.notifications
        .unread()
        .then(setUnread)
        .catch(() => undefined);
    };
    const timer = window.setInterval(refreshUnread, 30_000);
    return () => window.clearInterval(timer);
  }, [layout.viewer.isAuthenticated, runtime.api.notifications]);

  useEffect(
    () => () => {
      window.clearTimeout(menuCloseTimers.current.language);
      window.clearTimeout(menuCloseTimers.current.user);
    },
    [],
  );

  const navigation = (
    <ShellNavigation
      primary={primary}
      resources={resources}
      groups={groups}
      categories={categories}
      footer={layout.footer}
      labels={{ resources: t("resources"), categories: t("categories") }}
      onNavigate={() => setMobileOpen(false)}
    />
  );

  return (
    <ShellHeaderContext.Provider value={setShellHeader}>
      <div className="min-h-svh bg-muted text-foreground">
      {runtime.isNavigating ? (
        <div className="fixed inset-x-0 top-0 z-50 h-0.5 animate-pulse bg-primary" />
      ) : null}
      <header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur-sm">
        <div className="mx-auto flex h-16 w-full max-w-[1600px] items-center gap-2 px-3 lg:gap-8 lg:px-8">
          <Sheet open={mobileOpen} onOpenChange={setMobileOpen}>
            <SheetTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="[&_svg]:size-5 lg:hidden"
                aria-label={t("openMenu")}
              >
                <MenuIcon className="size-5" />
              </Button>
            </SheetTrigger>
            <SheetContent
              side="left"
              className="w-72 p-0"
              showCloseButton={false}
            >
              <SheetHeader className="relative border-b">
                <SheetTitle>{t("menu")}</SheetTitle>
                <SheetDescription className="sr-only">
                  {t("menu")}
                </SheetDescription>
                <SheetClose asChild>
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    className="absolute right-3 top-3"
                    aria-label={t("closeMenu")}
                  >
                    <XIcon />
                  </Button>
                </SheetClose>
              </SheetHeader>
              <div className="min-h-0 flex-1 overflow-y-auto px-3 pb-5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
                {navigation}
              </div>
            </SheetContent>
          </Sheet>

          <div className={cn(shellHeader.visible && "hidden md:block")}>
            <SiteBrand layout={layout} />
          </div>
          {shellHeader.visible ? (
            <button
              type="button"
              className="flex min-w-0 flex-1 flex-col items-start justify-center gap-0.5 self-stretch text-left"
              onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
            >
              <span className="block max-w-full truncate text-lg font-semibold leading-6 hover:text-primary md:text-xl">
                {shellHeader.title}
              </span>
              {shellHeader.tags.length ? (
                <span className="flex max-w-full items-center gap-2 overflow-hidden text-[11px] font-medium leading-4 text-muted-foreground">
                  {shellHeader.tags.map((tag) => (
                    <span
                      key={tag.id}
                      className="inline-flex min-w-0 shrink-0 items-center gap-1"
                    >
                      <span
                        className="size-1.5 rounded-sm"
                        style={{ backgroundColor: tag.color || "currentColor" }}
                      />
                      <span className="max-w-28 truncate">{tag.name}</span>
                    </span>
                  ))}
                </span>
              ) : null}
            </button>
          ) : null}
          <nav
            className={cn(
              "hidden items-center gap-1 lg:flex",
              shellHeader.visible && "lg:hidden",
            )}
            aria-label="Header navigation"
          >
            {headerItems.map((item) => (
              <GooseLink
                key={item.key}
                href={item.url}
                className="rounded-md px-2 py-1.5 text-sm font-medium text-foreground/75 hover:bg-accent"
              >
                {item.label}
              </GooseLink>
            ))}
          </nav>

          <div
            className={cn(
              "ml-auto items-center gap-0.5 lg:gap-1",
              shellHeader.visible ? "hidden md:flex" : "flex",
            )}
          >
            <Button
              asChild
              variant="ghost"
              size="icon-lg"
              className="[&_svg]:size-5"
              aria-label={t("search")}
            >
              <GooseLink href="/search">
                <SearchIcon className="size-5" />
              </GooseLink>
            </Button>
            <Button
              variant="ghost"
              size="icon-lg"
              className="[&_svg]:size-5"
              onClick={runtime.toggleTheme}
              aria-label={
                runtime.theme === "gf-dark" ? t("switchLight") : t("switchDark")
              }
            >
              {runtime.theme === "gf-dark" ? (
                <SunIcon className="size-5" />
              ) : (
                <MoonIcon className="size-5" />
              )}
            </Button>
            <DropdownMenu
              modal={false}
              open={languageMenuOpen}
              onOpenChange={(open) => setHeaderMenu("language", open)}
            >
              <div
                className="relative"
                onMouseEnter={() => setHeaderMenu("language", true)}
                onMouseLeave={() => closeHeaderMenuSoon("language")}
              >
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="ghost"
                    size="icon-lg"
                    className="[&_svg]:size-5"
                    aria-label={t("switchLanguage")}
                  >
                    <LanguagesIcon className="size-5" />
                  </Button>
                </DropdownMenuTrigger>
              </div>
              <DropdownMenuContent
                align="end"
                sideOffset={8}
                onMouseEnter={() => setHeaderMenu("language", true)}
                onMouseLeave={() => closeHeaderMenuSoon("language")}
                onCloseAutoFocus={(event) => event.preventDefault()}
              >
                <DropdownMenuRadioGroup
                  value={runtime.locale}
                  onValueChange={(value) =>
                    runtime.setLocale(value as typeof runtime.locale)
                  }
                >
                  {authLocales.map((locale) => (
                    <DropdownMenuRadioItem key={locale} value={locale}>
                      {i18n.getFixedT(locale, "auth")("locale.label")}
                    </DropdownMenuRadioItem>
                  ))}
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>

            {layout.viewer.isAuthenticated ? (
              <DropdownMenu
                modal={false}
                open={userMenuOpen}
                onOpenChange={(open) => setHeaderMenu("user", open)}
              >
                <div
                  className="relative"
                  onMouseEnter={() => setHeaderMenu("user", true)}
                  onMouseLeave={() => closeHeaderMenuSoon("user")}
                >
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon-lg"
                      className="relative"
                      aria-label={layout.viewer.username}
                    >
                      <Avatar>
                        <AvatarImage
                          src={layout.viewer.avatarUrl}
                          alt={layout.viewer.username}
                        />
                        <AvatarFallback>
                          {layout.viewer.username.slice(0, 2).toUpperCase()}
                        </AvatarFallback>
                      </Avatar>
                      {unread.messages || unread.notifications ? (
                        <span
                          className="absolute right-0 top-0 size-2.5 rounded-full bg-destructive ring-2 ring-background"
                          aria-hidden="true"
                        />
                      ) : null}
                    </Button>
                  </DropdownMenuTrigger>
                </div>
                <DropdownMenuContent
                  align="end"
                  sideOffset={8}
                  className="w-48"
                  onMouseEnter={() => setHeaderMenu("user", true)}
                  onMouseLeave={() => closeHeaderMenuSoon("user")}
                  onCloseAutoFocus={(event) => event.preventDefault()}
                >
                  <DropdownMenuGroup>
                    <DropdownMenuItem asChild>
                      <GooseLink href={`/u/${layout.viewer.id}`}>
                        <UserRoundIcon />
                        {layout.viewer.username}
                      </GooseLink>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <GooseLink href="/messages">
                        <InboxIcon />
                        {t("nav.messages")}
                        {unread.messages ? <MenuDot /> : null}
                      </GooseLink>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <GooseLink href="/notifications">
                        <BellIcon />
                        {t("nav.notifications")}
                        {unread.notifications ? <MenuDot /> : null}
                      </GooseLink>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <GooseLink href="/drafts">
                        <FileTextIcon />
                        {t("nav.drafts")}
                      </GooseLink>
                    </DropdownMenuItem>
                  </DropdownMenuGroup>
                  <DropdownMenuSeparator />
                  <DropdownMenuGroup>
                    <DropdownMenuItem asChild>
                      <GooseLink href="/publish">
                        <PenSquareIcon />
                        {t("publish")}
                      </GooseLink>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <GooseLink href="/settings">
                        <SettingsIcon />
                        {t("settings")}
                      </GooseLink>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <GooseLink href="/access-groups">
                        <UsersRoundIcon />
                        {t("accessGroups")}
                      </GooseLink>
                    </DropdownMenuItem>
                    {layout.viewer.canAccessAdmin ? (
                      <DropdownMenuItem asChild>
                        <GooseLink href="/theme-preview">
                          <PaletteIcon />
                          {t("themePreview")}
                        </GooseLink>
                      </DropdownMenuItem>
                    ) : null}
                    {layout.viewer.canAccessAdmin ? (
                      <DropdownMenuItem asChild>
                        <GooseLink href="/admin">
                          <ShieldIcon />
                          {t("admin")}
                        </GooseLink>
                      </DropdownMenuItem>
                    ) : null}
                  </DropdownMenuGroup>
                  <DropdownMenuSeparator />
                  <DropdownMenuGroup>
                    <DropdownMenuItem
                      variant="destructive"
                      onSelect={() => void logout()}
                    >
                      <LogOutIcon />
                      {t("logout")}
                    </DropdownMenuItem>
                  </DropdownMenuGroup>
                </DropdownMenuContent>
              </DropdownMenu>
            ) : (
              <>
                <Button asChild variant="ghost">
                  <GooseLink href="/login">{t("login")}</GooseLink>
                </Button>
                <Button asChild className="hidden lg:inline-flex">
                  <GooseLink href="/login?register=true">
                    {t("register")}
                  </GooseLink>
                </Button>
              </>
            )}
          </div>
        </div>
      </header>

      <main className="mx-auto grid w-full max-w-[1600px] grid-cols-1 lg:grid-cols-[210px_minmax(0,1fr)] lg:gap-3 lg:px-8 lg:py-3 xl:grid-cols-[224px_minmax(0,1fr)]">
        <aside
          className="sticky top-16 -my-3 hidden h-[calc(100vh-4rem)] min-w-0 self-start overflow-y-auto py-3 pl-1 pr-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden lg:block"
          aria-label="Sidebar"
        >
          {navigation}
        </aside>
        <section className="min-w-0">{children}</section>
      </main>
      </div>
    </ShellHeaderContext.Provider>
  );
}

function SiteBrand({ layout }: { layout: LayoutPayload }) {
  const site = layout.site;
  const content =
    site.brandType === "image" && site.brandImage ? (
      <img
        src={site.brandImage}
        alt={site.name}
        className="h-8 w-auto max-w-40 object-contain"
      />
    ) : site.brandType === "text" ? (
      site.brandText || site.name
    ) : (
      <>
        Goose<span className="text-foreground">Forum</span>
      </>
    );
  return (
    <GooseLink
      href="/"
      className="shrink-0 text-xl font-semibold tracking-tight text-primary lg:text-2xl"
    >
      {content}
    </GooseLink>
  );
}

function ShellNavigation({
  primary,
  resources,
  groups,
  categories,
  footer,
  labels,
  onNavigate,
}: {
  primary: ShellNavItem[];
  resources: ShellNavItem[];
  groups: Array<{ key: string; title: string; items: ShellNavItem[] }>;
  categories: ShellNavItem[];
  footer: LayoutPayload["footer"];
  labels: { resources: string; categories: string };
  onNavigate(): void;
}) {
  return (
    <nav className="flex flex-col gap-2">
      <NavList items={primary} onNavigate={onNavigate} />
      <NavSection title={labels.resources}>
        <NavList items={resources} onNavigate={onNavigate} />
      </NavSection>
      {groups.map((group) => (
        <NavSection key={group.key} title={group.title}>
          <NavList items={group.items} onNavigate={onNavigate} />
        </NavSection>
      ))}
      {categories.length ? (
        <NavSection title={labels.categories}>
          <NavList items={categories} onNavigate={onNavigate} />
        </NavSection>
      ) : null}
      <footer className="px-2 text-xs leading-5 text-muted-foreground">
        <div className="flex flex-wrap gap-x-3">
          {(footer.links || []).map((link) => (
            <GooseLink key={`${link.name}-${link.url}`} href={link.url}>
              {link.name}
            </GooseLink>
          ))}
        </div>
        <div className="mt-1 flex flex-wrap gap-x-3">
          {(footer.primary || []).map((item) => (
            <span key={item}>{item}</span>
          ))}
        </div>
      </footer>
    </nav>
  );
}

function NavSection({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section>
      <h2 className="mb-1 px-2 text-[10px] font-bold uppercase tracking-wide text-muted-foreground">
        {title}
      </h2>
      {children}
    </section>
  );
}

function NavList({
  items,
  onNavigate,
}: {
  items: ShellNavItem[];
  onNavigate(): void;
}) {
  return (
    <ul className="flex flex-col gap-0.5">
      {items.map((item) => {
        const Icon = item.icon;
        return (
          <li key={item.key}>
            <Button
              asChild
              variant="ghost"
              className={cn(
                "h-8 w-full justify-start text-[13px] leading-[18.5714px] transition-none",
                "focus-visible:ring-2",
                item.active
                  ? "bg-primary/10 text-primary hover:bg-primary/15 hover:text-primary"
                  : "text-foreground/75 hover:bg-accent hover:text-foreground",
              )}
            >
              <GooseLink
                href={item.url}
                aria-current={item.active ? "page" : undefined}
                onClick={onNavigate}
              >
                {Icon ? (
                  <Icon aria-hidden="true" />
                ) : (
                  <span
                    className="size-2 rounded-sm"
                    style={{ backgroundColor: item.color }}
                  />
                )}
                <span className="min-w-0 truncate">{item.label}</span>
                {item.attention ? <MenuDot /> : null}
              </GooseLink>
            </Button>
          </li>
        );
      })}
    </ul>
  );
}

function MenuDot() {
  return (
    <span
      className="ml-auto size-2 shrink-0 rounded-full bg-destructive"
      aria-hidden="true"
    />
  );
}

// resource/src/site/components/AppShell.vue
<script setup lang="ts">
import { computed, defineAsyncComponent, nextTick, onBeforeUnmount, onMounted, ref, shallowRef, watch } from 'vue'
import {
  Bell,
  FileText,
  Flame,
  Heart,
  Inbox,
  Link,
  MessageCircle,
  Languages,
  LogOut,
  Menu,
  Palette,
  PenSquare,
  Scale,
  TrendingUp,
  Search,
  Settings,
  Shield,
  Moon,
  Sun,
  UserRound,
	UsersRound,
} from '@lucide/vue'
import { useI18n } from 'vue-i18n'
import GlobalFlash from './GlobalFlash.vue'
import { setLocale, supportedLocales, type Locale } from '@/runtime/i18n'
import { useSiteTheme } from '@/runtime/site-theme'
import { useNavigationState } from '@/runtime/navigation-state'
import { useUnreadStatus } from '@/runtime/unread-status'
import { createGooseClient, type LayoutPayload } from '@gooseforum/client'
import type { UserCardShowDetail } from '@/runtime/user-card-events'
import UserAvatar from './UserAvatar.vue'
import type UserCardComponent from './UserCard.vue'

const client = createGooseClient()

const props = defineProps<{
  layout: LayoutPayload
  rail?: boolean
  headerTitle?: string
  headerTags?: Array<{ id: number | string; name: string; color?: string }>
  showHeaderTitle?: boolean
}>()

interface SidebarNavItem {
  key: string
  label: string
  i18nLabel?: string
  url: string
  active: boolean
}

interface SidebarCategoryItem extends SidebarNavItem {
  id: number
  color: string
}

interface SidebarGroupItem {
  key: string
  title: string
  i18nLabel?: string
  items: SidebarNavItem[]
}

const MobileDrawer = defineAsyncComponent(() => import('./MobileDrawer.vue'))
const UserCard = shallowRef<typeof UserCardComponent | null>(null)
const drawerOpen = ref(false)
const headerElevated = ref(false)
const langMenuOpen = ref(false)
const userMenuOpen = ref(false)
const closeTimers: Record<'lang' | 'user', number | undefined> = {
  lang: undefined,
  user: undefined,
}
const { navigating } = useNavigationState()
const { t, te, locale } = useI18n()
const { isDark, toggleTheme } = useSiteTheme()
const unreadStatus = useUnreadStatus()
const hasUnreadNotification = computed(() => unreadStatus.notifications.value)
const hasUnreadMessage = computed(() => unreadStatus.messages.value)
const hasModerationReports = computed(() => unreadStatus.moderationReports.value)
const notificationTitle = computed(() => unreadStatus.notificationMessage.value)
const asArray = <T>(value: T[] | null | undefined): T[] => (Array.isArray(value) ? value : [])
const activeSidebarKey = computed(() => props.layout.sidebar.activeKey || 'topics')
const primaryItems = computed<SidebarNavItem[]>(() => {
  const items: SidebarNavItem[] = [
    sidebarItem('topics', t('shell.nav.topics'), '/'),
    sidebarItem('hot', t('shell.nav.hot'), '/?sort=hot'),
    sidebarItem('popular', t('shell.nav.popular'), '/?sort=popular'),
  ]
  if (props.layout.viewer.isAuthenticated) {
    items.push(
      sidebarItem('messages', t('shell.nav.messages'), '/messages'),
      sidebarItem('notifications', t('shell.nav.notifications'), '/notifications'),
      sidebarItem('drafts', t('shell.nav.drafts'), '/drafts'),
    )
  }
  if (props.layout.viewer.isModerator) {
    items.push(sidebarItem('moderation', t('shell.nav.moderation'), '/moderation'))
  }
  return [...items, ...serverSidebarItems(props.layout.sidebar.main)]
})
const resourceItems = computed<SidebarNavItem[]>(() => [
  sidebarItem('links', t('shell.nav.links'), '/links'),
  sidebarItem('sponsors', t('shell.nav.sponsors'), '/sponsors'),
  ...serverSidebarItems(props.layout.sidebar.resources),
])
const sidebarGroups = computed<SidebarGroupItem[]>(() =>
  asArray(props.layout.sidebar.groups)
    .map((group) => ({
      key: group.key,
      title: displayNavLabel(group),
      i18nLabel: group.i18nLabel,
      items: serverSidebarItems(group.items),
    }))
    .filter((group) => group.title && group.items.length > 0),
)
const categoryItems = computed<SidebarCategoryItem[]>(() =>
  asArray(props.layout.sidebar.categories).map((category) => {
    const key = `category_${category.id}`
    return {
      key,
      id: category.id,
      label: category.label,
      url: category.url,
      color: category.color,
      active: activeSidebarKey.value === key,
    }
  }),
)
const headerResourceItems = computed(() => {
  const configured = serverSidebarItems(props.layout.header)
  return configured.length > 0
    ? configured
    : ['sponsors', 'links']
      .map((key) => resourceItems.value.find((item) => item.key === key))
      .filter((item): item is NonNullable<typeof item> => Boolean(item))
})
const footerLinks = computed(() => asArray(props.layout.footer.links))
const footerPrimary = computed(() => asArray(props.layout.footer.primary))
const hasFooter = computed(() => footerLinks.value.length > 0 || footerPrimary.value.length > 0)
const brandType = computed(() => props.layout.site.brandType || 'default')
const brandText = computed(() => props.layout.site.brandText || props.layout.site.name)
const hasHeaderTitle = computed(() => Boolean(props.showHeaderTitle && props.headerTitle))
const sidebarIconMap = {
  topics: MessageCircle,
  hot: Flame,
  popular: TrendingUp,
  messages: Inbox,
  notifications: Bell,
  drafts: FileText,
  moderation: Scale,
  links: Link,
  sponsors: Heart,
} as const
let userCardLoading: Promise<void> | undefined

watch(
  () => props.layout.sidebar.activeKey,
  () => {
    drawerOpen.value = false
    langMenuOpen.value = false
    userMenuOpen.value = false
  },
)

onMounted(() => {
  if (props.layout.viewer.isAuthenticated) {
    unreadStatus.startPolling(props.layout.unread)
  }
  updateHeaderElevated()
  window.addEventListener('scroll', updateHeaderElevated, { passive: true })
  window.addEventListener('goose:user-card-show', ensureUserCardForEvent)
})

onBeforeUnmount(() => {
  window.removeEventListener('scroll', updateHeaderElevated)
  window.removeEventListener('goose:user-card-show', ensureUserCardForEvent)
})

watch(
  () => props.layout.unread,
  (unread) => {
    if (props.layout.viewer.isAuthenticated) {
      unreadStatus.applyUnread(unread)
    }
  },
  { deep: true },
)

function setLang(lang: Locale) {
  setLocale(lang)
  langMenuOpen.value = false
}

function openDrawer() {
  drawerOpen.value = true
}

function closeDrawer() {
  drawerOpen.value = false
}

async function logout() {
  await client.api.auth.logout()
  window.location.reload()
}

function navIcon(item: SidebarNavItem) {
  return sidebarIconMap[item.key as keyof typeof sidebarIconMap] || Link
}

function displayNavLabel(item: { label?: string; title?: string; i18nLabel?: string }) {
  return item.i18nLabel && te(item.i18nLabel) ? t(item.i18nLabel) : item.label || item.title || ''
}

function sidebarItem(key: string, label: string, url: string): SidebarNavItem {
  return {
    key,
    label,
    url,
    active: activeSidebarKey.value === key,
  }
}

function serverSidebarItems(items: typeof props.layout.sidebar.main): SidebarNavItem[] {
  return asArray(items).map((item) => ({
    key: item.key,
    label: displayNavLabel(item),
    i18nLabel: item.i18nLabel,
    url: item.url,
    active: activeSidebarKey.value === item.key,
  }))
}

function scrollToTop() {
  window.scrollTo({ top: 0, behavior: 'smooth' })
}

function updateHeaderElevated() {
  headerElevated.value = window.scrollY > 8
}

function setHoverMenu(menu: 'lang' | 'user', open: boolean) {
  window.clearTimeout(closeTimers[menu])
  closeTimers[menu] = undefined
  if (menu === 'lang') langMenuOpen.value = open
  else userMenuOpen.value = open
}

function closeHoverMenuSoon(menu: 'lang' | 'user') {
  window.clearTimeout(closeTimers[menu])
  closeTimers[menu] = window.setTimeout(() => {
    if (menu === 'lang') langMenuOpen.value = false
    else userMenuOpen.value = false
  }, 120)
}

function ensureUserCardForEvent(event: Event) {
  if (UserCard.value) return
  const detail = (event as CustomEvent<UserCardShowDetail>).detail
  if (!detail?.user?.id || !detail.target) return
  void loadUserCard().then(async () => {
    await nextTick()
    window.dispatchEvent(new CustomEvent<UserCardShowDetail>('goose:user-card-show', { detail }))
  })
}

async function loadUserCard() {
  if (UserCard.value) return
  if (!userCardLoading) {
    userCardLoading = import('./UserCard.vue')
      .then((module) => {
        UserCard.value = module.default
      })
      .finally(() => {
        userCardLoading = undefined
      })
  }
  await userCardLoading
}
</script>

<template>
  <div class="min-h-screen bg-base-200 text-base-content">
    <div
      v-show="navigating"
      class="fixed left-0 top-0 z-[100] h-0.5 w-full overflow-hidden bg-info/10"
    >
      <div class="h-full w-24 animate-[gf-loading-bar_1s_ease-in-out_infinite] rounded-r-full bg-primary sm:w-36" />
    </div>

    <header
      class="sticky top-0 z-50 border-b border-line bg-base-100/95 backdrop-blur-sm transition-[background-color,border-color,box-shadow,backdrop-filter] duration-200"
      :class="headerElevated
        ? 'sm:shadow-[0_1px_10px_rgb(15_23_42/0.04)]'
        : 'sm:shadow-none'"
    >
      <div class="mx-auto grid h-16 w-full max-w-[1600px] grid-cols-[minmax(0,1fr)_auto] items-center gap-2 px-3 sm:gap-4 sm:px-5 md:grid-cols-[auto_minmax(0,1fr)_auto] lg:gap-8 lg:px-8">
        <div class="flex min-w-0 items-center gap-2 sm:gap-4 lg:gap-8">
          <button
            type="button"
            class="inline-flex h-9 w-9 items-center justify-center rounded-md text-icon-muted hover:bg-base-300 hover:text-base-content lg:hidden"
            :aria-label="t('shell.openMenu')"
            @click="openDrawer"
          >
            <Menu class="h-5 w-5" />
          </button>
          <button
            v-if="hasHeaderTitle"
            type="button"
            class="flex min-w-0 flex-1 flex-col items-start justify-center gap-0.5 self-stretch text-left transition md:hidden"
            @click="scrollToTop"
          >
            <span class="block max-w-full truncate text-lg font-semibold leading-6 text-base-content hover:text-primary">
              {{ headerTitle }}
            </span>
            <span
              v-if="headerTags?.length"
              class="flex max-w-full items-center gap-1 overflow-hidden text-[11px] font-medium leading-4 text-base-content/55"
            >
              <span
                v-for="tag in headerTags"
                :key="tag.id"
                class="inline-flex min-w-0 shrink-0 items-center gap-1"
              >
                <span
                  class="h-1.5 w-1.5 rounded-[2px]"
                  :style="{ backgroundColor: tag.color || 'var(--gf-color-base-content)' }"
                />
                <span class="max-w-20 truncate">{{ tag.name }}</span>
              </span>
            </span>
          </button>
          <a
            href="/"
            class="min-w-0 items-center gap-2"
            :class="hasHeaderTitle ? 'hidden md:flex' : 'flex'"
          >
            <img
              v-if="brandType === 'image' && layout.site.brandImage"
              :src="layout.site.brandImage"
              :alt="layout.site.name"
              class="h-8 w-auto max-w-32 shrink-0 object-contain sm:max-w-40 sm:h-9"
            />
            <span
              v-else-if="brandType === 'text'"
              class="max-w-36 truncate text-xl font-semibold tracking-tighter text-primary sm:max-w-44 sm:text-2xl md:max-w-none"
            >
              {{ brandText }}
            </span>
            <span v-else class="max-w-36 truncate text-xl font-semibold tracking-tighter text-primary sm:max-w-44 sm:text-2xl md:max-w-none">
              Goose<span class="text-base-content">Forum</span>
            </span>
          </a>
          <nav
            v-if="!showHeaderTitle"
            class="hidden items-center gap-1 md:flex"
            aria-label="Header navigation"
          >
            <a
              v-for="item in headerResourceItems"
              :key="item.key"
              :href="item.url"
              class="inline-flex h-7 items-center rounded-md px-2 text-sm font-medium text-base-content/75 transition-colors duration-150 hover:bg-base-300 hover:text-base-content"
            >
              {{ item.label }}
            </a>
          </nav>
        </div>

        <div class="hidden min-w-0 md:block">
          <button
            v-if="hasHeaderTitle"
            type="button"
            class="flex h-16 max-w-full flex-col items-start justify-center gap-0.5 text-left transition"
            @click="scrollToTop"
          >
            <span class="block max-w-full truncate text-xl font-semibold leading-6 text-base-content hover:text-primary">
              {{ headerTitle }}
            </span>
            <span
              v-if="headerTags?.length"
              class="flex max-w-full items-center gap-2 overflow-hidden text-[11px] font-medium leading-4 text-base-content/55"
            >
              <span
                v-for="tag in headerTags"
                :key="tag.id"
                class="inline-flex min-w-0 shrink-0 items-center gap-1"
              >
                <span
                  class="h-1.5 w-1.5 rounded-[2px]"
                  :style="{ backgroundColor: tag.color || 'var(--gf-color-base-content)' }"
                />
                <span class="max-w-28 truncate">{{ tag.name }}</span>
              </span>
            </span>
          </button>
        </div>

        <div
          class="items-center justify-end gap-0.5 sm:gap-1"
          :class="hasHeaderTitle ? 'hidden md:flex' : 'flex'"
        >
          <a
            href="/search"
            class="hidden h-9 w-9 items-center justify-center rounded-full text-icon-muted transition-colors duration-150 hover:bg-base-300 hover:text-base-content sm:inline-flex"
            :aria-label="t('shell.search')"
            :title="t('shell.search')"
          >
            <Search class="h-5 w-5" />
          </a>

          <button
            type="button"
            class="inline-flex h-9 w-9 items-center justify-center rounded-full text-icon-muted transition-colors duration-150 hover:bg-base-300 hover:text-base-content"
            :aria-label="isDark ? 'Switch to light theme' : 'Switch to dark theme'"
            :title="isDark ? 'Light' : 'Dark'"
            @click="toggleTheme"
          >
            <Sun v-if="isDark" class="h-5 w-5" />
            <Moon v-else class="h-5 w-5" />
          </button>

          <div
            class="relative"
            @mouseenter="setHoverMenu('lang', true)"
            @mouseleave="closeHoverMenuSoon('lang')"
            @focusin="setHoverMenu('lang', true)"
            @focusout="closeHoverMenuSoon('lang')"
          >
            <button
              type="button"
              class="inline-flex h-9 w-9 items-center justify-center rounded-full text-icon-muted transition-colors duration-150 hover:bg-base-300 hover:text-base-content"
              :aria-label="t('shell.switchLanguage')"
              :title="t('shell.switchLanguage')"
              :aria-expanded="langMenuOpen"
              @click="langMenuOpen = !langMenuOpen"
            >
              <Languages class="h-5 w-5" />
            </button>
            <Transition name="gf-menu">
              <div
                v-if="langMenuOpen"
                class="absolute right-0 top-full z-[70] w-36 pt-2"
              >
                <div class="gf-menu-surface overflow-hidden py-1">
                  <button
                    v-for="item in supportedLocales"
                    :key="item"
                    class="block w-full px-3 py-1.5 text-left text-sm transition-colors duration-150 hover:bg-base-200"
                    :class="locale === item ? 'font-semibold text-primary' : 'text-base-content/75'"
                    type="button"
                    @click="setLang(item)"
                  >
                    {{ t(`locale.${item}`) }}
                  </button>
                </div>
              </div>
            </Transition>
          </div>

          <template v-if="layout.viewer.isAuthenticated">
            <div
              class="relative"
              @mouseenter="setHoverMenu('user', true)"
              @mouseleave="closeHoverMenuSoon('user')"
              @focusin="setHoverMenu('user', true)"
              @focusout="closeHoverMenuSoon('user')"
            >
              <button
                type="button"
                class="relative ml-1 flex h-10 w-10 items-center justify-center rounded-full transition-colors duration-150 hover:bg-base-300"
                :aria-label="t('shell.userMenu')"
                :aria-expanded="userMenuOpen"
              >
                <UserAvatar :src="layout.viewer.avatarUrl" :alt="layout.viewer.username" class="h-9 w-9 rounded-full object-cover ring-1 ring-line/80" />
                <span
                  v-show="hasUnreadMessage || hasUnreadNotification"
                  class="absolute right-0.5 top-0.5 h-2.5 w-2.5 rounded-full bg-error ring-2 ring-base-100"
                />
              </button>
              <Transition name="gf-menu">
                <div
                  v-if="userMenuOpen"
                  class="absolute right-0 top-full z-[70] w-56 pt-2"
                >
                  <div class="gf-menu-surface overflow-hidden">
                    <div class="border-b border-line/70 px-3 py-2.5">
                      <div class="truncate text-sm font-semibold text-base-content">{{ layout.viewer.username }}</div>
                    </div>
                    <div class="py-1">
                      <a :href="`/u/${layout.viewer.id}`" class="gf-menu-item">
                        <UserRound class="h-4 w-4 text-icon-muted" /> {{ t('shell.profile') }}
                      </a>
                      <a href="/messages" class="gf-menu-item">
                        <Inbox class="h-4 w-4 text-icon-muted" />
                        <span class="min-w-0 flex-1">{{ t('shell.nav.messages') }}</span>
                        <span v-show="hasUnreadMessage" class="h-2 w-2 rounded-full bg-error" />
                      </a>
                      <a href="/notifications" class="gf-menu-item" :title="notificationTitle">
                        <Bell class="h-4 w-4 text-icon-muted" />
                        <span class="min-w-0 flex-1">{{ t('shell.nav.notifications') }}</span>
                        <span v-show="hasUnreadNotification" class="h-2 w-2 rounded-full bg-error" />
                      </a>
                      <a href="/drafts" class="gf-menu-item">
                        <FileText class="h-4 w-4 text-icon-muted" /> {{ t('shell.nav.drafts') }}
                      </a>
                    </div>
                    <div class="border-t border-line/70 py-1">
                      <a href="/publish" class="gf-menu-item-primary">
                        <PenSquare class="h-4 w-4" /> {{ t('shell.publish') }}
                      </a>
                      <a href="/settings" class="gf-menu-item">
                        <Settings class="h-4 w-4 text-icon-muted" /> {{ t('shell.settings') }}
                      </a>
					  <a href="/access-groups" class="gf-menu-item">
						<UsersRound class="h-4 w-4 text-icon-muted" /> {{ t('accessGroups.groups') }}
					  </a>
                      <a v-if="layout.viewer.canAccessAdmin" href="/theme-preview" class="gf-menu-item">
                        <Palette class="h-4 w-4 text-icon-muted" /> {{ t('shell.themePreview') }}
                      </a>
                      <a v-if="layout.viewer.canAccessAdmin" href="/admin" class="gf-menu-item-warning">
                        <Shield class="h-4 w-4" /> {{ t('shell.admin') }}
                      </a>
                    </div>
                    <div class="border-t border-line/70 py-1">
                      <button class="gf-menu-item-danger" type="button" @click="logout">
                        <LogOut class="h-4 w-4" /> {{ t('shell.logout') }}
                      </button>
                    </div>
                  </div>
                </div>
              </Transition>
            </div>
          </template>
          <template v-else>
            <a href="/login" class="rounded-md px-3 py-2 text-sm font-medium text-base-content/75 hover:bg-base-300">{{ t('shell.login') }}</a>
            <a href="/login?register=true" class="gf-button gf-button-md gf-button-neutral hidden sm:inline-flex">{{ t('shell.register') }}</a>
          </template>
        </div>
      </div>
    </header>

    <GlobalFlash />

    <main
      class="gf-shell-main mx-auto grid w-full max-w-[1600px] grid-cols-1 gap-0 px-0 py-0 sm:gap-3 sm:px-5 sm:py-3 lg:grid-cols-[210px_minmax(0,1fr)] lg:px-8 xl:grid-cols-[224px_minmax(0,1fr)]"
      :class="{ 'xl:grid-cols-[224px_minmax(0,1fr)_280px]': rail }"
    >
      <aside class="gf-scrollbar-none sticky top-16 -my-3 hidden h-[calc(100vh-4rem)] overflow-y-auto self-start lg:block" aria-label="Sidebar">
        <nav class="py-3">
          <div class="pb-2">
            <div class="space-y-0.5">
              <a
                v-for="item in primaryItems"
                :key="item.key"
                :href="item.url"
                class="flex h-8 items-center gap-2 rounded-md px-2 text-[13px] font-medium transition-colors duration-150"
                :class="item.active ? 'bg-info/10 text-primary' : 'text-base-content/75 hover:bg-base-300 hover:text-base-content'"
              >
                <component
                  :is="navIcon(item)"
                  v-if="navIcon(item)"
                  class="h-4 w-4 shrink-0"
                  aria-hidden="true"
                />
                <span class="min-w-0 flex-1 truncate">{{ item.label }}</span>
                <span
                  v-if="(item.key === 'messages' && hasUnreadMessage) || (item.key === 'notifications' && hasUnreadNotification) || (item.key === 'moderation' && hasModerationReports)"
                  class="h-2 w-2 shrink-0 rounded-full bg-error/100"
                  aria-hidden="true"
                />
              </a>
            </div>

            <div v-if="resourceItems.length" class="mt-2">
              <div class="mb-1 px-2 text-[10px] font-bold uppercase tracking-wide text-base-content/55">{{ t('shell.resources') }}</div>
              <div class="space-y-px">
                <a
                  v-for="item in resourceItems"
                  :key="item.key"
                  :href="item.url"
                  class="flex h-7 items-center gap-2 rounded-md px-2 text-[13px] font-medium transition-colors duration-150"
                  :class="item.active ? 'bg-info/10 text-primary' : 'text-base-content/75 hover:bg-base-300 hover:text-base-content'"
                >
                  <component
                    :is="navIcon(item)"
                    v-if="navIcon(item)"
                    class="h-4 w-4 shrink-0"
                    aria-hidden="true"
                  />
                  <span class="truncate">{{ item.label }}</span>
                </a>
              </div>
            </div>

            <div
              v-for="group in sidebarGroups"
              :key="group.key"
              class="mt-2"
            >
              <div class="mb-1 px-2 text-[10px] font-bold uppercase tracking-wide text-base-content/55">{{ group.title }}</div>
              <div class="space-y-px">
                <a
                  v-for="item in group.items"
                  :key="item.key"
                  :href="item.url"
                  class="flex h-7 items-center gap-2 rounded-md px-2 text-[13px] font-medium transition-colors duration-150"
                  :class="item.active ? 'bg-info/10 text-primary' : 'text-base-content/75 hover:bg-base-300 hover:text-base-content'"
                >
                  <component
                    :is="navIcon(item)"
                    v-if="navIcon(item)"
                    class="h-4 w-4 shrink-0"
                    aria-hidden="true"
                  />
                  <span class="truncate">{{ item.label }}</span>
                </a>
              </div>
            </div>

            <div v-if="categoryItems.length" class="mt-2">
              <div class="mb-1 px-2 text-[10px] font-bold uppercase tracking-wide text-base-content/55">{{ t('shell.categories') }}</div>
              <div class="space-y-px">
                <a
                  v-for="category in categoryItems"
                  :key="category.key"
                  :href="category.url"
                  class="flex h-7 items-center gap-2 rounded-md px-2 text-[13px] font-medium transition-colors duration-150"
                  :class="category.active ? 'bg-base-300 text-base-content' : 'text-base-content/75 hover:bg-base-300 hover:text-base-content'"
                >
                  <span class="h-2 w-2 rounded-[3px]" :style="{ backgroundColor: category.color }" />
                  <span class="truncate">{{ category.label }}</span>
                </a>
              </div>
            </div>
          </div>

          <footer v-if="hasFooter" class="mt-0 px-2 pt-0.5 text-xs leading-5 text-base-content/75">
            <div v-if="footerLinks.length" class="flex flex-wrap items-center gap-x-3 gap-y-0.5">
              <a
                v-for="link in footerLinks"
                :key="`${link.name}-${link.url}`"
                :href="link.url"
                class="inline-flex min-h-5 items-center rounded hover:text-primary"
              >
                {{ link.name }}
              </a>
            </div>
            <div v-if="footerPrimary.length" class="mt-1 flex flex-wrap items-center gap-x-3 gap-y-0.5 text-base-content/75">
              <span
                v-for="item in footerPrimary"
                :key="item"
                class="inline-flex min-h-5 items-center rounded"
              >
                {{ item }}
              </span>
            </div>
          </footer>
        </nav>
      </aside>

      <section class="gf-shell-content min-w-0">
        <slot />
      </section>

      <aside v-if="rail" id="goose-shell-rail" class="hidden min-w-0 xl:block">
        <slot name="rail" />
      </aside>

      <section
        id="goose-shell-wide-content"
        class="min-w-0 empty:hidden lg:col-start-2 lg:row-start-2 xl:col-start-2 xl:col-span-2"
      />
    </main>

    <MobileDrawer
      v-if="drawerOpen"
      :open="drawerOpen"
      :primary-items="primaryItems"
      :resource-items="resourceItems"
      :sidebar-groups="sidebarGroups"
      :category-items="categoryItems"
      :footer="layout.footer"
      :has-unread-messages="hasUnreadMessage"
      :has-unread-notifications="hasUnreadNotification"
      :has-moderation-reports="hasModerationReports"
      :close-label="t('shell.closeMenu')"
      :menu-label="t('shell.menu')"
      :resources-label="t('shell.resources')"
      :categories-label="t('shell.categories')"
      :sidebar-icon="navIcon"
      @close="closeDrawer"
    />

    <component :is="UserCard" v-if="UserCard" />
  </div>
</template>
