// resource/packages/react/src/site/layout/app-shell.tsx
"use client"

import { useEffect, useState, type ComponentType, type ReactNode, type SVGProps } from 'react'
import {
  BellIcon, FileTextIcon, FlameIcon, HeartIcon, InboxIcon, LanguagesIcon,
  LayoutGridIcon, LinkIcon, LogOutIcon, MenuIcon, MessageCircleIcon, MoonIcon,
  PaletteIcon, PenSquareIcon, SearchIcon, SettingsIcon, ShieldIcon, SunIcon,
  TrendingUpIcon, UserRoundIcon, UsersRoundIcon, XIcon,
} from 'lucide-react'
import type { LayoutPayload, NavItemPayload } from '@gooseforum/client'
import { useTranslation } from 'react-i18next'
import { Avatar, AvatarFallback, AvatarImage } from '../../components/ui/avatar'
import { Button } from '../../components/ui/button'
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem,
  DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuTrigger,
} from '../../components/ui/dropdown-menu'
import {
  Sheet, SheetClose, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger,
} from '../../components/ui/sheet'
import { authLocales } from '../../i18n/auth'
import { cn } from '../../lib/utils'
import { GooseLink, useGooseRuntime } from '../../runtime'

interface ShellNavItem {
  key: string
  label: string
  url: string
  active: boolean
  icon?: ComponentType<SVGProps<SVGSVGElement>>
  color?: string
  attention?: boolean
}

export function AppShell({ layout, children }: { layout: LayoutPayload, children: ReactNode }) {
  const { t, i18n } = useTranslation('shell')
  const runtime = useGooseRuntime()
  const [mobileOpen, setMobileOpen] = useState(false)
  const [unread, setUnread] = useState(layout.unread)
  const activeKey = layout.sidebar.activeKey || 'topics'
  const primary = [
    nav('topics', t('nav.topics'), '/', MessageCircleIcon),
    nav('hot', t('nav.hot'), '/?sort=hot', FlameIcon),
    nav('popular', t('nav.popular'), '/?sort=popular', TrendingUpIcon),
    nav('categories', t('nav.categories'), '/categories', LayoutGridIcon),
    nav('members', t('nav.members'), '/members', UsersRoundIcon),
    ...(layout.viewer.isAuthenticated ? [
      nav('messages', t('nav.messages'), '/messages', InboxIcon, unread.messages),
      nav('notifications', t('nav.notifications'), '/notifications', BellIcon, unread.notifications),
      nav('drafts', t('nav.drafts'), '/drafts', FileTextIcon),
    ] : []),
    ...(layout.viewer.isModerator ? [nav('moderation', t('nav.moderation'), '/moderation', BellIcon, unread.moderationReports)] : []),
    ...serverItems(layout.sidebar.main),
  ]
  const resources = [
    nav('links', t('nav.links'), '/links', LinkIcon),
    nav('sponsors', t('nav.sponsors'), '/sponsors', HeartIcon),
    ...serverItems(layout.sidebar.resources),
  ]
  const categories = (layout.sidebar.categories || []).map((category) => ({
    key: `category_${category.id}`,
    label: category.label,
    url: category.url,
    active: activeKey === `category_${category.id}`,
    color: category.color,
  }))
  const groups = (layout.sidebar.groups || []).map((group) => ({
    key: group.key,
    title: displayLabel(group, group.title),
    items: serverItems(group.items),
  })).filter((group) => group.title && group.items.length)
  const headerItems = layout.header?.length ? serverItems(layout.header) : resources.slice(0, 2)

  function nav(key: string, label: string, url: string, icon?: ShellNavItem['icon'], attention = false): ShellNavItem {
    return { key, label, url, icon, attention, active: activeKey === key }
  }

  function displayLabel(item: { i18nLabel?: string }, fallback: string) {
    const key = item.i18nLabel?.startsWith('shell.') ? item.i18nLabel.slice('shell.'.length) : ''
    return key && i18n.exists(key, { ns: 'shell' }) ? t(key) : fallback
  }

  function serverItems(items?: NavItemPayload[]): ShellNavItem[] {
    return (items || []).map((item) => nav(item.key, displayLabel(item, item.label), item.url, LinkIcon))
  }

  async function logout() {
    await runtime.api.auth.logout()
    runtime.redirect(runtime.currentUrl)
  }

  useEffect(() => {
    setUnread(layout.unread)
  }, [layout.unread])

  useEffect(() => {
    if (!layout.viewer.isAuthenticated) return
    const refreshUnread = () => {
      void runtime.api.notifications.unread().then(setUnread).catch(() => undefined)
    }
    const timer = window.setInterval(refreshUnread, 30_000)
    return () => window.clearInterval(timer)
  }, [layout.viewer.isAuthenticated, runtime.api.notifications])

  const navigation = (
    <ShellNavigation
      primary={primary}
      resources={resources}
      groups={groups}
      categories={categories}
      footer={layout.footer}
      labels={{ resources: t('resources'), categories: t('categories') }}
      onNavigate={() => setMobileOpen(false)}
    />
  )

  return (
    <div className="min-h-svh bg-muted text-foreground">
      {runtime.isNavigating ? <div className="fixed inset-x-0 top-0 z-50 h-0.5 animate-pulse bg-primary" /> : null}
      <header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur-sm">
        <div className="mx-auto flex h-16 w-full max-w-[1600px] items-center gap-2 px-3 lg:gap-8 lg:px-8">
          <Sheet open={mobileOpen} onOpenChange={setMobileOpen}>
            <SheetTrigger asChild>
              <Button variant="ghost" size="icon" className="[&_svg]:size-5 lg:hidden" aria-label={t('openMenu')}>
                <MenuIcon className="size-5" />
              </Button>
            </SheetTrigger>
            <SheetContent side="left" className="w-72 p-0" showCloseButton={false}>
              <SheetHeader className="relative border-b">
                <SheetTitle>{t('menu')}</SheetTitle>
                <SheetDescription className="sr-only">{t('menu')}</SheetDescription>
                <SheetClose asChild>
                  <Button variant="ghost" size="icon-sm" className="absolute right-3 top-3" aria-label={t('closeMenu')}>
                    <XIcon />
                  </Button>
                </SheetClose>
              </SheetHeader>
              <div className="min-h-0 flex-1 overflow-y-auto px-3 pb-5">{navigation}</div>
            </SheetContent>
          </Sheet>

          <SiteBrand layout={layout} />
          <nav className="hidden items-center gap-1 lg:flex" aria-label="Header navigation">
            {headerItems.map((item) => (
              <GooseLink key={item.key} href={item.url} className="rounded-md px-2 py-1.5 text-sm font-medium text-foreground/75 hover:bg-accent">
                {item.label}
              </GooseLink>
            ))}
          </nav>

          <div className="ml-auto flex items-center gap-0.5 lg:gap-1">
            <Button asChild variant="ghost" size="icon-lg" className="[&_svg]:size-5" aria-label={t('search')}>
              <GooseLink href="/search"><SearchIcon className="size-5" /></GooseLink>
            </Button>
            <Button variant="ghost" size="icon-lg" className="[&_svg]:size-5" onClick={runtime.toggleTheme} aria-label={runtime.theme === 'gf-dark' ? t('switchLight') : t('switchDark')}>
              {runtime.theme === 'gf-dark' ? <SunIcon className="size-5" /> : <MoonIcon className="size-5" />}
            </Button>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon-lg" className="[&_svg]:size-5" aria-label={t('switchLanguage')}><LanguagesIcon className="size-5" /></Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuRadioGroup value={runtime.locale} onValueChange={(value) => runtime.setLocale(value as typeof runtime.locale)}>
                  {authLocales.map((locale) => (
                    <DropdownMenuRadioItem key={locale} value={locale}>
                      {i18n.getFixedT(locale, 'auth')('locale.label')}
                    </DropdownMenuRadioItem>
                  ))}
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>

            {layout.viewer.isAuthenticated
              ? (
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="icon-lg" className="relative" aria-label={layout.viewer.username}>
                        <Avatar>
                          <AvatarImage src={layout.viewer.avatarUrl} alt={layout.viewer.username} />
                          <AvatarFallback>{layout.viewer.username.slice(0, 2).toUpperCase()}</AvatarFallback>
                        </Avatar>
                        {unread.messages || unread.notifications ? <span className="absolute right-0 top-0 size-2.5 rounded-full bg-destructive ring-2 ring-background" aria-hidden="true" /> : null}
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" className="w-48">
                      <DropdownMenuGroup>
                        <DropdownMenuItem asChild><GooseLink href={`/u/${layout.viewer.id}`}><UserRoundIcon />{layout.viewer.username}</GooseLink></DropdownMenuItem>
                        <DropdownMenuItem asChild><GooseLink href="/messages"><InboxIcon />{t('nav.messages')}{unread.messages ? <MenuDot /> : null}</GooseLink></DropdownMenuItem>
                        <DropdownMenuItem asChild><GooseLink href="/notifications"><BellIcon />{t('nav.notifications')}{unread.notifications ? <MenuDot /> : null}</GooseLink></DropdownMenuItem>
                        <DropdownMenuItem asChild><GooseLink href="/drafts"><FileTextIcon />{t('nav.drafts')}</GooseLink></DropdownMenuItem>
                      </DropdownMenuGroup>
                      <DropdownMenuSeparator />
                      <DropdownMenuGroup>
                        <DropdownMenuItem asChild><GooseLink href="/publish"><PenSquareIcon />{t('publish')}</GooseLink></DropdownMenuItem>
                        <DropdownMenuItem asChild><GooseLink href="/settings"><SettingsIcon />{t('settings')}</GooseLink></DropdownMenuItem>
                        <DropdownMenuItem asChild><GooseLink href="/access-groups"><UsersRoundIcon />{t('accessGroups')}</GooseLink></DropdownMenuItem>
                        {layout.viewer.canAccessAdmin ? <DropdownMenuItem asChild><GooseLink href="/theme-preview"><PaletteIcon />{t('themePreview')}</GooseLink></DropdownMenuItem> : null}
                        {layout.viewer.canAccessAdmin ? <DropdownMenuItem asChild><GooseLink href="/admin"><ShieldIcon />{t('admin')}</GooseLink></DropdownMenuItem> : null}
                      </DropdownMenuGroup>
                      <DropdownMenuSeparator />
                      <DropdownMenuGroup><DropdownMenuItem variant="destructive" onSelect={() => void logout()}><LogOutIcon />{t('logout')}</DropdownMenuItem></DropdownMenuGroup>
                    </DropdownMenuContent>
                  </DropdownMenu>
                )
              : (
                  <>
                    <Button asChild variant="ghost"><GooseLink href="/login">{t('login')}</GooseLink></Button>
                    <Button asChild className="hidden lg:inline-flex"><GooseLink href="/login?register=true">{t('register')}</GooseLink></Button>
                  </>
                )}
          </div>
        </div>
      </header>

      <main className="mx-auto grid w-full max-w-[1600px] grid-cols-1 lg:grid-cols-[210px_minmax(0,1fr)] lg:gap-3 lg:px-8 lg:py-3 xl:grid-cols-[224px_minmax(0,1fr)]">
        <aside className="sticky top-16 -my-3 hidden h-[calc(100vh-4rem)] min-w-0 self-start overflow-y-auto py-3 pr-3 lg:block" aria-label="Sidebar">
          {navigation}
        </aside>
        <section className="min-w-0">{children}</section>
      </main>
    </div>
  )
}

function SiteBrand({ layout }: { layout: LayoutPayload }) {
  const site = layout.site
  const content = site.brandType === 'image' && site.brandImage
    ? <img src={site.brandImage} alt={site.name} className="h-8 w-auto max-w-40 object-contain" />
    : site.brandType === 'text'
      ? site.brandText || site.name
      : <>Goose<span className="text-foreground">Forum</span></>
  return <GooseLink href="/" className="shrink-0 text-xl font-semibold tracking-tight text-primary lg:text-2xl">{content}</GooseLink>
}

function ShellNavigation({
  primary, resources, groups, categories, footer, labels, onNavigate,
}: {
  primary: ShellNavItem[]
  resources: ShellNavItem[]
  groups: Array<{ key: string, title: string, items: ShellNavItem[] }>
  categories: ShellNavItem[]
  footer: LayoutPayload['footer']
  labels: { resources: string, categories: string }
  onNavigate(): void
}) {
  return (
    <nav className="flex flex-col gap-3">
      <NavList items={primary} onNavigate={onNavigate} />
      <NavSection title={labels.resources}><NavList items={resources} onNavigate={onNavigate} /></NavSection>
      {groups.map((group) => <NavSection key={group.key} title={group.title}><NavList items={group.items} onNavigate={onNavigate} /></NavSection>)}
      {categories.length ? <NavSection title={labels.categories}><NavList items={categories} onNavigate={onNavigate} /></NavSection> : null}
      <footer className="px-2 text-xs leading-5 text-muted-foreground">
        <div className="flex flex-wrap gap-x-3">
          {(footer.links || []).map((link) => <GooseLink key={`${link.name}-${link.url}`} href={link.url}>{link.name}</GooseLink>)}
        </div>
        <div className="mt-1 flex flex-wrap gap-x-3">{(footer.primary || []).map((item) => <span key={item}>{item}</span>)}</div>
      </footer>
    </nav>
  )
}

function NavSection({ title, children }: { title: string, children: ReactNode }) {
  return <section><h2 className="mb-1 px-2 text-[10px] font-bold uppercase tracking-wide text-muted-foreground">{title}</h2>{children}</section>
}

function NavList({ items, onNavigate }: { items: ShellNavItem[], onNavigate(): void }) {
  return (
    <ul className="flex flex-col gap-0.5">
      {items.map((item) => {
        const Icon = item.icon
        return (
          <li key={item.key}>
            <Button asChild variant="ghost" className={cn('h-8 w-full justify-start text-[13px] leading-[18.5714px]', item.active && 'bg-primary/10 text-primary')}>
              <GooseLink href={item.url} aria-current={item.active ? 'page' : undefined} onClick={onNavigate}>
                {Icon ? <Icon aria-hidden="true" /> : <span className="size-2 rounded-sm" style={{ backgroundColor: item.color }} />}
                <span className="min-w-0 truncate">{item.label}</span>
                {item.attention ? <MenuDot /> : null}
              </GooseLink>
            </Button>
          </li>
        )
      })}
    </ul>
  )
}

function MenuDot() {
  return <span className="ml-auto size-2 shrink-0 rounded-full bg-destructive" aria-hidden="true" />
}

// resource/src/components/AppShell.vue
<script setup lang="ts">
import { computed, defineAsyncComponent, onMounted, ref, watch } from 'vue'
import {
  Bell,
  Flame,
  Heart,
  Inbox,
  Link,
  MessageCircle,
  Languages,
  LogOut,
  Menu,
  PenSquare,
  TrendingUp,
  Search,
  Settings,
  Shield,
  UserRound,
} from '@lucide/vue'
import { useI18n } from 'vue-i18n'
import UserHoverCard from './UserHoverCard.vue'
import { setLocale, supportedLocales, type Locale } from '@/runtime/i18n'
import { useNavigationState } from '@/runtime/navigation-state'
import { useUnreadNotifications } from '@/runtime/unread-notifications'
import type { LayoutPayload } from '@/types/payload'

const props = defineProps<{
  layout: LayoutPayload
  rail?: boolean
  headerTitle?: string
  showHeaderTitle?: boolean
}>()

const MobileDrawer = defineAsyncComponent(() => import('./MobileDrawer.vue'))
const drawerOpen = ref(false)
const langMenuOpen = ref(false)
const userMenuOpen = ref(false)
const closeTimers: Record<'lang' | 'user', number | undefined> = {
  lang: undefined,
  user: undefined,
}
const { navigating } = useNavigationState()
const { t, locale } = useI18n()
const unreadNotifications = useUnreadNotifications()
const hasUnreadNotification = computed(() => unreadNotifications.hasUnread.value)
const notificationTitle = computed(() => unreadNotifications.message.value)
const asArray = <T>(value: T[] | null | undefined): T[] => (Array.isArray(value) ? value : [])
const primaryItems = computed(() => asArray(props.layout.sidebar.main))
const resourceItems = computed(() => asArray(props.layout.sidebar.resources))
const categoryItems = computed(() => asArray(props.layout.sidebar.categories))
const headerResourceItems = computed(() =>
  ['sponsors', 'links']
    .map((key) => resourceItems.value.find((item) => item.key === key))
    .filter((item): item is NonNullable<typeof item> => Boolean(item)),
)
const footerLinks = computed(() => asArray(props.layout.footer.links))
const footerPrimary = computed(() => asArray(props.layout.footer.primary))
const hasFooter = computed(() => footerLinks.value.length > 0 || footerPrimary.value.length > 0)
const brandType = computed(() => props.layout.site.brandType || 'default')
const brandText = computed(() => props.layout.site.brandText || props.layout.site.name)
const sidebarIconMap = {
  topics: MessageCircle,
  hot: Flame,
  popular: TrendingUp,
  messages: Inbox,
  notifications: Bell,
  links: Link,
  sponsors: Heart,
} as const

watch(
  () => props.layout.sidebar.activeKey,
  () => {
    drawerOpen.value = false
    langMenuOpen.value = false
    userMenuOpen.value = false
  },
)

onMounted(() => {
  if (props.layout.viewer.isAuthenticated) {
    unreadNotifications.startPolling()
  }
})

function setLang(lang: Locale) {
  setLocale(lang)
  langMenuOpen.value = false
}

function openDrawer() {
  drawerOpen.value = true
}

function closeDrawer() {
  drawerOpen.value = false
}

async function logout() {
  await fetch('/api/logout', { method: 'POST' })
  window.location.reload()
}

function sidebarIcon(key: string) {
  return sidebarIconMap[key as keyof typeof sidebarIconMap]
}

function scrollToTop() {
  window.scrollTo({ top: 0, behavior: 'smooth' })
}

function setHoverMenu(menu: 'lang' | 'user', open: boolean) {
  window.clearTimeout(closeTimers[menu])
  closeTimers[menu] = undefined
  if (menu === 'lang') langMenuOpen.value = open
  else userMenuOpen.value = open
}

function closeHoverMenuSoon(menu: 'lang' | 'user') {
  window.clearTimeout(closeTimers[menu])
  closeTimers[menu] = window.setTimeout(() => {
    if (menu === 'lang') langMenuOpen.value = false
    else userMenuOpen.value = false
  }, 120)
}
</script>

<template>
  <div class="min-h-screen bg-gray-50 text-gray-900">
    <div
      v-show="navigating"
      class="fixed left-0 top-0 z-[100] h-0.5 w-full overflow-hidden bg-blue-100"
    >
      <div class="h-full w-24 animate-[gf-loading-bar_1s_ease-in-out_infinite] rounded-r-full bg-blue-600 sm:w-36" />
    </div>

    <header class="sticky top-0 z-50 border-b border-gray-200/70 bg-white/95 backdrop-blur">
      <div class="mx-auto grid h-16 w-full max-w-[1600px] grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-4 px-3 sm:gap-8 sm:px-5 lg:px-8">
        <div class="flex min-w-0 items-center gap-5 sm:gap-8">
          <button
            type="button"
            class="inline-flex h-9 w-9 items-center justify-center rounded-md text-gray-500 hover:bg-gray-100 hover:text-gray-900 lg:hidden"
            :aria-label="t('shell.openMenu')"
            @click="openDrawer"
          >
            <Menu class="h-5 w-5" />
          </button>
          <a href="/" class="flex min-w-0 shrink-0 items-center gap-2">
            <img
              v-if="brandType === 'image' && layout.site.brandImage"
              :src="layout.site.brandImage"
              :alt="layout.site.name"
              class="h-8 w-auto max-w-40 shrink-0 object-contain sm:h-9"
            />
            <span
              v-else-if="brandType === 'text'"
              class="truncate text-xl font-semibold tracking-tighter text-blue-600 sm:text-2xl"
            >
              {{ brandText }}
            </span>
            <span v-else class="truncate text-xl font-semibold tracking-tighter text-blue-600 sm:text-2xl">
              Goose<span class="text-gray-950">Forum</span>
            </span>
          </a>
          <nav
            v-if="!showHeaderTitle"
            class="hidden items-center gap-6 md:flex"
            aria-label="Header navigation"
          >
            <a
              v-for="item in headerResourceItems"
              :key="item.key"
              :href="item.url"
              class="text-sm font-medium text-gray-500 transition hover:text-blue-600"
            >
              {{ item.label }}
            </a>
          </nav>
        </div>

        <div class="min-w-0">
          <button
            v-if="showHeaderTitle && headerTitle"
            type="button"
            class="block max-w-full truncate text-left text-base font-semibold text-gray-900 transition hover:text-blue-600 sm:text-lg"
            @click="scrollToTop"
          >
            {{ headerTitle }}
          </button>
        </div>

        <div class="flex items-center justify-end gap-1">
          <a
            href="/search"
            class="inline-flex h-9 w-9 items-center justify-center rounded-md text-gray-500 hover:bg-gray-100 hover:text-gray-900"
            :aria-label="t('shell.search')"
            :title="t('shell.search')"
          >
            <Search class="h-5 w-5" />
          </a>

          <div
            class="relative"
            @mouseenter="setHoverMenu('lang', true)"
            @mouseleave="closeHoverMenuSoon('lang')"
            @focusin="setHoverMenu('lang', true)"
            @focusout="closeHoverMenuSoon('lang')"
          >
            <button
              type="button"
              class="inline-flex h-9 w-9 items-center justify-center rounded-md text-gray-500 hover:bg-gray-100 hover:text-gray-900"
              :aria-label="t('shell.switchLanguage')"
              :title="t('shell.switchLanguage')"
              :aria-expanded="langMenuOpen"
            >
              <Languages class="h-5 w-5" />
            </button>
            <div
              v-if="langMenuOpen"
              class="absolute right-0 top-full z-[70] w-36 pt-2"
            >
              <div class="rounded-md border border-gray-100 bg-white py-1 shadow-[0_4px_20px_-4px_rgba(0,0,0,0.1)]">
                <button
                  v-for="item in supportedLocales"
                  :key="item"
                  class="block w-full px-3 py-1.5 text-left text-sm hover:bg-gray-50"
                  :class="locale === item ? 'font-semibold text-blue-600' : 'text-gray-700'"
                  type="button"
                  @click="setLang(item)"
                >
                  {{ t(`locale.${item}`) }}
                </button>
              </div>
            </div>
          </div>

          <template v-if="layout.viewer.isAuthenticated">
            <a
              href="/notifications"
              class="relative inline-flex h-9 w-9 items-center justify-center rounded-md text-gray-500 hover:bg-gray-100 hover:text-gray-900"
              :aria-label="t('shell.notifications')"
              :title="notificationTitle"
            >
              <Bell class="h-5 w-5" />
              <span
                v-show="hasUnreadNotification"
                class="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500 ring-2 ring-white"
              />
            </a>
            <a
              href="/publish"
              class="inline-flex h-9 w-9 items-center justify-center rounded-md text-blue-600 hover:bg-blue-50 hover:text-blue-700"
              :aria-label="t('shell.publish')"
              :title="t('shell.publish')"
            >
              <PenSquare class="h-5 w-5" />
            </a>
            <div
              class="relative"
              @mouseenter="setHoverMenu('user', true)"
              @mouseleave="closeHoverMenuSoon('user')"
              @focusin="setHoverMenu('user', true)"
              @focusout="closeHoverMenuSoon('user')"
            >
              <button
                type="button"
                class="ml-1 flex h-10 w-10 items-center justify-center rounded-full hover:bg-gray-100"
                :aria-label="t('shell.userMenu')"
                :aria-expanded="userMenuOpen"
              >
                <img :src="layout.viewer.avatarUrl" :alt="layout.viewer.username" class="h-9 w-9 rounded-full object-cover" />
              </button>
              <div
                v-if="userMenuOpen"
                class="absolute right-0 top-full z-[70] w-52 pt-2"
              >
                <div class="rounded-md border border-gray-100 bg-white py-1 shadow-[0_4px_20px_-4px_rgba(0,0,0,0.1)]">
                  <div class="border-b border-gray-50 px-3 py-2">
                    <div class="truncate text-sm font-semibold text-gray-900">{{ layout.viewer.username }}</div>
                  </div>
                  <a :href="`/u/${layout.viewer.id}`" class="flex items-center gap-2 px-3 py-1.5 text-sm text-gray-700 hover:bg-gray-50">
                    <UserRound class="h-4 w-4 text-gray-400" /> {{ t('shell.profile') }}
                  </a>
                  <a href="/settings" class="flex items-center gap-2 px-3 py-1.5 text-sm text-gray-700 hover:bg-gray-50">
                    <Settings class="h-4 w-4 text-gray-400" /> {{ t('shell.settings') }}
                  </a>
                  <a v-if="layout.viewer.isAdmin" href="/admin/" class="flex items-center gap-2 px-3 py-1.5 text-sm text-amber-700 hover:bg-amber-50">
                    <Shield class="h-4 w-4" /> {{ t('shell.admin') }}
                  </a>
                  <button class="flex w-full items-center gap-2 px-3 py-1.5 text-left text-sm text-red-600 hover:bg-red-50" type="button" @click="logout">
                    <LogOut class="h-4 w-4" /> {{ t('shell.logout') }}
                  </button>
                </div>
              </div>
            </div>
          </template>
          <template v-else>
            <a href="/login" class="rounded-md px-3 py-2 text-sm font-medium text-gray-600 hover:bg-gray-100">{{ t('shell.login') }}</a>
            <a href="/login?register=true" class="hidden rounded-md bg-gray-900 px-3 py-2 text-sm font-semibold text-white hover:bg-gray-800 sm:inline-flex">{{ t('shell.register') }}</a>
          </template>
        </div>
      </div>
    </header>

    <main
      class="mx-auto grid w-full max-w-[1600px] grid-cols-1 gap-3 px-3 py-3 sm:px-5 lg:grid-cols-[210px_minmax(0,1fr)] lg:px-8 xl:grid-cols-[224px_minmax(0,1fr)]"
      :class="{ 'xl:grid-cols-[224px_minmax(0,1fr)_280px]': rail }"
    >
      <aside class="sticky top-19 hidden h-[calc(100vh-5.5rem)] overflow-y-auto self-start lg:block" aria-label="Sidebar">
        <nav>
          <div class="pb-2">
            <div class="space-y-0.5">
              <a
                v-for="item in primaryItems"
                :key="item.key"
                :href="item.url"
                class="flex h-8 items-center gap-2 rounded-md px-2 text-[13px] font-medium"
                :class="item.active ? 'bg-blue-50 text-blue-700' : 'text-gray-700 hover:bg-gray-100 hover:text-gray-950'"
              >
                <component
                  :is="sidebarIcon(item.key)"
                  v-if="sidebarIcon(item.key)"
                  class="h-4 w-4 shrink-0"
                  aria-hidden="true"
                />
                <span v-else class="flex w-4 justify-center text-[13px] opacity-80" aria-hidden="true">{{ item.icon }}</span>
                <span class="truncate">{{ item.label }}</span>
              </a>
            </div>

            <div v-if="resourceItems.length" class="mt-2.5">
              <div class="mb-1 px-2 text-[10px] font-bold uppercase tracking-wide text-gray-500">{{ t('shell.resources') }}</div>
              <div class="space-y-0.5">
                <a
                  v-for="item in resourceItems"
                  :key="item.key"
                  :href="item.url"
                  class="flex h-8 items-center gap-2 rounded-md px-2 text-[13px] font-medium"
                  :class="item.active ? 'bg-blue-50 text-blue-700' : 'text-gray-700 hover:bg-gray-100 hover:text-gray-950'"
                >
                  <component
                    :is="sidebarIcon(item.key)"
                    v-if="sidebarIcon(item.key)"
                    class="h-4 w-4 shrink-0"
                    aria-hidden="true"
                  />
                  <span v-else class="flex w-4 justify-center text-[13px] opacity-80" aria-hidden="true">{{ item.icon }}</span>
                  <span class="truncate">{{ item.label }}</span>
                </a>
              </div>
            </div>

            <div v-if="categoryItems.length" class="mt-2.5">
              <div class="mb-1 px-2 text-[10px] font-bold uppercase tracking-wide text-gray-500">{{ t('shell.categories') }}</div>
              <div class="space-y-0.5">
                <a
                  v-for="category in categoryItems"
                  :key="category.key"
                  :href="category.url"
                  class="flex h-8 items-center gap-2 rounded-md px-2 text-[13px] font-medium"
                  :class="category.active ? 'bg-gray-100 text-gray-950' : 'text-gray-700 hover:bg-gray-100 hover:text-gray-950'"
                >
                  <span class="h-2 w-2 rounded-[3px]" :style="{ backgroundColor: category.color }" />
                  <span class="truncate">{{ category.label }}</span>
                </a>
              </div>
            </div>
          </div>

          <footer v-if="hasFooter" class="mt-1.5 border-t border-gray-100 px-2 pt-2 text-xs leading-5 text-gray-600">
            <div v-if="footerLinks.length" class="flex flex-wrap items-center gap-x-3 gap-y-0.5">
              <a
                v-for="link in footerLinks"
                :key="`${link.name}-${link.url}`"
                :href="link.url"
                class="inline-flex min-h-5 items-center rounded hover:text-blue-600"
              >
                {{ link.name }}
              </a>
            </div>
            <div v-if="footerPrimary.length" class="mt-1 flex flex-wrap items-center gap-x-3 gap-y-0.5 text-gray-600">
              <span
                v-for="item in footerPrimary"
                :key="item"
                class="inline-flex min-h-5 items-center rounded"
              >
                {{ item }}
              </span>
            </div>
          </footer>
        </nav>
      </aside>

      <section class="min-w-0">
        <slot />
      </section>

      <aside v-if="rail" id="goose-shell-rail" class="hidden min-w-0 xl:block">
        <slot name="rail" />
      </aside>
    </main>

    <MobileDrawer
      :open="drawerOpen"
      :primary-items="primaryItems"
      :resource-items="resourceItems"
      :category-items="categoryItems"
      :footer="layout.footer"
      :close-label="t('shell.closeMenu')"
      :menu-label="t('shell.menu')"
      :categories-label="t('shell.categories')"
      :sidebar-icon="sidebarIcon"
      @close="closeDrawer"
    />

    <UserHoverCard />
  </div>
</template>
