// resource/apps/react/src/admin/components/app-sidebar.tsx
import * as React from 'react'
import type { LayoutPayload } from '@gooseforum/client'
import { Avatar, AvatarFallback, AvatarImage } from '@gooseforum/react/components/ui/avatar'
import {
  Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarHeader,
  SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarRail, useSidebar,
} from '@gooseforum/react/components/ui/sidebar'
import { ExternalLink, GalleryVerticalEnd } from 'lucide-react'
import { hasAnyAdminPermission } from '../access'
import { adminNavGroups } from '../nav'
import type { AdminTextKey } from '../i18n'
import { shouldUseClientNavigation } from '../navigation'

export function AppSidebar({ layout, pathname, text, onNavigate, onPrefetch, ...props }: React.ComponentProps<typeof Sidebar> & {
  layout: LayoutPayload
  pathname: string
  text(key: AdminTextKey): string
  onNavigate(path: string): void
  onPrefetch(path: string): void
}) {
  const { setOpenMobile } = useSidebar()
  const logo = layout.site.logo || layout.site.brandImage || layout.site.favicon
  const initials = (layout.viewer.username || 'A').slice(0, 2).toUpperCase()
  const groups = adminNavGroups.map((group) => ({
    ...group,
    items: group.items.filter((item) => hasAnyAdminPermission(layout.viewer.adminPermissions, item.permission)),
  })).filter((group) => group.items.length)

  return <Sidebar collapsible="offcanvas" {...props}>
    <SidebarHeader className="px-2 pt-2"><SidebarMenu><SidebarMenuItem><SidebarMenuButton asChild size="lg" className="h-10 px-2"><a href="/" target="_blank" rel="noreferrer" title={text('openSite')}>
      <div className="flex size-8 items-center justify-center overflow-hidden rounded-full border bg-background shadow-xs">{logo ? <img src={logo} alt={layout.site.name || 'GooseForum'} className="size-full object-cover" /> : <GalleryVerticalEnd className="size-4.5" />}</div>
      <div className="grid flex-1 text-left leading-tight"><span className="truncate text-base font-semibold tracking-tight">{layout.site.name || 'GooseForum'}</span><span className="truncate text-[11px] text-muted-foreground">{text('console')}</span></div><ExternalLink className="size-3.5 text-muted-foreground" />
    </a></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarHeader>
    <SidebarContent className="gap-1 px-1 py-1.5">{groups.map((group, index) => <SidebarGroup key={group.label || 'main'} className="px-1.5 py-0.5">
      {index > 0 && group.label && <SidebarGroupLabel className="h-7 px-2 text-xs font-medium">{text(group.label)}</SidebarGroupLabel>}
      <SidebarMenu className="gap-0.5">{group.items.map((item) => <SidebarMenuItem key={item.url}><SidebarMenuButton asChild isActive={pathname === item.url} size="sm" tooltip={text(item.label)} className="h-7.5 rounded-md px-2 text-[13px] font-medium text-sidebar-foreground/75 data-[active=true]:bg-sidebar-accent data-[active=true]:text-sidebar-primary"><a
        href={item.url}
        onMouseEnter={() => onPrefetch(item.url)}
        onFocus={() => onPrefetch(item.url)}
        onClick={(event) => {
          if (!shouldUseClientNavigation(event)) return
          event.preventDefault()
          onNavigate(item.url)
          setOpenMobile(false)
        }}
      >{item.icon}<span>{text(item.label)}</span></a></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>
    </SidebarGroup>)}</SidebarContent>
    <SidebarFooter className="px-2 pb-2"><SidebarMenu><SidebarMenuItem><SidebarMenuButton size="lg" className="h-11 rounded-xl px-2"><Avatar className="size-8"><AvatarImage className="object-cover" src={layout.viewer.avatarUrl} alt={layout.viewer.username || 'Admin'} /><AvatarFallback>{initials}</AvatarFallback></Avatar><div className="grid flex-1 text-left text-sm leading-tight"><span className="truncate font-semibold">{layout.viewer.username || 'Admin'}</span><span className="truncate text-xs text-muted-foreground">{layout.viewer.email}</span></div></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarFooter>
    <SidebarRail />
  </Sidebar>
}

// resource/src/admin/components/layout/AppSidebar.vue
<script lang="ts" setup>
import { adminText } from '@/admin/runtime/i18n-text'
import {
  Award,
  FileText,
  Files,
  ExternalLink,
  GalleryVerticalEnd,
  Heart,
  Link,
  ListChecks,
  Mail,
  Megaphone,
  Monitor,
  KeyRound,
  LogIn,
  PanelsTopLeft,
  ShieldCheck,
  PanelLeft,
  Tags,
  UserCog,
  UsersRound,
  Webhook,
  ShieldAlert,
} from '@lucide/vue'
import { computed } from 'vue'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarRail,
} from '@/components/ui/sidebar'
import { RouterLink, useRoute } from 'vue-router'
import type { LayoutPayload } from '@gooseforum/client'
import type { LucideIcon } from '@lucide/vue'
import type { SidebarProps } from '@/components/ui/sidebar'
import { useI18n } from 'vue-i18n'
import { AdminPermission, hasAnyAdminPermission } from '@/admin/runtime/access'

const props = withDefaults(defineProps<{
  layout: LayoutPayload
  variant?: SidebarProps['variant']
}>(), {
  variant: 'sidebar',
})

const route = useRoute()
const { locale, t } = useI18n()
const currentPath = computed(() => route.path.replace(/\/+$/, '') || '/admin')
const siteLogo = computed(() => props.layout.site.logo || props.layout.site.brandImage || props.layout.site.favicon)
const viewerInitials = computed(() => (props.layout.viewer.username || 'A').slice(0, 2).toUpperCase())

interface NavItem {
  title: string
  url: string
  icon: LucideIcon
  permission?: AdminPermission | AdminPermission[]
  active?: boolean
  external?: boolean
  items?: NavItem[]
}

interface NavGroup {
  title: string
  items: NavItem[]
}

const navGroups = computed<NavGroup[]>(() => {
  locale.value
  return [
    {
      title: 'GooseForum',
      items: [
        { title: adminText('k004c'), url: '/admin', icon: Monitor, permission: AdminPermission.Admin },
        { title: adminText('k006i'), url: '/admin/users', icon: UserCog, permission: AdminPermission.UserManager },
        { title: adminText('k007f'), url: '/admin/roles', icon: ShieldCheck, permission: AdminPermission.RoleManager },
        {
          title: t('accessGroups.groups'),
          url: '/admin/access-groups',
          icon: UsersRound,
          permission: AdminPermission.RoleManager,
        },
        {
          title: adminText('k005l'),
          url: '/admin/categories',
          icon: Tags,
          permission: [AdminPermission.TopicsManager, AdminPermission.RoleManager],
        },
        { title: adminText('k005u'), url: '/admin/posts', icon: FileText, permission: AdminPermission.TopicsManager },
        { title: adminText('k002j'), url: '/admin/links', icon: Link, permission: AdminPermission.PageManager },
        { title: adminText('k004o'), url: '/admin/sponsors', icon: Heart, permission: AdminPermission.PageManager },
        { title: adminText('k0058'), url: '/admin/badges', icon: Award, permission: AdminPermission.SiteManager },
        {
          title: adminText('k00f6'),
          url: '/admin/files/resources',
          icon: Files,
          permission: AdminPermission.SiteManager,
        },
        { title: adminText('k007c'), url: '/admin/opt-records', icon: ListChecks, permission: AdminPermission.Admin },
      ],
    },
    {
      title: adminText('k007t'),
      items: [
        {
          title: adminText('k007u'),
          url: '/admin/settings/site-info',
          icon: PanelsTopLeft,
          permission: AdminPermission.SiteManager,
        },
        {
          title: adminText('k00d9'),
          url: '/admin/settings/site-chrome',
          icon: PanelLeft,
          permission: AdminPermission.SiteManager,
        },
        { title: adminText('k007v'), url: '/admin/settings/mail', icon: Mail, permission: AdminPermission.SiteManager },
        { title: 'OAuth', url: '/admin/settings/oauth', icon: KeyRound, permission: AdminPermission.SiteManager },
        {
          title: adminText('oidcTitle'),
          url: '/admin/settings/oidc-provider',
          icon: LogIn,
          permission: AdminPermission.SiteManager,
        },
        {
          title: adminText('k0005'),
          url: '/admin/settings/security',
          icon: ShieldCheck,
          permission: AdminPermission.SiteManager,
        },
        {
          title: adminText('k007w'),
          url: '/admin/settings/posting',
          icon: FileText,
          permission: AdminPermission.SiteManager,
        },
        {
          title: adminText('k0009'),
          url: '/admin/settings/announcement',
          icon: Megaphone,
          permission: AdminPermission.PageManager,
        },
        {
          title: adminText('k00cj'),
          url: '/admin/settings/http-notify',
          icon: Webhook,
          permission: AdminPermission.SiteManager,
        },
        { title: adminText('sensitiveTitle'), url: '/admin/settings/sensitive-words', icon: ShieldAlert, permission: AdminPermission.SiteManager },
      ],
    },
  ]
    .map((group) => ({
      ...group,
      items: group.items.filter((item) => item.permission === undefined || hasAnyAdminPermission(item.permission)),
    }))
    .filter((group) => group.items.length > 0)
})

function isActive(item: NavItem) {
  return currentPath.value === item.url
}
</script>

<template>
  <Sidebar :variant="variant" collapsible="offcanvas" class="z-50">
    <SidebarHeader class="px-2 pt-2">
      <SidebarMenu>
        <SidebarMenuItem>
          <SidebarMenuButton
            as-child
            size="lg"
            class="h-10 px-2 data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
          >
            <a href="/" target="_blank" rel="noopener noreferrer" :title="adminText('k007s')">
              <div class="flex aspect-square size-8 items-center justify-center overflow-hidden rounded-full border border-sidebar-border bg-background text-foreground shadow-xs">
                <img
                  v-if="siteLogo"
                  :src="siteLogo"
                  :alt="layout.site.name || 'GooseForum'"
                  class="size-full rounded-full object-cover"
                />
                <GalleryVerticalEnd v-else class="size-4.5" />
              </div>
              <div class="grid flex-1 text-left text-sm leading-tight">
                <span class="truncate text-base font-semibold tracking-tight">{{ layout.site.name || 'GooseForum' }}</span>
                <span class="truncate text-[11px] text-muted-foreground">Admin Console</span>
              </div>
            </a>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
    </SidebarHeader>

    <SidebarContent class="gap-2 px-1 py-1">
      <SidebarGroup v-for="(group, groupIndex) in navGroups" :key="group.title" class="py-0">
        <SidebarGroupLabel v-if="groupIndex > 0" class="h-8 px-2 text-xs font-medium">{{ group.title }}</SidebarGroupLabel>
        <SidebarMenu class="gap-1">
          <SidebarMenuItem v-for="item in group.items" :key="item.title">
            <SidebarMenuButton
              as-child
              :is-active="isActive(item)"
              :tooltip="item.title"
              class="h-8 rounded-md px-2 text-[13px] font-medium text-base-content/75 hover:bg-base-300 hover:text-base-content data-[active=true]:border-transparent data-[active=true]:bg-info/10 data-[active=true]:text-primary data-[active=true]:shadow-none data-[active=true]:hover:bg-info/10 data-[active=true]:hover:text-primary"
            >
              <a v-if="item.external" :href="item.url" target="_blank" rel="noopener noreferrer">
                <component :is="item.icon" />
                <span>{{ item.title }}</span>
                <ExternalLink class="ml-auto size-4" />
              </a>
              <RouterLink v-else :to="item.url">
                <component :is="item.icon" />
                <span>{{ item.title }}</span>
              </RouterLink>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarGroup>
    </SidebarContent>

    <SidebarFooter class="px-2 pb-2">
      <SidebarMenu>
        <SidebarMenuItem>
          <SidebarMenuButton size="lg" class="h-11 rounded-xl border border-transparent px-2 hover:border-sidebar-border hover:bg-sidebar-accent">
            <Avatar class="size-8 rounded-full">
              <AvatarImage class="object-cover" :src="layout.viewer.avatarUrl" :alt="layout.viewer.username || 'admin'" />
              <AvatarFallback class="rounded-full">{{ viewerInitials }}</AvatarFallback>
            </Avatar>
            <div class="grid flex-1 text-left text-sm leading-tight">
              <span class="truncate font-semibold">{{ layout.viewer.username || 'Admin' }}</span>
              <span class="truncate text-xs">{{ layout.viewer.email || adminText('k007x') }}</span>
            </div>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
    </SidebarFooter>

    <SidebarRail />
  </Sidebar>
</template>
