// resource/src/admin/pages/stats/TrafficOverview.vue
<script setup lang="ts">
import { VisArea, VisAxis, VisLine, VisXYContainer } from '@unovis/vue'
import { computed } from 'vue'
import type { ChartConfig } from '@/admin/components/ui/chart'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/admin/components/ui/card'
import {
  ChartContainer,
  ChartCrosshair,
  ChartLegendContent,
  ChartTooltip,
  ChartTooltipContent,
  componentToString,
} from '@/admin/components/ui/chart'
import type { DailyTraffic } from '@/admin/types'

const props = defineProps<{
  data: DailyTraffic[]
  loading?: boolean
}>()

type Data = {
  date: Date
  regCount: number
  articleCount: number
  replyCount: number
}

const chartData = computed<Data[]>(() =>
  props.data.map(item => ({
    date: new Date(item.date),
    regCount: item.regCount,
    articleCount: item.articleCount,
    replyCount: item.replyCount,
  })),
)

const chartConfig = {
  regCount: {
    label: '注册用户',
    color: 'var(--chart-1)',
  },
  articleCount: {
    label: '新增文章',
    color: 'var(--chart-2)',
  },
  replyCount: {
    label: '新增回复',
    color: 'var(--chart-4)',
  },
} satisfies ChartConfig

const svgDefs = `
  <linearGradient id="fillRegCount" x1="0" y1="0" x2="0" y2="1">
    <stop offset="5%" stop-color="var(--color-regCount)" stop-opacity="0.8" />
    <stop offset="95%" stop-color="var(--color-regCount)" stop-opacity="0.1" />
  </linearGradient>
  <linearGradient id="fillArticleCount" x1="0" y1="0" x2="0" y2="1">
    <stop offset="5%" stop-color="var(--color-articleCount)" stop-opacity="0.8" />
    <stop offset="95%" stop-color="var(--color-articleCount)" stop-opacity="0.1" />
  </linearGradient>
  <linearGradient id="fillReplyCount" x1="0" y1="0" x2="0" y2="1">
    <stop offset="5%" stop-color="var(--color-replyCount)" stop-opacity="0.8" />
    <stop offset="95%" stop-color="var(--color-replyCount)" stop-opacity="0.1" />
  </linearGradient>
`
</script>

<template>
  <Card class="h-full pt-0">
    <CardHeader class="flex items-center gap-2 space-y-0 border-b py-5 sm:flex-row">
      <div class="grid flex-1 gap-1">
        <CardTitle>流量概览</CardTitle>
        <CardDescription>展示注册用户、文章和回复的增长趋势</CardDescription>
      </div>
      <slot name="headerAction" />
    </CardHeader>
    <CardContent class="px-2 pt-4 pb-4 sm:px-6 sm:pt-6">
      <div v-if="loading" class="flex h-[350px] items-center justify-center text-muted-foreground">
        加载中...
      </div>
      <ChartContainer v-else :config="chartConfig" class="aspect-auto h-[300px] w-full" :cursor="false">
        <VisXYContainer
          :data="chartData"
          :svg-defs="svgDefs"
          :margin="{ top: 12, right: 12, left: -40, bottom: 24 }"
        >
          <VisArea
            :x="(d: Data) => d.date"
            :y="[(d: Data) => d.regCount, (d: Data) => d.articleCount, (d: Data) => d.replyCount]"
            :color="(_d: Data, i: number) => ['url(#fillRegCount)', 'url(#fillArticleCount)', 'url(#fillReplyCount)'][i]"
            :opacity="0.6"
          />
          <VisLine
            :x="(d: Data) => d.date"
            :y="[(d: Data) => d.regCount, (d: Data) => d.articleCount, (d: Data) => d.replyCount]"
            :color="(_d: Data, i: number) => [chartConfig.regCount.color, chartConfig.articleCount.color, chartConfig.replyCount.color][i]"
            :line-width="1"
          />
          <VisAxis
            type="x"
            :x="(d: Data) => d.date"
            :tick-line="false"
            :domain-line="false"
            :grid-line="false"
            :num-ticks="6"
            :tick-format="(d: number) => {
              const date = new Date(d)
              return date.toLocaleDateString('en-US', {
                month: 'short',
                day: 'numeric',
              })
            }"
          />
          <VisAxis
            type="y"
            :num-ticks="4"
            :tick-line="false"
            :domain-line="false"
          />
          <ChartTooltip />
          <ChartCrosshair
            :template="componentToString(chartConfig, ChartTooltipContent, {
              labelFormatter: (d) => {
                const date = new Date(d)
                return date.toLocaleDateString('en-US', {
                  month: 'short',
                  day: 'numeric',
                  year: 'numeric',
                })
              },
            })"
            :color="(_d: Data, i: number) => [chartConfig.regCount.color, chartConfig.articleCount.color, chartConfig.replyCount.color][i % 3]"
          />
        </VisXYContainer>
        <ChartLegendContent />
      </ChartContainer>
    </CardContent>
  </Card>
</template>

// admin/src/features/dashboard-stats/components/traffic-overview.tsx
import { ReactNode } from 'react'
import { Area, AreaChart, ResponsiveContainer, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'

interface TrafficData {
  date: string
  regCount: number
  articleCount: number
  replyCount: number
}

interface TrafficOverviewProps {
  data: TrafficData[]
  loading?: boolean
  headerAction?: ReactNode
}

export function TrafficOverview({ data, loading, headerAction }: TrafficOverviewProps) {
  return (
    <Card className='h-full'>
      <CardHeader className='flex flex-row items-center justify-between space-y-0 pb-7'>
        <div className='space-y-1'>
          <CardTitle>流量概览</CardTitle>
          <CardDescription>展示注册用户、文章和回复的增长趋势</CardDescription>
        </div>
        {headerAction}
      </CardHeader>
      <CardContent className='px-2 sm:px-6'>
        <div className='h-[350px] w-full' style={{ minWidth: 0 }}>
          {loading ? (
            <div className='flex h-full w-full items-center justify-center text-muted-foreground'>
              加载中...
            </div>
          ) : (
            <ResponsiveContainer width='100%' height={350}>
              <AreaChart data={data} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                <defs>
                          <linearGradient id='colorReg' x1='0' y1='0' x2='0' y2='1'>
                            <stop offset='5%' stopColor='#2563eb' stopOpacity={0.3} />
                            <stop offset='95%' stopColor='#2563eb' stopOpacity={0} />
                          </linearGradient>
                          <linearGradient id='colorArticle' x1='0' y1='0' x2='0' y2='1'>
                            <stop offset='5%' stopColor='#10b981' stopOpacity={0.3} />
                            <stop offset='95%' stopColor='#10b981' stopOpacity={0} />
                          </linearGradient>
                          <linearGradient id='colorReply' x1='0' y1='0' x2='0' y2='1'>
                            <stop offset='5%' stopColor='#f59e0b' stopOpacity={0.3} />
                            <stop offset='95%' stopColor='#f59e0b' stopOpacity={0} />
                          </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray='3 3' vertical={false} stroke='hsl(var(--muted-foreground))' opacity={0.1} />
                        <XAxis
                          dataKey='date'
                          stroke='hsl(var(--muted-foreground))'
                          fontSize={12}
                          tickLine={false}
                          axisLine={false}
                          tickFormatter={(value) => value.split('-').slice(1).join('/')}
                        />
                        <YAxis
                          stroke='hsl(var(--muted-foreground))'
                          fontSize={12}
                          tickLine={false}
                          axisLine={false}
                        />
                        <Tooltip
                          content={({ active, payload, label }) => {
                            if (active && payload && payload.length) {
                              return (
                                <div className='rounded-lg border bg-background p-2 shadow-sm'>
                                  <div className='mb-2 border-b pb-1'>
                                    <span className='text-[0.70rem] uppercase text-muted-foreground'>
                                      日期：
                                    </span>
                                    <span className='font-bold text-foreground ml-1'>
                                      {label}
                                    </span>
                                  </div>
                                  <div className='flex flex-col gap-1'>
                                    {payload.map((item) => (
                                      <div key={item.name} className='flex items-center justify-between gap-4'>
                                        <div className='flex items-center gap-1.5'>
                                          <div 
                                            className='h-2 w-2 rounded-full' 
                                            style={{ backgroundColor: item.color }}
                                          />
                                          <span className='text-[0.70rem] text-muted-foreground'>
                                            {item.name === 'regCount' ? '注册用户' : item.name === 'articleCount' ? '新增文章' : '新增回复'}
                                          </span>
                                        </div>
                                        <span className='font-bold text-sm' style={{ color: item.color }}>
                                          {item.value}
                                        </span>
                                      </div>
                                    ))}
                                  </div>
                                </div>
                              )
                            }
                            return null
                          }}
                        />
                        <Area
                          name='regCount'
                          type='monotone'
                          dataKey='regCount'
                          stroke='#2563eb'
                          strokeWidth={2}
                          fill='url(#colorReg)'
                        />
                        <Area
                          name='articleCount'
                          type='monotone'
                          dataKey='articleCount'
                          stroke='#10b981'
                          strokeWidth={2}
                          fill='url(#colorArticle)'
                        />
                        <Area
                          name='replyCount'
                          type='monotone'
                          dataKey='replyCount'
                          stroke='#f59e0b'
                          strokeWidth={2}
                          fill='url(#colorReply)'
                        />
              </AreaChart>
            </ResponsiveContainer>
          )}
        </div>
      </CardContent>
    </Card>
  )
}
