// resource/src/admin/pages/stats/DateRangePicker.vue
<script setup lang="ts">
import type { DateValue } from '@internationalized/date'
import type { DateRange } from 'reka-ui'
import { CalendarDate, DateFormatter, getLocalTimeZone } from '@internationalized/date'
import { Calendar } from '@lucide/vue'
import { computed, ref, shallowRef, watch } from 'vue'
import { Button } from '@/admin/components/ui/button'
import { Popover, PopoverContent, PopoverTrigger } from '@/admin/components/ui/popover'
import { RangeCalendar } from '@/admin/components/ui/range-calendar'
import { cn } from '@/admin/utils/cn'

const props = defineProps<{
  startDate: string
  endDate: string
}>()

const emit = defineEmits<{
  'update:startDate': [value: string]
  'update:endDate': [value: string]
  change: []
}>()

const formatter = new DateFormatter('en-US', {
  month: 'short',
  day: 'numeric',
  year: 'numeric',
})

const open = ref(false)
const value = shallowRef<DateRange>({
  start: parseDate(props.startDate),
  end: parseDate(props.endDate),
})

const label = computed(() => {
  if (!value.value.start) return '选择日期范围'
  const start = formatDateValue(value.value.start)
  if (!value.value.end) return start
  return `${start} - ${formatDateValue(value.value.end)}`
})

watch(
  () => [props.startDate, props.endDate],
  ([startDate, endDate]) => {
    const nextStart = parseDate(startDate)
    const nextEnd = parseDate(endDate)
    if (toISO(value.value.start) === startDate && toISO(value.value.end) === endDate) return
    value.value = { start: nextStart, end: nextEnd }
  },
)

function handleValueChange(next: DateRange) {
  value.value = next
  const start = toISO(next.start)
  const end = toISO(next.end)
  if (!start || !end) return
  emit('update:startDate', start)
  emit('update:endDate', end)
  emit('change')
  open.value = false
}

function parseDate(value?: string): CalendarDate | undefined {
  if (!value) return undefined
  const [year, month, day] = value.split('-').map(Number)
  if (!year || !month || !day) return undefined
  return new CalendarDate(year, month, day)
}

function toISO(value?: DateValue): string {
  if (!value) return ''
  return value.toString()
}

function formatDateValue(value: DateValue): string {
  return formatter.format(value.toDate(getLocalTimeZone()))
}
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button
        variant="outline"
        :class="cn(
          'h-10 w-full justify-start rounded-lg bg-background px-3 text-left font-normal shadow-sm sm:w-[320px]',
          !value.start && 'text-muted-foreground',
        )"
      >
        <Calendar class="mr-2 h-4 w-4 text-muted-foreground" />
        <span class="truncate">{{ label }}</span>
      </Button>
    </PopoverTrigger>
    <PopoverContent class="w-auto p-0" align="end">
      <RangeCalendar
        :model-value="value"
        :number-of-months="2"
        initial-focus
        @update:model-value="handleValueChange"
      />
    </PopoverContent>
  </Popover>
</template>

// admin/src/components/date-range-picker.tsx
import * as React from 'react'
import { format } from 'date-fns'
import { Calendar as CalendarIcon } from 'lucide-react'
import { DateRange } from 'react-day-picker'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Calendar } from '@/components/ui/calendar'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'

interface DateRangePickerProps extends React.HTMLAttributes<HTMLDivElement> {
  date: DateRange | undefined
  setDate: (date: DateRange | undefined) => void
}

export function DateRangePicker({
  className,
  date,
  setDate,
}: DateRangePickerProps) {
  return (
    <div className={cn('grid gap-2', className)}>
      <Popover>
        <PopoverTrigger asChild>
          <Button
            id='date'
            variant={'outline'}
            className={cn(
              'w-[300px] justify-start text-left font-normal',
              !date && 'text-muted-foreground'
            )}
          >
            <CalendarIcon className='mr-2 h-4 w-4' />
            {date?.from ? (
              date.to ? (
                <>
                  {format(date.from, 'LLL dd, y')} -{' '}
                  {format(date.to, 'LLL dd, y')}
                </>
              ) : (
                format(date.from, 'LLL dd, y')
              )
            ) : (
              <span>选择日期范围</span>
            )}
          </Button>
        </PopoverTrigger>
        <PopoverContent className='w-auto p-0' align='start'>
          <Calendar
            initialFocus
            mode='range'
            defaultMonth={date?.from}
            selected={date}
            onSelect={setDate}
            numberOfMonths={2}
          />
        </PopoverContent>
      </Popover>
    </div>
  )
}
