// resource/apps/web/src/admin/components/traffic-overview.tsx
import { useMemo, type CSSProperties } from "react";
import { parseISO } from "date-fns";
import type { DailyTraffic } from "@gooseforum/client";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@gooseforum/ui/components/card";
import {
  type ChartConfig,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@gooseforum/ui/components/chart";
import { Skeleton } from "@gooseforum/ui/components/skeleton";
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts";
import type { DashboardTextKey } from "../dashboard-i18n";
import { type DashboardDateRange } from "./date-range";
import { DateRangePicker } from "./date-range-picker";

type Text = (key: DashboardTextKey) => string;

export function TrafficOverview({
  data,
  loading,
  range,
  locale,
  text,
  onRangeChange,
}: {
  data: DailyTraffic[];
  loading: boolean;
  range: DashboardDateRange;
  locale: string;
  text: Text;
  onRangeChange(value: DashboardDateRange): void;
}) {
  const config = useMemo(
    () =>
      ({
        regCount: { label: text("registrations"), color: "var(--chart-1)" },
        topicCount: { label: text("topics"), color: "var(--chart-2)" },
        replyCount: { label: text("posts"), color: "var(--chart-4)" },
      }) satisfies ChartConfig,
    [text],
  );
  const totals = useMemo(
    () =>
      data.reduce(
        (result, item) => ({
          regCount: result.regCount + item.regCount,
          topicCount: result.topicCount + item.topicCount,
          replyCount: result.replyCount + item.replyCount,
        }),
        { regCount: 0, topicCount: 0, replyCount: 0 },
      ),
    [data],
  );
  const dateFormatter = useMemo(
    () => new Intl.DateTimeFormat(locale, { month: "short", day: "numeric" }),
    [locale],
  );
  const longDateFormatter = useMemo(
    () =>
      new Intl.DateTimeFormat(locale, {
        year: "numeric",
        month: "short",
        day: "numeric",
      }),
    [locale],
  );

  return (
    <Card className="h-full gap-0 overflow-hidden py-0">
      <CardHeader className="border-b px-4 py-4 sm:flex sm:flex-row sm:items-center sm:justify-between sm:px-5">
        <div className="flex flex-col gap-1">
          <CardTitle>{text("traffic")}</CardTitle>
          <CardDescription>{text("trafficHint")}</CardDescription>
        </div>
        <DateRangePicker
          value={range}
          locale={locale}
          text={text}
          onChange={onRangeChange}
        />
      </CardHeader>
      <div className="grid grid-cols-3 divide-x border-b bg-muted/20">
        {(
          [
            ["regCount", text("registrations")],
            ["topicCount", text("topics")],
            ["replyCount", text("posts")],
          ] as const
        ).map(([key, label]) => (
          <div
            key={key}
            className="flex min-w-0 flex-col gap-1 px-3 py-3 sm:px-5"
          >
            <div className="flex items-center gap-2 text-xs text-muted-foreground sm:text-sm">
              <span
                className="size-2 shrink-0 rounded-full bg-(--metric-color)"
                style={{ "--metric-color": config[key].color } as CSSProperties}
              />
              <span className="truncate">{label}</span>
            </div>
            {loading ? (
              <Skeleton className="h-7 w-16" />
            ) : (
              <strong className="text-xl tabular-nums tracking-tight sm:text-2xl">
                {totals[key].toLocaleString(locale)}
              </strong>
            )}
          </div>
        ))}
      </div>
      <CardContent className="px-2 pb-4 pt-5 sm:px-4">
        {loading ? (
          <div className="flex h-[290px] flex-col gap-4 px-4 py-3 sm:h-[330px]">
            <Skeleton className="h-full w-full" />
          </div>
        ) : data.length ? (
          <ChartContainer
            config={config}
            className="h-[290px] w-full sm:h-[330px]"
          >
            <AreaChart
              accessibilityLayer
              data={data}
              margin={{ top: 8, right: 12, left: 4, bottom: 0 }}
            >
              <defs>
                {Object.entries(config).map(([key, item]) => (
                  <linearGradient
                    key={key}
                    id={`traffic-${key}`}
                    x1="0"
                    y1="0"
                    x2="0"
                    y2="1"
                  >
                    <stop
                      offset="8%"
                      stopColor={item.color}
                      stopOpacity={0.28}
                    />
                    <stop
                      offset="92%"
                      stopColor={item.color}
                      stopOpacity={0.02}
                    />
                  </linearGradient>
                ))}
              </defs>
              <CartesianGrid vertical={false} strokeDasharray="3 3" />
              <XAxis
                dataKey="date"
                tickLine={false}
                axisLine={false}
                tickMargin={10}
                minTickGap={28}
                tickFormatter={(value) =>
                  dateFormatter.format(parseISO(String(value)))
                }
              />
              <YAxis
                tickLine={false}
                axisLine={false}
                tickMargin={8}
                allowDecimals={false}
                width={36}
              />
              <ChartTooltip
                cursor={{ stroke: "var(--border)", strokeDasharray: "4 4" }}
                content={
                  <ChartTooltipContent
                    indicator="line"
                    labelFormatter={(value) =>
                      longDateFormatter.format(parseISO(String(value)))
                    }
                  />
                }
              />
              <Area
                type="monotone"
                dataKey="replyCount"
                stroke="var(--color-replyCount)"
                fill="url(#traffic-replyCount)"
                strokeWidth={2}
              />
              <Area
                type="monotone"
                dataKey="topicCount"
                stroke="var(--color-topicCount)"
                fill="url(#traffic-topicCount)"
                strokeWidth={2}
              />
              <Area
                type="monotone"
                dataKey="regCount"
                stroke="var(--color-regCount)"
                fill="url(#traffic-regCount)"
                strokeWidth={2}
              />
            </AreaChart>
          </ChartContainer>
        ) : (
          <div className="grid h-[290px] place-items-center text-sm text-muted-foreground sm:h-[330px]">
            {text("empty")}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// resource/src/admin/pages/stats/TrafficOverview.vue
<script setup lang="ts">
import { VisArea, VisAxis, VisLine, VisXYContainer } from '@unovis/vue'
import { computed } from 'vue'
import type { ChartConfig } from '@/admin/components/ui/chart'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/admin/components/ui/card'
import {
  ChartContainer,
  ChartCrosshair,
  ChartLegendContent,
  ChartTooltip,
  ChartTooltipContent,
  componentToString,
} from '@/admin/components/ui/chart'
import type { DailyTraffic } from '@/admin/types'

const props = defineProps<{
  data: DailyTraffic[]
  loading?: boolean
}>()

type Data = {
  date: Date
  regCount: number
  articleCount: number
  replyCount: number
}

const chartData = computed<Data[]>(() =>
  props.data.map(item => ({
    date: new Date(item.date),
    regCount: item.regCount,
    articleCount: item.articleCount,
    replyCount: item.replyCount,
  })),
)

const chartConfig = {
  regCount: {
    label: '注册用户',
    color: 'var(--chart-1)',
  },
  articleCount: {
    label: '新增文章',
    color: 'var(--chart-2)',
  },
  replyCount: {
    label: '新增回复',
    color: 'var(--chart-4)',
  },
} satisfies ChartConfig

const svgDefs = `
  <linearGradient id="fillRegCount" x1="0" y1="0" x2="0" y2="1">
    <stop offset="5%" stop-color="var(--color-regCount)" stop-opacity="0.8" />
    <stop offset="95%" stop-color="var(--color-regCount)" stop-opacity="0.1" />
  </linearGradient>
  <linearGradient id="fillArticleCount" x1="0" y1="0" x2="0" y2="1">
    <stop offset="5%" stop-color="var(--color-articleCount)" stop-opacity="0.8" />
    <stop offset="95%" stop-color="var(--color-articleCount)" stop-opacity="0.1" />
  </linearGradient>
  <linearGradient id="fillReplyCount" x1="0" y1="0" x2="0" y2="1">
    <stop offset="5%" stop-color="var(--color-replyCount)" stop-opacity="0.8" />
    <stop offset="95%" stop-color="var(--color-replyCount)" stop-opacity="0.1" />
  </linearGradient>
`
</script>

<template>
  <Card class="h-full overflow-hidden pt-0">
    <CardHeader class="grid gap-3 space-y-0 border-b px-4 py-4 sm:flex sm:flex-row sm:items-center sm:px-5">
      <div class="grid min-w-0 flex-1 gap-1">
        <CardTitle>流量概览</CardTitle>
        <CardDescription>展示注册用户、文章和回复的增长趋势</CardDescription>
      </div>
      <div class="min-w-0 sm:shrink-0">
        <slot name="headerAction" />
      </div>
    </CardHeader>
    <CardContent class="px-3 pb-3 pt-4 sm:px-5">
      <div v-if="loading" class="flex h-[260px] items-center justify-center text-muted-foreground sm:h-[320px]">
        加载中...
      </div>
      <ChartContainer v-else :config="chartConfig" class="aspect-auto h-[260px] w-full sm:h-[320px]" :cursor="false">
        <VisXYContainer
          :data="chartData"
          :svg-defs="svgDefs"
          :margin="{ top: 18, right: 18, left: -24, bottom: 28 }"
        >
          <VisArea
            :x="(d: Data) => d.date"
            :y="[(d: Data) => d.regCount, (d: Data) => d.articleCount, (d: Data) => d.replyCount]"
            :color="(_d: Data, i: number) => ['url(#fillRegCount)', 'url(#fillArticleCount)', 'url(#fillReplyCount)'][i]"
            :opacity="1"
          />
          <VisLine
            :x="(d: Data) => d.date"
            :y="[
              (d: Data) => d.regCount,
              (d: Data) => d.regCount + d.articleCount,
              (d: Data) => d.regCount + d.articleCount + d.replyCount,
            ]"
            :color="(_d: Data, i: number) => [chartConfig.regCount.color, chartConfig.articleCount.color, chartConfig.replyCount.color][i]"
            :line-width="1"
          />
          <VisAxis
            type="x"
            :x="(d: Data) => d.date"
            :tick-line="false"
            :domain-line="false"
            :grid-line="false"
            :num-ticks="7"
            :tick-format="(d: number) => {
              const date = new Date(d)
              return date.toLocaleDateString('en-US', {
                month: 'short',
                day: 'numeric',
              })
            }"
          />
          <VisAxis
            type="y"
            :num-ticks="5"
            :tick-line="false"
            :domain-line="false"
          />
          <ChartTooltip />
          <ChartCrosshair
            :template="componentToString(chartConfig, ChartTooltipContent, {
              labelFormatter: (d) => {
                const date = new Date(d)
                return date.toLocaleDateString('en-US', {
                  month: 'short',
                  day: 'numeric',
                  year: 'numeric',
                })
              },
            })"
            :color="(_d: Data, i: number) => [chartConfig.regCount.color, chartConfig.articleCount.color, chartConfig.replyCount.color][i % 3]"
          />
        </VisXYContainer>
        <ChartLegendContent />
      </ChartContainer>
    </CardContent>
  </Card>
</template>
