// resource/src/site/pages/AccessGroupsPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { CheckCircle2, Clock3, Lock, UsersRound } from '@lucide/vue'
import { useI18n } from 'vue-i18n'
import { Button } from '@/components/ui/button'
import PageHeader from '@/site/components/PageHeader.vue'
import {
  applyToAccessGroup,
  getJoinableAccessGroups,
  getManagedAccessGroups,
  reviewManagedAccessGroupApplication,
  type JoinableAccessGroup,
  type ManagedAccessGroup,
} from '@/runtime/api'
import type { AccessGroupsPageProps, LayoutPayload } from '@gooseforum/client'

defineProps<{ layout: LayoutPayload; props: AccessGroupsPageProps }>()

const { t } = useI18n()
const groups = ref<JoinableAccessGroup[]>([])
const managedGroups = ref<ManagedAccessGroup[]>([])
const loading = ref(true)
const applyingId = ref(0)
const reviewingMemberId = ref(0)
const error = ref('')

async function load() {
  loading.value = true
  error.value = ''
  try {
    ;[groups.value, managedGroups.value] = await Promise.all([getJoinableAccessGroups(), getManagedAccessGroups()])
  } catch (err) {
    error.value = err instanceof Error ? err.message : t('accessGroups.loadFailed')
  } finally {
    loading.value = false
  }
}

async function review(groupId: number, memberId: number, approve: boolean) {
  if (reviewingMemberId.value) return
  reviewingMemberId.value = memberId
  error.value = ''
  try {
    await reviewManagedAccessGroupApplication(groupId, memberId, approve)
    managedGroups.value = await getManagedAccessGroups()
  } catch (err) {
    error.value = err instanceof Error ? err.message : t('accessGroups.memberSaveFailed')
  } finally {
    reviewingMemberId.value = 0
  }
}

async function apply(group: JoinableAccessGroup) {
  if (applyingId.value) return
  applyingId.value = group.id
  error.value = ''
  try {
    await applyToAccessGroup(group.id)
    group.status = 2
  } catch (err) {
    error.value = err instanceof Error ? err.message : t('accessGroups.applicationFailed')
  } finally {
    applyingId.value = 0
  }
}

onMounted(() => void load())
</script>

<template>
  <main class="min-w-0 pb-8">
    <PageHeader :title="t('accessGroups.joinTitle')" :description="t('accessGroups.joinDescription')" />
    <div v-if="error" class="gf-status-message gf-status-message-error mb-3">
      {{ error }}
    </div>
    <section class="gf-card overflow-hidden">
      <div v-if="loading" class="px-5 py-12 text-center text-sm text-base-content/55">
        {{ t('common.loadingShort') }}
      </div>
      <div v-else-if="!groups.length" class="px-5 py-12 text-center">
        <UsersRound class="mx-auto h-8 w-8 text-base-content/35" />
        <h2 class="mt-3 font-semibold">
          {{ t('accessGroups.noJoinableGroups') }}
        </h2>
        <p class="mt-1 text-sm text-base-content/55">
          {{ t('accessGroups.noJoinableGroupsHint') }}
        </p>
      </div>
      <div v-else class="divide-y divide-line">
        <article
          v-for="group in groups"
          :key="group.id"
          class="flex flex-col gap-4 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"
        >
          <div class="min-w-0">
            <h2 class="flex items-center gap-2 font-semibold">
              <Lock class="h-4 w-4 text-base-content/45" />{{ group.name }}
            </h2>
            <p class="mt-1 text-sm text-base-content/55">
              {{
                group.categories.length
                  ? t('accessGroups.unlocksCategories', {
                      categories: group.categories.join('、'),
                    })
                  : t('accessGroups.noCategoryGrants')
              }}
            </p>
          </div>
          <span v-if="group.status === 1" class="inline-flex items-center gap-1.5 text-sm font-medium text-success"
            ><CheckCircle2 class="h-4 w-4" />{{ t('accessGroups.joined') }}</span
          >
          <span v-else-if="group.status === 2" class="inline-flex items-center gap-1.5 text-sm font-medium text-warning"
            ><Clock3 class="h-4 w-4" />{{ t('accessGroups.pending') }}</span
          >
          <Button v-else type="button" variant="brand" :disabled="applyingId !== 0" @click="apply(group)">
            {{ applyingId === group.id ? t('common.saving') : t('accessGroups.apply') }}
          </Button>
        </article>
      </div>
    </section>

    <section v-if="managedGroups.length" class="gf-card mt-4 overflow-hidden">
      <div class="border-b border-line px-5 py-4">
        <h2 class="font-semibold">
          {{ t('accessGroups.applicationsToReview') }}
        </h2>
        <p class="mt-1 text-sm text-base-content/55">
          {{ t('accessGroups.managerReviewHint') }}
        </p>
      </div>
      <div class="divide-y divide-line">
        <article v-for="group in managedGroups" :key="group.id" class="px-5 py-4">
          <h3 class="font-medium">{{ group.name }}</h3>
          <p v-if="!group.applications.length" class="mt-2 text-sm text-base-content/55">
            {{ t('accessGroups.noPendingApplications') }}
          </p>
          <div
            v-for="application in group.applications"
            :key="application.id"
            class="mt-3 flex items-center justify-between gap-3 rounded-md border border-line p-3"
          >
            <span class="font-medium">{{ application.username || `#${application.userId}` }}</span>
            <div class="flex gap-2">
              <Button
                type="button"
                variant="muted"
                :disabled="reviewingMemberId !== 0"
                @click="review(group.id, application.id, false)"
              >
                {{ t('accessGroups.reject') }}
              </Button>
              <Button
                type="button"
                variant="brand"
                :disabled="reviewingMemberId !== 0"
                @click="review(group.id, application.id, true)"
              >
                {{ t('accessGroups.approve') }}
              </Button>
            </div>
          </div>
        </article>
      </div>
    </section>
  </main>
</template>

// resource/packages/theme-default/src/site/pages/access-groups-page.tsx
import { useCallback, useEffect, useState } from "react";
import type {
  JoinableAccessGroup,
  ManagedAccessGroup,
} from "@gooseforum/client";
import { CheckCircle2, Clock3, Lock, UsersRound } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Alert, AlertDescription } from "@gooseforum/ui/components/alert";
import { Button } from "@gooseforum/ui/components/button";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@gooseforum/ui/components/empty";
import { Spinner } from "@gooseforum/ui/components/spinner";
import { useGooseRuntime } from "@gooseforum/runtime";
import { PageHeader } from "../layout/page-header";

export function AccessGroupsPageView() {
  const { t } = useTranslation("accessGroups");
  const { t: commonT } = useTranslation("contentCommon");
  const { api } = useGooseRuntime();
  const [groups, setGroups] = useState<JoinableAccessGroup[]>([]);
  const [managed, setManaged] = useState<ManagedAccessGroup[]>([]);
  const [loading, setLoading] = useState(true);
  const [applyingId, setApplyingId] = useState(0);
  const [reviewingId, setReviewingId] = useState(0);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const [nextGroups, nextManaged] = await Promise.all([
        api.accessGroups.list(),
        api.accessGroups.managed(),
      ]);
      setGroups(nextGroups);
      setManaged(nextManaged);
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : t("loadFailed"));
    } finally {
      setLoading(false);
    }
  }, [api.accessGroups, t]);
  useEffect(() => {
    void load();
  }, [load]);

  async function apply(group: JoinableAccessGroup) {
    if (applyingId) return;
    setApplyingId(group.id);
    setError("");
    try {
      await api.accessGroups.apply(group.id);
      setGroups((items) =>
        items.map((item) =>
          item.id === group.id ? { ...item, status: 2 } : item,
        ),
      );
    } catch (reason) {
      setError(
        reason instanceof Error ? reason.message : t("applicationFailed"),
      );
    } finally {
      setApplyingId(0);
    }
  }
  async function review(groupId: number, memberId: number, approve: boolean) {
    if (reviewingId) return;
    setReviewingId(memberId);
    setError("");
    try {
      await api.accessGroups.review(groupId, memberId, approve);
      setManaged(await api.accessGroups.managed());
    } catch (reason) {
      setError(
        reason instanceof Error ? reason.message : t("memberSaveFailed"),
      );
    } finally {
      setReviewingId(0);
    }
  }

  return (
    <main className="min-w-0 pb-8">
      <PageHeader divided={false} title={t("joinTitle")} description={t("joinDescription")} />
      {error ? (
        <Alert variant="destructive" className="mb-3">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      ) : null}
      <section className="site-panel overflow-hidden rounded-xl border bg-background">
        {loading ? (
          <div className="flex min-h-40 items-center justify-center gap-2 text-sm text-muted-foreground">
            <Spinner />
            {commonT("loading")}
          </div>
        ) : groups.length ? (
          <div className="divide-y">
            {groups.map((group) => (
              <article
                key={group.id}
                className="flex flex-col gap-4 px-5 py-4 lg:flex-row lg:items-center lg:justify-between"
              >
                <div className="min-w-0">
                  <h2 className="flex items-center gap-2 font-semibold">
                    <Lock />
                    {group.name}
                  </h2>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {group.categories.length
                      ? t("unlocksCategories", {
                          categories: group.categories.join("、"),
                        })
                      : t("noCategoryGrants")}
                  </p>
                </div>
                {group.status === 1 ? (
                  <span className="inline-flex items-center gap-1.5 text-sm font-medium text-success">
                    <CheckCircle2 />
                    {t("joined")}
                  </span>
                ) : group.status === 2 ? (
                  <span className="inline-flex items-center gap-1.5 text-sm font-medium text-warning">
                    <Clock3 />
                    {t("pending")}
                  </span>
                ) : (
                  <Button
                    disabled={Boolean(applyingId)}
                    onClick={() => void apply(group)}
                  >
                    {applyingId === group.id ? (
                      <Spinner data-icon="inline-start" />
                    ) : null}
                    {applyingId === group.id ? commonT("saving") : t("apply")}
                  </Button>
                )}
              </article>
            ))}
          </div>
        ) : (
          <Empty className="min-h-48 border-0">
            <EmptyHeader>
              <EmptyMedia variant="icon">
                <UsersRound />
              </EmptyMedia>
              <EmptyTitle>{t("noJoinableGroups")}</EmptyTitle>
              <EmptyDescription>{t("noJoinableGroupsHint")}</EmptyDescription>
            </EmptyHeader>
          </Empty>
        )}
      </section>
      {managed.length ? (
        <section className="site-panel overflow-hidden rounded-xl border bg-background lg:mt-4">
          <header className="border-b px-5 py-4">
            <h2 className="font-semibold">{t("applicationsToReview")}</h2>
            <p className="mt-1 text-sm text-muted-foreground">
              {t("managerReviewHint")}
            </p>
          </header>
          <div className="divide-y">
            {managed.map((group) => (
              <article key={group.id} className="px-5 py-4">
                <h3 className="font-medium">{group.name}</h3>
                {group.applications.length ? (
                  group.applications.map((application) => (
                    <div
                      key={application.id}
                      className="mt-3 flex items-center justify-between gap-3 rounded-lg border p-3"
                    >
                      <span className="font-medium">
                        {application.username || `#${application.userId}`}
                      </span>
                      <div className="flex gap-2">
                        <Button
                          variant="outline"
                          disabled={Boolean(reviewingId)}
                          onClick={() =>
                            void review(group.id, application.id, false)
                          }
                        >
                          {t("reject")}
                        </Button>
                        <Button
                          disabled={Boolean(reviewingId)}
                          onClick={() =>
                            void review(group.id, application.id, true)
                          }
                        >
                          {reviewingId === application.id ? (
                            <Spinner data-icon="inline-start" />
                          ) : null}
                          {t("approve")}
                        </Button>
                      </div>
                    </div>
                  ))
                ) : (
                  <p className="mt-2 text-sm text-muted-foreground">
                    {t("noPendingApplications")}
                  </p>
                )}
              </article>
            ))}
          </div>
        </section>
      ) : null}
    </main>
  );
}
