// resource/src/site/pages/HomePage.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { Bell, Mail, Plus, UsersRound } from '@lucide/vue'
import { fetchPage } from '@/runtime/router'
import EmptyState from '@/site/components/EmptyState.vue'
import TopicListFooter from '@/site/components/TopicListFooter.vue'
import TopicListModeSwitch from '@/site/components/TopicListModeSwitch.vue'
import TopicList from '@/site/components/TopicList.vue'
import { useTopicListMode } from '@/site/composables/useTopicListMode'
import type { HomeProps, LayoutPayload, PagePayload, TopicPayload } from '@/types/payload'

const page = defineProps<{
  layout: LayoutPayload
  props: HomeProps
}>()
const { t } = useI18n()
const { mode: listMode, setMode: setListMode } = useTopicListMode()

const topics = ref<TopicPayload[]>([])
const pagination = ref<HomeProps['pagination']>(page.props.pagination)
const loadingMore = ref(false)
const loadError = ref('')
const loadMoreSentinel = ref<HTMLElement | null>(null)
let observer: IntersectionObserver | undefined

const hasTopics = computed(() => topics.value.length > 0)
const showPinnedLabels = computed(() => page.props.sort === '' || page.props.sort === 'latest')
const isWaterfallMode = computed(() => listMode.value === 'waterfall')

watch(
  () => [page.props.sort, page.props.pagination.page, page.props.topics],
  () => {
    topics.value = [...page.props.topics]
    pagination.value = page.props.pagination
    loadError.value = ''
    void nextTick(observeSentinel)
  },
  { immediate: true },
)

watch(listMode, (mode) => {
  if (mode === 'pagination') {
    observer?.disconnect()
    topics.value = [...page.props.topics]
    pagination.value = page.props.pagination
    return
  }
  void nextTick(observeSentinel)
})

async function loadMore() {
  if (!isWaterfallMode.value || loadingMore.value || !pagination.value.hasNext || !pagination.value.nextUrl) return

  loadingMore.value = true
  loadError.value = ''
  try {
    const payload = (await fetchPage(new URL(pagination.value.nextUrl, window.location.origin))) as PagePayload<HomeProps>
    topics.value = mergeTopics(topics.value, payload.props.topics)
    pagination.value = payload.props.pagination
  } catch (error) {
    loadError.value = error instanceof Error ? error.message : t('common.loadFailed')
  } finally {
    loadingMore.value = false
  }
}

function mergeTopics(current: TopicPayload[], incoming: TopicPayload[]) {
  const seen = new Set(current.map((topic) => topic.id))
  return [...current, ...incoming.filter((topic) => !seen.has(topic.id))]
}

function sortTabLabel(key: string, fallback?: string) {
  if (key === 'latest') return t('topicList.tabs.latest')
  if (key === 'hot') return t('topicList.tabs.hot')
  if (key === 'popular') return t('topicList.tabs.popular')
  return fallback || key
}

function observeSentinel() {
  observer?.disconnect()
  if (!isWaterfallMode.value || !loadMoreSentinel.value || !('IntersectionObserver' in window)) return
  observer = new IntersectionObserver(
    (entries) => {
      if (entries.some((entry) => entry.isIntersecting)) void loadMore()
    },
    { rootMargin: '480px 0px' },
  )
  observer.observe(loadMoreSentinel.value)
}

onMounted(observeSentinel)

onBeforeUnmount(() => {
  observer?.disconnect()
})

</script>

<template>
    <div class="pb-12">
      <aside
        v-if="page.layout.viewer.requiresEmailVerification"
        class="-mt-3 mb-3 rounded-b-lg border-x border-b border-warning/30 bg-warning/10"
        :aria-label="t('topicList.emailVerification.title')"
      >
        <div class="flex items-center gap-2 px-4 py-2 text-sm leading-5 text-warning">
          <Mail class="h-4 w-4 shrink-0 text-warning" />
          <div class="min-w-0 flex-1">
            <span class="font-semibold text-warning">{{ t('topicList.emailVerification.title') }}</span>
            <span class="mx-1 text-warning">·</span>
            <span>{{ t('topicList.emailVerification.description') }}</span>
          </div>
          <a href="/settings" class="shrink-0 font-semibold text-warning hover:text-warning">
            {{ t('topicList.emailVerification.action') }}
          </a>
        </div>
      </aside>

      <section class="gf-card overflow-hidden">
        <div class="gf-home-topic-toolbar">
          <div class="gf-home-topic-tools">
            <div class="gf-home-topic-tabs">
              <a
                v-for="tab in page.props.tabs"
                :key="tab.key"
                :href="tab.url"
                class="gf-tab"
                :class="tab.active ? 'gf-tab-active' : 'gf-tab-idle'"
              >
                {{ sortTabLabel(tab.key, tab.label) }}
              </a>
            </div>
            <TopicListModeSwitch :model-value="listMode" @update:model-value="setListMode" />
          </div>
          <a href="/publish" class="gf-button gf-button-md gf-button-primary shrink-0 whitespace-nowrap px-3 sm:h-8">
            <Plus class="h-4 w-4" />
            {{ t('topicList.newTopic') }}
          </a>
        </div>

        <aside v-if="page.props.announcement.enabled" class="border-b border-line/70 bg-base-100 px-4 py-2.5" :aria-label="t('topicList.announcement')">
          <div class="flex items-start gap-2.5">
            <Bell class="mt-[3px] h-[18px] w-[18px] shrink-0 text-primary" aria-hidden="true" />
            <div class="min-w-0">
              <div class="gf-prose gf-prose-announcement" v-html="page.props.announcement.html" />
            </div>
          </div>
        </aside>

        <TopicList :topics="topics" home :show-pinned="showPinnedLabels">
          <template #empty>
            <EmptyState v-if="!hasTopics" :icon="UsersRound" :title="t('topicList.emptyTitle')" :description="t('topicList.emptyDescription')" />
          </template>
        </TopicList>

        <div ref="loadMoreSentinel">
          <TopicListFooter
            :pagination="pagination"
            :mode="listMode"
            :loading-more="loadingMore"
            :has-topics="hasTopics"
            :load-error="loadError"
            @load-more="loadMore"
          />
        </div>
      </section>
    </div>
</template>

// resource/packages/theme-default/src/site/pages/home-page.tsx
import type { HomeProps, LayoutPayload } from "@gooseforum/client";
import { Mail, Plus, UsersRound } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Button } from "@gooseforum/ui/components/button";
import { ListFilter, ListFilterItem } from "@gooseforum/ui/components/list-filter";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@gooseforum/ui/components/empty";
import { GooseLink } from "@gooseforum/runtime";
import { AnnouncementPanel } from "../content/announcement-panel";
import { SiteListPanel } from "../layout/site-panel";
import {
  TopicListFooter,
  TopicListToolbar,
  TopicListModeSwitch,
  TopicTable,
  useTopicList,
} from "../topics/topic-list";

export function HomePageView({
  layout,
  page,
  pageUrl,
}: {
  layout: LayoutPayload;
  page: HomeProps;
  pageUrl: string;
}) {
  const { t } = useTranslation("home");
  const list = useTopicList(page, pageUrl);
  return (
    <div className="pb-12">
      {layout.viewer.requiresEmailVerification ? (
        <aside className="border-y border-warning/30 bg-warning/10 lg:-mt-3 lg:mb-3 lg:rounded-b-lg lg:border-x lg:border-t-0">
          <div className="flex items-center gap-2 px-3 py-2 text-[13px] text-warning lg:px-4 lg:text-sm">
            <Mail className="size-4" />
            <div className="flex-1">
              <strong>{t("emailTitle")}</strong> · {t("emailDescription")}
            </div>
            <GooseLink href="/settings" className="font-semibold">
              {t("emailAction")}
            </GooseLink>
          </div>
        </aside>
      ) : null}
      <AnnouncementPanel announcement={page.announcement} />
      <SiteListPanel>
        <TopicListToolbar
          action={
            <Button asChild className="shrink-0">
              <GooseLink href="/publish">
                <Plus data-icon="inline-start" />
                {t("newTopic")}
              </GooseLink>
            </Button>
          }
        >
            <ListFilter asChild>
            <nav>
              {page.tabs.map((tab) => (
                <ListFilterItem
                  key={tab.key}
                  asChild
                >
                  <GooseLink
                    href={tab.url}
                    aria-current={tab.active ? "page" : undefined}
                  >
                    {tab.key === "latest"
                      ? t("latest")
                      : tab.key === "hot"
                        ? t("hot")
                        : tab.key === "popular"
                          ? t("popular")
                          : tab.label || tab.key}
                  </GooseLink>
                </ListFilterItem>
              ))}
            </nav>
            </ListFilter>
            <TopicListModeSwitch
              mode={list.mode}
              t={t}
              onClick={list.switchMode}
            />
        </TopicListToolbar>
        <TopicTable
          topics={list.topics}
          showPinned={page.sort === "" || page.sort === "latest"}
          t={t}
        />
        {!list.topics.length ? (
          <Empty className="min-h-48 border-0">
            <EmptyHeader>
              <EmptyMedia variant="icon">
                <UsersRound />
              </EmptyMedia>
              <EmptyTitle>{t("emptyTitle")}</EmptyTitle>
              <EmptyDescription>{t("emptyDescription")}</EmptyDescription>
            </EmptyHeader>
          </Empty>
        ) : null}
        <TopicListFooter
          mode={list.mode}
          pagination={list.pagination}
          loading={list.loading}
          error={list.error}
          t={t}
          onLoad={list.loadMore}
        />
        <div ref={list.sentinel} />
      </SiteListPanel>
    </div>
  );
}
