// resource/src/admin/pages/management/OptRecordsManagementPage.vue
<script setup lang="ts">import { adminText } from '@/admin/runtime/i18n-text'

import { onMounted, ref } from 'vue'
import { RefreshCw } from '@lucide/vue'
import { i18n } from '@/runtime/i18n'
import { BasicPage } from '@/admin/components/global-layout'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { getOptRecordList } from '@/admin/runtime/api'
import type { AdminOptRecord, AdminPayload, ManageHomeProps } from '@/admin/types'
import ManagementTable from './ManagementTable.vue'

const props = defineProps<{
  payload: AdminPayload<ManageHomeProps>
}>()

const rows = ref<AdminOptRecord[]>([])
const loading = ref(false)
const error = ref('')
const page = ref(1)
const pageSize = ref(20)
const total = ref(0)

const columns = ['ID', adminText('k0036'), adminText('k0037'), adminText('k0038'), adminText('k0039'), adminText('k003a'), adminText('k003b')]

const optTypeCodeMap: Record<number, string> = {
  0: 'editUser',
  1: 'editTopic',
  2: 'editCategory',
}

const targetTypeCodeMap: Record<number, string> = {
  0: 'system',
  1: 'user',
  2: 'topic',
  3: 'docProject',
  4: 'docVersion',
  5: 'docContent',
  6: 'category',
}

const optInfoMessageKeyMap: Record<string, string> = {
  'admin.opt.content.reviewed': 'adminOptLog.messages.contentReviewed',
  'admin.opt.user.updated': 'adminOptLog.messages.userUpdated',
  'admin.opt.topic.statusChanged': 'adminOptLog.messages.topicStatusChanged',
  'admin.opt.topic.pinWeightChanged': 'adminOptLog.messages.topicPinWeightChanged',
  'admin.opt.topic.categoriesChanged': 'adminOptLog.messages.topicCategoriesChanged',
  'admin.opt.topic.deleted': 'adminOptLog.messages.topicDeleted',
  'moderator.opt.topic.statusChanged': 'adminOptLog.messages.moderatorTopicStatusChanged',
  'admin.opt.category.moderatorAdded': 'adminOptLog.messages.categoryModeratorAdded',
  'admin.opt.category.moderatorRemoved': 'adminOptLog.messages.categoryModeratorRemoved',
}

function pageResultSize(result: { pageSize?: number, size?: number }) {
  return result.pageSize || result.size || pageSize.value
}

async function loadRecords() {
  loading.value = true
  error.value = ''
  try {
    const result = await getOptRecordList({ page: page.value, pageSize: pageSize.value })
    rows.value = result.list || []
    total.value = result.total || 0
    page.value = result.page + 1
    pageSize.value = pageResultSize(result)
  } catch (err) {
    error.value = err instanceof Error ? err.message : adminText('k0013')
  } finally {
    loading.value = false
  }
}

function updatePage(value: number) {
  page.value = value
  void loadRecords()
}

function updatePageSize(value: number) {
  pageSize.value = value
  page.value = 1
  void loadRecords()
}

function optTypeName(value: number) {
  const code = optTypeCodeMap[value]
  const key = code ? `adminOptLog.optType.${code}` : ''
  return key && i18n.global.te(key) ? i18n.global.t(key) : adminText('k00aj', { value })
}

function targetTypeName(value: number) {
  const code = targetTypeCodeMap[value]
  const key = code ? `adminOptLog.targetType.${code}` : ''
  return key && i18n.global.te(key) ? i18n.global.t(key) : adminText('k00ak', { value })
}

function normalizeParam(value: unknown) {
  if (Array.isArray(value)) return value.join(', ')
  if (value === undefined || value === null) return ''
  return String(value)
}

function localizeOptParams(params: Record<string, unknown>) {
  const next: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(params)) {
    next[key] = normalizeParam(value)
  }

  const status = typeof params.status === 'string' ? params.status : ''
  if (status) {
    const statusKey = `adminOptLog.status.${status}`
    next.status = i18n.global.te(statusKey) ? i18n.global.t(statusKey) : status
  }

  const changedFields = Array.isArray(params.changes)
    ? params.changes
      .map((item) => {
        const field = String(item)
        const fieldKey = `adminOptLog.userField.${field}`
        return i18n.global.te(fieldKey) ? i18n.global.t(fieldKey) : field
      })
      .join(', ')
    : ''
  if (changedFields) next.changedFields = changedFields

  return next
}

function tryParseOptInfo(value: string) {
  if (!value || value[0] !== '{') return undefined
  try {
    const parsed = JSON.parse(value) as { messageCode?: unknown, params?: unknown }
    if (typeof parsed.messageCode !== 'string') return undefined
    return {
      messageCode: parsed.messageCode,
      params: parsed.params && typeof parsed.params === 'object' && !Array.isArray(parsed.params)
        ? parsed.params as Record<string, unknown>
        : {},
    }
  } catch {
    return undefined
  }
}

function optInfoText(item: AdminOptRecord) {
  const payload = item.optInfoPayload || tryParseOptInfo(item.optInfo)
  if (!payload?.messageCode) return item.optInfo || '-'

  const key = optInfoMessageKeyMap[payload.messageCode]
  if (!i18n.global.te(key)) return item.optInfo || payload.messageCode
  return i18n.global.t(key, localizeOptParams(payload.params || {}))
}

function formatTime(value: string) {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return date.toLocaleString('zh-CN', { hour12: false })
}

onMounted(loadRecords)
</script>

<template>
  <BasicPage :title="adminText('k007c')" :description="adminText('k007d')">
      <ManagementTable
        :columns="columns"
        :loading="loading && rows.length === 0"
        :error="error"
        :empty-text="adminText('k007e')"
        :total="total"
        :page="page"
        :page-size="pageSize"
        @retry="loadRecords"
        @update:page="updatePage"
        @update:page-size="updatePageSize"
      >
        <template #header>
          <div class="flex justify-end">
            <Button variant="outline" size="sm" type="button" :disabled="loading" @click="loadRecords">
              <RefreshCw class="size-4" :class="loading ? 'animate-spin' : ''" />
              {{ adminText('k004q') }}
            </Button>
          </div>
        </template>
        <tr v-if="rows.length === 0">
          <td :colspan="columns.length" class="h-28 px-4 text-center text-muted-foreground">{{ adminText('k007e') }}</td>
        </tr>
        <tr v-for="item in rows" v-else :key="item.id" class="transition-colors hover:bg-muted/35">
          <td class="px-4 py-3 font-mono text-xs text-muted-foreground">{{ item.id }}</td>
          <td class="px-4 py-3 font-mono text-xs">{{ item.optUserId || '-' }}</td>
          <td class="px-4 py-3">
            <Badge variant="secondary">{{ optTypeName(item.optType) }}</Badge>
          </td>
          <td class="px-4 py-3 text-muted-foreground">{{ targetTypeName(item.targetType) }}</td>
          <td class="px-4 py-3 font-mono text-xs text-muted-foreground">{{ item.targetId || '-' }}</td>
          <td class="max-w-xl px-4 py-3">
            <div class="line-clamp-2 text-foreground">{{ optInfoText(item) }}</div>
          </td>
          <td class="whitespace-nowrap px-4 py-3 text-muted-foreground">{{ formatTime(item.createdAt) }}</td>
        </tr>
      </ManagementTable>
    </BasicPage>
</template>

// resource/apps/web/src/admin/pages/opt-records-management-page.tsx
import { AdminPage } from '../components/admin-page'
import { useCallback, useEffect, useState } from 'react'
import type { AdminOptRecord, GooseAdminApi } from '@gooseforum/client'
import type { AuthLocale } from '@gooseforum/runtime/i18n/auth'
import { Badge } from '@gooseforum/ui/components/badge'
import { Button } from '@gooseforum/ui/components/button'
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle } from '@gooseforum/ui/components/empty'
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@gooseforum/ui/components/select'
import { Spinner } from '@gooseforum/ui/components/spinner'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@gooseforum/ui/components/table'
import { ChevronLeft, ChevronRight, ListChecks, RefreshCw } from 'lucide-react'
import { formatAuditMessage, type AuditTextKey } from '../audit-i18n'

type Text = (key: AuditTextKey) => string
const optTypes: Record<number, AuditTextKey> = { 0: 'editUser', 1: 'editTopic', 2: 'editCategory', 3: 'manageOIDC' }
const targetTypes: Record<number, AuditTextKey> = { 0: 'system', 1: 'user', 2: 'topic', 3: 'docProject', 4: 'docVersion', 5: 'docContent', 6: 'category' }

export function OptRecordsManagementPage({ api, text, locale }: { api: GooseAdminApi; text: Text; locale: AuthLocale }) {
  const [items, setItems] = useState<AdminOptRecord[]>([])
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const totalPages = Math.max(1, Math.ceil(total / pageSize))

  const load = useCallback(async () => {
    setLoading(true); setError('')
    try {
      const result = await api.audit.records({ page, pageSize })
      setItems(result.list || []); setTotal(result.total || 0)
      setPage((result.page ?? page - 1) + 1)
      setPageSize(result.pageSize || result.size || pageSize)
    } catch (reason) {
      setError(reason instanceof Error && reason.message ? reason.message : text('loadFailed'))
    } finally { setLoading(false) }
  }, [api, page, pageSize, text])

  useEffect(() => { void load() }, [load])

  return <AdminPage>
    <header className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">{text('title')}</h2><p className="text-xs text-muted-foreground">{text('description')}</p></div><Button variant="outline" size="sm" disabled={loading} onClick={() => void load()}><RefreshCw data-icon="inline-start" className={loading ? 'animate-spin' : undefined} />{text('refresh')}</Button></header>
    <section className="overflow-hidden rounded-lg border bg-background">
      {loading && !items.length ? <LogEmpty icon={<Spinner />} title={text('loading')} /> : error ? <LogEmpty icon={<ListChecks />} title={error} /> : !items.length ? <LogEmpty icon={<ListChecks />} title={text('empty')} /> : <Table className="min-w-240 table-fixed"><TableHeader className="bg-muted/30"><TableRow><TableHead className="h-8 w-14">ID</TableHead><TableHead className="h-8 w-24">{text('operator')}</TableHead><TableHead className="h-8 w-32">{text('operation')}</TableHead><TableHead className="h-8 w-32">{text('targetType')}</TableHead><TableHead className="h-8 w-28">{text('targetId')}</TableHead><TableHead className="h-8">{text('details')}</TableHead><TableHead className="h-8 w-44">{text('time')}</TableHead></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell className="py-2 font-mono text-xs text-muted-foreground">{item.id}</TableCell><TableCell className="py-2 font-mono text-xs">{item.optUserId || '—'}</TableCell><TableCell className="py-2"><Badge variant="secondary">{text(optTypes[item.optType] || 'unknown')} {optTypes[item.optType] ? null : item.optType}</Badge></TableCell><TableCell className="py-2 text-muted-foreground">{text(targetTypes[item.targetType] || 'unknown')} {targetTypes[item.targetType] ? null : item.targetType}</TableCell><TableCell className="py-2 font-mono text-xs text-muted-foreground">{item.targetId || '—'}</TableCell><TableCell className="py-2"><div className="line-clamp-2">{optInfo(item, locale)}</div></TableCell><TableCell className="whitespace-nowrap py-2 text-muted-foreground">{formatTime(item.createdAt, locale)}</TableCell></TableRow>)}</TableBody></Table>}
      <footer className="flex items-center justify-between gap-3 border-t bg-muted/10 px-3 py-2 text-sm text-muted-foreground"><span>{total}</span><div className="flex items-center gap-1.5"><Select value={String(pageSize)} onValueChange={(value) => { setPageSize(Number(value)); setPage(1) }}><SelectTrigger className="w-20"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{[10, 20, 30, 50].map((size) => <SelectItem key={size} value={String(size)}>{size}</SelectItem>)}</SelectGroup></SelectContent></Select><Button variant="outline" size="icon-sm" disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft /></Button><span>{text('page')} {page}/{totalPages}</span><Button variant="outline" size="icon-sm" disabled={page >= totalPages} onClick={() => setPage(page + 1)}><ChevronRight /></Button></div></footer>
    </section>
  </AdminPage>
}

function optInfo(item: AdminOptRecord, locale: AuthLocale) {
  const payload = item.optInfoPayload || parsePayload(item.optInfo)
  if (!payload?.messageCode) return item.optInfo || '—'
  return formatAuditMessage(locale, payload.messageCode, payload.params || {}, item.optInfo)
}

function parsePayload(value: string) {
  if (!value || value[0] !== '{') return undefined
  try {
    const parsed = JSON.parse(value) as { messageCode?: unknown; params?: unknown }
    if (typeof parsed.messageCode !== 'string') return undefined
    return { messageCode: parsed.messageCode, params: parsed.params && typeof parsed.params === 'object' && !Array.isArray(parsed.params) ? parsed.params as Record<string, unknown> : {} }
  } catch { return undefined }
}

function formatTime(value: string, locale: AuthLocale) {
  if (!value) return '—'
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString(locale === 'zh' ? 'zh-CN' : locale, { hour12: false })
}

function LogEmpty({ icon, title }: { icon: React.ReactNode; title: string }) { return <Empty className="min-h-32 border-0"><EmptyHeader><EmptyMedia variant="icon">{icon}</EmptyMedia><EmptyTitle>{title}</EmptyTitle></EmptyHeader></Empty> }
