// resource/src/admin/pages/management/PostsManagementPage.vue
<script setup lang="ts">
import { adminText } from '@/admin/runtime/i18n-text'

import { computed, onMounted, ref } from 'vue'
import { Ban, Eye, FileText, Heart, MessageSquare, Pin, RefreshCw, Search, Tags, Trash2, Undo2 } from '@lucide/vue'
import AdminActionButton from '@/admin/components/AdminActionButton.vue'
import AdminConfirmDialog from '@/admin/components/AdminConfirmDialog.vue'
import AdminSection from '@/admin/components/AdminSection.vue'
import AdminToolbar from '@/admin/components/AdminToolbar.vue'
import { BasicPage } from '@/admin/components/global-layout'
import { Button } from '@/admin/components/ui/button'
import { Badge } from '@/admin/components/ui/badge'
import { Input } from '@/admin/components/ui/input'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/admin/components/ui/dialog'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/admin/components/ui/table'
import {
  editArticle,
  editArticleCategories,
  editArticlePin,
  deleteArticle,
  getArticleSource,
  getArticlesList,
  getCategoryList,
} from '@/admin/runtime/api'
import { adminToast } from '@/admin/runtime/toast'
import type { AdminArticle, AdminCategory, AdminPayload, ArticleSource, ManageHomeProps } from '@/admin/types'

defineProps<{
  payload: AdminPayload<ManageHomeProps>
}>()

const loading = ref(false)
const saving = ref(false)
const sourceLoading = ref(false)
const error = ref('')
const rows = ref<AdminArticle[]>([])
const hasNext = ref(false)
const page = ref(1)
const pageSize = ref(10)
const search = ref('')
const appliedSearch = ref('')
const categories = ref<AdminCategory[]>([])
const categoryDialogRow = ref<AdminArticle | null>(null)
const selectedCategoryIds = ref<number[]>([])
const sourceDialogRow = ref<AdminArticle | null>(null)
const source = ref<ArticleSource | null>(null)
const actionRow = ref<AdminArticle | null>(null)
const deleteRow = ref<AdminArticle | null>(null)
const pinDialogRow = ref<AdminArticle | null>(null)
const pinWeightInput = ref(0)

interface CategoryOption {
  id: number
  category: string
  color: string
  missing: boolean
}

const categoryMap = computed(() => new Map(categories.value.map(item => [item.id, item])))
const categoryDialogOptions = computed<CategoryOption[]>(() => {
  const options = categories.value.map(category => ({
    id: category.id,
    category: category.category,
    color: category.color || '#64748b',
    missing: false,
  }))
  const missingIds = selectedCategoryIds.value.filter(id => !categoryMap.value.has(id))
  return [
    ...options,
    ...missingIds.map(id => ({
      id,
      category: adminText('k00cc', { id }),
      color: '#94a3b8',
      missing: true,
    })),
  ]
})
const rangeStart = computed(() => (rows.value.length === 0 ? 0 : (page.value - 1) * pageSize.value + 1))
const rangeEnd = computed(() => rows.value.length === 0 ? 0 : rangeStart.value + rows.value.length - 1)

const articleTypes: Record<number, { label: string, className: string }> = {
  0: { label: adminText('k003m'), className: 'bg-blue-50 text-blue-700 border-blue-100' },
  1: { label: adminText('k003n'), className: 'bg-emerald-50 text-emerald-700 border-emerald-100' },
  2: { label: adminText('k003o'), className: 'bg-amber-50 text-amber-700 border-amber-100' },
  3: { label: adminText('k003p'), className: 'bg-violet-50 text-violet-700 border-violet-100' },
}

function typeInfo(type: number) {
  return articleTypes[type] || { label: adminText('k003g'), className: 'bg-slate-50 text-slate-700 border-slate-100' }
}

function avatarText(post: AdminArticle) {
  return post.username.slice(0, 1).toUpperCase()
}

function postCategories(post: AdminArticle) {
  return (post.categoryId || []).map((id) => {
    const category = categoryMap.value.get(id)
    if (category) {
      return {
        id: category.id,
        category: category.category,
        color: category.color || '#64748b',
        missing: false,
      }
    }
    return {
      id,
      category: adminText('k00cc', { id }),
      color: '#94a3b8',
      missing: true,
    }
  })
}

function postDate(value?: string) {
  if (!value) return '-'
  return value.slice(0, 10)
}

function postTime(value?: string) {
  if (!value) return ''
  return value.slice(11, 16)
}

function articleStatusInfo(status: number) {
  return status === 1
    ? { label: adminText('k003q'), className: 'bg-slate-950 text-white' }
    : { label: adminText('k003r'), className: 'bg-slate-100 text-slate-600' }
}

async function loadPosts() {
  loading.value = true
  error.value = ''
  try {
    const [postPage, categoryList] = await Promise.all([
      getArticlesList({ page: page.value, pageSize: pageSize.value, search: appliedSearch.value || undefined }),
      categories.value.length ? Promise.resolve(categories.value) : getCategoryList(),
    ])
    rows.value = postPage.list || []
    hasNext.value = Boolean(postPage.hasNext)
    categories.value = categoryList || []
  } catch (err) {
    error.value = err instanceof Error ? err.message : adminText('k003s')
  } finally {
    loading.value = false
  }
}

function applySearch() {
  appliedSearch.value = search.value.trim()
  page.value = 1
  void loadPosts()
}

function changePage(nextPage: number) {
  page.value = nextPage
  void loadPosts()
}

function changePageSize(event: Event) {
  pageSize.value = Number((event.target as HTMLSelectElement).value)
  page.value = 1
  void loadPosts()
}

function openCategoryDialog(post: AdminArticle) {
  categoryDialogRow.value = post
  selectedCategoryIds.value = [...(post.categoryId || [])]
}

function openPinDialog(post: AdminArticle) {
  pinDialogRow.value = post
  pinWeightInput.value = post.pinWeight || 0
}

function toggleCategory(id: number) {
  if (selectedCategoryIds.value.includes(id)) {
    selectedCategoryIds.value = selectedCategoryIds.value.filter(value => value !== id)
    return
  }
  if (selectedCategoryIds.value.length >= 3) {
    adminToast.warning(adminText('k003t'))
    return
  }
  selectedCategoryIds.value = [...selectedCategoryIds.value, id]
}

async function saveCategories() {
  if (!categoryDialogRow.value) return
  const validCategoryIds = selectedCategoryIds.value.filter(id => categoryMap.value.has(id))
  if (validCategoryIds.length === 0) {
    adminToast.warning(adminText('k003u'))
    return
  }
  saving.value = true
  try {
    await editArticleCategories({ id: categoryDialogRow.value.id, categoryId: validCategoryIds })
    categoryDialogRow.value = null
    await loadPosts()
    adminToast.success(adminText('k003v'))
  } catch (err) {
    adminToast.error(err, adminText('k0010'))
  } finally {
    saving.value = false
  }
}

async function savePinWeight() {
  if (!pinDialogRow.value) return
  const pinWeight = Math.max(0, Math.trunc(Number(pinWeightInput.value) || 0))
  saving.value = true
  try {
    await editArticlePin({ id: pinDialogRow.value.id, pinWeight })
    pinDialogRow.value = null
    await loadPosts()
    adminToast.success(pinWeight > 0 ? adminText('k003w') : adminText('k003x'))
  } catch (err) {
    adminToast.error(err, adminText('k0016'))
  } finally {
    saving.value = false
  }
}

async function openSource(post: AdminArticle) {
  sourceDialogRow.value = post
  source.value = null
  sourceLoading.value = true
  try {
    source.value = await getArticleSource(post.id)
  } catch (err) {
    adminToast.error(err, adminText('k003y'))
  } finally {
    sourceLoading.value = false
  }
}

async function copySource() {
  if (!source.value?.content) return
  try {
    await navigator.clipboard.writeText(source.value.content)
    adminToast.success(adminText('k003z'))
  } catch (err) {
    adminToast.error(err, adminText('k0040'))
  }
}

async function toggleProcessStatus() {
  if (!actionRow.value) return
  const restoring = actionRow.value.processStatus === 1
  saving.value = true
  try {
    await editArticle({
      id: actionRow.value.id,
      processStatus: restoring ? 0 : 1,
    })
    actionRow.value = null
    await loadPosts()
    adminToast.success(restoring ? adminText('k0041') : adminText('k0042'))
  } catch (err) {
    adminToast.error(err, adminText('k001u'))
  } finally {
    saving.value = false
  }
}

async function confirmDeleteArticle() {
  if (!deleteRow.value) return
  saving.value = true
  try {
    await deleteArticle(deleteRow.value.id)
    deleteRow.value = null
    await loadPosts()
    adminToast.success(adminText('k00ce'))
  } catch (err) {
    adminToast.error(err, adminText('k00cd'))
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  void loadPosts()
})
</script>

<template>
  <BasicPage :title="adminText('k005u')" :description="adminText('k005v')" sticky>
    <template #actions>
      <Button variant="outline" type="button" @click="loadPosts">
        <RefreshCw class="size-4" />
        {{ adminText('k004q') }}
      </Button>
    </template>

      <AdminSection>
        <template #header>
        <AdminToolbar class="-mx-3 -my-2 border-b-0">
          <form class="flex min-w-0 flex-1 items-center gap-2" @submit.prevent="applySearch">
            <div class="relative min-w-64 max-w-xl flex-1">
              <Search class="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
              <Input v-model="search" class="h-9 pl-8 text-sm" :placeholder="adminText('k006a')" />
            </div>
            <Button type="submit" size="sm" class="h-9 px-4">{{ adminText('k00al') }}</Button>
            <Button v-if="appliedSearch" variant="ghost" size="sm" type="button" class="h-9" @click="search = ''; applySearch()">
              {{ adminText('k00at') }}
            </Button>
          </form>
          <div class="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
            <span class="whitespace-nowrap">{{ rangeStart }}-{{ rangeEnd }}</span>
            <div class="h-4 w-px bg-border" />
            <div class="flex flex-wrap items-center gap-2">
              <select class="h-9 rounded-md border bg-background px-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" :value="pageSize" @change="changePageSize">
                <option :value="10">{{ adminText('k002x') }}</option>
                <option :value="20">{{ adminText('k002y') }}</option>
                <option :value="50">{{ adminText('k0030') }}</option>
              </select>
              <Button variant="outline" size="sm" type="button" :disabled="page <= 1 || loading" @click="changePage(page - 1)">{{ adminText('k00au') }}</Button>
              <span class="whitespace-nowrap">{{ adminText('k0056') }} {{ page }} {{ adminText('k0057') }}</span>
              <Button variant="outline" size="sm" type="button" :disabled="!hasNext || loading" @click="changePage(page + 1)">{{ adminText('k00av') }}</Button>
            </div>
          </div>
        </AdminToolbar>
        </template>

        <div class="md:hidden">
          <div v-if="loading" class="px-3 py-10 text-center text-sm text-muted-foreground">{{ adminText('k0046') }}</div>
          <div v-else-if="error" class="px-3 py-10 text-center text-sm text-destructive">{{ error }}</div>
          <div v-else-if="rows.length === 0" class="px-3 py-10 text-center text-sm text-muted-foreground">{{ adminText('k00aw') }}</div>
          <div v-else class="divide-y">
            <article v-for="post in rows" :key="post.id" class="space-y-2 px-3 py-3">
              <div class="flex min-w-0 items-start justify-between gap-3">
                <div class="min-w-0 flex-1 space-y-1">
                  <div class="flex min-w-0 items-center gap-1.5">
                    <a :href="`/p/post/${post.id}`" target="_blank" rel="noreferrer" class="min-w-0 truncate text-[15px] font-semibold leading-5 text-foreground hover:text-primary hover:underline">
                      {{ post.title }}
                    </a>
                    <span class="inline-flex h-5 shrink-0 items-center rounded-full border px-1.5 text-[11px] font-semibold" :class="typeInfo(post.type).className">
                      {{ typeInfo(post.type).label }}
                    </span>
                    <Badge v-if="post.processStatus === 1" variant="destructive" class="h-5 shrink-0 rounded-full px-1.5 text-[10px]">{{ adminText('k0069') }}</Badge>
                    <Badge v-if="post.pinWeight > 0" variant="secondary" class="h-5 shrink-0 rounded-full px-1.5 text-[10px]">{{ adminText('k00ax') }} {{ post.pinWeight }}</Badge>
                  </div>
                  <p class="line-clamp-2 break-words text-[12px] leading-5 text-muted-foreground">
                    {{ post.description || adminText('k005w') }}
                  </p>
                </div>
                <span class="inline-flex h-6 shrink-0 items-center rounded-md px-2 text-xs font-semibold" :class="articleStatusInfo(post.articleStatus).className">
                  {{ articleStatusInfo(post.articleStatus).label }}
                </span>
              </div>

              <div class="flex min-w-0 flex-wrap items-center gap-x-1.5 gap-y-1 text-[12px] leading-4 text-muted-foreground">
                <span v-for="category in postCategories(post)" :key="category.id" class="inline-flex h-5 max-w-32 items-center gap-1 rounded-full bg-muted px-1.5 font-medium" :class="category.missing ? 'text-destructive' : ''">
                  <span class="size-1.5 shrink-0 rounded-full" :style="{ backgroundColor: category.color || '#64748b' }" />
                  <span class="truncate">{{ category.category }}</span>
                </span>
                <span v-if="postCategories(post).length === 0" class="inline-flex h-5 items-center rounded-full bg-muted px-1.5">{{ adminText('k00ay') }}</span>
                <span class="inline-flex items-center gap-1"><Eye class="size-3.5" />{{ post.viewCount }}</span>
                <span class="inline-flex items-center gap-1"><MessageSquare class="size-3.5" />{{ post.replyCount }}</span>
                <span class="inline-flex items-center gap-1"><Heart class="size-3.5" />{{ post.likeCount }}</span>
              </div>

              <div class="flex items-center justify-between gap-3">
                <div class="flex min-w-0 items-center gap-2">
                  <img v-if="post.userAvatarUrl" :src="post.userAvatarUrl" class="size-7 shrink-0 rounded-full object-cover ring-1 ring-border" alt="" />
                  <span v-else class="flex size-7 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold">{{ avatarText(post) }}</span>
                  <div class="min-w-0">
                    <a :href="`/u/${post.userId}`" target="_blank" rel="noreferrer" class="block truncate text-[13px] font-semibold hover:text-primary hover:underline">
                      {{ post.username }}
                    </a>
                    <div class="truncate text-xs text-muted-foreground">{{ postDate(post.createdAt) }} {{ postTime(post.createdAt) }} · {{ post.processStatus === 1 ? adminText('k005x') : adminText('k005y') }}</div>
                  </div>
                </div>
                <div class="flex shrink-0 items-center gap-0.5">
                  <AdminActionButton compact :title="adminText('k006c')" @click="openSource(post)">
                    <FileText class="size-4" />
                  </AdminActionButton>
                  <AdminActionButton compact :title="adminText('k006d')" @click="openCategoryDialog(post)">
                    <Tags class="size-4" />
                  </AdminActionButton>
                  <AdminActionButton compact :tone="post.pinWeight > 0 ? 'primary' : 'default'" :title="adminText('k006e')" @click="openPinDialog(post)">
                    <Pin class="size-4" />
                  </AdminActionButton>
                  <AdminActionButton compact :tone="post.processStatus === 1 ? 'success' : 'danger'" :title="post.processStatus === 1 ? adminText('k005z') : adminText('k0060')" @click="actionRow = post">
                    <Undo2 v-if="post.processStatus === 1" class="size-4" />
                    <Ban v-else class="size-4" />
                  </AdminActionButton>
                  <AdminActionButton compact tone="danger" :title="adminText('k005i')" @click="deleteRow = post">
                    <Trash2 class="size-4" />
                  </AdminActionButton>
                </div>
              </div>
            </article>
          </div>
        </div>

          <Table class="hidden table-fixed md:table">
            <TableHeader class="bg-muted/30">
              <TableRow>
                <TableHead class="px-3">{{ adminText('k00az') }}</TableHead>
                <TableHead class="w-[180px]">{{ adminText('k00b0') }}</TableHead>
                <TableHead class="w-[96px] text-center">{{ adminText('k007j') }}</TableHead>
                <TableHead class="w-[176px] text-right pr-3">{{ adminText('k007m') }}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow v-if="loading">
                <TableCell colspan="4" class="h-28 text-center text-muted-foreground">{{ adminText('k0046') }}</TableCell>
              </TableRow>
              <TableRow v-else-if="error">
                <TableCell colspan="4" class="h-28 text-center text-destructive">{{ error }}</TableCell>
              </TableRow>
              <TableRow v-else-if="rows.length === 0">
                <TableCell colspan="4" class="h-28 text-center text-muted-foreground">{{ adminText('k00aw') }}</TableCell>
              </TableRow>
              <template v-else>
                <TableRow v-for="post in rows" :key="post.id" class="group hover:bg-muted/20">
                  <TableCell class="max-w-0 whitespace-normal px-3 py-2">
                    <div class="min-w-0 space-y-1">
                      <div class="flex min-w-0 items-center gap-1.5">
                        <a :href="`/p/post/${post.id}`" target="_blank" rel="noreferrer" class="min-w-0 truncate text-[15px] font-semibold leading-5 text-foreground hover:text-primary hover:underline">
                          {{ post.title }}
                        </a>
                        <span class="inline-flex h-5 shrink-0 items-center rounded-full border px-1.5 text-[11px] font-semibold" :class="typeInfo(post.type).className">
                          {{ typeInfo(post.type).label }}
                        </span>
                        <Badge v-if="post.processStatus === 1" variant="destructive" class="h-5 shrink-0 rounded-full px-1.5 text-[10px]">{{ adminText('k0069') }}</Badge>
                        <Badge v-if="post.pinWeight > 0" variant="secondary" class="h-5 shrink-0 rounded-full px-1.5 text-[10px]">{{ adminText('k00ax') }} {{ post.pinWeight }}</Badge>
                      </div>
                      <p class="truncate text-[12px] leading-4 text-muted-foreground">
                        {{ post.description || adminText('k005w') }}
                      </p>
                      <div class="flex min-w-0 flex-wrap items-center gap-x-1.5 gap-y-1 text-[12px] leading-4 text-muted-foreground">
                        <span class="whitespace-nowrap">{{ postDate(post.createdAt) }} {{ postTime(post.createdAt) }}</span>
                        <span v-for="category in postCategories(post)" :key="category.id" class="inline-flex h-5 max-w-32 items-center gap-1 rounded-full bg-muted px-1.5 font-medium" :class="category.missing ? 'text-destructive' : ''">
                          <span class="size-1.5 shrink-0 rounded-full" :style="{ backgroundColor: category.color || '#64748b' }" />
                          <span class="truncate">{{ category.category }}</span>
                        </span>
                        <span v-if="postCategories(post).length === 0" class="inline-flex h-5 items-center rounded-full bg-muted px-1.5">{{ adminText('k00ay') }}</span>
                        <span class="inline-flex items-center gap-1" :title="adminText('k006f')"><Eye class="size-3.5" />{{ post.viewCount }}</span>
                        <span class="inline-flex items-center gap-1" :title="adminText('k006g')"><MessageSquare class="size-3.5" />{{ post.replyCount }}</span>
                        <span class="inline-flex items-center gap-1" :title="adminText('k006h')"><Heart class="size-3.5" />{{ post.likeCount }}</span>
                      </div>
                    </div>
                  </TableCell>
                  <TableCell class="max-w-0 py-2 align-middle">
                    <div class="flex min-w-0 items-center gap-2">
                      <img v-if="post.userAvatarUrl" :src="post.userAvatarUrl" class="size-7 shrink-0 rounded-full object-cover ring-1 ring-border" alt="" />
                      <span v-else class="flex size-7 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold">{{ avatarText(post) }}</span>
                      <a :href="`/u/${post.userId}`" target="_blank" rel="noreferrer" class="min-w-0 truncate text-[13px] font-semibold hover:text-primary hover:underline">
                        {{ post.username }}
                      </a>
                    </div>
                  </TableCell>
                  <TableCell class="py-2 text-center align-middle">
                    <div class="inline-flex min-w-[52px] flex-col items-center gap-0.5">
                      <span class="inline-flex h-6 items-center rounded-md px-2 text-xs font-semibold" :class="articleStatusInfo(post.articleStatus).className">
                        {{ articleStatusInfo(post.articleStatus).label }}
                      </span>
                      <span class="text-[11px]" :class="post.processStatus === 1 ? 'text-destructive' : 'text-muted-foreground'">
                        {{ post.processStatus === 1 ? adminText('k005x') : adminText('k005y') }}
                      </span>
                    </div>
                  </TableCell>
                  <TableCell class="pr-3">
                    <div class="flex justify-end gap-0.5">
                      <AdminActionButton compact :title="adminText('k006c')" @click="openSource(post)">
                        <FileText class="size-4" />
                      </AdminActionButton>
                      <AdminActionButton compact :title="adminText('k006d')" @click="openCategoryDialog(post)">
                        <Tags class="size-4" />
                      </AdminActionButton>
                      <AdminActionButton compact :tone="post.pinWeight > 0 ? 'primary' : 'default'" :title="adminText('k006e')" @click="openPinDialog(post)">
                        <Pin class="size-4" />
                      </AdminActionButton>
                      <AdminActionButton compact :tone="post.processStatus === 1 ? 'success' : 'danger'" :title="post.processStatus === 1 ? adminText('k005z') : adminText('k0060')" @click="actionRow = post">
                        <Undo2 v-if="post.processStatus === 1" class="size-4" />
                        <Ban v-else class="size-4" />
                      </AdminActionButton>
                      <AdminActionButton compact tone="danger" :title="adminText('k005i')" @click="deleteRow = post">
                        <Trash2 class="size-4" />
                      </AdminActionButton>
                    </div>
                  </TableCell>
                </TableRow>
              </template>
            </TableBody>
          </Table>

      </AdminSection>

      <Dialog :open="categoryDialogRow !== null" @update:open="(open) => !open && (categoryDialogRow = null)">
        <DialogContent class="sm:max-w-xl">
          <DialogHeader>
            <DialogTitle>{{ adminText('k00b1') }}</DialogTitle>
            <DialogDescription class="line-clamp-2">
              {{ adminText('k00b2', { title: categoryDialogRow?.title || '' }) }}
            </DialogDescription>
          </DialogHeader>
          <div class="flex max-h-[46vh] flex-wrap gap-2 overflow-y-auto pr-1">
            <button
              v-for="category in categoryDialogOptions"
              :key="category.id"
              class="inline-flex max-w-full items-center gap-1.5 rounded-md border px-2.5 py-1.5 text-left text-sm font-medium transition-colors"
              :class="[
                selectedCategoryIds.includes(category.id) ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground hover:border-muted-foreground/30 hover:bg-muted/50',
                category.missing ? 'border-destructive/30 bg-destructive/5 text-destructive hover:bg-destructive/10' : '',
              ]"
              type="button"
              @click="toggleCategory(category.id)"
            >
              <span class="size-2 rounded-[3px]" :style="{ backgroundColor: category.color || '#64748b' }" />
              <span class="max-w-48 truncate">{{ category.category }}</span>
            </button>
          </div>
          <DialogFooter>
            <Button variant="outline" type="button" @click="categoryDialogRow = null">{{ adminText('k009q') }}</Button>
            <Button type="button" :disabled="saving" @click="saveCategories">{{ saving ? adminText('k005f') : adminText('k0061') }}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog :open="pinDialogRow !== null" @update:open="(open) => !open && (pinDialogRow = null)">
        <DialogContent class="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{{ adminText('k00b4') }}</DialogTitle>
            <DialogDescription class="line-clamp-2">
              {{ adminText('k00b5', { title: pinDialogRow?.title || '' }) }}
            </DialogDescription>
          </DialogHeader>
          <div class="space-y-2">
            <Input v-model.number="pinWeightInput" type="number" min="0" max="1000000" />
            <p class="text-xs text-muted-foreground">{{ adminText('k00b6') }}</p>
          </div>
          <DialogFooter>
            <Button variant="outline" type="button" @click="pinDialogRow = null">{{ adminText('k009q') }}</Button>
            <Button type="button" :disabled="saving" @click="savePinWeight">{{ saving ? adminText('k005f') : adminText('k005g') }}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog :open="sourceDialogRow !== null" @update:open="(open) => !open && (sourceDialogRow = null)">
        <DialogContent class="sm:max-w-3xl">
          <DialogHeader>
            <DialogTitle>{{ adminText('k00b7') }}</DialogTitle>
            <DialogDescription>{{ sourceDialogRow?.title }}</DialogDescription>
          </DialogHeader>
          <div class="max-h-[58vh] overflow-auto rounded-lg border bg-muted/20 p-4">
            <pre v-if="sourceLoading" class="text-sm text-muted-foreground">{{ adminText('k0046') }}</pre>
            <pre v-else class="whitespace-pre-wrap break-words text-sm leading-6">{{ source?.content || adminText('k0062') }}</pre>
          </div>
          <DialogFooter>
            <Button variant="outline" type="button" @click="sourceDialogRow = null">{{ adminText('k00b8') }}</Button>
            <Button type="button" :disabled="!source?.content" @click="copySource">{{ adminText('k00b9') }}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog :open="actionRow !== null" @update:open="(open) => !open && (actionRow = null)">
        <DialogContent class="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{{ actionRow?.processStatus === 1 ? adminText('k0063') : adminText('k0064') }}</DialogTitle>
            <DialogDescription>
              {{ actionRow?.processStatus === 1 ? adminText('k0065') : adminText('k0066') }}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" type="button" @click="actionRow = null">{{ adminText('k009q') }}</Button>
            <Button :variant="actionRow?.processStatus === 1 ? 'default' : 'destructive'" type="button" :disabled="saving" @click="toggleProcessStatus">
              {{ saving ? adminText('k0067') : (actionRow?.processStatus === 1 ? adminText('k0068') : adminText('k0069')) }}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <AdminConfirmDialog
        :open="deleteRow !== null"
        :title="adminText('k00cf')"
        :description="adminText('k00cg', { title: deleteRow?.title || '' })"
        :loading="saving"
        @update:open="(open) => !open && (deleteRow = null)"
        @confirm="confirmDeleteArticle"
      />
    </BasicPage>
</template>

// resource/apps/web/src/admin/pages/posts-management-page.tsx
import { AdminPage } from '../components/admin-page'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { AdminCategory, AdminTopic, GooseAdminApi, ReviewPost, TopicSource } from '@gooseforum/client'
import { Avatar, AvatarFallback, AvatarImage } from '@gooseforum/ui/components/avatar'
import { Badge } from '@gooseforum/ui/components/badge'
import { Button } from '@gooseforum/ui/components/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@gooseforum/ui/components/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@gooseforum/ui/components/dropdown-menu'
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle } from '@gooseforum/ui/components/empty'
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@gooseforum/ui/components/field'
import { Input } from '@gooseforum/ui/components/input'
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@gooseforum/ui/components/select'
import { Spinner } from '@gooseforum/ui/components/spinner'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@gooseforum/ui/components/table'
import { Ban, FileText, MoreHorizontal, Pin, RefreshCw, Search, Tags, Trash2, Undo2 } from 'lucide-react'
import { toast } from 'sonner'
import type { PostTextKey } from '../posts-i18n'

type Text = (key: PostTextKey) => string
type ReviewAction = 'approve' | 'reject' | 'recheck'

export function PostsManagementPage({ api, text }: { api: GooseAdminApi; text: Text }) {
  const [kind, setKind] = useState<'topic' | 'post'>('topic')
  const [moderationStatus, setModerationStatus] = useState('all')
  const [categoryId, setCategoryId] = useState('all')
  const [topics, setTopics] = useState<AdminTopic[]>([])
  const [replies, setReplies] = useState<ReviewPost[]>([])
  const [categories, setCategories] = useState<AdminCategory[]>([])
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [hasNext, setHasNext] = useState(false)
  const [search, setSearch] = useState('')
  const [appliedSearch, setAppliedSearch] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [categoryTopic, setCategoryTopic] = useState<AdminTopic | null>(null)
  const [pinTopic, setPinTopic] = useState<AdminTopic | null>(null)
  const [sourceTopic, setSourceTopic] = useState<AdminTopic | null>(null)
  const [reviewReply, setReviewReply] = useState<ReviewPost | null>(null)
  const [processTopic, setProcessTopic] = useState<AdminTopic | null>(null)
  const [deleteTopic, setDeleteTopic] = useState<AdminTopic | null>(null)
  const requestVersion = useRef(0)
  useEffect(() => () => { requestVersion.current++ }, [])

  useEffect(() => {
    let active = true
    void api.categories.list().then((items) => { if (active) setCategories(items) }).catch(() => undefined)
    return () => { active = false }
  }, [api])

  const load = useCallback(async () => {
    const version = ++requestVersion.current
    setLoading(true); setError('')
    try {
      if (kind === 'post') {
        const result = await api.topics.reviewPosts({ page, pageSize, moderationStatus: moderationStatus === 'all' ? undefined : moderationStatus, search: appliedSearch || undefined })
        if (version !== requestVersion.current) return
        setReplies(result.list || []); setHasNext(Boolean(result.hasNext))
      } else {
        const result = await api.topics.list({ page, pageSize, search: appliedSearch || undefined, moderationStatus: moderationStatus === 'all' ? undefined : moderationStatus, categoryId: categoryId === 'all' ? undefined : Number(categoryId) })
        if (version !== requestVersion.current) return
        setTopics(result.list || []); setHasNext(Boolean(result.hasNext))
      }
    } catch (reason) {
      if (version === requestVersion.current) setError(errorMessage(reason, text('loadFailed')))
    } finally {
      if (version === requestVersion.current) setLoading(false)
    }
  }, [api, appliedSearch, categoryId, kind, moderationStatus, page, pageSize, text])

  useEffect(() => { void load() }, [load])
  const visibleCount = kind === 'topic' ? topics.length : replies.length
  const rangeStart = visibleCount ? (page - 1) * pageSize + 1 : 0
  const rangeEnd = visibleCount ? rangeStart + visibleCount - 1 : 0

  return <AdminPage>
    <header><h2 className="text-lg font-semibold tracking-tight">{text('title')}</h2><p className="text-xs text-muted-foreground">{text('description')}</p></header>
    <div className="flex flex-wrap items-center gap-1.5"><FilterSelect value={kind} label={text('topics')} onChange={(value) => { setKind(value as 'topic' | 'post'); setPage(1) }} options={[['topic', text('topics')], ['post', text('replies')]]} /><FilterSelect value={moderationStatus} label={text('allReviews')} onChange={(value) => { setModerationStatus(value); setPage(1) }} options={[['all', text('allReviews')], ['pending', text('pending')], ['approved', text('approved')], ['rejected', text('rejected')], ['none', text('none')]]} />{kind === 'topic' ? <FilterSelect value={categoryId} label={text('allCategories')} onChange={(value) => { setCategoryId(value); setPage(1) }} options={[['all', text('allCategories')], ...categories.map((category) => [String(category.id), category.category] as [string, string])]} /> : null}</div>
    <section className="overflow-hidden rounded-lg border bg-background"><div className="flex flex-col gap-2 border-b bg-muted/20 p-2 lg:flex-row lg:items-center lg:justify-between"><form className="flex min-w-0 flex-1 gap-1.5 lg:max-w-xl" onSubmit={(event) => { event.preventDefault(); setAppliedSearch(search.trim()); setPage(1) }}><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} className="h-8 pl-8" placeholder={text('search')} /></div><Button type="submit" size="sm">{text('searchAction')}</Button>{appliedSearch ? <Button type="button" variant="ghost" size="sm" onClick={() => { setSearch(''); setAppliedSearch(''); setPage(1) }}>{text('clear')}</Button> : null}</form><div className="flex flex-wrap items-center gap-1.5 text-xs text-muted-foreground"><Button variant="outline" size="sm" disabled={loading} onClick={() => void load()}><RefreshCw data-icon="inline-start" className={loading ? 'animate-spin' : undefined} />{text('refresh')}</Button><span>{rangeStart}-{rangeEnd}</span><Select value={String(pageSize)} onValueChange={(value) => { setPageSize(Number(value)); setPage(1) }}><SelectTrigger size="sm" className="w-20"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{[10, 20, 50].map((size) => <SelectItem key={size} value={String(size)}>{size}</SelectItem>)}</SelectGroup></SelectContent></Select><Button variant="outline" size="sm" disabled={page <= 1 || loading} onClick={() => setPage(page - 1)}>{text('previous')}</Button><span>{text('page')} {page}</span><Button variant="outline" size="sm" disabled={!hasNext || loading} onClick={() => setPage(page + 1)}>{text('next')}</Button></div></div>
      {loading && !visibleCount ? <ContentEmpty icon={<Spinner />} title={text('loading')} /> : error ? <ContentEmpty icon={<FileText />} title={error} /> : !visibleCount ? <ContentEmpty icon={<Search />} title={text('empty')} /> : kind === 'post' ? <ReplyList replies={replies} text={text} onReview={setReviewReply} /> : <TopicList topics={topics} categories={categories} text={text} onSource={setSourceTopic} onCategories={setCategoryTopic} onPin={setPinTopic} onProcess={setProcessTopic} onDelete={setDeleteTopic} />}
    </section>
    <CategoryDialog topic={categoryTopic} categories={categories} api={api} text={text} onClose={() => setCategoryTopic(null)} onSaved={load} />
    <PinDialog topic={pinTopic} api={api} text={text} onClose={() => setPinTopic(null)} onSaved={load} />
    <SourceDialog topic={sourceTopic} api={api} text={text} onClose={() => setSourceTopic(null)} onSaved={load} />
    <ReviewReplyDialog reply={reviewReply} api={api} text={text} onClose={() => setReviewReply(null)} onSaved={load} />
    <TopicActionDialog topic={processTopic} mode="process" api={api} text={text} onClose={() => setProcessTopic(null)} onSaved={load} />
    <TopicActionDialog topic={deleteTopic} mode="delete" api={api} text={text} onClose={() => setDeleteTopic(null)} onSaved={load} />
  </AdminPage>
}

function TopicList({ topics, categories, text, onSource, onCategories, onPin, onProcess, onDelete }: { topics: AdminTopic[]; categories: AdminCategory[]; text: Text; onSource(topic: AdminTopic): void; onCategories(topic: AdminTopic): void; onPin(topic: AdminTopic): void; onProcess(topic: AdminTopic): void; onDelete(topic: AdminTopic): void }) {
  const categoryMap = new Map(categories.map((category) => [category.id, category]))
  return <><div className="hidden md:block"><Table className="min-w-245 table-fixed"><TableHeader className="bg-muted/30"><TableRow><TableHead className="h-8">{text('topic')}</TableHead><TableHead className="h-8 w-44">{text('author')}</TableHead><TableHead className="h-8 w-24 text-center">{text('status')}</TableHead><TableHead className="h-8 w-20 text-right">{text('actions')}</TableHead></TableRow></TableHeader><TableBody>{topics.map((topic) => <TableRow key={topic.id}><TableCell className="max-w-0 py-2"><TopicSummary topic={topic} categoryMap={categoryMap} text={text} /></TableCell><TableCell className="py-2"><Author topic={topic} /></TableCell><TableCell className="py-2 text-center"><StatusBadge topic={topic} text={text} /></TableCell><TableCell className="py-2"><TopicActions topic={topic} text={text} onSource={() => onSource(topic)} onCategories={() => onCategories(topic)} onPin={() => onPin(topic)} onProcess={() => onProcess(topic)} onDelete={() => onDelete(topic)} /></TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y md:hidden">{topics.map((topic) => <article key={topic.id} className="flex flex-col gap-2 px-3 py-2.5"><div className="flex items-start justify-between gap-2"><TopicSummary topic={topic} categoryMap={categoryMap} text={text} /><StatusBadge topic={topic} text={text} /></div><div className="flex items-center gap-2"><Author topic={topic} /><span className="text-xs text-muted-foreground">{datePart(topic.createdAt)}</span><TopicActions topic={topic} text={text} onSource={() => onSource(topic)} onCategories={() => onCategories(topic)} onPin={() => onPin(topic)} onProcess={() => onProcess(topic)} onDelete={() => onDelete(topic)} /></div></article>)}</div></>
}

function TopicSummary({ topic, categoryMap, text }: { topic: AdminTopic; categoryMap: Map<number, AdminCategory>; text: Text }) {
  return <div className="flex min-w-0 flex-1 flex-col gap-1.5 py-0.5">
    <div className="flex min-w-0 items-center gap-4">
      <a href={`/p/post/${topic.id}`} target="_blank" rel="noreferrer" title={topic.title} className="min-w-0 flex-1 truncate text-sm font-medium leading-5 hover:text-primary hover:underline">{topic.title}</a>
      <time className="hidden shrink-0 text-xs tabular-nums text-muted-foreground md:block">{datePart(topic.createdAt)}</time>
    </div>
    <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5">
      <div className="flex min-w-0 flex-wrap items-center gap-1.5 text-xs text-muted-foreground">
        {topic.pinWeight > 0 ? <span className="inline-flex items-center gap-1"><Pin className="size-3" />{text('pin')} {topic.pinWeight}</span> : null}
        {topic.categoryId?.length ? topic.categoryId.map((id) => { const category = categoryMap.get(id); return <span key={id} className="inline-flex min-w-0 items-center gap-1.5" title={category?.category || `${text('unknownCategory')} ${id}`}><span className="size-1.5 shrink-0 rounded-full" style={{ backgroundColor: category?.color || '#94a3b8' }} /><span className="max-w-32 truncate">{category?.category || id}</span></span> }) : <span>{text('noCategory')}</span>}
        {topic.moderationStatus && !['none', 'approved'].includes(topic.moderationStatus) ? <Badge variant="outline" title={topic.moderationReason}>{reviewLabel(topic.moderationStatus, text)}</Badge> : null}
        {topic.processStatus === 1 ? <Badge variant="destructive">{text('processed')}</Badge> : null}
      </div>
      <div className="ml-auto flex shrink-0 items-center gap-3 text-xs tabular-nums text-muted-foreground">
        <span>{text('views')} <span className="text-foreground">{topic.viewCount}</span></span>
        <span>{text('repliesCount')} <span className="text-foreground">{topic.replyCount}</span></span>
        <span>{text('likes')} <span className="text-foreground">{topic.likeCount}</span></span>
      </div>
    </div>
  </div>
}

function Author({ topic }: { topic: AdminTopic }) { return <div className="flex min-w-0 flex-1 items-center gap-2"><Avatar className="size-7"><AvatarImage src={topic.userAvatarUrl || undefined} alt={topic.username} /><AvatarFallback>{topic.username.slice(0, 1).toUpperCase()}</AvatarFallback></Avatar><a href={`/u/${topic.userId}`} target="_blank" rel="noreferrer" className="truncate text-[13px] hover:text-primary hover:underline">{topic.username}</a></div> }
function StatusBadge({ topic, text }: { topic: AdminTopic; text: Text }) { const label = topic.deleted ? text('deleted') : topic.topicStatus === 1 ? text('active') : ['rejected', 'pending', 'denied'].includes(topic.moderationStatus) ? reviewLabel(topic.moderationStatus, text) : text('inactive'); return <Badge variant={topic.deleted || ['rejected', 'denied'].includes(topic.moderationStatus) ? 'destructive' : 'secondary'}>{label}</Badge> }
function TopicActions({ topic, text, onSource, onCategories, onPin, onProcess, onDelete }: { topic: AdminTopic; text: Text; onSource(): void; onCategories(): void; onPin(): void; onProcess(): void; onDelete(): void }) { return <div className="ml-auto flex justify-end"><Button variant="ghost" size="icon-sm" title={text('openReview')} onClick={onSource}><FileText /></Button>{!topic.deleted ? <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" title={text('actions')}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuGroup><DropdownMenuItem onSelect={onCategories}><Tags />{text('editCategories')}</DropdownMenuItem><DropdownMenuItem onSelect={onPin}><Pin />{text('editPin')}</DropdownMenuItem></DropdownMenuGroup><DropdownMenuSeparator /><DropdownMenuGroup><DropdownMenuItem variant={topic.processStatus === 1 ? 'default' : 'destructive'} onSelect={onProcess}>{topic.processStatus === 1 ? <Undo2 /> : <Ban />}{topic.processStatus === 1 ? text('restore') : text('disable')}</DropdownMenuItem><DropdownMenuItem variant="destructive" onSelect={onDelete}><Trash2 />{text('delete')}</DropdownMenuItem></DropdownMenuGroup></DropdownMenuContent></DropdownMenu> : null}</div> }

function ReplyList({ replies, text, onReview }: { replies: ReviewPost[]; text: Text; onReview(reply: ReviewPost): void }) { return <div className="divide-y">{replies.map((reply) => <article key={reply.id} className="flex flex-col gap-2 p-3"><div className="flex items-center justify-between gap-3"><span className="font-medium">{reply.topicTitle} · #{reply.postNo} · UID {reply.userId}</span><Badge>{reviewLabel(reply.moderationStatus, text)}</Badge></div><p className="line-clamp-3 whitespace-pre-wrap break-words text-sm">{reply.content}</p>{reply.moderationReason ? <p className="text-sm text-muted-foreground">{reply.moderationReason}</p> : null}<Button variant="outline" size="sm" className="self-start" onClick={() => onReview(reply)}>{text('openReview')}</Button></article>)}</div> }

function CategoryDialog({ topic, categories, api, text, onClose, onSaved }: { topic: AdminTopic | null; categories: AdminCategory[]; api: GooseAdminApi; text: Text; onClose(): void; onSaved(): Promise<void> }) {
  const [selected, setSelected] = useState<number[]>([]); const [pending, setPending] = useState<number[] | null>(null); const [saving, setSaving] = useState(false)
  const categoryMap = useMemo(() => new Map(categories.map((category) => [category.id, category])), [categories])
  const options = useMemo(() => [...categories, ...selected.filter((id) => !categoryMap.has(id)).map((id) => ({ id, category: `${text('unknownCategory')} ${id}`, color: '#94a3b8' }))], [categories, categoryMap, selected, text])
  useEffect(() => { if (topic) { setSelected([...(topic.categoryId || [])]); setPending(null) } }, [topic])
  function toggle(id: number) {
    if (selected.includes(id)) { setSelected(selected.filter((value) => value !== id)); return }
    if (selected.length >= 3) { toast.warning(text('categoryLimit')); return }
    setSelected([...selected, id])
  }
  async function persist(ids: number[]) { if (!topic) return; setSaving(true); try { await api.topics.setCategories(topic.id, ids); toast.success(text('saved')); onClose(); await onSaved() } catch (reason) { toast.error(errorMessage(reason, text('loadFailed'))) } finally { setSaving(false) } }
  function save() { const valid = selected.filter((id) => categoryMap.has(id)); if (!valid.length) { toast.warning(text('categoryRequired')); return } if (topic?.categoryId?.[0] !== valid[0]) setPending(valid); else void persist(valid) }
  return <><Dialog open={Boolean(topic)} onOpenChange={(open) => !open && !saving && onClose()}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{text('categoryTitle')}</DialogTitle><DialogDescription>{text('categoryHint')} {topic?.title}</DialogDescription></DialogHeader><div className="flex max-h-[46vh] flex-wrap gap-1.5 overflow-y-auto">{options.map((category) => <Button key={category.id} type="button" variant="ghost" data-current={selected.includes(category.id)} onClick={() => toggle(category.id)} className="h-auto max-w-full border px-2.5 py-1.5 font-normal data-[current=true]:border-primary data-[current=true]:bg-primary/10 data-[current=true]:text-primary"><span className="size-2 rounded-[3px]" style={{ backgroundColor: category.color || '#64748b' }} />{category.category}{selected[0] === category.id ? <Badge variant="secondary">{text('mainCategory')}</Badge> : null}</Button>)}</div><DialogFooter><Button variant="outline" disabled={saving} onClick={onClose}>{text('cancel')}</Button><Button disabled={saving} onClick={save}>{saving ? <Spinner data-icon="inline-start" /> : null}{text('save')}</Button></DialogFooter></DialogContent></Dialog><Dialog open={Boolean(pending)} onOpenChange={(open) => !open && setPending(null)}><DialogContent><DialogHeader><DialogTitle>{text('mainCategoryChange')}</DialogTitle><DialogDescription>{text('mainCategoryChangeHint')} {categoryMap.get(topic?.categoryId?.[0] || 0)?.category || '—'} → {categoryMap.get(pending?.[0] || 0)?.category || '—'}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setPending(null)}>{text('cancel')}</Button><Button onClick={() => { const ids = pending; setPending(null); if (ids) void persist(ids) }}>{text('confirm')}</Button></DialogFooter></DialogContent></Dialog></>
}

function PinDialog({ topic, api, text, onClose, onSaved }: { topic: AdminTopic | null; api: GooseAdminApi; text: Text; onClose(): void; onSaved(): Promise<void> }) { const [weight, setWeight] = useState(0); const [saving, setSaving] = useState(false); useEffect(() => { if (topic) setWeight(topic.pinWeight || 0) }, [topic]); async function save() { if (!topic) return; setSaving(true); try { await api.topics.setPin(topic.id, Math.max(0, Math.trunc(weight || 0))); toast.success(text('saved')); onClose(); await onSaved() } catch (reason) { toast.error(errorMessage(reason, text('loadFailed'))) } finally { setSaving(false) } } return <Dialog open={Boolean(topic)} onOpenChange={(open) => !open && !saving && onClose()}><DialogContent><DialogHeader><DialogTitle>{text('pinTitle')}</DialogTitle><DialogDescription>{topic?.title}</DialogDescription></DialogHeader><FieldGroup><Field><FieldLabel>{text('pinTitle')}</FieldLabel><Input type="number" min={0} max={1_000_000} value={weight} onChange={(event) => setWeight(Number(event.target.value) || 0)} /><FieldDescription>{text('pinHint')}</FieldDescription></Field></FieldGroup><DialogFooter><Button variant="outline" onClick={onClose}>{text('cancel')}</Button><Button disabled={saving} onClick={() => void save()}>{saving ? <Spinner data-icon="inline-start" /> : null}{text('save')}</Button></DialogFooter></DialogContent></Dialog> }

function SourceDialog({ topic, api, text, onClose, onSaved }: { topic: AdminTopic | null; api: GooseAdminApi; text: Text; onClose(): void; onSaved(): Promise<void> }) { const [source, setSource] = useState<TopicSource | null>(null); const [reason, setReason] = useState(''); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const textRef = useRef(text); useEffect(() => { textRef.current = text }, [text]); useEffect(() => { if (!topic) return; let active = true; setSource(null); setReason(''); setLoading(true); void api.topics.source(topic.id).then((value) => { if (active) setSource(value) }).catch((error) => toast.error(errorMessage(error, textRef.current('loadFailed')))).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [api, topic]); async function review(action: ReviewAction) { if (!source || !reason.trim()) return; setSaving(true); try { await api.topics.review('topic', { id: source.id, version: source.moderationVersion, action, reason: reason.trim() }); toast.success(text('reviewSaved')); onClose(); await onSaved() } catch (error) { toast.error(errorMessage(error, text('loadFailed'))) } finally { setSaving(false) } } async function copy() { if (!source?.content) return; try { await navigator.clipboard.writeText(source.content); toast.success(text('copied')) } catch { toast.error(text('loadFailed')) } } const reviewable = source && (source.topicStatus === 1 || ['rejected', 'pending', 'denied'].includes(source.moderationStatus)); return <Dialog open={Boolean(topic)} onOpenChange={(open) => !open && !saving && onClose()}><DialogContent className="sm:max-w-3xl"><DialogHeader><DialogTitle>{text('openReview')}</DialogTitle><DialogDescription>{topic?.title}</DialogDescription></DialogHeader><pre className="max-h-[50vh] overflow-auto whitespace-pre-wrap break-words rounded-lg border bg-muted/20 p-3 text-sm leading-6">{loading ? text('loading') : source?.content || text('sourceEmpty')}</pre>{source && !loading ? <div className="flex flex-col gap-1 text-sm"><p>{reviewLabel(source.moderationStatus, text)} · {source.moderatedAt || '—'}</p>{source.moderationReason ? <p className="text-muted-foreground">{source.moderationReason}</p> : null}</div> : null}{reviewable ? <div className="flex flex-col gap-2"><Input value={reason} maxLength={300} onChange={(event) => setReason(event.target.value)} placeholder={text('reviewReason')} /><div className="flex flex-wrap gap-1.5"><Button disabled={saving || !reason.trim()} onClick={() => void review('approve')}>{text('approve')}</Button><Button variant="destructive" disabled={saving || !reason.trim()} onClick={() => void review('reject')}>{text('reject')}</Button><Button variant="outline" disabled={saving || !reason.trim()} onClick={() => void review('recheck')}>{text('recheck')}</Button></div></div> : null}<DialogFooter><Button variant="outline" onClick={onClose}>{text('close')}</Button><Button disabled={!source?.content} onClick={() => void copy()}>{text('copy')}</Button></DialogFooter></DialogContent></Dialog> }

function ReviewReplyDialog({ reply, api, text, onClose, onSaved }: { reply: ReviewPost | null; api: GooseAdminApi; text: Text; onClose(): void; onSaved(): Promise<void> }) { const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false); useEffect(() => { if (reply) setReason('') }, [reply]); async function review(action: ReviewAction) { if (!reply || !reason.trim()) return; setSaving(true); try { await api.topics.review('post', { id: reply.id, version: reply.moderationVersion, action, reason: reason.trim() }); toast.success(text('reviewSaved')); onClose(); await onSaved() } catch (error) { toast.error(errorMessage(error, text('loadFailed'))) } finally { setSaving(false) } } return <Dialog open={Boolean(reply)} onOpenChange={(open) => !open && !saving && onClose()}><DialogContent className="sm:max-w-3xl"><DialogHeader><DialogTitle>{text('replies')}</DialogTitle><DialogDescription>{reply?.topicTitle} · #{reply?.postNo}</DialogDescription></DialogHeader><pre className="max-h-[45vh] overflow-auto whitespace-pre-wrap break-words rounded-lg border p-3 text-sm">{reply?.content}</pre>{reply?.moderationReason ? <p className="text-sm text-muted-foreground">{reply.moderationReason}</p> : null}<Input value={reason} maxLength={300} onChange={(event) => setReason(event.target.value)} placeholder={text('reviewReason')} /><DialogFooter><Button disabled={saving || !reason.trim()} onClick={() => void review('approve')}>{text('approve')}</Button><Button variant="destructive" disabled={saving || !reason.trim()} onClick={() => void review('reject')}>{text('reject')}</Button><Button variant="outline" disabled={saving || !reason.trim()} onClick={() => void review('recheck')}>{text('recheck')}</Button></DialogFooter></DialogContent></Dialog> }

function TopicActionDialog({ topic, mode, api, text, onClose, onSaved }: { topic: AdminTopic | null; mode: 'process' | 'delete'; api: GooseAdminApi; text: Text; onClose(): void; onSaved(): Promise<void> }) { const [saving, setSaving] = useState(false); const restoring = topic?.processStatus === 1; async function confirm() { if (!topic) return; setSaving(true); try { if (mode === 'delete') await api.topics.delete(topic.id); else await api.topics.setProcessStatus(topic.id, restoring ? 0 : 1); toast.success(text('saved')); onClose(); await onSaved() } catch (error) { toast.error(errorMessage(error, text('loadFailed'))) } finally { setSaving(false) } } const title = mode === 'delete' ? text('deleteTitle') : restoring ? text('actionRestoreTitle') : text('actionDisableTitle'); const description = mode === 'delete' ? text('deleteHint') : restoring ? text('actionRestoreHint') : text('actionDisableHint'); return <Dialog open={Boolean(topic)} onOpenChange={(open) => !open && !saving && onClose()}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description} {topic?.title}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" disabled={saving} onClick={onClose}>{text('cancel')}</Button><Button variant={mode === 'delete' || !restoring ? 'destructive' : 'default'} disabled={saving} onClick={() => void confirm()}>{saving ? <Spinner data-icon="inline-start" /> : null}{text('confirm')}</Button></DialogFooter></DialogContent></Dialog> }

function FilterSelect({ value, label, options, onChange }: { value: string; label: string; options: [string, string][]; onChange(value: string): void }) { return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="min-w-32"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{options.map(([option, title]) => <SelectItem key={option} value={option}>{title}</SelectItem>)}</SelectGroup></SelectContent></Select> }
function ContentEmpty({ icon, title }: { icon: React.ReactNode; title: string }) { return <Empty className="min-h-32 rounded-none border-0"><EmptyHeader><EmptyMedia variant="icon">{icon}</EmptyMedia><EmptyTitle>{title}</EmptyTitle></EmptyHeader></Empty> }
function reviewLabel(status: string, text: Text) { if (status === 'pending') return text('pending'); if (status === 'approved') return text('approved'); if (status === 'rejected' || status === 'denied') return text('rejected'); return text('none') }
function datePart(value?: string) { return value ? value.replace('T', ' ').replace(/\.\d+/, '').slice(0, 19) : '—' }
function errorMessage(reason: unknown, fallback: string) { return reason instanceof Error && reason.message ? reason.message : fallback }
