// resource/src/admin/pages/management/UsersManagementPage.vue
<script setup lang="ts">
import { adminText } from '@/admin/runtime/i18n-text'

import { computed, onMounted, reactive, ref } from 'vue'
import { Award, ChevronLeft, ChevronRight, CheckCircle2, Loader2, RefreshCw, Search, ShieldOff, UserCog } from '@lucide/vue'
import AdminSection from '@/admin/components/AdminSection.vue'
import AdminToolbar from '@/admin/components/AdminToolbar.vue'
import { BasicPage } from '@/admin/components/global-layout'
import { Button } from '@/admin/components/ui/button'
import { Dialog, DialogContent } from '@/admin/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/admin/components/ui/select'
import { Switch } from '@/admin/components/ui/switch'
import { editUser, getAllRoleItem, getUserBadgeOptions, getUserList, saveUserBadges } from '@/admin/runtime/api'
import { adminToast } from '@/admin/runtime/toast'
import type { AdminBadge, AdminPayload, AdminUser, ManageHomeProps, UserBadge } from '@/admin/types'

defineProps<{
  payload: AdminPayload<ManageHomeProps>
}>()

const loading = ref(false)
const saving = ref(false)
const error = ref('')
const rows = ref<AdminUser[]>([])
const total = ref(0)
const page = ref(1)
const pageSize = ref(10)
const search = ref('')
const appliedSearch = ref('')
const editingUser = ref<AdminUser | null>(null)
const roles = ref<{ name: string, value: number }[]>([])
const form = reactive({ status: 0, validate: 0, roleId: 0 })
const badgeLoading = ref(false)
const badgesLoaded = ref(false)
const badgeOptions = ref<AdminBadge[]>([])
const activeBadges = ref<UserBadge[]>([])
const selectedBadgeCodes = ref<string[]>([])

const totalPages = computed(() => Math.max(1, Math.ceil(total.value / pageSize.value)))
const rangeStart = computed(() => (total.value === 0 ? 0 : (page.value - 1) * pageSize.value + 1))
const rangeEnd = computed(() => Math.min(page.value * pageSize.value, total.value))

async function loadUsers() {
  loading.value = true
  error.value = ''
  try {
    const data = await getUserList({
      page: page.value,
      pageSize: pageSize.value,
      username: appliedSearch.value || undefined,
    })
    rows.value = data.list || []
    total.value = data.total || 0
    if (page.value > totalPages.value) page.value = totalPages.value
  } catch (err) {
    error.value = err instanceof Error ? err.message : adminText('k0031')
  } finally {
    loading.value = false
  }
}

async function ensureRoles() {
  if (roles.value.length) return
  try {
    roles.value = [{ name: adminText('k0032'), value: 0 }, ...(await getAllRoleItem())]
  } catch {
    roles.value = [{ name: adminText('k0032'), value: 0 }]
  }
}

function applySearch() {
  appliedSearch.value = search.value.trim()
  page.value = 1
  void loadUsers()
}

function changePage(nextPage: number) {
  page.value = nextPage
  void loadUsers()
}

function changePageSize(nextPageSize: number) {
  pageSize.value = nextPageSize
  page.value = 1
  void loadUsers()
}

function roleNames(user: AdminUser) {
  return user.roleList?.map(role => role.name).filter(Boolean) || []
}

function badgeIconURL(badge: AdminBadge | UserBadge) {
  return badge.iconUrl || '/static/badges/contributor.svg'
}

function badgeToneClass(badge: AdminBadge | UserBadge) {
  const classes: Record<string, string> = {
    blue: 'bg-blue-100 text-blue-700 ring-blue-200',
    emerald: 'bg-emerald-100 text-emerald-700 ring-emerald-200',
    teal: 'bg-teal-100 text-teal-700 ring-teal-200',
    sky: 'bg-sky-100 text-sky-700 ring-sky-200',
    cyan: 'bg-cyan-100 text-cyan-700 ring-cyan-200',
    rose: 'bg-rose-100 text-rose-700 ring-rose-200',
    violet: 'bg-violet-100 text-violet-700 ring-violet-200',
    purple: 'bg-purple-100 text-purple-700 ring-purple-200',
    fuchsia: 'bg-fuchsia-100 text-fuchsia-700 ring-fuchsia-200',
    indigo: 'bg-indigo-100 text-indigo-700 ring-indigo-200',
    amber: 'bg-amber-100 text-amber-700 ring-amber-200',
    orange: 'bg-orange-100 text-orange-700 ring-orange-200',
    yellow: 'bg-yellow-100 text-yellow-700 ring-yellow-200',
    slate: 'bg-slate-100 text-slate-700 ring-slate-200',
  }
  if (badge.color && classes[badge.color]) return classes[badge.color]
  if (badge.level === 'gold') return classes.amber
  if (badge.level === 'special') return classes.indigo
  return classes.blue
}

function autoBadges() {
  return activeBadges.value.filter(badge => badge.source !== 'manual')
}

function toggleBadge(code: string) {
  if (selectedBadgeCodes.value.includes(code)) {
    selectedBadgeCodes.value = selectedBadgeCodes.value.filter(item => item !== code)
    return
  }
  selectedBadgeCodes.value = [...selectedBadgeCodes.value, code]
}

async function loadUserBadges(userId: number) {
  badgeLoading.value = true
  badgesLoaded.value = false
  badgeOptions.value = []
  activeBadges.value = []
  selectedBadgeCodes.value = []
  try {
    const data = await getUserBadgeOptions(userId)
    const options = data.options || []
    const active = data.active || []
    const optionCodes = new Set(options.map(item => item.code))
    badgeOptions.value = options
    activeBadges.value = active
    selectedBadgeCodes.value = active
      .filter(item => item.source === 'manual' && optionCodes.has(item.code))
      .map(item => item.code)
    badgesLoaded.value = true
  } catch (err) {
    adminToast.error(err, adminText('k0033'))
  } finally {
    badgeLoading.value = false
  }
}

async function openEdit(user: AdminUser) {
  editingUser.value = user
  form.status = user.status
  form.validate = user.validate
  form.roleId = user.roleId || 0
  await Promise.all([
    ensureRoles(),
    loadUserBadges(user.userId),
  ])
}

async function saveUser() {
  if (!editingUser.value) return
  saving.value = true
  try {
    await editUser({
      userId: editingUser.value.userId,
      status: Number(form.status),
      validate: Number(form.validate),
      roleId: Number(form.roleId),
    })
    if (badgesLoaded.value) {
      await saveUserBadges(editingUser.value.userId, selectedBadgeCodes.value)
    }
    editingUser.value = null
    await loadUsers()
    adminToast.success(adminText('k000e'))
  } catch (err) {
    adminToast.error(err, adminText('k000r'))
  } finally {
    saving.value = false
  }
}

function avatarText(user: AdminUser) {
  return user.username.slice(0, 2).toUpperCase()
}

function updateRoleId(value: unknown) {
  if (value === null || value === undefined) return
  form.roleId = Number(value)
}

onMounted(() => {
  void loadUsers()
})
</script>

<template>
  <BasicPage :title="adminText('k006i')" :description="adminText('k006j')" sticky>
    <template #actions>
      <Button variant="outline" type="button" @click="loadUsers">
        <RefreshCw class="size-4" />
        {{ adminText('k004q') }}
      </Button>
    </template>

      <AdminSection>
        <template #header>
        <AdminToolbar class="-mx-3 -my-2 border-b-0">
          <form class="flex min-w-0 flex-1 items-center gap-2" @submit.prevent="applySearch">
            <div class="relative min-w-0 flex-1 sm:max-w-md">
              <Search class="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
              <input
                v-model="search"
                class="h-9 w-full rounded-md border bg-background pl-8 pr-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
                :placeholder="adminText('k006t')"
              />
            </div>
            <Button size="sm" type="submit" class="h-9 px-4">{{ adminText('k00al') }}</Button>
            <Button v-if="appliedSearch" variant="ghost" size="sm" type="button" class="h-9" @click="search = ''; applySearch()">
              {{ adminText('k00at') }}
            </Button>
          </form>
          <div class="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
            <span class="whitespace-nowrap">{{ rangeStart }}-{{ rangeEnd }} / {{ total }}</span>
            <select
              class="h-9 rounded-md border bg-background px-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
              :value="pageSize"
              @change="changePageSize(Number(($event.target as HTMLSelectElement).value))"
            >
              <option :value="10">{{ adminText('k002x') }}</option>
              <option :value="20">{{ adminText('k002y') }}</option>
              <option :value="30">{{ adminText('k002z') }}</option>
              <option :value="50">{{ adminText('k0030') }}</option>
            </select>
            <Button
              variant="outline"
              size="icon"
              type="button"
              :disabled="page <= 1 || loading"
              @click="changePage(page - 1)"
            >
              <ChevronLeft class="size-4" />
            </Button>
            <span class="min-w-14 text-center">{{ page }} / {{ totalPages }}</span>
            <Button
              variant="outline"
              size="icon"
              type="button"
              :disabled="page >= totalPages || loading"
              @click="changePage(page + 1)"
            >
              <ChevronRight class="size-4" />
            </Button>
          </div>
        </AdminToolbar>
        </template>

        <div class="md:hidden">
          <div v-if="loading && rows.length === 0" class="px-3 py-10 text-center text-sm text-muted-foreground">{{ adminText('k0046') }}</div>
          <div v-else-if="error" class="px-3 py-10 text-center">
            <div class="text-sm text-destructive">{{ error }}</div>
            <Button variant="link" size="sm" class="mt-2 h-auto px-0 text-destructive" type="button" @click="loadUsers">{{ adminText('k002w') }}</Button>
          </div>
          <div v-else-if="rows.length === 0" class="px-3 py-10 text-center text-sm text-muted-foreground">{{ adminText('k00bm') }}</div>
          <div v-else class="divide-y">
            <article v-for="user in rows" :key="user.userId" class="px-3 py-3">
              <div class="flex min-w-0 items-start gap-3">
                <a :href="`/u/${user.userId}`" target="_blank" rel="noreferrer" class="shrink-0">
                  <img v-if="user.avatarUrl" :src="user.avatarUrl" class="size-10 rounded-full object-cover ring-1 ring-border" alt="" />
                  <span v-else class="flex size-10 items-center justify-center rounded-full bg-muted text-sm font-semibold">{{ avatarText(user) }}</span>
                </a>
                <div class="min-w-0 flex-1">
                  <div class="flex min-w-0 items-center justify-between gap-2">
                    <a :href="`/u/${user.userId}`" target="_blank" rel="noreferrer" class="truncate font-semibold hover:text-primary hover:underline">{{ user.username }}</a>
                    <Button variant="ghost" size="icon-sm" type="button" :title="adminText('k005j')" @click="openEdit(user)">
                      <UserCog class="size-4" />
                    </Button>
                  </div>
                  <div class="mt-0.5 truncate text-xs text-muted-foreground">{{ user.email || '-' }}</div>
                  <div class="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground">
                    <span class="inline-flex items-center gap-1" :class="user.status === 0 ? 'text-emerald-700' : 'text-destructive'">
                      <span class="size-1.5 rounded-full" :class="user.status === 0 ? 'bg-emerald-500' : 'bg-destructive'" />
                      {{ user.status === 0 ? adminText('k005y') : adminText('k006k') }}
                    </span>
                    <span class="inline-flex items-center gap-1" :class="user.validate === 1 ? 'text-emerald-700' : ''">
                      <span class="size-1.5 rounded-full" :class="user.validate === 1 ? 'bg-emerald-500' : 'bg-muted-foreground/40'" />
                      {{ user.validate === 1 ? adminText('k006l') : adminText('k006m') }}
                    </span>
                    <span>{{ roleNames(user).join(' / ') || adminText('k006n') }}</span>
                  </div>
                </div>
              </div>
            </article>
          </div>
        </div>

        <div class="hidden overflow-x-auto md:block">
          <table class="w-full min-w-[880px] table-fixed text-sm">
            <thead class="border-b bg-muted/25 text-xs font-medium text-muted-foreground">
              <tr>
                <th class="h-10 px-3 text-left align-middle">{{ adminText('k003f') }}</th>
                <th class="w-[220px] px-3 text-left align-middle">{{ adminText('k00bn') }}</th>
                <th class="w-[150px] px-3 text-left align-middle">{{ adminText('k007j') }}</th>
                <th class="w-[150px] px-3 text-left align-middle">{{ adminText('k00bo') }}</th>
                <th class="w-[150px] px-3 text-left align-middle">{{ adminText('k00bp') }}</th>
                <th class="w-[72px] px-3 text-right align-middle">{{ adminText('k007m') }}</th>
              </tr>
            </thead>
            <tbody class="divide-y">
              <tr v-if="loading && rows.length === 0">
                <td colspan="6" class="h-28 px-3 text-center text-muted-foreground">{{ adminText('k0046') }}</td>
              </tr>
              <tr v-else-if="error">
                <td colspan="6" class="h-28 px-3 text-center">
                  <div class="inline-flex items-center gap-3 rounded-md border border-destructive/30 bg-destructive/5 px-4 py-2 text-destructive">
                    <span>{{ error }}</span>
                    <Button variant="link" size="sm" class="h-auto px-0 text-destructive" type="button" @click="loadUsers">{{ adminText('k002w') }}</Button>
                  </div>
                </td>
              </tr>
              <tr v-else-if="rows.length === 0">
                <td colspan="6" class="h-28 px-3 text-center text-muted-foreground">{{ adminText('k00bm') }}</td>
              </tr>
              <tr v-for="user in rows" v-else :key="user.userId" class="hover:bg-muted/25">
                <td class="max-w-0 px-3 py-2">
                  <div class="flex min-w-0 items-center gap-2.5">
                    <a :href="`/u/${user.userId}`" target="_blank" rel="noreferrer" class="shrink-0">
                      <img v-if="user.avatarUrl" :src="user.avatarUrl" class="size-9 rounded-full object-cover ring-1 ring-border" alt="" />
                      <span v-else class="flex size-9 items-center justify-center rounded-full bg-muted text-xs font-semibold">{{ avatarText(user) }}</span>
                    </a>
                    <div class="min-w-0">
                      <a :href="`/u/${user.userId}`" target="_blank" rel="noreferrer" class="block truncate font-semibold leading-5 hover:text-primary hover:underline">{{ user.username }}</a>
                      <div class="mt-0.5 flex min-w-0 items-center gap-2 text-xs text-muted-foreground">
                        <span class="truncate">{{ user.email || '-' }}</span>
                        <span class="inline-flex shrink-0 items-center gap-1" :class="user.validate === 1 ? 'text-emerald-700' : ''">
                          <span class="size-1.5 rounded-full" :class="user.validate === 1 ? 'bg-emerald-500' : 'bg-muted-foreground/40'" />
                          {{ user.validate === 1 ? adminText('k006l') : adminText('k006m') }}
                        </span>
                      </div>
                    </div>
                  </div>
                </td>
                <td class="px-3 py-2">
                  <div class="flex flex-wrap gap-1">
                    <span v-for="role in user.roleList" :key="role.value" class="rounded-md bg-muted px-1.5 py-0.5 text-xs text-muted-foreground">{{ role.name }}</span>
                    <span v-if="!user.roleList?.length" class="text-xs text-muted-foreground">{{ adminText('k0032') }}</span>
                  </div>
                </td>
                <td class="px-3 py-2">
                  <span class="inline-flex items-center gap-1.5 text-xs font-medium" :class="user.status === 0 ? 'text-emerald-700' : 'text-destructive'">
                    <CheckCircle2 v-if="user.status === 0" class="size-3.5" />
                    <ShieldOff v-else class="size-3.5" />
                    {{ user.status === 0 ? adminText('k005y') : adminText('k006k') }}
                  </span>
                </td>
                <td class="px-3 py-2 text-xs text-muted-foreground">{{ user.createTime || '-' }}</td>
                <td class="px-3 py-2 text-xs text-muted-foreground">{{ user.lastActiveTime || adminText('k006o') }}</td>
                <td class="px-3 py-2 text-right">
                  <Button variant="ghost" size="icon-sm" type="button" :title="adminText('k005j')" @click="openEdit(user)">
                    <UserCog class="size-4" />
                  </Button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </AdminSection>

      <Dialog :open="editingUser !== null" @update:open="(open) => !open && (editingUser = null)">
        <DialogContent class="flex max-h-[min(700px,calc(100vh-1.5rem))] gap-0 overflow-hidden p-0 sm:max-w-4xl">
        <form v-if="editingUser" class="flex min-h-0 w-full flex-col" @submit.prevent="saveUser">
          <div class="flex items-center justify-between gap-4 border-b px-4 py-3">
            <div class="flex min-w-0 items-center gap-3">
              <img v-if="editingUser.avatarUrl" :src="editingUser.avatarUrl" class="size-10 rounded-full object-cover ring-1 ring-border" alt="" />
              <span v-else class="flex size-10 items-center justify-center rounded-full bg-muted text-sm font-semibold">{{ avatarText(editingUser) }}</span>
              <div class="min-w-0">
                <h2 class="truncate text-base font-semibold">{{ adminText('k00bq') }}</h2>
                <p class="truncate text-xs text-muted-foreground">{{ editingUser.username }} · {{ editingUser.email || adminText('k006p') }}</p>
              </div>
            </div>
          </div>

          <div class="min-h-0 flex-1 overflow-y-auto p-4">
            <div class="grid gap-3 lg:grid-cols-[280px_minmax(0,1fr)]">
              <aside class="space-y-3">
                <section class="rounded-lg border bg-background p-3">
                  <div class="mb-2 text-sm font-semibold">{{ adminText('k00br') }}</div>
                  <div class="divide-y">
                    <label class="flex items-center justify-between gap-3 py-2.5">
                      <span class="text-sm font-medium">{{ adminText('k00br') }}</span>
                      <span class="inline-flex items-center gap-2">
                        <span class="text-xs text-muted-foreground">{{ form.status === 0 ? adminText('k005y') : adminText('k006k') }}</span>
                        <Switch :model-value="form.status === 0" @update:model-value="(checked: boolean) => form.status = checked ? 0 : 1" />
                      </span>
                    </label>
                    <label class="flex items-center justify-between gap-3 py-2.5">
                      <span class="text-sm font-medium">{{ adminText('k00bs') }}</span>
                      <span class="inline-flex items-center gap-2">
                        <span class="text-xs text-muted-foreground">{{ form.validate === 1 ? adminText('k006l') : adminText('k006m') }}</span>
                        <Switch :model-value="form.validate === 1" @update:model-value="(checked: boolean) => form.validate = checked ? 1 : 0" />
                      </span>
                    </label>
                    <div class="grid gap-1.5 py-2.5 text-sm font-medium">
                      {{ adminText('k00bt') }}
                      <Select :model-value="String(form.roleId)" @update:model-value="updateRoleId">
                        <SelectTrigger class="h-9 w-full">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem v-for="role in roles" :key="role.value" :value="String(role.value)">
                            {{ role.name }}
                          </SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                </section>

                <section class="rounded-lg border bg-background p-3">
                  <div class="mb-2 text-sm font-semibold">{{ adminText('k00bu') }}</div>
                  <dl class="grid gap-2 text-sm">
                    <div class="flex justify-between gap-3">
                      <dt class="text-muted-foreground">{{ adminText('k00bv') }}</dt>
                      <dd class="truncate text-right">{{ editingUser.createTime || '-' }}</dd>
                    </div>
                    <div class="flex justify-between gap-3">
                      <dt class="text-muted-foreground">{{ adminText('k00bp') }}</dt>
                      <dd class="truncate text-right">{{ editingUser.lastActiveTime || adminText('k006o') }}</dd>
                    </div>
                    <div class="flex justify-between gap-3">
                      <dt class="text-muted-foreground">{{ adminText('k00bw') }}</dt>
                      <dd class="font-medium">{{ editingUser.prestige || 0 }}</dd>
                    </div>
                  </dl>
                </section>
              </aside>

              <section class="rounded-lg border bg-background">
                <div class="flex items-center justify-between gap-3 border-b px-3 py-2.5">
                  <div>
                    <div class="flex items-center gap-2 text-sm font-semibold">
                      <Award class="size-4 text-muted-foreground" />
                      {{ adminText('k00bx') }}
                    </div>
                    <p class="mt-0.5 text-xs text-muted-foreground">{{ adminText('k00by') }}</p>
                  </div>
                  <Loader2 v-if="badgeLoading" class="size-4 animate-spin text-muted-foreground" />
                </div>

                <div class="space-y-3 p-3">
                  <div v-if="autoBadges().length" class="space-y-2">
                    <div class="text-xs font-medium text-muted-foreground">{{ adminText('k00bz') }}</div>
                    <div class="flex flex-wrap gap-1.5">
                      <span v-for="badge in autoBadges()" :key="badge.code" class="rounded-md bg-muted px-2 py-1 text-xs text-muted-foreground">
                        {{ badge.name }}
                      </span>
                    </div>
                  </div>

                  <div class="space-y-2">
                    <div class="text-xs font-medium text-muted-foreground">{{ adminText('k00c0') }}</div>
                    <div v-if="badgeOptions.length" class="grid grid-cols-3 gap-2 sm:grid-cols-4 md:grid-cols-5 xl:grid-cols-6">
                      <button
                        v-for="badge in badgeOptions"
                        :key="badge.code"
                        class="group relative flex min-h-20 min-w-0 flex-col items-center justify-center gap-1 rounded-md border p-2 text-center transition-colors hover:bg-muted/50"
                        :class="selectedBadgeCodes.includes(badge.code) ? 'border-primary bg-primary/5 shadow-xs' : 'border-transparent bg-muted/40'"
                        type="button"
                        :title="badge.description || badge.code"
                        @click="toggleBadge(badge.code)"
                      >
                        <span
                          class="flex size-10 shrink-0 items-center justify-center ring-1 ring-inset transition-transform group-hover:scale-105"
                          :class="badgeToneClass(badge)"
                          style="clip-path: polygon(25% 5%, 75% 5%, 100% 50%, 75% 95%, 25% 95%, 0 50%)"
                        >
                          <img :src="badgeIconURL(badge)" :alt="badge.name" class="size-5 object-contain" />
                        </span>
                        <span class="block max-w-full truncate text-xs font-medium leading-4">{{ badge.name }}</span>
                        <span class="absolute right-1.5 top-1.5 grid size-4 place-items-center rounded-full border bg-background text-[10px] font-bold" :class="selectedBadgeCodes.includes(badge.code) ? 'border-primary bg-primary text-primary-foreground' : 'text-transparent'">✓</span>
                      </button>
                    </div>
                    <div v-else class="rounded-md border border-dashed p-6 text-center text-sm text-muted-foreground">
                      {{ badgeLoading ? adminText('k006q') : adminText('k006r') }}
                    </div>
                  </div>
                </div>
              </section>
            </div>
          </div>

          <div class="flex justify-end gap-2 border-t bg-muted/20 px-4 py-3">
            <Button variant="outline" type="button" @click="editingUser = null">{{ adminText('k009q') }}</Button>
            <Button type="submit" :disabled="saving">
              {{ saving ? adminText('k005f') : adminText('k006s') }}
            </Button>
          </div>
        </form>
        </DialogContent>
      </Dialog>
    </BasicPage>
</template>

// resource/apps/web/src/admin/pages/users-management-page.tsx
import { AdminPage } from '../components/admin-page'
import { useLatestRequest } from '../use-latest-request'
import { useCallback, useEffect, useRef, useState } from 'react'
import type { AdminBadge, AdminUser, GooseAdminApi, UserBadge } from '@gooseforum/client'
import { Alert, AlertDescription, AlertTitle } from '@gooseforum/ui/components/alert'
import { Avatar, AvatarFallback, AvatarImage } from '@gooseforum/ui/components/avatar'
import { Badge } from '@gooseforum/ui/components/badge'
import { Button } from '@gooseforum/ui/components/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@gooseforum/ui/components/dialog'
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle } from '@gooseforum/ui/components/empty'
import { Field, FieldGroup, FieldLabel } from '@gooseforum/ui/components/field'
import { Input } from '@gooseforum/ui/components/input'
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@gooseforum/ui/components/select'
import { Spinner } from '@gooseforum/ui/components/spinner'
import { Switch } from '@gooseforum/ui/components/switch'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@gooseforum/ui/components/table'
import { AlertTriangle, Award, CheckCircle2, ChevronLeft, ChevronRight, RefreshCw, Search, ShieldOff, UserCog } from 'lucide-react'
import { toast } from 'sonner'
import type { UserTextKey } from '../users-i18n'

type Text = (key: UserTextKey) => string

export function UsersManagementPage({ api, text }: { api: GooseAdminApi; text: Text }) {
  const [users, setUsers] = useState<AdminUser[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [search, setSearch] = useState('')
  const [appliedSearch, setAppliedSearch] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [editingUser, setEditingUser] = useState<AdminUser | null>(null)

  const totalPages = Math.max(1, Math.ceil(total / pageSize))
  const rangeStart = total ? (page - 1) * pageSize + 1 : 0
  const rangeEnd = Math.min(page * pageSize, total)

  const beginRequest = useLatestRequest();
  const load = useCallback(async () => {
    const isCurrent = beginRequest();
    setLoading(true)
    setError('')
    try {
      const result = await api.users.list({ page, pageSize, username: appliedSearch || undefined })
      if (!isCurrent()) return;
      setUsers(result.list || [])
      setTotal(result.total || 0)
    } catch (reason) {
      if (!isCurrent()) return;
      setError(errorMessage(reason, text('loadFailed')))
    } finally {
      if (isCurrent()) setLoading(false)
    }
  }, [beginRequest, api, appliedSearch, page, pageSize, text])

  useEffect(() => { void load() }, [load])
  useEffect(() => { if (page > totalPages) setPage(totalPages) }, [page, totalPages])

  function applySearch(event?: React.FormEvent) {
    event?.preventDefault()
    setAppliedSearch(search.trim())
    setPage(1)
  }

  return <AdminPage>
    <header><h2 className="text-lg font-semibold tracking-tight">{text('title')}</h2><p className="text-xs text-muted-foreground">{text('description')}</p></header>
    {error ? <Alert variant="destructive"><AlertTriangle /><AlertTitle>{text('loadFailed')}</AlertTitle><AlertDescription className="flex items-center justify-between gap-3"><span>{error}</span><Button variant="outline" size="sm" onClick={() => void load()}>{text('retry')}</Button></AlertDescription></Alert> : null}
    <section className="overflow-hidden rounded-lg border bg-background">
      <div className="flex flex-col gap-2 border-b bg-muted/20 p-2 lg:flex-row lg:items-center lg:justify-between">
        <form className="flex min-w-0 flex-1 items-center gap-1.5 lg:max-w-md" onSubmit={applySearch}><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} className="h-8 pl-8" placeholder={text('search')} /></div><Button size="sm" type="submit">{text('searchAction')}</Button>{appliedSearch ? <Button variant="ghost" size="sm" type="button" onClick={() => { setSearch(''); setAppliedSearch(''); setPage(1) }}>{text('clear')}</Button> : null}</form>
        <div className="flex flex-wrap items-center gap-1.5 text-xs text-muted-foreground"><Button variant="outline" size="sm" disabled={loading} onClick={() => void load()}><RefreshCw data-icon="inline-start" className={loading ? 'animate-spin' : undefined} />{text('refresh')}</Button><span className="whitespace-nowrap">{rangeStart}-{rangeEnd} / {total}</span><Select value={String(pageSize)} onValueChange={(value) => { setPageSize(Number(value)); setPage(1) }}><SelectTrigger size="sm" className="w-20"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{[10, 20, 30, 50].map((size) => <SelectItem key={size} value={String(size)}>{size}</SelectItem>)}</SelectGroup></SelectContent></Select><Button variant="outline" size="icon-sm" disabled={page <= 1 || loading} title={text('previous')} onClick={() => setPage(page - 1)}><ChevronLeft /></Button><span className="min-w-12 text-center">{page}/{totalPages}</span><Button variant="outline" size="icon-sm" disabled={page >= totalPages || loading} title={text('next')} onClick={() => setPage(page + 1)}><ChevronRight /></Button></div>
      </div>
      {loading && !users.length ? <UserEmpty icon={<Spinner />} title={text('loading')} /> : !users.length ? <UserEmpty icon={<Search />} title={text('empty')} /> : <><div className="hidden md:block"><Table className="min-w-220 table-fixed"><TableHeader className="bg-muted/30"><TableRow><TableHead className="h-8">{text('user')}</TableHead><TableHead className="h-8 w-48">{text('roles')}</TableHead><TableHead className="h-8 w-28">{text('status')}</TableHead><TableHead className="h-8 w-40">{text('createdAt')}</TableHead><TableHead className="h-8 w-40">{text('lastActive')}</TableHead><TableHead className="h-8 w-16 text-right">{text('actions')}</TableHead></TableRow></TableHeader><TableBody>{users.map((user) => <TableRow key={user.userId}><TableCell className="py-2"><UserIdentity user={user} text={text} /></TableCell><TableCell className="py-2"><div className="flex flex-wrap gap-1">{user.roleList?.length ? user.roleList.map((role) => <Badge key={role.value} variant="secondary">{role.name}</Badge>) : <span className="text-xs text-muted-foreground">{text('noRole')}</span>}</div></TableCell><TableCell className="py-2"><Badge variant={user.status === 0 ? 'outline' : 'destructive'}>{user.status === 0 ? <CheckCircle2 data-icon="inline-start" /> : <ShieldOff data-icon="inline-start" />}{user.status === 0 ? text('enabled') : text('disabled')}</Badge></TableCell><TableCell className="truncate py-2 text-xs text-muted-foreground">{user.createTime || '—'}</TableCell><TableCell className="truncate py-2 text-xs text-muted-foreground">{user.lastActiveTime || text('never')}</TableCell><TableCell className="py-2 text-right"><Button variant="ghost" size="icon-sm" title={text('edit')} onClick={() => setEditingUser(user)}><UserCog /></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y md:hidden">{users.map((user) => <article key={user.userId} className="flex items-start gap-2.5 px-3 py-2.5"><UserIdentity user={user} text={text} compact /><Button variant="ghost" size="icon-sm" title={text('edit')} onClick={() => setEditingUser(user)}><UserCog /></Button></article>)}</div></>}
    </section>
    <UserEditor user={editingUser} api={api} text={text} onClose={() => setEditingUser(null)} onSaved={async () => { setEditingUser(null); await load() }} />
  </AdminPage>
}

function UserIdentity({ user, text, compact = false }: { user: AdminUser; text: Text; compact?: boolean }) {
  return <div className="flex min-w-0 flex-1 items-center gap-2.5"><a href={`/u/${user.userId}`} target="_blank" rel="noreferrer" className="shrink-0"><Avatar className={compact ? 'size-10' : 'size-9'}><AvatarImage src={user.avatarUrl || undefined} alt={user.username} /><AvatarFallback>{user.username.slice(0, 2).toUpperCase()}</AvatarFallback></Avatar></a><div className="min-w-0 flex-1"><a href={`/u/${user.userId}`} target="_blank" rel="noreferrer" className="block truncate font-semibold hover:text-primary hover:underline">{user.username}</a><div className="flex min-w-0 items-center gap-2 text-xs text-muted-foreground"><span className="truncate">{user.email || '—'}</span><Badge variant="outline" className="shrink-0">{user.validate === 1 ? text('verified') : text('unverified')}</Badge></div>{compact ? <div className="mt-1 flex flex-wrap gap-1"><Badge variant={user.status === 0 ? 'outline' : 'destructive'}>{user.status === 0 ? text('enabled') : text('disabled')}</Badge>{user.roleList?.map((role) => <Badge key={role.value} variant="secondary">{role.name}</Badge>)}</div> : null}</div></div>
}

function UserEditor({ user, api, text, onClose, onSaved }: { user: AdminUser | null; api: GooseAdminApi; text: Text; onClose(): void; onSaved(): Promise<void> }) {
  const [form, setForm] = useState({ status: 0, validate: 0, roleId: 0 })
  const [roles, setRoles] = useState<{ name: string; value: number }[]>([])
  const [badgeOptions, setBadgeOptions] = useState<AdminBadge[]>([])
  const [activeBadges, setActiveBadges] = useState<UserBadge[]>([])
  const [selectedBadgeCodes, setSelectedBadgeCodes] = useState<string[]>([])
  const [badgeLoading, setBadgeLoading] = useState(false)
  const [badgesLoaded, setBadgesLoaded] = useState(false)
  const [saving, setSaving] = useState(false)
  const textRef = useRef(text)
  useEffect(() => { textRef.current = text }, [text])

  useEffect(() => {
    if (!user) return
    let active = true
    setForm({ status: user.status, validate: user.validate, roleId: user.roleId || 0 })
    setBadgeLoading(true); setBadgesLoaded(false); setBadgeOptions([]); setActiveBadges([]); setSelectedBadgeCodes([])
    void api.users.roles().then((roleItems) => {
      if (active) setRoles(roleItems)
    }).catch(() => {
      if (active) setRoles([])
    })
    void api.users.badgeOptions(user.userId).then((badges) => {
      if (!active) return
      setBadgeOptions(badges.options || [])
      setActiveBadges(badges.active || [])
      const optionCodes = new Set((badges.options || []).map((badge) => badge.code))
      setSelectedBadgeCodes((badges.active || []).filter((badge) => badge.source === 'manual' && optionCodes.has(badge.code)).map((badge) => badge.code))
      setBadgesLoaded(true)
    }).catch((reason) => { if (active) toast.error(errorMessage(reason, textRef.current('badgeLoading'))) }).finally(() => { if (active) setBadgeLoading(false) })
    return () => { active = false }
  }, [api, user])

  const automaticBadges = activeBadges.filter((badge) => badge.source !== 'manual')
  function toggleBadge(code: string) { setSelectedBadgeCodes((current) => current.includes(code) ? current.filter((item) => item !== code) : [...current, code]) }
  async function save(event: React.FormEvent) {
    event.preventDefault()
    if (!user) return
    setSaving(true)
    try { await api.users.edit({ userId: user.userId, ...form }); if (badgesLoaded) await api.users.saveBadges(user.userId, selectedBadgeCodes); toast.success(text('saved')); await onSaved() } catch (reason) { toast.error(errorMessage(reason, text('saveFailed'))) } finally { setSaving(false) }
  }

  return <Dialog open={Boolean(user)} onOpenChange={(open) => !open && !saving && onClose()}><DialogContent className="flex max-h-[min(700px,calc(100vh-1.5rem))] gap-0 overflow-hidden p-0 sm:max-w-4xl"><form onSubmit={save} className="flex min-h-0 w-full flex-col"><DialogHeader className="border-b px-4 py-3"><div className="flex items-center gap-3">{user ? <Avatar className="size-10"><AvatarImage src={user.avatarUrl || undefined} alt={user.username} /><AvatarFallback>{user.username.slice(0, 2).toUpperCase()}</AvatarFallback></Avatar> : null}<div className="min-w-0"><DialogTitle>{text('edit')}</DialogTitle><DialogDescription className="truncate">{user?.username} · {user?.email || '—'}</DialogDescription></div></div></DialogHeader><div className="min-h-0 flex-1 overflow-y-auto p-3"><div className="grid gap-3 lg:grid-cols-[280px_minmax(0,1fr)]"><aside className="flex flex-col gap-3"><section className="rounded-lg border p-3"><h3 className="mb-2 text-sm font-semibold">{text('account')}</h3><FieldGroup><Field orientation="horizontal"><FieldLabel>{text('status')}</FieldLabel><span className="ml-auto flex items-center gap-2 text-xs text-muted-foreground">{form.status === 0 ? text('enabled') : text('disabled')}<Switch checked={form.status === 0} onCheckedChange={(checked) => setForm({ ...form, status: checked ? 0 : 1 })} /></span></Field><Field orientation="horizontal"><FieldLabel>{text('emailVerification')}</FieldLabel><span className="ml-auto flex items-center gap-2 text-xs text-muted-foreground">{form.validate === 1 ? text('verified') : text('unverified')}<Switch checked={form.validate === 1} onCheckedChange={(checked) => setForm({ ...form, validate: checked ? 1 : 0 })} /></span></Field><Field><FieldLabel>{text('role')}</FieldLabel><Select value={String(form.roleId)} onValueChange={(value) => setForm({ ...form, roleId: Number(value) })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="0">{text('noRole')}</SelectItem>{roles.map((role) => <SelectItem key={role.value} value={String(role.value)}>{role.name}</SelectItem>)}</SelectGroup></SelectContent></Select></Field></FieldGroup></section><section className="rounded-lg border p-3"><h3 className="mb-2 text-sm font-semibold">{text('details')}</h3><dl className="grid gap-2 text-sm"><Detail label={text('createdAt')} value={user?.createTime || '—'} /><Detail label={text('lastActive')} value={user?.lastActiveTime || text('never')} /><Detail label={text('prestige')} value={String(user?.prestige || 0)} /></dl></section></aside><section className="rounded-lg border"><div className="flex items-center justify-between gap-3 border-b px-3 py-2.5"><div><h3 className="flex items-center gap-2 text-sm font-semibold"><Award className="size-4 text-muted-foreground" />{text('badges')}</h3><p className="text-xs text-muted-foreground">{text('badgeHint')}</p></div>{badgeLoading ? <Spinner /> : null}</div><div className="flex flex-col gap-3 p-3">{automaticBadges.length ? <div className="flex flex-col gap-2"><h4 className="text-xs font-medium text-muted-foreground">{text('automaticBadges')}</h4><div className="flex flex-wrap gap-1.5">{automaticBadges.map((badge) => <Badge key={badge.code} variant="secondary">{badge.name}</Badge>)}</div></div> : null}<div className="flex flex-col gap-2"><h4 className="text-xs font-medium text-muted-foreground">{text('manualBadges')}</h4>{badgeOptions.length ? <div className="grid grid-cols-3 gap-2 sm:grid-cols-4 xl:grid-cols-6">{badgeOptions.map((badge) => <Button key={badge.code} type="button" variant="ghost" data-current={selectedBadgeCodes.includes(badge.code)} title={badge.description || badge.code} onClick={() => toggleBadge(badge.code)} className="relative h-auto min-h-20 min-w-0 flex-col gap-1 whitespace-normal rounded-md border border-transparent bg-muted/40 p-2 font-normal data-[current=true]:border-primary data-[current=true]:bg-primary/5"><span className="grid size-9 place-items-center rounded-full bg-background ring-1 ring-border"><img src={badge.iconUrl || '/static/badges/contributor.svg'} alt="" className="size-5 object-contain" /></span><span className="max-w-full truncate text-xs font-medium">{badge.name}</span>{selectedBadgeCodes.includes(badge.code) ? <span className="absolute right-1 top-1 text-primary">✓</span> : null}</Button>)}</div> : <Empty className="min-h-28 border-dashed p-3"><EmptyHeader><EmptyTitle>{badgeLoading ? text('badgeLoading') : text('noBadges')}</EmptyTitle></EmptyHeader></Empty>}</div></div></section></div></div><DialogFooter className="mx-0 mb-0 rounded-b-none"><Button variant="outline" type="button" disabled={saving} onClick={onClose}>{text('cancel')}</Button><Button type="submit" disabled={saving}>{saving ? <Spinner data-icon="inline-start" /> : null}{saving ? text('saving') : text('save')}</Button></DialogFooter></form></DialogContent></Dialog>
}

function Detail({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3"><dt className="text-muted-foreground">{label}</dt><dd className="truncate text-right">{value}</dd></div> }
function UserEmpty({ icon, title }: { icon: React.ReactNode; title: string }) { return <Empty className="min-h-32 rounded-none border-0"><EmptyHeader><EmptyMedia variant="icon">{icon}</EmptyMedia><EmptyTitle>{title}</EmptyTitle></EmptyHeader></Empty> }
function errorMessage(reason: unknown, fallback: string) { return reason instanceof Error && reason.message ? reason.message : fallback }
